### ISSUE TITLE
Rename offsets columns

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#1015]
To make offsets indication more clear we have to:
Topic details page:
1) Rename min/max offset to first/next (earliest/latest?) offset
2) Add a column "message count"

CC @iliax @GneyHabub

**Comment by sasunprov** [comment]
> To make offsets indication more clear we have to: Topic details page:
> 
> 1. Rename min/max offset to first/next (earliest/latest?) offset
> 2. Add a column "message count"
> 
> CC @iliax @GneyHabub
