### ISSUE TITLE
Proposal: Add info about `SERVER_USEFORWARDHEADERS` to SSO guide

### ISSUE THREAD

**Issue by clocklear** [provectus/kafka-ui#1017]
### Is your proposal related to a problem?

I recently set up kafka-ui with MSK in ECS on AWS with the intent of using SSO with Auth0 to secure the application.  I am terminating SSL on the load balancer; connections between the load balancer and the kafka-ui container are HTTP.  Following the SSO guide, I set up only the environment variables that were relevant to SSO:

```
AUTH_ENABLED=true
SECURITY_BASIC_ENABLED=true
SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_AUTH0_CLIENTID=uhvaPKIHU4ZF8Ne4B6PGvF0hWW6OcUSB
SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_AUTH0_CLIENTSECRET=YXfRjmodifiedTujnkVr7zuW9ECCAK4TcnCio-i
SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_AUTH0_ISSUER_URI=https://dev-a63ggcut.auth0.com/
```

However, what I observed is that the redirect URI that was formed by the application and passed to Auth0 used the HTTP scheme instead of HTTPS, ostensibly because the connection between the LB and the app is non-TLS. 

### Describe the solution you'd like

After digging through a few articles online (and deducing that Spring Security is being used to facilitate authN/Z), I found that there is a Spring setting that must be enabled in my particular configuration that causes Spring to use the `X-Forwarded-For` headers to determine the originating scheme in order to form the correct redirect URI to pass to Auth0.  By setting `SERVER_USEFORWARDHEADERS` to `true`, the application now properly handles my SSO authentication with Auth0.  I propose that the SSO guide be augmented in such a way to call out the scenario in which SSL is terminated prior to the application (such as on a load balancer), the app _may_ need to be configured to respect the `X-Forwarded-For` headers (which is apparently not the default).

(tl;dr -- the docs for SSO should suggest setting `SERVER_USEFORWARDHEADERS` to `true` when TLS is terminated by a proxy.)

### Describe alternatives you've considered

None.

### Additional context

More info can be found in this SO answer: https://stackoverflow.com/a/40879393

**Comment by Haarolean** [comment]
Thanks once again, done.

**Comment by Haarolean** [comment]
@clocklear hey, yeah, we've updated boot some time ago. Thanks for this information, I'll update the docs.
