### ISSUE TITLE
New incoming messages not visible when "Newest first" enabled

### ISSUE THREAD

**Issue by iliax** [provectus/kafka-ui#1024]
**Describe the bug**
(A clear and concise description of what the bug is.)

When "Newest first" is enabled on Submit we should send request with latest partitions offsets.

**Steps to Reproduce**

1. write messages to topic
2. open Messages tab
3. enable "Newest first" mode
4. write new messages
5. click Submit 
6. nothing happened

**Expected behavior**
(A clear and concise description of what you expected to happen)

New submitted messages should be visible. 
To Fix it we should get latest partitions offsets and send as params

**Screenshots**
(If applicable, add screenshots to help explain your problem)

**Additional context**
(Add any other context about the problem here)

**Comment by Haarolean** [comment]
1. When "newest first" is selected or "submit" button is pressed while "newest first" is selected we should use `seekType` as `LATEST` instead of `OFFSET`.
2. The same for "oldest first": `seekType` should be `BEGINNING`.

**Comment by simonyandev** [comment]
@Haarolean When we submit a message, it redirects to the topic messages page with the default params, so the seekDirection is reset to FORWARD (Oldest first). I can set the seekType to BEGINNING, but the results are the same. What about the newest first option, seekType=LATEST doesn't help, the new messages still don't appear. I think the problem comes from the back end.

**Comment by Haarolean** [comment]
@simonyandev the first part is okay, results should be the same, adjusting the seekDirection to make it clear.

@iliax any ideas about the second part?

**Comment by iliax** [comment]
@simonyandev We fixed issue with wrong backend behaviour in Newest first mode, so I think you can continue work on UI

**Comment by Haarolean** [comment]
@ssiradeghyan PTAL
