### ISSUE TITLE
Better logging to know what failed in KafkaService/getUpdatedCluster

### ISSUE THREAD

**Issue by tooptoop4** [provectus/kafka-ui#1029]
i get this error connecting to MSK IAM:
```
10:13:48.106 [kafka-admin-client-thread | adminclient-2] ERROR com.provectus.kafka.ui.service.KafkaService - Failed to collect cluster msk info
org.apache.kafka.common.errors.ClusterAuthorizationException: Cluster authorization failed.
```
This function is doing a lot:
https://github.com/provectus/kafka-ui/blob/v0.2.1/kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaService.java#L124-L156
 
but it doesn't have enough debug logs to isolate which individual call is causing the issue

**Comment by Haarolean** [comment]
Hi, thanks for raising the issue. I remember this being a problem because kafka's admin client itself returns a message which is not much of a help. We'll have to do something.

**Comment by brutttttttt** [comment]
Hi check it with the latest version

**Comment by tooptoop4** [comment]
I can't see release after 5th October

**Comment by Haarolean** [comment]
Please try master labeled docker image.

**Comment by allanpaiste** [comment]
@tooptoop4 you can get more information about the comms when you update root logger level to be of level: debug.

It'll still mean that you have to hunt down the actual line. Here's one example of such failure (that I'm currently struggling with):

In my case, I could identify that the failing call was **DESCRIBE_CONFIGS**, which maps directly to a method name used in code. From there we can backtrack: **describeConfigs** > **loadTopicsConfig** > **getTopicsData** (which is the method that is used in the block of code you referred to).
