### ISSUE TITLE
Cannot Produce a message with an empty key

### ISSUE THREAD

**Issue by blueghostuk** [provectus/kafka-ui#1046]
**Describe the bug**

When trying to produce a message, I want the ability to not set a key value

**Set up**

Via docker, using master image (v0.2.2-SNAPSHOT(289791a))

**Steps to Reproduce**

1. Find the relevant topic
2. Click "Produce Message" button
3. Clear the auto-generated key
4. enter some random content, e.g. a JSON object
5. Click Send

**Expected behavior**
Message is sent to the topic, the key is not set

**Actual behavior**
Message is sent to the topic, the key has a random generated string content

**Screenshots**
![image](https://user-images.githubusercontent.com/1785586/140068489-0702cc69-87fd-4b6a-a986-87e20257e0e3.png)
![image](https://user-images.githubusercontent.com/1785586/140068527-2d18c187-f5b6-4689-b3ae-5216e397a11c.png)

**Comment by Haarolean** [comment]
Hey, thanks for reaching out. We'll get back to this issue soon.
