### ISSUE TITLE
Displaying wrong consumers host ip address

### ISSUE THREAD

**Issue by Nitesh-vaidyanath** [provectus/kafka-ui#1047]
[](url)**Describe the bug**
Consumer host ip address is not displayed correctly i see /127.0.0.6 ip address for all the consumers.

**Set up**
Using latest docker image 0.2.1 and helm version kafka-ui-0.0.1.

**Steps to Reproduce**

1. We can check under consumer sections.

**Expected behavior**
UI should display pod ip address

**Screenshots**
<img width="1549" alt="Screenshot 2021-11-03 at 10 04 54 PM" src="https://user-images.githubusercontent.com/12709763/140075519-294c1656-d92b-4cc1-b021-7227e2c480c8.png">

**Comment by Haarolean** [comment]
Hey, thanks for reaching out. We'll take a look at this.

**Comment by Haarolean** [comment]
Hey, this is the IP we get from kafka itself, so it's "relative" to kafka pod/container, kafka-ui has nothing to do with this IP.
