### ISSUE TITLE
Topics->Create new: Disabled dropdown option(s) in Additional parameters

### ISSUE THREAD

**Issue by agolosen** [provectus/kafka-ui#1050]
**Describe the bug**
During creating a new topic dropdown option(s) in Additional parameters are disabled if you click it but it was not added.

**Set up**
docker-compose -f ./docker/kafka-ui.yaml up 

**Steps to Reproduce**

1. Navigate to Topics -> Create new http://localhost:8080/ui/clusters/Cluster_Name/topics/create_new
2. Click button Add Custom Parameter 
3. Choose several parameters one by one but submit (Add Custom Parameter ) only one of them 
4. Click one more time Add Custom Parameter 
5. Observe: in dropdown list unavailable all parameters you click at the previous step, not only submitted one. 

**Expected behavior**

Unavailable only added/submitted parameters in the dropdown list of Add Custom Parameter
**Screenshots**

<img width="1439" alt="Screenshot 2021-11-05 at Bug" src="https://user-images.githubusercontent.com/92585878/140542027-14aa5c7d-e5f5-487e-b128-d7b5ef4fc172.png">

**Additional context**
(Add any other context about the problem here)

**Comment by Haarolean** [comment]
Fixed.
