### ISSUE TITLE
Add positive notifications

### ISSUE THREAD

**Issue by GneyHabub** [provectus/kafka-ui#1052]
Right now we can only display error notifications. They are created after every failed request. We need to add a mechanism to trigger them manually.

**Comment by GneyHabub** [comment]
Potential usages:
1. Edit Connect - warning about credentials
2. Connector tasks - clear messages confirmation

**Comment by Haarolean** [comment]
@Dekshut is the solution from #1545 you implemented reusable and suitable for these purposes?
