### ISSUE TITLE
Request to add a github action to the repo

### ISSUE THREAD

**Issue by Jassi10000** [provectus/kafka-ui#1058]
### Is your proposal related to a problem?

(Write your answer here.)
No, rather related  to adding a new feature

### Describe the solution you'd like

(Describe your proposed solution here.)
I see that the repo is quite engaging
I would love to see a github - action welcoming all the new contributors on their issues and Prs

If you love the idea , assign me

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

If you love the idea , assign me

**Comment by Haarolean** [comment]
Hey, sounds like a great idea. Would be nice to see that!
