### ISSUE TITLE
Double topic message display on consequent pages

### ISSUE THREAD

**Issue by Khakha-A** [provectus/kafka-ui#1059]
**Describe the bug**
(A clear and concise description of what the bug is.)
The last message on page 1 of topic messages gets displayed on page 2

**Set up**
(How do you run the app?)
Windows build

**Steps to Reproduce**
1. Topics
2. Select a Topic
3. Messages
4. See message 99
5. Click "Next"
6. See message 99 on Page 2

**Expected behavior**
(A clear and concise description of what you expected to happen)
The last message from Page 1 (99) should not be displayed on Page 2

**Screenshots**
(If applicable, add screenshots to help explain your problem)

**Additional context**
(Add any other context about the problem here)
Maybe a feature, not a bug designed to let users see the last message on previous page

**Comment by Haarolean** [comment]
@GneyHabub I guess we have to adjust (off by one) `seekTo` param value when clicking on `next` button
