### ISSUE TITLE
Calculation error in Time to retain data [topic creation]

### ISSUE THREAD

**Issue by Khakha-A** [provectus/kafka-ui#1060]
**Describe the bug**
(A clear and concise description of what the bug is.)
Time to retain data tab displays 168d when 4w is selected; 28d should be selected; calculation error in ms (s vs ms)

**Set up**
(How do you run the app?)
docker-compose -f ./docker/kafka-ui.yaml up

**Steps to Reproduce**

1. Topics
2. Add a Topic
3. Navigate to Time to retain data
4. Select 4w
5. 168d (supposedly 14515200000ms) is displayed

**Expected behavior**
(A clear and concise description of what you expected to happen)
28d (2.419e+9ms) should be displayed when 4w is selected

**Screenshots**
(If applicable, add screenshots to help explain your problem)

**Additional context**
(Add any other context about the problem here)

**Comment by Haarolean** [comment]
Hey, thanks for reaching out. We'll get a look at this.

**Comment by Haarolean** [comment]
@GneyHabub this one applies just for the 4w selector for some reason.
