### ISSUE TITLE
Can't connect to locally running Kafka

### ISSUE THREAD

**Issue by GloWorm0** [provectus/kafka-ui#1073]
I'm trying to connect Kafka-ui to a Kafka cluster that is running locally on my machine, NOT via a Docker container.  It will connect fine to other clusters that I am monitoring, but not to my local cluster.  No matter what I try it reports the local cluster as offline.

In my Kafka config/server.properties I have the following entries:
listeners=PLAINTEXT://localhost:9092
advertised.listeners=PLAINTEXT://localhost:9092

I'm currently using the following docker-compose file:
version: '3.7'
services:
  kafka-ui:
    image: provectuslabs/kafka-ui
    ports:
      - "9080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: Local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: host.docker.internal:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: host.docker.internal:2181
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: Local
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://host.docker.internal:8093

I see the following in the log output:
kafka-ui_1  | 17:02:27.776 [kafka-admin-client-thread | adminclient-60] ERROR com.provectus.kafka.ui.service.KafkaService - Failed to collect cluster Local info

kafka-ui_1  | org.apache.kafka.common.errors.TimeoutException: Call(callName=listNodes, deadlineMs=1636563747774, tries=1, nextAllowedTryMs=1636563747875) timed out at 1636563747775 after 1 attempt(s)

kafka-ui_1  | Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: listNodes

This is what I get in the ui:
![image](https://user-images.githubusercontent.com/12738569/141159348-007ad5f4-b76d-4550-9b49-b715a72b1d5f.png)

As you can see, I can connect to other clusters on my network, just not my local cluster.

I've tried replacing host.docker.internal with my the local IP address of my machine and the IP address assigned by my VPN, and  receive the same problem.

Is there some other configuration that I'm missing?

Thanks

**Comment by GloWorm0** [comment]
Yes, that is correct.

**Comment by Haarolean** [comment]
@GloWorm0 
Which platform are you running the app on?
How did you try passing the `host.docker.internal`?

**Comment by GloWorm0** [comment]
I'm running on macOS (10.15.7).

I'm not sure I understand.  I just tried to use it when setting the environment variables for the container.  So instead of `KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: localhost:9092` (which obviously won't work because it's not running in the container) I tried `KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: host.docker.internal:9092` (as well as actually using the IP.

**Comment by Haarolean** [comment]
It's not just that.
First of all, your docker-compose should have this:
```
services:
  kafka-ui:
    extra_hosts:
      - host.docker.internal:host-gateway
[...]
```
Secondly, your `KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS` should look like this: `host.docker.internal:9092`.
Moreover, take a look at your `KAFKA_ADVERTISED_LISTENERS`, it should be like this: `PLAINTEXT://host.docker.internal:9092`.

**Comment by Haarolean** [comment]
I just tried that setup and it worked for me.

`KAFKA_ADVERTISED_LISTENERS` is kafka's variable.
Yeah, that's probably right. I tried that setup with kafka running in a container but I've accessed it externally via port forwarding, so, something close to your setup.

**Comment by GloWorm0** [comment]
Adding `extra-hosts` didn't change anything.  Very frustrating.  I can access other clusters, just not my local Kafka.  I'm trying to evaluate this tool and would rather do some of the tests just on my local cluster, but I guess I won't be able to do that.

I'm sure it's something with my setup, but have no idea what it could be.  Kafka is up and running and accessible, just not from within Docker.

I've run other simpler tests with containers not involving Kafka and can use `hosts.docker.internal` to access the local machine, just not with this container.

I'll have to see if I can get another container to interact with my local Kafka.

**Comment by Haarolean** [comment]
I'd also try to run a 'fair' instance of kafka on bare metal to try that thing out. I suppose the trick might be about `KAFKA_ADVERTISED_LISTENERS`.

**Comment by GloWorm0** [comment]
OK, I figured it out.

In my Kafka `server.properties` I had `advertised.listeners=PLAINTEXT://localhost:9092`.  This only allow access via `localhost`.  Once I changed it to my machine's IP address everything worked fine.

Thanks for the help.

**Comment by Haarolean** [comment]
You're welcome :) I'll convert this to a discussion to make it easily discoverable for others.
