### ISSUE TITLE
bump snakeyaml from 1.25 to 1.29 in kafka-ui-api

### ISSUE THREAD

**Issue by rgsurfs** [provectus/kafka-ui#1082]
Current version in use is over two years old.

https://mvnrepository.com/artifact/org.yaml/snakeyaml

**Comment by rgsurfs** [comment]
Current version in use is over two years old.

https://mvnrepository.com/artifact/org.yaml/snakeyaml

**Comment by Haarolean** [comment]
I don't see this one used anywhere either. Would you elaborate where do you see this dependency used?

**Comment by Haarolean** [comment]
#1083

**Comment by Haarolean** [comment]
Current version of transitive dependency of snakeyaml (via spring-boot-starter-webflux) is 1.28
