### ISSUE TITLE
bump nimbus-jose-jwt from 7.8 to 9.16 in kafka-ui-api

### ISSUE THREAD

**Issue by rgsurfs** [provectus/kafka-ui#1083]
Current version in use is almost two years old.

https://mvnrepository.com/artifact/com.nimbusds/nimbus-jose-jwt

**Comment by Haarolean** [comment]
Hi, I don't see this dependency anywhere in our project at all.

**Comment by rgsurfs** [comment]
appreciate the reply. tks.  Close my tickets then, maybe I was given bum info.....  I have  75mb jar file 
kafka-ui-api-0.2.1.jar 

When I expanded that jar, i get three folders:BOOT-INFMETA-INForg
There are 171 jars in here:\kafka-ui-api-0.2.1\BOOT-INF\lib\

Robert


    On Saturday, November 13, 2021, 09:05:22 AM EST, Roman Zabaluev ***@***.***> wrote:  
 
 


Hi, I don't see this dependency anywhere in our project at all.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Haarolean** [comment]
This might be a transitive dependency. There's nothing wrong with it, considering we're getting notifications about security vulnerabilities via dependabot and sonar. But thanks for the concern!

**Comment by rgsurfs** [comment]
We are getting our reports from Twistlock scans.  copy attached. I'll step back out of the issues for the moment.  tks for the replies.
Robert
    On Sunday, November 14, 2021, 09:08:04 AM EST, Roman Zabaluev ***@***.***> wrote:  
 
 


This might be a transitive dependency. There's nothing wrong with it, considering we're getting notifications about security vulnerabilities via dependabot and sonar. But thanks for the concern!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Haarolean** [comment]
If you’ve attached a copy via email it won’t work probably. Can you send it to me via rzabaluev at provectus dot com please?

**Comment by Haarolean** [comment]
Current version of nimbus-jose-jwt (via spring-security) is 9.10.1.
