### ISSUE TITLE
Browse message for avro (with schema registry) not working. Messages produced by Oracle Debezium Kafka Connect

### ISSUE THREAD

**Issue by tooptoop4** [provectus/kafka-ui#1098]
The avro messages (produced by Oracle Debezium Kafka Connect) appear fine in kafka-avro-console-consumer or kcat but not in kafka-ui. My oracle table has NUMBER data types

![image](https://user-images.githubusercontent.com/33283496/141898113-b434cf77-3b6d-47f2-a75b-ba1b7a7e0eed.png)

I confirmed json messages appear fine in kafka-ui but not these avro ones. I am using 0.2.1 jar

**Comment by Haarolean** [comment]
Hi, 
1) which exact version are you running? There's a commit hash available in the left upper corner.
2) Can you share an example message? A full one.

**Comment by tooptoop4** [comment]
Version:v0.2.1(da29a20)

**Comment by iliax** [comment]
@tooptoop4 can you please provided config that you run kafka-ui with ? Are you setting KAFKA_CLUSTERS_0_SCHEMAREGISTRY property ?

**Comment by tooptoop4** [comment]
export KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=SASL_SSL
export KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM=AWS_MSK_IAM
export KAFKA_CLUSTERS_0_PROPERTIES_SASL_CLIENT_CALLBACK_HANDLER_CLASS=software.amazon.msk.auth.iam.IAMClientCallbackHandler
export KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG='software.amazon.msk.auth.iam.IAMLoginModule required;'
export KAFKA_CLUSTERS_0_NAME=msk
export KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=redact
export KAFKA_CLUSTERS_0_ZOOKEEPER=redact
export KAFKA_CLUSTERS_0_SCHEMAREGISTRY=http://localhost:8081
export KAFKA_IAM_ENABLED=true
export KAFKA_SASL_MECHANISM=AWS_MSK_IAM
export KAFKA_SECURITY_PROTOCOL=SASL_SSL
export KAFKA_IS_SECURED=true

**Comment by iliax** [comment]
@tooptoop4 here are some questions:
1. does schema is called {topic-name}-value for this topic?
2. do you have messages of multiple types inside this topic? ex. some msgs are json, some are avro?
3. do you have any error/warn msgs in logs? We are interested in warn msgs starting with `Failed to parse by`

**Comment by tooptoop4** [comment]
1. schema registry shows 2 schemas: {topic-name}-value and {topic-name}-key
2. all avrò
3. none like that

**Comment by iliax** [comment]
@tooptoop4 can you please share warn&err messages you have in logs? Restart app, open Messages tab for this topic - logs from this steps should be enough.
