### ISSUE TITLE
ARM docker image

### ISSUE THREAD

**Issue by Qwertie-** [provectus/kafka-ui#1111]
### Is your proposal related to a problem?

It looks like the docker images are only built for x86 so they don't work by default on the M1 mac. I know you can force it to run in x86 emulation but it would be nice to get a native ARM build for docker.

### Describe the solution you'd like

ARM build of docker image

**Comment by Haarolean** [comment]
Hey, thanks for reaching out. This is a duplicate of #986.
We'll implement this in near future, once we get enough bandwidth for this.
