### ISSUE TITLE
Can not produce a message

### ISSUE THREAD

**Issue by littleKitchen** [provectus/kafka-ui#1126]
When I try to produce a message, I got the following issue:

Content schema with key or id "http://unknown.unknown" already exists

I am following this link [https://javascript.plainenglish.io/a-beginners-introduction-to-kafka-with-typescript-using-nestjs-7c92fe78f638](url)

**Comment by iliax** [comment]
@littleKitchen this [bug](https://github.com/provectus/kafka-ui/issues/953) was fixed in current master. please try to use it: just replace `provectuslabs/kafka-ui:latest` with `provectuslabs/kafka-ui:master` in your docker-compose.yaml file

**Comment by Haarolean** [comment]
Hey @littleKitchen, thanks for your interest in kafka-ui. As @iliax mentioned, this has been fixed a long time ago in master. The thing is, `latest`-tagged image is about latest **release**, but not the latest commit. 
Let us know if you encounter any other problem!
