### ISSUE TITLE
Collapsible cluster items in cluster left (left column)

### ISSUE THREAD

**Issue by akamensky** [provectus/kafka-ui#1138]
### Is your proposal related to a problem?

We have quite a few Kafka clusters, each with own schema registry, kafka connect etc. That creates a very long list of clusters that need to be scrolled to reach desired one (if it somewhere in 2nd half of the list).

### Describe the solution you'd like

Collapsible items in the left column list.

Right now it is (* is for currently "selected" cluster):

```
Cluster1
- Brokers
- Topics
- Consumers
- Schema Registry
- KafkaConnect

Cluster2 *
- Brokers
- Topics
- Consumers
- Schema Registry
- KafkaConnect

Cluster3
- Brokers
- Topics
- Consumers
- Schema Registry
- KafkaConnect
```

When they are collapsible it would be:

```
Cluster1

Cluster2 *
- Brokers
- Topics
- Consumers
- Schema Registry
- KafkaConnect

Cluster3
```

### Describe alternatives you've considered

There may be other good solutions to this issue. This is just one of.

### Additional context

We have 15 clusters and will be adding more, the list is very long to scroll with 15 already.

**Comment by Haarolean** [comment]
Seems like this has already been implemented within the redesign.
![image](https://user-images.githubusercontent.com/1494347/144011764-be3bb63e-e438-4507-a2e9-d84d150f2b0e.png)
@workshur @alinamiryuk can we make this collapsed by default based on some env. variable?

**Comment by workshur** [comment]
@Haarolean it will work without any env cars

**Comment by Haarolean** [comment]
> @Haarolean it will work without any env cars

based on what circumstances are they gonna be collapsed by default?

**Comment by Haarolean** [comment]
All clusters will be collapsed unless there's just one cluster.

**Comment by akamensky** [comment]
@Haarolean when is the re-design expected to be on master branch?

**Comment by Haarolean** [comment]
> @Haarolean when is the re-design expected to be on master branch?

@akamensky We'll release 0.3 once the redesign is done, currently we're fixing some minor stuff.

@workshur any estimates on redesign?

**Comment by Haarolean** [comment]
@akamensky you could check out master. There are various issues there which are WIP
