### ISSUE TITLE
Kafka ui Failed to connect to broker clusters

### ISSUE THREAD

**Issue by Jabsal** [provectus/kafka-ui#1159]
**Describe the bug**
I am not able to connect to the kafka brokers from the ui

**Set up**
I am running the app via docker compose
pull image from https://hub.docker.com/r/provectuslabs/kafka-ui

Or add the following below to your docker-compose.yml
kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka_ui
    ports:
      - "XXX:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=XXX
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=xxxx

**Steps to Reproduce**
docker compose up kafka-ui

**Expected behavior**
Throws error below
kafka_ui  | 09:43:07.530 [kafka-admin-client-thread | adminclient-1] ERROR com.provectus.kafka.ui.service.KafkaService - Failed to collect cluster XXX info
kafka_ui  | org.apache.kafka.common.errors.TimeoutException: Call(callName=listNodes, deadlineMs=1638438187529, tries=1, nextAllowedTryMs=1638438187630) timed out at 1638438187530 after 1 attempt(s)

I was able to use the kafka-ui container few hours ago but I am not able to connect any longer. I am still able to connect to the remote kafka brokers using my local kafka installed on my bare machine but I would like to get the kafka ui working because it is easier for me to monitor what is going with my brokers than using cli.

![image](https://user-images.githubusercontent.com/20836657/144416420-c8945b3d-0f3c-4927-83d4-b5a312f050f2.png)

I am happy to explain more if required

**Comment by Haarolean** [comment]
Hi, could you please click on that version you marked with yellow color and share the link? I can't find the corresponding commit.

**Comment by Jabsal** [comment]
Thanks for your response. It is something to do with this commit https://github.com/provectus/kafka-ui/commit/**da29a20**0cd8ec46da709e0523787479ac6fb274b 

Btw, I am pulling from this docker image https://hub.docker.com/r/provectuslabs/kafka-ui

**Comment by Haarolean** [comment]
Could you try `image: provectuslabs/kafka-ui:master` instead please?

**Comment by Jabsal** [comment]
Using the master tag worked. 
Thank you so much !

**Comment by Haarolean** [comment]
You're most welcome!
