### ISSUE TITLE
ksql ui streamsProperties usage

### ISSUE THREAD

**Issue by tooptoop4** [provectus/kafka-ui#1168]
ksql ui or docs don't have instructions on expected format for streamsProperties. ie with {} or = or : or "" or ,

**Comment by Haarolean** [comment]
Hi, ksql is kind of in "beta", there are even more serious issues with that. We're planning to get it sorted out in 0.4.

**Comment by Haarolean** [comment]
TODO: Update documentation after #1109

**Comment by Haarolean** [comment]
#1962
