### ISSUE TITLE
Update helm chart on artifacthub

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#1174]
via #1160

**Comment by madrisan** [comment]
The commit d6ada34a7e30a9b95d4ce206fc05b0af37472f9e breaks the kafka-ui helm template for app version 0.2.1.
So the Helm chart should only be updated in the artifacthub when a new release will be shipped with this new probing path.

**Comment by Haarolean** [comment]
Done.
![image](https://user-images.githubusercontent.com/1494347/147475447-9757e3ae-2fb3-45ce-ade4-8f3dd9b90ff8.png)
