### ISSUE TITLE
Apicurio registry support

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#1179]
### Discussed in https://github.com/provectus/kafka-ui/discussions/1177

<div type='discussions-op-text'>

<sup>Originally posted by **smeana** December  7, 2021</sup>
Hello 

We are trying to have the UI working with Apicurio but the UI cant deserialize the avro messages.
Any advise on how to integrate Apicurio?

regards</div>

**Comment by Haarolean** [comment]
Related #1098

**Comment by Haarolean** [comment]
@smeana could you please follow debugging instructions from #1098?

**Comment by barnyrelph** [comment]
I've been looking at the same thing: Plugging in Apicurio. 

I've set the following when running Docker: 
`  -e KAFKA_CLUSTERS_0_SCHEMAREGISTRY=http://host.docker.internal:8080/apis/registry/v2 `

and I see the following in the logs for my APIcurio server:

`2022-01-04 15:14:50 INFO <_> [io.apicurio.registry.logging.audit.AuditLogService] (executor-thread-256) registry.audit action="request" result="failure" src_ip="null" path="/apis/registry/v2/subjects" response_code="404" method="GET" user=""`

So it looks like Kafka-UI has an expectation of a path that APIcurio isn't serving?

**Comment by Haarolean** [comment]
@barnyrelph hey, thanks for the feedback. Could you please answer the same questions posted [here](https://github.com/provectus/kafka-ui/issues/1098#issuecomment-971510515)?

**Comment by Haarolean** [comment]
a working example with Apicurio: #1621
