### ISSUE TITLE
Timeouts are not configurable in envvars

### ISSUE THREAD

**Issue by akamensky** [provectus/kafka-ui#1183]
**Describe the bug**

Default timeouts are way too short and there is no documented way to configure them when running from official Docker image. In our system only clusters that are physically nearby the UI are "online", the rest are all "offline" with logs:

```
01:35:06.481 [kafka-admin-client-thread | adminclient-11] ERROR com.provectus.kafka.ui.service.MetricsService - Failed to collect cluster CLUSTER_NAME info
org.apache.kafka.common.errors.TimeoutException: Call(callName=describeConfigs, deadlineMs=1638927306473, tries=12, nextAllowedTryMs=1638927306574) timed out at 1638927306474 after 12 attempt(s)
```

Meantime I can use Kafka own cli tools just fine to connect to those and get all information that I need, so it is just that timeouts are way too short and there is not way to configure them.

**Set up**

* Globally distributed large number of clusters
* Single UI to manage all of them
* Private (MPLS) networking between sites

**Steps to Reproduce**

1. Have a cluster that physically on the other side of the planet
2. Run cluster in Docker swarm using official "master" image
2. Add clusters to UI cluster list using env vars
3. ....
4. Observe timeouts on every connect

**Expected behavior**
Works

**Actual behavior**
Timeouts on remote clusters

**Screenshots**
N/A

**Additional context**
N/A

**Comment by akamensky** [comment]
Looking at YAML configuration file I've tried to use following in Docker stack envvars:

```
      KAFKA_ADMIN-CLIENT-TIMEOUT: 30000
      ZOOKEEPER_CONNECTION-TIMEOUT: 30000
```

Which works, but again for some clusters it timeouts (but fewer this time). I don't understand why it needs such a high value, because in fact the connections are not that slow to those clusters, bundled-in Kafka scripts complete their requests in under a second to the most remote cluster (tested from the same host where UI runs).

It looks to me something with connection logic is off here.

**Comment by iliax** [comment]
@akamensky please try to incerease `KAFKA_ADMIN-CLIENT-TIMEOUT` to 60000 or more and check behaviour. Note that it is not connection timeout - it is API operation timeout.  If it will help it mean that problem is in high latency. Otherwise maybe some connections error can take place (like closed ports or smth).

**Comment by akamensky** [comment]
@iliax yes, already done that and it does work with 60000, but it is still quite high value I feel and perhaps default value is too low.

But overall I think this issue is more about documenting the configuration options and perhaps make them uniform (replace `-` with `_` for envvar options). But would be nice to perhaps raise default values as well to something higher as some operations may be slow. In our case it is the network link speed, because this connection goes over "management" link, which is slow (to leave capacity for actual data link).

**Comment by iliax** [comment]
@akamensky I increased default timeout to 30s (it was 5s) and added doc for this property
