### ISSUE TITLE
Invalid list of schemas after removing 1 of the schemas

### ISSUE THREAD

**Issue by agolosen** [provectus/kafka-ui#1189]
**Describe the bug**
1. For JSON
Displayed the list with removed a json schema
2. For PROTOBUF and AVRO
Confusing Message 'No schemas found' is displayed after removing a protobuf or avro schema 

**Set up**
http://redesign.internal.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to Schema Registry overview
2. Click a schema from the list
3. Choose from the dropdown menu Remove schema
4. Click the button Submit in pop-up window 'Confirm the action'
5. Observe:  
- 'No schemas found' is displayed after removing a **PROTOBUF** or **AVRO** schema (see attachment)
- original list of schemas with the removed one for **JSON** type schema

**Expected behavior**
The list of schemas without removed one

**Screenshots**
![image](https://user-images.githubusercontent.com/92585878/145200277-ad6944c9-ccaa-41d6-bea6-fdeccf7b5045.png)

**Additional context**
(Add any other context about the problem here)

**Comment by agolosen** [comment]
Before redesign Remove worked correctly for all types of schema.

**Comment by workshur** [comment]
@Haarolean page shows 'No schemas found' message because BE returns 404 on a schema list request
