### ISSUE TITLE
Pagination is missing on Scema registry overview page 

### ISSUE THREAD

**Issue by agolosen** [provectus/kafka-ui#1191]
**Describe the bug**
Pagination is missing on http://redesign.internal.kafka-ui.provectus.io/ui/clusters/local/schemas

**Set up**
http://redesign.internal.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to Shema registry
2. There is no pagination for schemas on the right panel

**Expected behavior**
(A clear and concise description of what you expected to happen)

**Screenshots**
(If applicable, add screenshots to help explain your problem)

**Additional context**
(Add any other context about the problem here)

**Comment by Haarolean** [comment]
@workshur backend done, pending frontend. PR: #1367
