### ISSUE TITLE
impossible to edit connector config

### ISSUE THREAD

**Issue by 5hin0bi** [provectus/kafka-ui#1192]
---
**Describe the bug**
(A clear and concise description of what the bug is.)

When clicking the "Edit Config" button in the connectors properties page it will lead you to this path: ui/clusters/local/connects/local/connectors/connector-name/edit, kafka-ui opens the configuration window but on any change it wont let you save this config saying :
<img width="505" alt="image" src="https://user-images.githubusercontent.com/94184844/145237729-353fdfbf-d135-4e49-bd3b-9c5d254f1103.png">
---
**Set up**
Internal provectus testing demo stand
---
**Steps to Reproduce**

1. Open the connector in the webui
2. Click Edit Config
3. Change anything to make it still be json file
4. See the error
---
**Expected behavior**
(A clear and concise description of what you expected to happen)

Configuration json is changed and saved.
---

**Comment by Haarolean** [comment]
Fixed in 0.3.something.
