### ISSUE TITLE
Kafka Connect error

### ISSUE THREAD

**Issue by tony4x8x** [provectus/kafka-ui#1194]
**Describe the bug**
(A clear and concise description of what the bug is.)
Hello support teams,
I got bellow the error when accessing Kafka connect. i  see this error in the api:
http://172.16.0.5:8083/connectors/connector-hdfs-sink/topics

remove /topics that work fine:

http://172.16.0.5:8083/connectors/connector-hdfs-sink

Thanks,

**Set up**
(How do you run the app?)

**Steps to Reproduce**

1. 

**Expected behavior**
(A clear and concise description of what you expected to happen)

**Screenshots**
(If applicable, add screenshots to help explain your problem)
![Screen Shot 2021-12-09 at 13 54 56](https://user-images.githubusercontent.com/95602353/145348734-42cc2ae5-9891-418a-914a-871b0189f761.png)

**Additional context**
(Add any other context about the problem here)

**Comment by iliax** [comment]
Heloo @tony4x8x, what version of kafka-ui you use? you can see it in the top left corner of page
