### ISSUE TITLE
[Avro] Message content not easily legible

### ISSUE THREAD

**Issue by pdebuitlear** [provectus/kafka-ui#1206]
Messages that are Avro encoded messages don't render nicely in the UI.

**Set up**
Produce messages to a topic in Avro format using a schema registry
Spin up v 0.2.1 of kafka-ui

**Steps to Reproduce**

1.  Navigate to the topic containing the AVRO encoded messages,
2. Select Messages
3. Expand an individual messgae

**Expected behavior**
A clear view of the message content

**Screenshots**
Screenshot from  a similar piece of software (Conduktor):
![conduktor](https://user-images.githubusercontent.com/10045036/145380634-2333d7f1-4912-4008-ad60-0a58e63e7056.png)

Screenshot from kafka-ui:
![kafka-ui](https://user-images.githubusercontent.com/10045036/145380692-8fd7a7a4-1b4f-4328-a5ee-076b4d723831.png)

**Comment by Haarolean** [comment]
Hi, thanks for raising the issue. We'll address it in a new design which is pretty close to be live.

**Comment by Haarolean** [comment]
@workshur can we make it a bit more readable?

**Comment by Motherships** [comment]
@Haarolean seems like this issue is fixed by redesign?
![image](https://user-images.githubusercontent.com/12596177/150162942-ee93fe38-e113-4551-b7f2-060553d12b8a.png)

**Comment by Haarolean** [comment]
@Motherships yeah, seems like that. The issue origins from 0.2.1.

**Comment by Haarolean** [comment]
Fixed in 0.3.0.

@pdebuitlear FYI
