### ISSUE TITLE
Implement search for Schema Registry

### ISSUE THREAD

**Issue by agolosen** [provectus/kafka-ui#1208]
### Is your proposal related to a problem?
Missing Search on the page Schema Registry

(Write your answer here.)
It would be convenient to have a Search line on this page like on others, especially if we have many schemas in the list.
### Describe the solution you'd like

(Describe your proposed solution here.)
Search line by name and type of schema

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by Haarolean** [comment]
@workshur backend done, pending frontend. PR: #1367
