### ISSUE TITLE
Topic Creation: Inconsistency in Deleted parameters

### ISSUE THREAD

**Issue by Khakha-A** [provectus/kafka-ui#1213]
**Describe the bug**
When creating a new topic, you have the ability to add custom parameters. When selecting a custom parameter, you can delete it, but if you want to add it again, it is either greyed out or still accessible -- and it should be not.

**Set up**
http://redesign.internal.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Go to Topics - Add a Topic
2. Add custom parameter - Select Preallocate
3. Add custom parameter - Select retention.bytes
4. Add custom parameter - Select segment.bytes
5. Delete preallocate parameter - Cannot be seelcted when clicking Add custom parameter
6.  Delete retention.bytes - Add custom parameter - preallocate not greyed out /available for selection
7. Delete segment.bytes - Add custom parameter - add deleted parameters are available for selection

**Expected behavior**
When parameter is deleted, it can be immediately added again, without inconsistencies

**Screenshots**
(If applicable, add screenshots to help explain your problem)

**Additional context**
There may a small lag in how the tool processes the add/delete functionality. It seems to affect specific parameters like preallocate, though.

**Comment by Haarolean** [comment]
a similar one for the old design: #996
