### ISSUE TITLE
No pop-up when a topic with -1 replication factor is created

### ISSUE THREAD

**Issue by Khakha-A** [provectus/kafka-ui#1218]
**Describe the bug**
You don't get a pop-up when creating a new topic with a negative replication factor (-1). The topic is created and displayed in the list of topics with 1.

**Set up**
http://redesign.internal.kafka-ui.provectus.io/ui

**Steps to Reproduce**

1. Go to Topics - Add a new Topic
2. Select Replication Factor -1 - Send
3. Check the list of topics - A topic with replication factor 1 is created

**Expected behavior**
The tool displays a pop-up not allowing to create a topic with negative replication factor.

**Screenshots**
(If applicable, add screenshots to help explain your problem)

**Additional context**
Note that the tool displays a required pop-up for -2, -3, etc. It seems that just -1 causes the issue.

**Comment by Hurenka** [comment]
Can't reproduce this one
