### ISSUE TITLE
Pop up for Clear Messages (not clear/remove at once)

### ISSUE THREAD

**Issue by Khakha-A** [provectus/kafka-ui#1229]
### Is your proposal related to a problem?

When accessing the Messages tab in a specific topic, you have the option to clear messages
![image](https://user-images.githubusercontent.com/39586798/145584117-92aaec22-e550-4f06-a08d-7bb46ea84bcd.png)
When clicked, all messages are removed at once - no warning pop up is displayed; you cannot restore deleted messages.

### Describe the solution you'd like

Please add a warning pop up so that users don't accidentally delete all messages, and have no ability to restore them.

### Describe alternatives you've considered

--

### Additional context

--

**Comment by Haarolean** [comment]
Fixed within #1324
