### ISSUE TITLE
Different number of Messages after sorting Latest first/Newest first

### ISSUE THREAD

**Issue by agolosen** [provectus/kafka-ui#1230]
**Describe the bug**
(A clear and concise description of what the bug is.)
After clicking the button Latest first/Newest first on the tab 'Messages' the different number of messages is displayed.

**Set up**
(How do you run the app? 
Which version of the app are you running? Provide either docker image version or check commit hash at the top left corner. We won't be able to help you without this information.)
http://redesign.internal.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to the menu item Topics
2. Choose some topic with a number of messages of more than 2
3. Click the button 'Latest first/Newest first' choosing the order of sorting
4. Compare the written number under the button for both options of sorting.
5. Compare the written number to the number of messages on the page after sorting.

**Expected behavior**
(A clear and concise description of what you expected to happen)
1. The written number under the button is the same before and after sortings.
2. The written number equals the number of messages on the page after sorting.

**Screenshots**
(If applicable, add screenshots to help explain your problem)
![image](https://user-images.githubusercontent.com/92585878/145587169-5615a3b5-a47a-4310-be9d-2c953d385485.png)
![image](https://user-images.githubusercontent.com/92585878/145587293-eeb70964-2ab4-4e28-a2c7-6baad52785a3.png)

**Additional context**
(Add any other context about the problem here)
This bug is floating, sometimes the number is really different like for this topic http://redesign.internal.kafka-ui.provectus.io/ui/clusters/local/topics/_schemas/messages?attempt=1&limit=100&seekDirection=BACKWARD&seekType=OFFSET&seekTo=0::57
Sometimes only the written number is different but the amount of messages is right and equal like here http://redesign.internal.kafka-ui.provectus.io/ui/clusters/local/topics/dev-cp-kafka-connect-status/messages?attempt=2&limit=100&seekDirection=FORWARD&seekType=OFFSET&seekTo=0::0,1::0,2::0,3::0,4::0
Sometimes it works correctly like here http://redesign.internal.kafka-ui.provectus.io/ui/clusters/local/topics/Test_Part6/messages?attempt=1&limit=100&seekDirection=BACKWARD&seekType=OFFSET&seekTo=0::1,1::2,2::2,3::3,4::2,5::2

The same behaviour was before the redesign.

**Comment by iliax** [comment]
@agolosen it is a expected behaviour since 'messages' it not a number of all messages in topic, but a number of **scanned** messages needed to form result page, which can different for different sorting options. It can be be more visible if you fill Seach field. The same is for size & time near messages count. 
Maybe we should explicitly rename 'messages' to 'scanned messages' to get rid of such confusion.
