### ISSUE TITLE
Add field bulk actions to Schemas page for changing Global Compatibility Level

### ISSUE THREAD

**Issue by agolosen** [provectus/kafka-ui#1236]
### Is your proposal related to a problem?

(Write your answer here.)
Now it's possible to change Global Compatibility Level only for all schemas from the list. But in case you need to change it for some schemas, the option Select isn't available http://redesign.internal.kafka-ui.provectus.io/ui/clusters/local/schemas
### Describe the solution you'd like

(Describe your proposed solution here.)
Adding a field with checkboxes at the very beginning of the schemas list could provide a choice of which schemas should change the Global Compatibility Level.
### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by Haarolean** [comment]
Global compatibility level is a, well, global thing with no relation no particular schemas.
