### ISSUE TITLE
Inconsistency of Search for Messages (Topics)

### ISSUE THREAD

**Issue by agolosen** [provectus/kafka-ui#1242]
### Is your proposal related to a problem?

(Write your answer here.)
Through the app in the search line, we see a reading-glass icon and the names of the fields by which the search is done, also the search starts immediately after typing in the search line. However, the behaviour of Search on the page Topics->Topic_name -> Messages is different: the search works only by clicking the button Submit.

### Describe the solution you'd like

(Describe your proposed solution here.)
Please make Search on tab Messages clear for users:
1. Visually combine all search fields and button submit.
2. Add hints to search line like Search by Key, Content
3. Maybe it makes sense to search by Key, Content immediately after typing in the search line as it does on other pages of the app.
### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)
![image](https://user-images.githubusercontent.com/92585878/145812990-3d323a1d-a6c5-4953-9e03-c1cf7504c4a0.png)

**Comment by Haarolean** [comment]
The thing is, this particular search box is a complex one, there are different filters present (to the right side), so immediate filtering is not a thing here. Other search inputs are kind of solid and persistent for now.
