### ISSUE TITLE
Redesign: topic creation fails randomly

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#1252]
Sometimes upon creating a topic this happens:
`404 Topic not found`
Clicking the button again produces this:
`400 Topic 'deltest' already exists.`.

**Comment by MichaelGonzalezMurillo** [comment]
This is what I get when reproducing it **java.util.concurrent.CompletionException: org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.**

It does randomly happen.

https://issues.apache.org/jira/browse/KAFKA-6221

**Comment by Haarolean** [comment]
Blocked by kafka's issue
