### ISSUE TITLE
Healthcheck endpoint returns 401 when BASIC Authentication is enabled

### ISSUE THREAD

**Issue by dtowf** [provectus/kafka-ui#1257]
**Describe the bug**
When Basic Authentication is enabled, the endpoint /ui/actuator/health returns a 401 code. Health check should be unauthenticated and return 200 on success, and 4XX on failure.

The health check endpoint is currently whitelisted when [OAUTH authentication](https://github.com/provectus/kafka-ui/blob/683ab231f436893b364a44d2fcff700f4ccbbbce/kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/OAuthSecurityConfig.java#L35) is enabled, but not for BASIC Authentication: 

**Set up**
Currently using 0.2.1 in ECS Fargate as a docker image. Fronted by an ALB with health check pointing to /ui/actuator/health

**Steps to Reproduce**

1. Enable Authentication via environment variable
"AUTH_ENABLED" : "true"
"SPRING_SECURITY_USER_NAME" : "admin"
"SPRING_SECURITY_USER_PASSWORD" : "mysecretpassword"
2. Hit endpoint /ui/actuator/health
3. Receive 401 code

**Expected behavior**
Expect a 200 success when hitting /ui/actuator/health

**Screenshots**
<img width="688" alt="Screen Shot 2021-12-16 at 8 37 13 am" src="https://user-images.githubusercontent.com/88873019/146269021-521b5c92-f16e-4b64-8dd0-8c26f8c3f08a.png">

**Additional context**
Current work around is to allow 401 on the ALB health check, however it would be better if 200 was provided on success.

**Comment by Haarolean** [comment]
Hey, thanks for raising the issue. This will be fixed within #1173
