### ISSUE TITLE
Topic messages: Smart filters

### ISSUE THREAD

**Issue by soffest** [provectus/kafka-ui#127]
1. Add query parameter js-filter with java script  predicate function
2. Add Nashorn dependency
3. Filter messages before string inclusion using this function and record
4. Pass variables to function:
4.1 key (key object)
4.2 value (content object)
4.3 headers
4.4 offset
4.5 partition

UPD: design for the frontend part is already done on figma
+ Support message preview (partial selection of  json fields)
+ Support searching by message headers (requested in #780)

**Comment by Haarolean** [comment]
#1741
