### ISSUE TITLE
Use AWS ECR for kafka-ui-infra envrionment

### ISSUE THREAD

**Issue by 5hin0bi** [provectus/kafka-ui#1298]
Need to:
1. Build and push kafka-ui images to AWS ECR + DOCKERHUB.
2. Use AWS ECR in kafka-ui-infra argocd to pull kafka-ui images instead of DOCKERHUB.

**Comment by azatsafin** [comment]
This issue is not more relevant, because we stopped to use ArgoCD image updater tool. This tool is use pull mechanism to get image hash for latest image periodically, this is why we had reached Docker Hub pull limits. So, we can close issue.
