### ISSUE TITLE
Whether kafka3.0 is supported.

### ISSUE THREAD

**Issue by ckk942062217** [provectus/kafka-ui#1300]
### Is your proposal related to a problem?

(Write your answer here.)

### Describe the solution you'd like

(Describe your proposed solution here.)

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by Haarolean** [comment]
Hi, thanks for your concern regarding kafka3.
As far as I can see, kafka-ui works fine with latest confluent kafka image (7.x.x, which is based on kafka 3.0-IV1).
If you find any bugs with this version, let us know!
