### ISSUE TITLE
AWS Glue support

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#1306]
### Discussed in https://github.com/provectus/kafka-ui/discussions/1305

<div type='discussions-op-text'>

<sup>Originally posted by **miguellgramacho96** December 21, 2021</sup>
Hi!

I'm currently storing the avro schema in the aws glue schema registry.
How can I (if its even possible) apply a avro schema to all of the messages from one topic, if I dont connect the kafka-ui to aws glue schema registry? (I think kafka-ui does not support aws glue).

Kind regards.</div>

**Comment by Haarolean** [comment]
https://github.com/awslabs/aws-glue-schema-registry

**Comment by nikola-vukadinov-htec** [comment]
Hi! Do you have an idea when will this issue be implemented? Thanks!

**Comment by Haarolean** [comment]
@nikola-vukadinov-htec hey, probably within a few weeks.

**Comment by ekeric13** [comment]
So it seems this will be in release 0.5. Is there a roadmap on when that will be released?

**Comment by DBTK1990** [comment]
@Haarolean can i become a contributor for this feature will be glad to take this from your hand, really love this product,
and would like to help :)

**Comment by Haarolean** [comment]
> @Haarolean can i become a contributor for this feature will be glad to take this from your hand, really love this product, and would like to help :)

hi and welcome! Yeah, please, go ahead. 
Please note that we have some (de)serializers for schema registry, so we'd have to implement some for glue as well. Also note that #1816 is in progress so we might need to refactor it in the future.
Also, feel free to join us on discord if you have any questions (development-related, or in general).

**Comment by DBTK1990** [comment]
can u give me an invite link for the discord group
u can send it to my email dudu.benafashi@gmail.com

**Comment by Haarolean** [comment]
https://discord.gg/4DWzD7pGE5
it's in the readme as well, btw

**Comment by Haarolean** [comment]
@DBTK1990 any luck?

**Comment by pc-akothapeta** [comment]
I am interested in this too.. let me know when this feature will be implemented. Thanks

**Comment by Haarolean** [comment]
@pc-akothapeta it kinda already is. We're waiting for some stuff to be done before it's usable.

**Comment by pc-akothapeta** [comment]
> @pc-akothapeta it kinda already is. We're waiting for some stuff to be done before it's usable.

Thanks @Haarolean
