### ISSUE TITLE
ksqldb

### ISSUE THREAD

**Issue by putao0525** [provectus/kafka-ui#1308]
![image](https://user-images.githubusercontent.com/12529019/147042023-2fba4c1d-4d3d-4e14-9311-1e5ddb76140c.png)

why ? 

![image](https://user-images.githubusercontent.com/12529019/147042144-587c17ba-8ea8-490b-9f21-ab2e32b742bc.png)

**Comment by putao0525** [comment]
![image](https://user-images.githubusercontent.com/12529019/147042282-9fce5223-34b4-42c3-831e-521e131921f6.png)

**Comment by putao0525** [comment]
I am not familiar with the use of proxy and webFlux, and my  English is not good

**Comment by Haarolean** [comment]
Hi, thanks for reaching out, we’ll take a look into this :)

**Comment by putao0525** [comment]
> Hi, thanks for reaching out, we’ll take a look into this :)
> […](#)
> On 22 Dec 2021, at 09:02, 陆遥 ***@***.***> wrote: ﻿ I am not familiar with the use of proxy and webFlux, and my English is not good — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.

Access through a tool like Postman is fine, but access through a front-end page is problematic

**Comment by Haarolean** [comment]
Could you please share the details on how do you run the app? Docker compose/k8s/helm? And your environment variables without sensitive values
