### ISSUE TITLE
Tag master docker image with a version number tag

### ISSUE THREAD

**Issue by swilliams-a3digital** [provectus/kafka-ui#1315]
The ":latest" tag does not have the latest.  It looks like the most recent image is only tagged as ":master".  It would be nice if it was tagged with a version number.  We like to specify a specific version so we know what we are installing.  The version from 3 months ago was tagged as 0.23.1.  Looking for something similar with the most recent image.

**Comment by Haarolean** [comment]
Hi, thanks for reaching out. The thing is, `latest` points to latest *release* version.
We'll consider additionally labelling each commit with a dockerhub label as well.
Btw, there's a 0.3 release coming out soon (this week).
