### ISSUE TITLE
kafka ui helm chart is unavailable

### ISSUE THREAD

**Issue by allexdav** [provectus/kafka-ui#1330]
**Describe the bug**
https://provectus.github.io/kafka-ui - error 404 

**Set up**
browser, hands, URL :)

**Steps to Reproduce**
Open link in browser

**Expected behavior**
helm chart as stated in your guide
located here  https://github.com/provectus/kafka-ui#running-in-kubernetes 
Running in Kubernetes
helm repo add kafka-ui https://provectus.github.io/kafka-ui
helm install kafka-ui kafka-ui/kafka-ui

**Screenshots**
(If applicable, add screenshots to help explain your problem)

**Additional context**
Created a link after email discussipn with Roman and German

**Comment by Haarolean** [comment]
hey Alexey, thanks for jumping in here.
We'll take a look as soon as possible.

**Comment by Haarolean** [comment]
Seems like everything works fine, since the file `index.yaml` required for helm, is indeed [present](https://provectus.github.io/kafka-ui/index.yaml). There's just `index.html` missing :) We'll add some to clarify that the repo does actually work.

**Comment by Haarolean** [comment]
Added a simple page.
