### ISSUE TITLE
[bug][minor] New UI looks broken in a few places

### ISSUE THREAD

**Issue by akamensky** [provectus/kafka-ui#1333]
**Describe the bug**

First thanks for a new more compact UI, it is definitely an improvement on the previous version. Just a few issues I noticed while testing new 0.3.0 release (some UI and some functional on frontend side).

The Dashboard UI looks broken with large number of clusters. The table is split into multiple with 2 clusters in each, causing columns be not aligned:

![Screenshot from 2021-12-29 09-33-42](https://user-images.githubusercontent.com/985805/147619185-8ff5379c-8022-4905-9c85-cd43ce179572.png)

The breadcrumbs are replacing hyphens with spaces:

![Screenshot from 2021-12-29 09-43-57](https://user-images.githubusercontent.com/985805/147619638-f1f20fd1-8a3a-4673-a9a7-ed7b8e94df0d.png)

KC Connector Overview UI shows red dot next to "tasks failed" and "f0" instead of 0: 

![Screenshot from 2021-12-29 09-45-11](https://user-images.githubusercontent.com/985805/147619699-da67f455-2497-4bd4-a61d-76f6183374ad.png)

Same for Under replicated partitions (btw, I think URP should not be abbreviated like that as nowhere it is being used like this, meanwhile in sync replicas CAN be abbreviated to ISR as that is used in many places in documentation and articles):

![Screenshot from 2021-12-29 09-47-05](https://user-images.githubusercontent.com/985805/147619862-5e0ee153-04ed-4195-bf30-26af6f2b795f.png)

Sorting where available (i.e. list of all topics in a cluster) can only be done in ASC order, no DESC for some reason.

**Set up**
Docker image `Version: v0.3.0 (9606d7e)`

**Steps to Reproduce**

1. Add 15+ clusters
2. Have some topics/schemas/connectors with hyphens in name
3. Have some connects running with 0 failed tasks
4. Have some topic with 0 under replicated partitions

**Expected behavior**
1. Tables are not broken down
2. Hyphens in names are not replaced with spaces
3. Status of things like failed tasks and URP is shown correctly (green label/dot) with a correct number
4. Sorting where available can be done both in ASC and DESC orders)

**Screenshots**
See above

**Additional context**
N/A

**Comment by Haarolean** [comment]
Hey Alexey, thanks for your kind feedback.

Regarding the issues, we're still have a lot of small quirks to fix. We're planning on releasing additional builds every few weeks.

**Comment by alexnikitchuk** [comment]
Also found double scrollbars if message content is too large. Go to Topics -> Click on topic -> click on Messages tab -> expand message -> click on Content
![image](https://user-images.githubusercontent.com/8694829/147741209-5f9b8c0c-045d-4788-84a0-924e9b815bec.png)
