### ISSUE TITLE
helm Ingress is deprecated 

### ISSUE THREAD

**Issue by bahaeddinoz** [provectus/kafka-ui#1337]
### Is your proposal related to a problem?
Can we change the ingress to make compatiable with k8s v1.22+

(Write your answer here.)

### Describe the solution you'd like
Can we change the ingress to make compatiable with k8s v1.22+

(Describe your proposed solution here.)

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by Haarolean** [comment]
Hey, thanks for reaching out. We'll take a look.

**Comment by bahaeddinoz** [comment]
Thanks @Haarolean for the so quick updates 🙏 Just one question why directly didn't we use the "networking.k8s.io/v1 " and instead specified if k8s version is highter then 1.22 ? k8s supports it since v1.10. Can be good to use it directly or is there any other reason ?
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#apiservice-v122

**Comment by Haarolean** [comment]
@bahaeddinoz first of all, your documentation says it's supported since 1.19, not 1.10 (`Migrate manifests and API clients to use the networking.k8s.io/v1 API version, available since v1.19.`). The main purpose is to save back compatibility.
