### ISSUE TITLE
protobuf schema is not formatted properly

### ISSUE THREAD

**Issue by alexnikitchuk** [provectus/kafka-ui#1346]
**Describe the bug**
Protobuf schema is not formatted properly (see screenshot below)

**Set up**
1. Setup Kafka UI with Schema Registry
2. Add a proto schema to Schema Registry

**Steps to Reproduce**
1. open Kafka UI
2. go to Schema Registry page 
3. click on registered protobuf schema

**Expected behavior**
Protobuf schema is well formatted: 
```
syntax = "proto3";

message User {
    string name = 1;
    int64 favorite_number = 2;
    string favorite_color = 3;
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/8694829/147738738-2b7e6b8c-a00d-4cd2-a38c-a4230a06705c.png)

**Additional context**
N/A

**Comment by Haarolean** [comment]
Hi, thanks for reaching out. Seems like this is the problem which appeared after the redesign. We'll fix it within next minor releases.

**Comment by Motherships** [comment]
It seems #1190 is related
Your PR fixes this
