### ISSUE TITLE
Snappy support missing

### ISSUE THREAD

**Issue by JoeryH** [provectus/kafka-ui#1347]
Hi guys,

My avro data in kafka is compressed with Snappy. Kafka-ui prints this stacktrace when I load messages:

```txt
java.lang.NoClassDefFoundError: Could not initialize class org.xerial.snappy.Snappy
	at org.xerial.snappy.SnappyInputStream.hasNextChunk(SnappyInputStream.java:435)
	at org.xerial.snappy.SnappyInputStream.read(SnappyInputStream.java:466)
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:270)
```
I fixed this locally by adding

```xml
        <dependency>
            <groupId>org.xerial.snappy</groupId>
            <artifactId>snappy-java</artifactId>
            <version>1.1.7.3</version>
        </dependency>
```

Which gave me something like:
```txt
java.lang.UnsatisfiedLinkError: /tmp/snappy-1.1.7-5cec5405-2ce7-4046-a8bd-922ce96534a0-libsnappyjava.so: 
Error loading shared library ld-linux-x86-64.so.2: No such file or directory
```

Which I solved by adding `gcompat` to the `apk add` command.

Would be awesome to have this added to this amazing project.

**Comment by JoeryH** [comment]
Hi 👋

**Comment by Haarolean** [comment]
Hi Joery, 
thanks for your interest in kafka-ui. And thank you for the solution! 
We’re having a long holidays streak here, so we’ll get back to this issue somewhere around 10th of January. 
Happy holidays!

**Comment by iliax** [comment]
Hi @JoeryH, we fixed this bug in current master - you can use docker image with "master" tag (sha256:5c1346c11a876af0d25bd2871409631b01a0d7d15c0ef22c40db16390aa1f919)

**Comment by JoeryH** [comment]
hey, the latest version works for me! Thank you for the quick fix!

**Comment by Haarolean** [comment]
@JoeryH glad it works!
