### ISSUE TITLE
data masking in provectus-kafka-ui

### ISSUE THREAD

**Issue by nemerna** [provectus/kafka-ui#1352]
### Is your proposal related to a problem?

in case users need to allow specific pepole to view the data inside topics messages for example
where they need other group of pepole to only see the title of the messages without the content 
then a data msking could be very helpful
### Describe the solution you'd like

add an option to enable datamasking
then when a specific user is authenticated and he is supposed to see the masked data only
when a more privileged user access to the ui he will be able to see the real content of messages
### Describe alternatives you've considered

regarding the user privilege based access ive been using an authentication proxy
where i have cofigure the same kafka cluster in the ui twice
but if the data masking was available then i would mention that flag in one of the cluster
then the auth-proxy will be able to give access to specific pepole into a specific kafka cluster inside the ui
### Additional context

in case data masking isnt available yet 
then me & my team may be able to contribute to this project and add this feature

**Comment by Haarolean** [comment]
Hi, thanks for reaching out.
We'll implement this as a part of the feature #753.
