### ISSUE TITLE
Unicode appear in topic.messages instead of Big Decimal

### ISSUE THREAD

**Issue by nemerna** [provectus/kafka-ui#1354]
### Is your proposal related to a problem?

when i define a schema in scheam registry where i need to push a key of type byte and
the values are presented inside the ui as unicode
for example:
		"bytes": "\u0002"
where i am expecting:
000920011700048000480004800050
asa bigDecimal
### Describe the solution you'd like

decerialize all /u prefix values into decimal values

### Describe alternatives you've considered

i didn't tried to resolve the issue yet
but i will try to have a look into the source code of the project and try to add another decode level
depending on environment variable which i will call
KAFKA_CLUSTERS_0_DECODE_UNICODE: true
### Additional context

i would be happy if i get small guidance on which src files to have a look where those are the files realted 
to adding this feature

**Comment by Haarolean** [comment]
Hey, thanks for reaching out.

We appreciate the wish to help, but we'll need to take a look at this ourselves first, since I'm not sure if it's more of a frontend or the backend thing.

**Comment by Haarolean** [comment]
@nemerna, could you please share an example schema you have for this kind of purpose?

**Comment by nitin1677** [comment]
we are using v0.4.0 and facing the same with bigdecimal in schemaregistry, displayed values are like "bytes": "#òoÁ\u0000\u0000", what is the plan to release the fix for bigdecimal support?

**Comment by Haarolean** [comment]
@nitin1677 this might get resolved within #2125. Can you provide an example schema to reproduce this behavior?

**Comment by nitin1677** [comment]
i tried to deploy from master branch, which was deployed from the following commit:
https://github.com/provectus/kafka-ui/commit/a9c31e6

still getting the same issue, field value is displayed as below:
"field1": {
"bytes": "#òoÁ\u0000\u0000"
},

Schema definition for the field is as below:
{
"name": "field1",
"type": [
	"null",
	{
		"type": "bytes",
		"logicalType": "decimal",
		"precision": 24,
		"scale": 16
	}
],
"doc": "test description.",
"default": null
}

**Comment by pgomes-lgc** [comment]
this stuff is still happening in v0.7.1

**Comment by Haarolean** [comment]
@pgomes-lgc raise a new issue
