### ISSUE TITLE
0.3.x Regression: SSO/OAuth2 support

### ISSUE THREAD

**Issue by clocklear** [provectus/kafka-ui#1359]
**Describe the bug**
There appears to be a regression on SSO/OAuth2 support via Spring Security that appeared between the transition from 0.2.1 to 0.3.0.  Following the guidance outlined in the SSO doc no longer yields a working SSO set up.  When I pass a known working ClientID, Client Secret, and Issuer URI into the 0.3.1 docker image, all login attempts fail with the error 'Invalid Credentials'.  No further information is given.

**Set up**
I'm running the `provectuslabs/kafka-ui:0.3.1` docker image available on docker hub.

**Steps to Reproduce**

Start `provectuslabs/kafka-ui:0.3.1`, passing in the following environment variables, and attempt to log in.

```
- AUTH_TYPE=OAUTH2
- SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_AUTH0_ISSUER_URI=<omitted>
- SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_AUTH0_CLIENTID=<omitted>
- SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_AUTH0_CLIENTSECRET=<omitted>
```

**Expected behavior**
Expected to land on app index after successful login

**Screenshots**
Screenshot of login failure (with our auth0 tenant omitted):
![image](https://user-images.githubusercontent.com/622205/148557033-92690bd0-8931-403c-892c-89ba139ee17a.png)

**Additional context**
This worked fine in (what I perceive to be) older versions of Spring that were used by the app in `0.2.1`.  I suspect there is more configuration that is required now and I am not familiar enough with Spring to understand what I should do to resolve the issue.

**Comment by Haarolean** [comment]
Hey, thanks for reaching out. I'll take a look at this on Monday.

**Comment by Haarolean** [comment]
@clocklear could you please try adding this env variable?
`SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_AUTH0_SCOPE: "openid"`
let me know how it goes

**Comment by clocklear** [comment]
> @clocklear could you please try adding this env variable?
> SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_AUTH0_SCOPE: "openid"
> let me know how it goes

That seems to fix it!  I suspected it might not know which scope needs to be present in order to 'authorize' the app; thanks for digging in and finding the solution!

This actually is a huge benefit for us; we can now control which folks in our organization can access the app instead of allowing anyone with a valid org login.  Huge win.  Thanks again!

**Comment by Haarolean** [comment]
Thanks for the feedback! Glad it worked.

We'll take care of documentation.
