### ISSUE TITLE
Create parameters of request for sorting topics

### ISSUE THREAD

**Issue by NelyDavtyan** [provectus/kafka-ui#1383]
**Describe the bug**
We can't get sorted names of topics 

**Steps to Reproduce**

1. 

**Expected behavior**
On clicking sorting button we should be able to have soretd list of names from A-Z and from Z-A. Now we get only A-Z

![image](https://user-images.githubusercontent.com/96067981/149346164-b63011bf-e88e-4fdd-85d3-f78daf0de03f.png)

**Additional context**
It will be better to send additional params in request

**Comment by Haarolean** [comment]
TopicsService#getComparatorForTopic implement sorting order (ASC/DESC)
