### ISSUE TITLE
Ignore spaces at the beginning and end of the Schema Name

### ISSUE THREAD

**Issue by agolosen** [provectus/kafka-ui#1385]
### Is your proposal related to a problem?

(Write your answer here.)
In case you put/past spaces before or after schema name at field Subject * while Create Schema the new schema isn`t creating. It`s not obvious that there are spaces there, it could irritate if you copy/paste for example.
### Describe the solution you'd like

Ignore spaces before and after the Schema Name at Schema Registry -> Create Schema.

(Describe your proposed solution here.)

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by jonasgeiregat** [comment]
I can tackle this one!

**Comment by Corlobin** [comment]
I receive a error when I try to add spaces at the beginning of the schema name: 
<img width="558" alt="image" src="https://user-images.githubusercontent.com/1748946/155450388-ecad5634-4e56-4c12-8362-1e813e8fb77c.png">
Is this still an issue? backend or frontend?

**Comment by jonasgeiregat** [comment]
I'm also only to reproduce this on master @agolosen ?

**Comment by Haarolean** [comment]
> I'm receiving an error when I try to add spaces at the beginning of the schema name: <img alt="image" width="558" src="https://user-images.githubusercontent.com/1748946/155450388-ecad5634-4e56-4c12-8362-1e813e8fb77c.png"> Is this still an issue? backend or frontend?

which version are you on? Revision, more importantly.

**Comment by Haarolean** [comment]
Works fine on master.
