### ISSUE TITLE
SR: Display a clear warning message if a schema already exists

### ISSUE THREAD

**Issue by agolosen** [provectus/kafka-ui#1386]
### Is your proposal related to a problem?

(Write your answer here.)
If you try to create a schema with a name that already exists now is displaying an unclear message (the same for already existing name, invalid syntax, incorrect schema`s type).

### Describe the solution you'd like

(Describe your proposed solution here.)
Display a clear warning message what the problem is, i.e. for this case, 'There is already a schema with the name XXX'.
 
### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by Haarolean** [comment]
Related #1387.

**Comment by Haarolean** [comment]
Connectors error messages are broken as well
![image](https://user-images.githubusercontent.com/1494347/151330767-32c21223-e5a7-447b-be65-7bccafcf6d09.png)

**Comment by Haarolean** [comment]
Topic creation:
<img width="541" alt="image" src="https://user-images.githubusercontent.com/1494347/153438290-dfc64d0e-8cd6-4235-8ec5-4d16f2df39a3.png">
