### ISSUE TITLE
open-id/oauth2 authentication for user interface

### ISSUE THREAD

**Issue by tilmann-bartsch** [provectus/kafka-ui#1393]
### Is your proposal related to a problem?

I would like to authenticate kafka-ui using a keycloak server.

### Describe the solution you'd like

Simple authentication can be obtained by the open-id/oauth2 implicit flow as described in
[OpenID Connect Implicit Client Implementer's Guide](https://openid.net/specs/openid-connect-implicit-1_0.html) which is supported by keycloak.

To achieve this I'd like to use the following environment variables in `docker-compose.yml`:
```
AUTH_TYPE="OAUTH_IMPLICIT_FLOW"
OAUTH_CLIENT_ID="kafka-ui"
OAUTH_AUTHORIZATION_URL="http://127.0.0.1:8080/auth/realms/master/protocol/openid-connect/auth"
```
where the URL is the default authorization endpoint of a Keycloak-Server in realm `master`.

Kafka-ui should then follow the implicit flow by redirecting:
```
GET "$OAUTH_AUTHORIZATION_URL"?
    response_type=id_token%20token
    &client_id="$OAUTH_CLIENT_ID"
    &redirect_uri=<kafka-ui-url>
    &scope=openid%20profile
    &state=af0ifjsldkj
    &nonce=n-0S6_WzA2Mj
```
the keycloak server redirects to `<kafka-ui-url>` and adds `access_token`, `token_type`, `id_token` which is used by kafka-ui to deny or grant access.

### Describe alternatives you've considered

A simpler but less general solution would be to use the `keycloak-js` library as described in this [medium-article](https://medium.com/keycloak/secure-react-app-with-keycloak-4a65614f7be2).

**Comment by Haarolean** [comment]
Hey, thanks for raising the issue. As I mentioned on discord, unfortunately it's not solvable by configuration alone, we'll have to implement some keycloak support.

**Comment by Haarolean** [comment]
Hey, actually I thought you need keycloak with roles.
If you need just the oauth, that's probably gonna work out of the box.
You could refer to [SSO guide](https://github.com/provectus/kafka-ui/blob/master/guides/SSO.md) and try the settings described there. Let me know how it goes.

**Comment by Dugong42** [comment]
FYI, I posted an example of Keycloak configuration as OIDC provider, see #3298

**Comment by Haarolean** [comment]
@alexted the documentation is open-source as well, located in `docs` branch. PRs are welcome!
