### ISSUE TITLE
Start using github reusable workflows

### ISSUE THREAD

**Issue by 5hin0bi** [provectus/kafka-ui#1398]
Currently we have several common actions done inside of workflows.
We can template the situation using GH reusable workflows: https://docs.github.com/en/actions/using-workflows/reusing-workflows

build in push docker image from branch and branch name extracting is the point to start.

**Comment by 5hin0bi** [comment]
Waiting for the github to allow passing dynamic variables to reusable workflows.

**Comment by Haarolean** [comment]
Closing due to limited usability
