### ISSUE TITLE
Incorrect charts service targetPort value  

### ISSUE THREAD

**Issue by Shodded** [provectus/kafka-ui#1399]
**Describe the bug**
On the Kuberenetes [service.yaml](https://github.com/provectus/kafka-ui/blob/611307ef59b7c5853716fcf4badd09c57ad347c5/charts/kafka-ui/templates/service.yaml#L15) chart targetPort is currently `http`, when it should be `8080`. Which this port is the current container's port from the [deployment.yaml](https://github.com/provectus/kafka-ui/blob/611307ef59b7c5853716fcf4badd09c57ad347c5/charts/kafka-ui/templates/deployment.yaml#L56). 
Only when I changed targetPort to 8080 it worked for me.

**Set up**
Helm: _version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.17.2"}_

App Version: _v0.3.1 (e75c251)_

**Steps to Reproduce**

Step 1: Installation
Helm upgrade --install kafka-ui ./<charts_directory> -f ./<values_file>

values_file:
Make sure that there is an option to get to the service port 
```
fullnameOverride: "kafka-ui"
service:
  type: NodePort
  port: 999
```

Step 2: Export port forward
kubectl port-forward deployment/kafka-ui 999:8080 

The Service will not have any communication at the moment. 
It should work after the service.yaml fix as described above.

**Expected behavior**
Should be able to browse the manager app on http://localhost:999/

**Comment by Haarolean** [comment]
Hey, thanks for reaching out. We'll take a look into this.

@5hin0bi fyi

**Comment by Haarolean** [comment]
So, 
>On the Kuberenetes service.yaml chart targetPort is currently http, when it should be 8080

No, it shouldn't. It's an alias for a pod/sts/deployment which is being forwarded by a reference to `deployment.yaml`, where it's defined.

Next,

passing values as such:
```
fullnameOverride: "kafka-ui"
service:
  type: NodePort
  port: 999
```
makes the service expose port `999` on *each node* that redirects all the traffic to selected pods.

The command `kubectl port-forward deployment/kafka-ui 999:8080` exposes port `999` and maps it to the port `8080` of the pods within the deployment. This works fine and has nothing to do with the previous config.

So I don't get what is your goal here. We've deployed the chart the way you described and it works fine for us.
`kubectl port-forward deployment/kafka-ui 30999:8080` - allows to access kafka-ui on http://localhost:30999
`kubectl port-forward svc/kafka-ui 30999:999` - allows to access kafka-ui on http://localhost:30999
