### ISSUE TITLE
Edit Schema is throwing error from backend for JSON and AVRO types

### ISSUE THREAD

**Issue by NelyDavtyan** [provectus/kafka-ui#1402]
**Describe the bug**
(A clear and concise description of what the bug is.)
While working on https://github.com/provectus/kafka-ui/issues/1388 I noticed that after submitting changes for both JSON and AVRO types in edit schema page it throws backend error and changes aren't being saved.
For Protobuf type backend works fine.

**Set up**
(How do you run the app? 
Which version of the app are you running? Provide either docker image version or check commit hash at the top left corner. We won't be able to help you without this information.)

**Steps to Reproduce**

1.Go to Schema registry
2.Select schema with JSON or AVRO schemaType
3.press Edit Schema button
4.make changes and press Submit button 

**Expected behavior**
(A clear and concise description of what you expected to happen)

**Screenshots**
(If applicable, add screenshots to help explain your problem)
![Screenshot from 2022-01-17 16-47-51](https://user-images.githubusercontent.com/96067981/149898286-9b5997b1-e624-4885-8c1a-9aecc64e85a3.png)
![Screenshot from 2022-01-18 12-31-28](https://user-images.githubusercontent.com/96067981/149899770-b3ffa0bc-5724-41ad-8459-592909c73bb5.png)

**Additional context**
(Add any other context about the problem here)

**Comment by maratgaliev** [comment]
@vdanylenko hey! Any updates here? What's the status on this issue?

**Comment by vdanylenko** [comment]
Can't reproduce this one on the master.

**Comment by moravcik94** [comment]
same problem here

**Comment by Haarolean** [comment]
@moravcik94 hey, can you provide steps to reproduce this?
