### ISSUE TITLE
UI: Invalid button title on Connector Tasks page

### ISSUE THREAD

**Issue by iliax** [provectus/kafka-ui#1412]
**Describe the bug**
(A clear and concise description of what the bug is.)

Go to Connectors -> Select any connector -> Tasks ->  Click ... -> Button should be called 'Restart' not Clear messages

**Set up**
(How do you run the app? 
Which version of the app are you running? Provide either docker image version or check commit hash at the top left corner. We won't be able to help you without this information.)

**Steps to Reproduce**

1. 

**Expected behavior**
(A clear and concise description of what you expected to happen)

**Screenshots**
(If applicable, add screenshots to help explain your problem)

**Additional context**
(Add any other context about the problem here)

**Comment by iliax** [comment]
<img width="1457" alt="Screenshot 2022-01-19 at 12 17 09" src="https://user-images.githubusercontent.com/702205/150102216-7a1370d8-4798-4071-bf1b-a6bf8017b0cf.png">

**Comment by 5hin0bi** [comment]
Btw team, I’ve noticed that the button in the screenshot seem to bring no effect when a task is failed, however, “clear messages” which is restart - does restart particular task. Can you check it please?
You can wait for reddit connector to fail someday (it sometimes fails) and try to click it.
![image](https://user-images.githubusercontent.com/94184844/150106690-d731af8a-4a52-402c-8e6d-374c2aede023.png)

**Comment by iliax** [comment]
@5hin0bi please create ticket for it

**Comment by 5hin0bi** [comment]
OK. I will test it once again first and if my proposal is correct I'll create a ticket.
