### ISSUE TITLE
Implement clear sorting for Schemas

### ISSUE THREAD

**Issue by agolosen** [provectus/kafka-ui#1432]
### Is your proposal related to a problem?

(Write your answer here.)
Now it`s changing order of schemas on the page Schemas registry view. If you create or edit a schema and after return to Schemas view the order is different, it`s annoying.

### Describe the solution you'd like
Create a clear sorting (by name, type or time, etc), don`t change it unexpectedly.

(Describe your proposed solution here.)

### Describe alternatives you've considered
Please implement 

(Write your answer here.)

### Additional context

(Write your answer here.)
Before creating new schema
![image](https://user-images.githubusercontent.com/92585878/150299937-864c6d58-90a4-43dc-b959-46e016ff39bd.png)
Aftr creating a schema
![image](https://user-images.githubusercontent.com/92585878/150300187-c490a2d5-8194-4e06-b207-3ab965ac711a.png)

**Comment by ValentinPrischepa** [comment]
@Haarolean , default sorting by Schema Name has been added within [issue 1191](https://github.com/provectus/kafka-ui/issues/1191), It was necessary for pagination. Do we need some extra functionality, like sort by version or compatibility, ascending/descending?

**Comment by Haarolean** [comment]
@ValentinPrischepa nice, thanks. Guess not, let's start from there.
