### ISSUE TITLE
Wrong number of Messages

### ISSUE THREAD

**Issue by agolosen** [provectus/kafka-ui#1438]
**Describe the bug**
(A clear and concise description of what the bug is.)

There are different values of Messages number on the Topic view page and inside the topic. 

**Set up**
(How do you run the app? 
Which version of the app are you running? Provide either docker image version or check commit hash at the top left corner. We won't be able to help you without this information.)

http://dependabot-npm-and-yarn-kafka-ui.internal.kafka-ui.provectus.io/
**Steps to Reproduce**

1. Navigate to Topics
2. Select a topic with number of messages of more than 2.
3. Remember the Number of messages
4. Click on this topic
5. Go to tab Messages
6. Observe the number of Messages on the right under the select box 'Oldest First' on all pages and sum them.
7. Compare the numbers from the Topics overview page and Messages tab - they are different.

**Expected behavior**
(A clear and concise description of what you expected to happen)
The numbers from the Topics overview page and Messages tab for the same topic are equal. 
**Screenshots**
(If applicable, add screenshots to help explain your problem)
![image](https://user-images.githubusercontent.com/92585878/150344432-a234b6ce-5f59-4a01-9262-de54263cc339.png)

![image](https://user-images.githubusercontent.com/92585878/150344218-43998e9b-ae9c-48cc-bbda-7c54a8a746f5.png)

**Additional context**
(Add any other context about the problem here)

**Comment by Haarolean** [comment]
@iliax is [this](https://github.com/provectus/kafka-ui/issues/1230#issuecomment-992288752) still applicable for this case?

**Comment by iliax** [comment]
@Haarolean yes, in Messages tab we show number of messages we scanned to construct page. In topics page we shou number of all messages in topic
@agolosen

**Comment by iliax** [comment]
@agolosen maybe we rename title from "messages" to "scanned messages " if you think it is confusing

**Comment by iliax** [comment]
@Haarolean, we discussed it with you, so, I think it ok to close it

**Comment by Haarolean** [comment]
Yeah, let's. There's a tooltip if you hover over the text
<img width="128" alt="image" src="https://user-images.githubusercontent.com/1494347/164007853-4183d41b-f3f9-4dbc-8f3c-a3de1a1bedf0.png">
