### ISSUE TITLE
Different amount of Messages while sorting Oldest first/Newest first

### ISSUE THREAD

**Issue by agolosen** [provectus/kafka-ui#1439]
**Describe the bug**
(A clear and concise description of what the bug is.)

 There is a different amount of messages when selecting a sorting Oldest First/Newest first.

**Set up**
(How do you run the app? 
Which version of the app are you running? Provide either docker image version or check commit hash at the top left corner. We won't be able to help you without this information.)

http://dependabot-npm-and-yarn-kafka-ui.internal.kafka-ui.provectus.io/ui

**Steps to Reproduce**

1. Navigate to Topics
2. Chose some topic with number of messages more than 2
3. Look the number of messages when the selector in the right cooner is Oldest First
4. Select Newest First and look the number of messages
5. The number of messages is different for sorting Oldest First and Newest first. 

**Expected behavior**
(A clear and concise description of what you expected to happen)

**Screenshots**
(If applicable, add screenshots to help explain your problem)
Oldest First
![image](https://user-images.githubusercontent.com/92585878/150346844-c6f42755-76d8-4561-a65b-bc127e9276cf.png)

Newest first
![image](https://user-images.githubusercontent.com/92585878/150346764-4c61b6a6-1046-411f-adb7-68b8439e7950.png)

**Additional context**
(Add any other context about the problem here)

**Comment by Haarolean** [comment]
Can we check this with any other topic which is not being used by connectors/consumers?

**Comment by tzahibena-simplex** [comment]
I can also take note that its the ordering is incorrect, when filtering by newest it there is a gap in the offsets it is shown.
For example for partition 1, the offset is 149, but when filtering by newest, i get that the latest message in partition 1 is offset 128.

**Comment by Haarolean** [comment]
https://github.com/provectus/kafka-ui/issues/1230#issuecomment-992288752
