### ISSUE TITLE
Connector "Restart All Tasks" button has no effect

### ISSUE THREAD

**Issue by 5hin0bi** [provectus/kafka-ui#1444]
When choosing a specific connector there are several options you can choose:
<img width="1083" alt="image" src="https://user-images.githubusercontent.com/94184844/150494050-67a4692f-2133-4c78-94e3-c74857b65057.png">

Restart all tasks sends the next POST request that actually does do nothing.
https://xxx/api/clusters/local/connects/local/connectors/reddit-source-json/action/RESTART

According to the REST API documentation https://docs.confluent.io/platform/current/connect/references/restapi.html there is no such request available. And the correct one is this:
<img width="904" alt="image" src="https://user-images.githubusercontent.com/94184844/150494299-2cffab5d-abb7-4e05-af35-f3af1a57a050.png">

Restarting the specific task using the triple dot context menu works great tho.

**Comment by iliax** [comment]
@5hin0bi we currently only restart **connector instance**, not tasks on this button click. I will change this to restart both connector and all its tasks. I think we will also need to rename this button to smth like "Restart connector".

**Comment by iliax** [comment]
@5hin0bi can you please verify it works, and reopen issue if not

**Comment by 5hin0bi** [comment]
Checked on our dev environment. The button is now called "Restart Connector", but failed tasks themselves are not restarted.

**Comment by Haarolean** [comment]
To do: create 3 buttons

**Comment by iliax** [comment]
Need to implement frontend

**Comment by kandji-alex** [comment]
I'm seeing a similar error with KafkaConnect where it's trying to hit an api endpoint:
```500 Server Error for HTTP GET "/api/clusters/local/connectors?search="```
that also doesn't seem to exist, per Confluent's API.

**Comment by Haarolean** [comment]
> I'm seeing a similar error with KafkaConnect where it's trying to hit an api endpoint: `500 Server Error for HTTP GET "/api/clusters/local/connectors?search="` that also doesn't seem to exist, per Confluent's API.

That's our backend with our API, not confluent's. Please raise a new issue.
