### ISSUE TITLE
Produce message without key

### ISSUE THREAD

**Issue by MaksimMyshkin** [provectus/kafka-ui#1451]
### Is your proposal related to a problem?
There is no possibility now to send message without a key (on message producer page). When I clear a key field before sending message this message is sending with default/generated key anyway. It can be critical when consumer is not supporting keys and/or read them as numbers.

### Describe the solution you'd like
It is need to be able to send message with null/empty key. On UI it can be checkbox that will indicate whether key needed or not.

**Comment by Haarolean** [comment]
Hey, thanks for reaching out.

Which version are you using? This feature is present and does work, just checked it out.

This is the payload frontend produces when emptying a `key` field:
![image](https://user-images.githubusercontent.com/1494347/150732272-bec18304-65ae-4a26-a8c1-0dbca81c11c2.png)

**Comment by MaksimMyshkin** [comment]
Sorry. I guess my local version was little old. All works perfect now after update! Thanks.

**Comment by Haarolean** [comment]
Glad it works :)
