### ISSUE TITLE
Cannot create a Kafka topic in Kafka-UI for Confluent Kafka

### ISSUE THREAD

**Issue by dmakeroam** [provectus/kafka-ui#1455]
**Describe the bug**

I cannot create a Kafka topic in Kafka-UI for Confluent Kafka.

**Set up**

Docker images:

Kafka UI: provectuslabs/kafka-ui:master
Confluent Kafka: confluentinc/cp-kafka:6.1.0

**Steps to Reproduce**

1. Go to Kafka UI topic creation page -> http://[local-ip]:[local-port]/ui/clusters/[cluster-name]/topics/create-new
2. Fill in the topic name such as "go"
3. Click "Send" to create the topic
4. Nothing will happen for you

**Expected behavior**

The topic name "go" should be created.

**Screenshots**

![Kafka UI can't create a topic](https://i.ibb.co/xqLF0zh/Screenshot-2565-01-24-at-00-56-14.png)

**Additional context**

I used Confluent Kafka on premise which setup with kubeadm

**Comment by dmakeroam** [comment]
I claim it

**Comment by dmakeroam** [comment]
Can you help to review this ? @workshur

**Comment by Haarolean** [comment]
Hi,

is there any failed requests upon clicking 'send'?

**Comment by Haarolean** [comment]
We've reproduced the issue We'll release a minor patch to address the problem soon.

**Comment by Haarolean** [comment]
Available in `master`-labeled image.
