### ISSUE TITLE
Table Row with dropdown is jumping on mouse over action

### ISSUE THREAD

**Issue by workshur** [provectus/kafka-ui#1473]
**Describe the bug**
Table Row with dropdown is jumping on mouse over action

**Expected behavior**
Check all the tables and fix. Use visibility hidden instead of removing dropdown

**Comment by sasunprov** [comment]
@workshur I can't reproduce, could you please tell in which exact table this happens?

**Comment by workshur** [comment]
Tables with action button in a row. It jumps on row hover/mouse out
