### ISSUE TITLE
Help - Health Check

### ISSUE THREAD

**Issue by filipemacedo** [provectus/kafka-ui#1477]
Hi guys, I looked in the documentation but didn't find it, what is the health check endpoint?
Basically, my load balancer is restarting my container because of the status code of the main endpoint.

Thank you very much.

**Comment by Haarolean** [comment]
Hey, it's `/actuator/health` and `/actuator/info` if you're not running a custom context path.

**Comment by filipemacedo** [comment]
> Hey, it's `/actuator/health` and `/actuator/info` if you're not running a custom context path.

Thank you very much, can we add this information to the documentation?
