### ISSUE TITLE
Breadcrumbs navigation doesn't work from Connectors page

### ISSUE THREAD

**Issue by iliax** [provectus/kafka-ui#1485]
**Steps to Reproduce**

Go to Kafka Connect ->  click on any connector
<img width="411" alt="Screenshot 2022-01-26 at 11 48 09" src="https://user-images.githubusercontent.com/702205/151131508-033a2b1e-b142-4755-b990-27a82a9dce1c.png">

click on cluster name or "Connectors" in  breadcrumbs on top of page
**expected**: we redirected to cluster/ connectors page
**actual**: we see empty page:

<img width="352" alt="Screenshot 2022-01-26 at 11 49 33" src="https://user-images.githubusercontent.com/702205/151131716-cd4d0ed0-d71c-4960-b6e4-ba5fd5cefae3.png">

**Comment by abelgibayev** [comment]
Duplicates https://github.com/provectus/kafka-ui/issues/1193
