### ISSUE TITLE
Invalid color of "tasks failed" badge

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#1491]
connectors-> select connector
"tasks failed" color is red even when it equals to zero

![image](https://user-images.githubusercontent.com/1494347/151153457-8ce971bf-f04e-4e81-9733-0af3f2e2a0eb.png)

**Comment by agolosen** [comment]
It should be consistent if Test running here in Connectors would be green if it > 0
<img width="348" alt="Screenshot 2022-02-01 at 23 08 56" src="https://user-images.githubusercontent.com/92585878/152051769-dd88ec72-3657-46c1-9ec9-7e6b4b1b6067.png">
