### ISSUE TITLE
Inconsistent task status badges colors

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#1492]
Connectors list: statuses can have different background badge colors, including read, yellow and green. On the connector's page it's always yellow.

**Comment by agolosen** [comment]
The same problem on the page Brokers for Partitions Online - should be Green not red
<img width="1264" alt="Screenshot 2022-01-27 at 20 56 38" src="https://user-images.githubusercontent.com/92585878/151425744-cf298f58-b813-44d0-b233-ae965c19442d.png">

**Comment by agolosen** [comment]
The same on the page Topics->Topic_Name-> Overview In Sync Replicas should be green if m of m

<img width="1264" alt="Screenshot 2022-01-27 at 21 04 56" src="https://user-images.githubusercontent.com/92585878/151426805-e064b364-c445-408d-8f57-ff51cb43c37b.png">

**Comment by agolosen** [comment]
The same for the Consumers.
<img width="1499" alt="Screenshot 2022-01-28 at 19 51 47" src="https://user-images.githubusercontent.com/92585878/151597061-857d3891-4038-4f5f-bc00-34f9241612e9.png">
<img width="1499" alt="Screenshot 2022-01-28 at 19 51 56" src="https://user-images.githubusercontent.com/92585878/151597074-38e8ef97-fe37-44d3-896d-99b67f538723.png">
