### ISSUE TITLE
[Topics] There are default values when user try to edit topic

### ISSUE THREAD

**Issue by sbritprovectus** [provectus/kafka-ui#1500]
**Describe the bug**
When user try to edit topic after creation there are defaults values in edit topic settings view

**Set up**
Local docker.
App version: Version:v0.3.3(38c4cf7)

**Steps to Reproduce**
1. Create topic (e.g. using API)
2. Go to newly created topic
3. Go to Edit Settings
4. Edit something (e.g. change Cleanup policy)
5. Save
6. Go to Edit settings again
7. Observe the view

**Expected behavior**
At Edit settings view should be current topic's values

**Actual result**
All setting are default

**Comment by jonasgeiregat** [comment]
Almost all fields are not set according to the actual values but rather contain the widgets default value. I'm happy to take a look at this.
