### ISSUE TITLE
Readonly mode regression

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#1501]
### Discussed in https://github.com/provectus/kafka-ui/discussions/1497

<div type='discussions-op-text'>

<sup>Originally posted by **giom-l** January 26, 2022</sup>
Hi, 

Long time no see. I just realized I had missed some releases since last time.
So I just tried to update our UI from 0.2.1 to 0.3.3. 
What a change ^^.

However, I have some concerns about one of the most useful feature to me : the read-only mode.
This was working perfectly in 0.2.1 and I'm little lost in 0.3.3 (
- no more "read only" label anywhere (I saw it was brought back in 0.3.2, but didn't find it)
- Also, all creation/deletion options are still visible but are just not working : 
      - sometimes with an error on the UI
      - sometimes without anything (I only get HTTP405 error)

From a user experience perspective, it is a huge regression (IMO, obviously)
As a user, I really prefer not to see unavailable options than having obscure error messages, like the following we have when trying to create a topic : 
![image](https://user-images.githubusercontent.com/29728596/151240631-463acb14-a0be-46f4-8c6f-162ba72dda33.png)

Is this behavior intended or the "UI_hide_all_readonly_incompatible_components" behavior could be back anytime soon ? 

For now, I can't make the switch without having lots of questions like "wait, whaaaaat, we can modify clusters now ?" or "wait, whaaat, I'm trying to create topics but can't understand why it is not working" and I'll stick with 0.2.1 :-/</div>

**Comment by Haarolean** [comment]
@giom-l thanks for the feedback, glad you like the update :)
As I mentioned in a discussion, this seems to be a regression indeed. We'll take a look!

**Comment by Haarolean** [comment]
@giom-l the fix is available in `master`-labeled image

**Comment by giom-l** [comment]
Sorry for the delay, I just tested it and it's OK :)

**Comment by Haarolean** [comment]
> Sorry for the delay, I just tested it and it's OK :)

glad it works! so you're on 0.3 now?
