### ISSUE TITLE
Error when trying to run the project locally

### ISSUE THREAD

**Issue by Guzel738** [provectus/kafka-ui#152]
Following the instructions of **Running From Docker Image** fails to start the project (operating system Windows).
![photo_2021-01-12_14-09-03](https://user-images.githubusercontent.com/66492070/104308009-0993fb80-54e1-11eb-81fa-42e065f012bc.jpg)

**Comment by alex198710** [comment]
Hello, the docker command line is not well formed. The docker image name should be at the end
You can try with this one for example:
`docker run -d -e KAFKA_CLUSTERS_0_NAME=local -e KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=localhost:9092 -e KAFKA_CLUSTERS_0_ZOOKEEPER=localhost:2181 -p 9000:8080 provectuslabs/kafka-ui:latest`
