### ISSUE TITLE
Show IP and port of brokers in UI/API

### ISSUE THREAD

**Issue by Alepacox** [provectus/kafka-ui#1521]
Good morning, thank you very much for the great work you are doing.
I just wanted to know if there is a possibility to also show the port of the brokers on the /clusters/clusterName/brokers endpoint.
It would be so useful for scenarios where brokers are added to the cluster with random port mappings, so that you can connect to the brokers by querying the Kafka-UI API first. 
Morover, those same data could be displayed in the UI (/ui/clusters/Local/brokers) along with each broker ID.

Thank you so much.

**Comment by Haarolean** [comment]
Hey, thanks for the suggestion. This seems like a good feature, we'll get this implemented :)

**Comment by Alepacox** [comment]
I'm glad to hear that, thank you so much!
