### ISSUE TITLE
[Feature] Feedback to the user when a message content is copied to clipboard

### ISSUE THREAD

**Issue by giom-l** [provectus/kafka-ui#1545]
When I copy a message to my clipboard, there is no clear indications that it is done. 
Obviously, I can paste it wherever I want.

But I'd find nice to have some notifications anywhere that would say me "message copied to clipboard" then disappears some seconds later.

Version tested : ([8a7399b](https://github.com/provectus/kafka-ui/commit/8a7399b))

**Comment by Haarolean** [comment]
Hey, thanks for the suggestion. Definitely will do :)
