### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by Zorii4** [provectus/kafka-ui#1552]
**Describe the bug**
Files are not completely covered with tests
src/components/Topics/Topic/Details/Details.tsx
src/components/Topics/Topic/Details/Overview/Overview.tsx

After refactored this components need update some test coverage.

**Expected behavior**
100% covered

**Comment by Haarolean** [comment]
And [this](https://github.com/provectus/kafka-ui/pull/1849#issuecomment-1102725089)

**Comment by Haarolean** [comment]
#215
