### ISSUE TITLE
Inconsistency in stats of Topics and Brokers [Bug]

### ISSUE THREAD

**Issue by agolosen** [provectus/kafka-ui#1554]
**Describe the bug**

Stats of Brokers and Topics look different for similar parameters (URP and ISR).
**Set up**

https://www.kafka-ui.provectus.io/ui

**Steps to Reproduce**

1. Go to Brokers page, look at stats of Partitions
2. URP has no dot; neither In Sync Replicas, also it written in full name (see attachment)
3. Go to Topics -> Click some topic name, look at topic`s overview stats
4. URP has red dot (although it should have a green one for 0), ISR is written in abbreviation and has a green dot for 1 of 1.

**Expected behavior**

URP and ISR look same for Brokers partitions and Topics overview

**Screenshots**

<img width="1087" alt="Screenshot 2022-02-04 at 19 46 38" src="https://user-images.githubusercontent.com/92585878/152577563-9c4fbbfc-e68d-4820-a982-e182f4fd6e81.png">
<img width="626" alt="Screenshot 2022-02-04 at 19 46 03" src="https://user-images.githubusercontent.com/92585878/152577549-d585d930-b387-4df4-b6b1-49e06e2c6048.png">

**Additional context**

**Comment by Haarolean** [comment]
#1268 ?
