### ISSUE TITLE
[Feature]Use an unprivileged user in the dockerfile

### ISSUE THREAD

**Issue by sandrospadaro** [provectus/kafka-ui#1555]
### Is your proposal related to a problem?

Use an unprivileged user in the dockerfile

### Describe the solution you'd like

Change the [Dockerfile](https://github.com/provectus/kafka-ui/blob/master/kafka-ui-api/Dockerfile) as follows:

```Dockerfile
FROM alpine:3.15.0
RUN apk add --no-cache openjdk13-jre libc6-compat gcompat

RUN addgroup -S kafkaui && adduser -S kafkaui -G kafkaui
USER kafkaui

ARG JAR_FILE
COPY "/target/${JAR_FILE}" "/kafka-ui-api.jar"

ENV JAVA_OPTS=

EXPOSE 8080

CMD java $JAVA_OPTS -jar kafka-ui-api.jar
```

**Comment by Haarolean** [comment]
Hey, thanks for the suggestion. I've considered this but got lost in other stuff :)
