### ISSUE TITLE
[Bug] Can't create the topic

### ISSUE THREAD

**Issue by fee1good** [provectus/kafka-ui#1566]
**Topic creation**

Hey guys, can't create a topic, probably FE bug, check the gif
ua  — `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:96.0) Gecko/20100101 Firefox/96.0`

![kafka_ui_bug](https://user-images.githubusercontent.com/16759866/152808603-8e54e2bb-c800-48f0-9fcd-7a83a7b7cadf.gif)

**Comment by Haarolean** [comment]
Hey, thanks for reaching out!

That version is outdated, there were hotfixes in next minor versions.

Please try 0.3.3 or even better `:master` if possible.

Let me know how it goes :)
