### ISSUE TITLE
Specify distinct image tag version for helm chart

### ISSUE THREAD

**Issue by montebove** [provectus/kafka-ui#1591]
**Describe the bug**
Trying to upgrade to last 3.3 version after the kafka-ui started, when trying to access to the Web UI  I get immediately disconnected and in containers log I see these lines:
`15:45:34.875 [parallel-1] DEBUG com.provectus.kafka.ui.service.MetricsUpdateService - Start getting metrics for kafkaCluster: strimzi
15:45:55.587 [boundedElastic-1] WARN  com.provectus.kafka.ui.exception.ErrorCode - Multiple class com.provectus.kafka.ui.exception.ErrorCode values refer to code 4001
15:45:55.708 [boundedElastic-2] DEBUG org.springframework.http.codec.json.Jackson2JsonEncoder - [694106d4] Encoding [class ErrorResponse {
    code: 5000
    message: 404 NOT_FOUND
    timestamp: 1644594355588
    req (truncated)...]
15:45:55.709 [boundedElastic-1] DEBUG org.springframework.http.codec.json.Jackson2JsonEncoder - [cfe32b23] Encoding [class ErrorResponse {
    code: 5000
    message: 404 NOT_FOUND
    timestamp: 1644594355588
    req (truncated)...]
15:46:04.875 [parallel-1] DEBUG com.provectus.kafka.ui.service.MetricsUpdateService - Start getting metrics for kafkaCluster: strimzi`

After few minutes containers restart because probing fails.
The old kafka-ui 2.0 version works fine on the same Kubernetes.

**Set up**
version 0.3.3
Kubernetes 1.21 on Amazon EKS

**Steps to Reproduce**
1)Install last version with Helm chart
2)Modify generated server to create an Internal Load Balancer on AWS EKS
3)try to access to the Web UI

**Expected behavior**
I can access the UI

**Comment by 5hin0bi** [comment]
Hi @montebove 

> 2)Modify generated server to create an Internal Load Balancer on AWS EKS
Do you mean the service? If so, could you please share the details of the service that you have now after the changes? As yaml file if possible please.

**Comment by montebove** [comment]
Here is the service.yaml. With identical modifications works fine on old 2.0 version. I changed extension to .txt because .yaml it's no supported  by github
[service.yaml.txt](https://github.com/provectus/kafka-ui/files/8050027/service.yaml.txt)

**Comment by Haarolean** [comment]
The warning you mentioned itself shouldn't be a problem itself.

**Comment by 5hin0bi** [comment]
@montebove thank you. Do I understand it correctly: as soon as the load balancer is up, you are trying to access the webui via the load balancer hostname and port 80?

**Comment by 5hin0bi** [comment]
@montebove if you have time we could jump into our discord to discuss the situation in more details. Just let me know if it's OK with you.

**Comment by montebove** [comment]
SOLVED:
There is a problem in the chart but not a real bug. I was using last helm chart version but as Kubernetes download new images only if it is a different version as ifnotpresent is specified I actually used always the old 2.0 version docker image. Forcing deployment to download the image all started to work. The problem originated from the fact I previously, some months ago,  installed the 2.0 version and the Helm chart indicated as image version provectuslabs/kafka-ui:latest (at that time 2.0), but after months the new Helm chart asked for the same provectuslabs/kafka-ui:latest and Kubernetes doesn't distinguishes that actually are not the same. I would suggest to use an explicit docker image version in Helm chart something like for the current version provectuslabs/kafka-ui:0.3.3

**Comment by Haarolean** [comment]
@montebove thank you for the info. Glad it works. We'll take a look.
