### ISSUE TITLE
Save "Show internal topics" preference

### ISSUE THREAD

**Issue by victornovy** [provectus/kafka-ui#1612]
### Is your proposal related to a problem?

Always when i click to show topics the preference for not "show internal topics" is selected

### Describe the solution you'd like

I would want to save my preferences for not have to click on "show internal topics" all times I enter to view topic

![simulation](https://user-images.githubusercontent.com/10718354/154108740-4a5b983e-a2c7-4cf3-bbf6-7e11cf19e3fd.gif)

**Comment by Haarolean** [comment]
Hi, thanks for reaching out.

We'll take a look into this.
