### ISSUE TITLE
TopicNotFound upon creating a topic

### ISSUE THREAD

**Issue by pikhovkin** [provectus/kafka-ui#1613]
**Describe the bug**

A topic is not created from the first time in KRaft mode. Most of the time. Sometimes a topic is created immediately.

**Set up**
![изображение](https://user-images.githubusercontent.com/630071/154234076-0f70bc96-4809-4c39-8498-eddd531b4006.png)

**Steps to Reproduce**

![изображение](https://user-images.githubusercontent.com/630071/154232665-ab3e95aa-1819-49e9-a487-3361d9492acf.png)

**Expected behavior**

A topic is created immediately without errors 

**Screenshots**

**Additional context**

**Comment by Haarolean** [comment]
Hey, thanks for raising the issue.

Could you share the details of a red (failed) request in network tab of browser's developer console?

**Comment by pikhovkin** [comment]
@Haarolean 
![изображение](https://user-images.githubusercontent.com/630071/154239054-ccf0dea7-3df4-4942-9fff-c9f20bc33d79.png)
![изображение](https://user-images.githubusercontent.com/630071/154239075-8ed8f17a-3692-4061-9e3c-88f416d41523.png)

**Comment by Haarolean** [comment]
@pikhovkin is it actually not created at all or are we just accessing it too early before it is actually created?
