### ISSUE TITLE
feature request: read only mode

### ISSUE THREAD

**Issue by andormarkus** [provectus/kafka-ui#164]
Dear Community,

It would be great if we could use the UI in read only mode.

Suggested changes: 
-  in the topic page when the UI is running in read only mode hide the "Add topic" and "edit settings" button.
-  when running in docker than `-e read_only=true` default to false

Use case:
> When the kafka cluster is configured with Terraform changes through UI should be avoided
> When the UI is used only for monitoring purposes than. accidental changes could be avoided.

Thank you to considering these feature request.
Andor Markus

**Comment by germanosin** [comment]
Thank you for your proposal, We'll include it in our roadmap.
