### ISSUE TITLE
Ingress resource will not survive k8s upgrade from 1.21 to 1.22

### ISSUE THREAD

**Issue by keeperUA** [provectus/kafka-ui#1640]
**Describe the bug**

Ingres template has wrong version logic
networking.k8s.io/v1beta1 - this api version is [depricated since 1.19 and totaly removed since 1.22](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122)
Current logic will work fine for new setup on kubernetes v1.22, but it completely broken when you try upgrade kubernetes from v1.21 to v1.22. Because setup on 1.21 has api version that will be removed in 1.22. So on kubernetes upgrade ingress resorce will be removed and you must install helm chart again.

1. Install helm chart on kubernetes v 1.21
2. Upgrade kubernetes to v 1.22
3. Ingress will be broken

**Expected behavior**
Ingress resource must survive the kubernetes upgrade

**Additional context**
Related to this [issue](https://github.com/provectus/kafka-ui/issues/1337)

**Comment by Haarolean** [comment]
@keeperUA hey, thanks for reporting!

**Comment by Haarolean** [comment]
@keeperUA you def can open a PR, you just have to fork a repo first, make a branch there and propose the changes to the base repo. Or you can even do it via github UI (editing a specific file will fork a repo for you).

**Comment by keeperUA** [comment]
ok, i will try
