### ISSUE TITLE
A number of CVEs is present

### ISSUE THREAD

**Issue by David-hod** [provectus/kafka-ui#1656]
it seems like the latest release 0.3.3 is very vulnerable 
https://artifacthub.io/packages/helm/kafka-ui/kafka-ui?modal=security-report
when can we get a version with those issues fixed?

**Comment by Haarolean** [comment]
Hi, thanks for reaching out.

Will take a look.

**Comment by Haarolean** [comment]
Stil have to get rid of ZK to get a clean scan #1663
