### ISSUE TITLE
Implement a SR client

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#1662]
Implement a schema registry client via openapi (like we have one for kafka-connect) and use it instead of webclient in `SchemaRegistryService` class.
The point: Reduce amount of URLs in the class and implement a decent failover in the future.

**Comment by Corlobin** [comment]
Hi @Haarolean , can I take this one?

**Comment by Haarolean** [comment]
@Corlobin hey, sure thing ;)

**Comment by Corlobin** [comment]
Hi @Haarolean , can you assign it to me?

**Comment by Haarolean** [comment]
@Corlobin I already did! :D

**Comment by Haarolean** [comment]
@Corlobin hey, any luck?
