### ISSUE TITLE
get SCRAM credentials from secret

### ISSUE THREAD

**Issue by mattia-crypto** [provectus/kafka-ui#1665]
### Is your proposal related to a problem?

Many people rely upon Kafka operators when they deploy Kafka in Kubernetes.

Usually, the operator lets you create `KafkaUser` CRDs, which may autogenerates passwords for a particular user and associates this password with a new Kubernetes `Secret`.

Currently, the `KAFKA_CLUSTERS_X_PROPERTIES_SASL_JAAS_CONFIG` env variable requires a username and password. However, there is no way to inject a previously existing secret into this environment variable AFAIK.

### Describe the solution you'd like

It would be great if the Helm chart supports injecting SCRAM credentials into the configuration without hardcoding them in the  `KAFKA_CLUSTERS_X_PROPERTIES_SASL_JAAS_CONFIG` parameter, in particular if it could re-use a pre-existing secret (such as the one created with a `KafkaUser` resource).

### Describe alternatives you've considered

Some operators also let you pre-create the password before the user, but this is an infeasible solution in my case since I need to bootstrap the users at cluster-creation time.

### Additional context

Using AWS and KMS envelope encryption for the secrets.

**Comment by mattia-crypto** [comment]
Sorry just found what I was looking for :-)

**Comment by Haarolean** [comment]
@mattia-crypto glad you've solved it. Could you share the solution so we add it in our FAQ in the future?

**Comment by mattia-crypto** [comment]
@Haarolean I found the `existingSecret` parameter for the `values`. However, it turned out that this has not actually solved my problem. Please see:  https://github.com/provectus/kafka-ui/issues/1667

**Comment by dimashenkov** [comment]
existingSecret. need to have KAFKA_USERNAME and KAFKA_PASSWORD keys then it works
