### ISSUE TITLE
Request: a command to compile just `kafka-ui-api`, ignoring the frontend

### ISSUE THREAD

**Issue by omh1280** [provectus/kafka-ui#1666]
### Is your proposal related to a problem?

I'd like to be able to iterate building the Java portion of `kafka-ui` without building the frontend.

I assumed this would work, but it runs npm:
```
cd kafka-ui-api
 ./mvnw compile -Pprod 
```

I was told to open this issue on Discord.

### Describe the solution you'd like
```
cd kafka-ui-api
 ./mvnw compile -Pprod 
```
The above should compile just the backend.

**Comment by Corlobin** [comment]
I can take this one. 

Actually the ` ./mvnw compile -Pprod` doesn't compile the "kafka-ui-contract" (or am I wrong?). So when compiling the "kafka-ui-api" if you dont compile the contract you can receive some erros (if the contracts were updated). 

Maybe this is an another issue?

**Comment by Haarolean** [comment]
Yeah, let's do something like this.
It depends on the directory you run this command in.

**Comment by MichaelGonzalezMurillo** [comment]
Since we don't have the wrapper as part of the modules what is the approach we want to follow regarding this request? Do we want to skip frontend build for ui-api and ui-contract?

By running something like this ./mvnw clean install -Pprod -DskipUIBuild=true


Original Request is based on this possibility but it is not anymore like this:

cd kafka-ui-api
 ./mvnw compile -Pprod

**Comment by Haarolean** [comment]
> Since we don't have the wrapper as part of the modules what is the approach we want to follow regarding this request? Do we want to skip frontend build for ui-api and ui-contract?
> 
> By running something like this ./mvnw clean install -Pprod -DskipUIBuild=true
> 
> And changing this on both POM's:
> 
> **configuration.skip.skipUIBuild**
> 
> Original Request is based on this possibility but it is not anymore like this:
> 
> cd kafka-ui-api ./mvnw compile -Pprod
> 
> @Haarolean

what if we create a new profile with skipUIBuild property set to enabled by default?

**Comment by MichaelGonzalezMurillo** [comment]
> > Since we don't have the wrapper as part of the modules what is the approach we want to follow regarding this request? Do we want to skip frontend build for ui-api and ui-contract?
> > By running something like this ./mvnw clean install -Pprod -DskipUIBuild=true
> > And changing this on both POM's:
> > **configuration.skip.skipUIBuild**
> > Original Request is based on this possibility but it is not anymore like this:
> > cd kafka-ui-api ./mvnw compile -Pprod
> > @Haarolean
> 
> what if we create a new profile with skipUIBuild property set to enabled by default?

That is what the closed PR was doing and was pushed back due to duplicated code.

**Comment by iliax** [comment]
@Haarolean Lets not create unnecessary profiles. I suggested simple solution here https://github.com/provectus/kafka-ui/pull/1696#discussion_r830601917 . 
In should work like `./mvnw compile -DskipUiBuild=true`.

**Comment by MichaelGonzalezMurillo** [comment]
> @Haarolean Lets not create unnecessary profiles. I suggested simple solution here [#1696 (comment)](https://github.com/provectus/kafka-ui/pull/1696#discussion_r830601917) . In should work like `./mvnw compile -DskipUiBuild=true`.

Do we want it just for api or also for contract project?

**Comment by MichaelGonzalezMurillo** [comment]
> @Haarolean Lets not create unnecessary profiles. I suggested simple solution here [#1696 (comment)](https://github.com/provectus/kafka-ui/pull/1696#discussion_r830601917) . In should work like `./mvnw compile -DskipUiBuild=true`.

https://github.com/provectus/kafka-ui/pull/2424 This is solution 2
