### ISSUE TITLE
How to set up SSO with G suite

### ISSUE THREAD

**Issue by kaotu** [provectus/kafka-ui#1678]
Hello, 
Kafka-UI is pretty and easier to use connect and manage Kafka but I have question. How can I set up SSO with our G suite? I should fill in what environment variables? 

Thank you!

**Comment by Haarolean** [comment]
Hi, please refer to [SSO guide](https://github.com/provectus/kafka-ui/blob/master/documentation/guides/SSO.md). Let us know if you have any problems.

**Comment by kaotu** [comment]
Hi, 
I use these variables
```bash
AUTH_TYPE=OAUTH2
SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENTID=<myclientid>
SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENTSECRET=<myclientsecret>
SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_GOOGLE_ISSUER_URI=https://accounts.google.com/
SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_SCOPE=openid 
```
via https://developers.google.com/oauthplayground/. It's not working, I found `ERROR 401 invalid_client`.

**Comment by kaotu** [comment]
Hey, 
Update, I try to config and seem like it working but I found `Invalid credentials` after sign in with SSO via G suite.
My config redirect URI is `http://mydomainname.com/login/oauth2/code/google`

![image](https://user-images.githubusercontent.com/32597649/155976801-10d5308c-ab31-4efb-8671-d1b64fdb3d77.png)

**Comment by Haarolean** [comment]
Thanks, I'll take a look into this.

**Comment by kaotu** [comment]
Hello,
Do you have anything to update?

**Comment by Haarolean** [comment]
Are you still trying to use playground credentials or have you created an oauth client?

**Comment by kaotu** [comment]
Yes, I already created an oauth client.

**Comment by Haarolean** [comment]
Works fine for me:
```
      AUTH_TYPE: 'OAUTH2'
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENTID: '832184027882-b0advma5u8cmerak61rvufgkfhr62k1g.apps.googleusercontent.com'
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENTSECRET: 'xxx'
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_GOOGLE_ISSUER_URI: 'https://accounts.google.com' # no slash at the end
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_SCOPE: 'openid'
```

**Comment by kaotu** [comment]
Oh, I think it's my mistake to configure the oauth2 client on google console.😅
Thank you for helping me. I will close this issue.

**Comment by Haarolean** [comment]
@kaotu you're welcome :)
