### ISSUE TITLE
Add configuration option to deserialize binary protobuf encoded message keys

### ISSUE THREAD

**Issue by jdechicchis** [provectus/kafka-ui#1699]
First off, Kafka UI is great, thanks for maintaining it!

I noticed [this TODO](https://github.com/provectus/kafka-ui/blob/master/kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/ProtobufFileRecordSerDe.java#L30) in `ProtobufFileRecordSerDe`:
```
//TODO: currently we assume that keys for this serde are always string - need to discuss if it is ok
```

I think it would be nice to provide the ability to deserialize binary protobuf encoded message keys in addition to message values. To support this, I think a new configuration value such as `Map<String, String> protobufMessageNameByTopicForKey` could be added (open to suggestions here). In terms of how a message key is deserialized when using `ProtobufFileRecordSerDe` I feel this precedence order would make sense:
- If the protobuf message name is found in `protobufMessageNameByTopicForKey` deserialize the message key using a descriptor.
- Else, deserialize the message key as a string.

Happy to make a PR for this (I've been playing around with the code and doesn't seem like it would be terribly difficult to add), but wanted to discuss if adding such a configuration makes sense

**Comment by Haarolean** [comment]
Hey, thanks for reaching out! Glad you like it.

Let's discuss and we'll see about the PR.

@iliax, what do you think?

**Comment by iliax** [comment]
I am ok with this. Will be happy to review PR, @jdechicchis

**Comment by jdechicchis** [comment]
@iliax @Haarolean Made a PR #1729. Would appreciate a review. I noticed that there didn't seem to be much documentation on how to use protobuf files with Kafka UI (maybe I missed it). I'm happy to document this change better if desired

**Comment by Haarolean** [comment]
@jdechicchis hey, yeah, unfortunately there's not much documentation for this. Would appreciate any documentation improvements.

**Comment by Haarolean** [comment]
@jdechicchis would be cool! The same PR is fine, the path is okay as well.

**Comment by jdechicchis** [comment]
Updated the PR with some docs
