### ISSUE TITLE
Proto SerializationException: Unknown magic byte

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#1704]
### Discussed in https://github.com/provectus/kafka-ui/discussions/1680

<div type='discussions-op-text'>

<sup>Originally posted by **mihelanjelo** February 25, 2022</sup>
Hello, i have problem with setting up proto schemas for topic.
I have connected schema registry confluentinc/cp-schema-registry:7.0.1
I set schema for key like topic_name-key and for value like topic_name-value
, but still messages are not shown decoded.
I checked schemas many times and decoded messages in code by google lib successfully.
Sometimes i saw error in log like:
```
org.apache.kafka.common.errors.SerializationException: Error deserializing Protobuf message for id -1
Caused by: org.apache.kafka.common.errors.SerializationException: Unknown magic byte!
```
Please, explain by steps how to set it up properly</div>

**Comment by iliax** [comment]
Replied in original thread.
