### ISSUE TITLE
Support data serialized with Long 

### ISSUE THREAD

**Issue by ngmip** [provectus/kafka-ui#1715]
### Is your proposal related to a problem?

Most of our topics have a Long type key but kafka-ui only support schema-registry based data or / UTF8 string (as I was told in [issue #1709](https://github.com/provectus/kafka-ui/issues/1709#issuecomment-1060984398)).
We can therefore not see/filter records based on the key.

### Describe the solution you'd like

Let the user change or choose the deserializer used to read the topic data for each individual topic

### Describe alternatives you've considered

Can't think of a way to do this that would not either be heavy duck tape or change my topic data. 
I will not change my topic to fit a tool, I'd rather change the tool to fit my topics.

**Comment by Haarolean** [comment]
Hey, thanks for raising the issue. We'll consider this for 0.5.

**Comment by alexkau** [comment]
Would it make sense to add support for other types, e.g. String and Integer, as part of this change, or would it be better to open separate issues for those other types? My team is running into this issue, and we use String and Integer keys/values in addition to Long.

**Comment by Haarolean** [comment]
Will be done as a part of #1777
