### ISSUE TITLE
KSQL execution works wrong

### ISSUE THREAD

**Issue by agolosen** [provectus/kafka-ui#1720]
**Describe the bug**

1. INSERT INTO lets to insert the same data multiple times.
2. SELECT  from tutorial gives an error message.

**Set up**

http://issues-1109.internal.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to KSQL DB in main menu
2. Push the button Execute KSQL Request
3. Execute the query INSERT INTO riderLocations (profileId, latitude, longitude) VALUES ('4ddad000', 37.7857, -122.4011); several times.
4. Observe that every time the result is Query succeed
5. Execute the push query SELECT * FROM riderLocations
  WHERE GEO_DISTANCE(latitude, longitude, 37.4133, -122.1162) < 5 EMIT CHANGES; 
6. Observe result - empty fields of table `PROFILEID` STRING `LATITUDE` DOUBLE   `LONGITUDE` DOUBLE
7. Execute the query SELECT * from ridersNearMountainView WHERE distanceInMiles <= 10;
8. Observe the result "SELECT * from ridersNearMountainView WHERE distanceInMiles <= 10;" Bound on key columns '[`DISTANCEINMILES` DOUBLE KEY]' must currently be '='. See https://cnfl.io/queries for more info. Add EMIT CHANGES if you intended to issue a push query. Pull queries require a WHERE clause that: - includes a key equality expression, e.g. `SELECT * FROM X WHERE <key-column>=Y;`. - in the case of a multi-column key, is a conjunction of equality expressions that cover all key columns. If more flexible queries are needed, table scans can be enabled by setting ksql.query.pull.table.scan.enabled=true.
9. However, it works with = only : SELECT * from ridersNearMountainView WHERE distanceInMiles = 10;
10. In conclusion no one SELECT (pull query) request from the page https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-reference/select-pull-query/ doesn`t works.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Haarolean** [comment]
Continuation of ##1109

**Comment by iliax** [comment]
@agolosen 
1. repeated insert should work without error - there is no concept of uniq key in kafka - following inserts with same primary key just overwrite existing 
2. point 8 -> like message sad to make it work you need to set `ksql.query.pull.table.scan.enabled` to `true`. if set - it works fine

For other queries - there are some error in confluent docs, so, need to check every question one by one.
