### ISSUE TITLE
Deep linking routes results in 404 on latest release

### ISSUE THREAD

**Issue by j4ys0n** [provectus/kafka-ui#1731]
**Describe the bug**

navigate to /clusters/<cluster_name>/topics, or refresh when you're on a routed page and you'll get a 404

**Set up**

docker-compose

**Steps to Reproduce**

1. see description

**Expected behavior**

no 404
**Screenshots**

**Additional context**

**Comment by Haarolean** [comment]
Hey, thanks for reaching out. We'll take a look asap.

**Comment by Haarolean** [comment]
#1693 ?

**Comment by Haarolean** [comment]
Couldn't reproduce on the latest master.
@j4ys0n please follow the issue template next time which clearly asks you to provide the version you're running.

**Comment by j4ys0n** [comment]
sorry for the late reply. i'm using this docker image: 
`provectuslabs/kafka-ui:c28ee0f08b24db31f19d7ab239ae140d326e2b2f`
