### ISSUE TITLE
Hide zookeeper on dashboard when not configured

### ISSUE THREAD

**Issue by jonasgeiregat** [provectus/kafka-ui#1733]
**Describe the bug**
When you do not configure zookeeper you should not see the zookeeper status on the dashboard.

**Steps to Reproduce**

1. Do not add any zookeeper configurations.

**Expected behavior**

2. zookeeper status block is not visible on the dashboard

**Comment by Haarolean** [comment]
Hey Jonas, we're planning to get rid of ZK at all within #1663
