### ISSUE TITLE
Unable to connect to a kafka cluster using SASL

### ISSUE THREAD

**Issue by shivansh** [provectus/kafka-ui#1736]
**Describe the bug**

I'm getting the error below after following instructions in [SASL_SCRAM.md](https://github.com/provectus/kafka-ui/blob/master/documentation/guides/SASL_SCRAM.md) when connecting to a cluster via kafka-ui using SASL -
```
Error while creating AdminClient for Cluster cluster_name
```

**Set up**
Commit hash: [38c4cf7](https://github.com/provectus/kafka-ui/commit/38c4cf7)

**Steps to Reproduce**
I used the following invocation from under `charts/kafka-ui/` -
```
$ helm install kafka-ui . \
  --set envs.config.KAFKA_CLUSTERS_0_NAME=cluster_name \
  --set envs.config.KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=<ENDPOINT> \
  --set envs.config.KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=SASL_SSL \
  --set envs.config.KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM=SCRAM-SHA-512 \
  --set envs.config.KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG="org.apache.kafka.common.security.scram.ScramLoginModule required username='<USERNAME>' password='<PASSWORD>';"
```

The corresponding pod logs are -
```
...(stripped)...
        ssl.truststore.password = null
        ssl.truststore.type = JKS

2022-03-17 12:39:10,011 INFO  [parallel-1] o.a.k.c.s.a.AbstractLogin: Successfully logged in.
2022-03-17 12:39:10,110 INFO  [parallel-1] o.a.k.c.u.AppInfoParser: Kafka version: 2.8.0
2022-03-17 12:39:10,110 INFO  [parallel-1] o.a.k.c.u.AppInfoParser: Kafka commitId: ebb1d6e21cc92130
2022-03-17 12:39:10,110 INFO  [parallel-1] o.a.k.c.u.AppInfoParser: Kafka startTimeMs: 1647520750108
2022-03-17 12:39:40,116 INFO  [kafka-admin-client-thread | adminclient-1] o.a.k.c.a.i.AdminMetadataManager: [AdminClient clientId=adminclient-1] Metadata update failed
org.apache.kafka.common.errors.TimeoutException: Call(callName=fetchMetadata, deadlineMs=1647520780112, tries=1, nextAllowedTryMs=1647520780213) timed out at 1647520780113 after 1 attempt(s)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call. Call: fetchMetadata
2022-03-17 12:40:10,115 ERROR [kafka-admin-client-thread | adminclient-1] c.p.k.u.s.MetricsService: Failed to collect cluster cluster_name info
java.lang.IllegalStateException: Error while creating AdminClient for Cluster cluster_name
```

I'm not sure if the line `Successfully logged in` indicates that the credentials are correct.

**Expected behavior**
I expected the metadata to be fetched successfully.

**Additional context**
The kafka cluster is provided via Confluent Cloud.

I was able to reproduce the same issue with the following `docker-compose.yaml` -
```
version: '3.4'
services:
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "9022:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=cluster_name
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=<ENDPOINT>
      - KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=SASL_SSL
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM=SCRAM-SHA-512
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.scram.ScramLoginModule required username="<USERNAME>" password="<PASSWORD>";
      - KAFKA_CLUSTERS_0_PROPERTIES_PROTOCOL=SASL
```

**Comment by shivansh** [comment]
I was able to resolve this by following the instructions [here](https://github.com/provectus/kafka-ui/issues/936#issuecomment-940096488), thanks!

**Comment by Haarolean** [comment]
Glad it works.

**Comment by paulolimarb** [comment]
Hi @shivansh 

Please, you can tell me how to resolved this problem? I can't to connect Kafka-ui on my kafka cloud confluent.

In your link i don't understand how to resolved this problem.

Thanks

**Comment by Haarolean** [comment]
> Hi @shivansh
> 
> Please, you can tell me how to resolved this problem? I can't to connect Kafka-ui on my kafka cloud confluent.
> 
> In your link i don't understand how to resolved this problem.
> 
> Thanks

@paulolimarb raise a new discussion or reach out to me on [discord](https://discord.gg/4DWzD7pGE5) and we'll take a look together.

**Comment by paulolimarb** [comment]
Thanks @Haarolean I will do it.
