### ISSUE TITLE
Hosts mismatched on the brokers page

### ISSUE THREAD

**Issue by felix-roo** [provectus/kafka-ui#1737]
**Describe the bug**
On the brokers page we have 6 brokers specified but only 6 hosts are returned. broker 1 (b-1.xxx) is missing.

**Set up**
Docker image is on the latest using very basic config with only broker links specified with READ_ONLY = true.

**Steps to Reproduce**

1. Specify 6 brokers in the configuration
2. Start the app
3. See that the brokers are not mapped correctly in the table

**Expected behavior**
I expect to see 6 brokers mapped correctly in the table

**Screenshots**
![image](https://user-images.githubusercontent.com/100605011/158861627-0e5ccb15-03e3-4363-9c4e-aa9a5c0d2b73.png)

**Additional context**
A quick inspect element shows me that the API does in fact respond with all 6 brokers intact. This makes me think it is likely an issue in the frontend where the brokers are filtered/modified in some way.

**Comment by Haarolean** [comment]
@felix-roo hey, thanks for reaching out! We'll take a look.

**Comment by simonyandev** [comment]
Can't find the bug, everything seems to work normally.

**Comment by Haarolean** [comment]
@simonyandev I could reproduce it, one of the brokers should be offline.
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/1494347/164317650-3f41cc4f-532f-4d8c-a792-90ea72c53ba4.png">
