### ISSUE TITLE
Bundle for 0.3.3

### ISSUE THREAD

**Issue by mario45211** [provectus/kafka-ui#1743]
Hi,

Are you planning to append bundled (compiled) version of application to the v0.3.3 release ? Manually building is not very convenient for some of my environments. 

Thanks in advance!

**Comment by Haarolean** [comment]
Hey, thanks for reaching out.
We've altered our release workflow that's why it's missing for 0.3.3. Future releases will have the jar file attached.
I've attached 0.3.3 [here](https://github.com/provectus/kafka-ui/releases/download/0.3.3/kafka-ui-0.3.3.jar).

**Comment by mario45211** [comment]
Many thanks!
