### ISSUE TITLE
"Connection to a secure broker" link is broken

### ISSUE THREAD

**Issue by lucasprograms** [provectus/kafka-ui#1752]
**Describe the bug**
1. Visit https://github.com/provectus/kafka-ui#guides
2. Click "Connection to a secure broker" link

Expected:
Guide, no octocat

Actual:
Octocat

**Comment by Haarolean** [comment]
Hey, thanks for bringing attention at this.

This link should actually lead to [this](https://github.com/provectus/kafka-ui/blob/master/documentation/compose/kafka-ssl.yml) compose file. We haven't done a separate page for it yet but there's a broken link already :)
