### ISSUE TITLE
kafka connect UI hide some config and can't update

### ISSUE THREAD

**Issue by raphaelauv** [provectus/kafka-ui#1755]
**Describe the bug**

I can't see my connector full config , it hide on line of the configuration ( it's a debezium connector )

![Screenshot from 2022-03-24 13-43-37](https://user-images.githubusercontent.com/10202690/159918926-237b8b10-b302-475e-9468-cf08b4f13aeb.png)

**Expected behavior**
I want see all my configuration , same connector in AKHQ 

![Screenshot from 2022-03-24 13-45-32](https://user-images.githubusercontent.com/10202690/159919036-3d03e009-edec-490c-bba8-74c6e46f5090.png) 

Also I can't update my config if I don't fully rewrite the hidden line

![Screenshot from 2022-03-24 13-47-21](https://user-images.githubusercontent.com/10202690/159919485-9e0ec581-fc13-4c8c-bbdc-72e223e4d48e.png)

I have to copy past this line in the conf to be able to edit it

```json
  "database.password": "${file:/secrets/credentials.properties:INVENTORY_CONNECTOR_MYSQL_PASSWORD}",
```

**Comment by Haarolean** [comment]
Hey, thanks for reaching out.

This is the obfuscation mechanism, unfortunately that would be difficult to tell a difference between a plaintext password and a link like in your case. I can only recommend you to disable obfuscation at all, if that suits you.

**Comment by Haarolean** [comment]
@raphaelauv this commit has been commited within 0.4 release, `latest` refers to 0.3.3. You could try `master`-labeled image or any fixed one (there's one per commit).

**Comment by raphaelauv** [comment]
It work ! Thank you @Haarolean 

![Screenshot from 2022-03-24 16-16-13](https://user-images.githubusercontent.com/10202690/159949137-c39d5a11-3787-4348-a3a5-f702e76c5ae5.png)

using

```yaml
  kafka-ui:
    image: provectuslabs/kafka-ui:73266f86af4c3cf093afdedcd9880b5f92d4c328
```

**Comment by Haarolean** [comment]
Great it works!
