### ISSUE TITLE
Update kafka-clients dependency to 3.1.0

### ISSUE THREAD

**Issue by raphaelauv** [provectus/kafka-ui#1756]
current version is Kafka version: 2.8.0

there is now the version 3.1.0

**Comment by Haarolean** [comment]
Hi, thanks for reaching out.

What's the point? Have you encountered any problem?

**Comment by raphaelauv** [comment]
I'm thinking about multiple features

- Apache Kafka supports Java 17
- Ability to restart a connector's tasks on a single call in Kafka Connect
- Extend OffsetFetch requests to accept multiple group ids.

**Comment by Haarolean** [comment]
So, you're using the app as API?

1. Good point, noted.
2. I feel like we might've done it within #1444 already. Is that right?
3. Okay.

**Comment by raphaelauv** [comment]
1717

**Comment by raphaelauv** [comment]
the feature to restart all tasks is buggy in 3.1.0 , let's wait for 3.1.1

-> https://issues.apache.org/jira/browse/KAFKA-13719?src=confmacro
