### ISSUE TITLE
Expand message view on row click

### ISSUE THREAD

**Issue by mario45211** [provectus/kafka-ui#1764]
Hi,

At first I would like to admit your app is so far the best Kafka's UI I've tried!
 
I'd like to kindly ask you to improve message view, where click on any place on a message's row would open extended view of that message. Currently, only left plus button could expand message's details.

Please consider and let me know what you're thinking about such improvement.

Best regards!

**Comment by Haarolean** [comment]
Hey, thanks for the kind words. Glad you like it :)

As for the tables, we've considered that (#1414), but there are some possible issues with that (like behaviour for sandwich buttons). I agree that it would be more convenient, but it's not a priority for now. But we'll consider it, thanks.
