### ISSUE TITLE
Show number of messages in the Topic Overview 

### ISSUE THREAD

**Issue by erik93slash** [provectus/kafka-ui#1765]
### Is your proposal related to a problem?

In the topics list there is a column reporting the number of messages published in each topic, but when you enter in the topic details you cannot find that info anywhere.
![image](https://user-images.githubusercontent.com/38383366/160137147-ef9dea82-3b91-4c1a-a5b3-c8b6099981bb.png)

### Describe the solution you'd like

In the Topic Overview section, it would be great to show the number of messages. It may be showed in the header of the section.
![image](https://user-images.githubusercontent.com/38383366/160137357-e9b8fdb3-c8a5-4810-861c-1d7ae6a033f0.png)

**Comment by Haarolean** [comment]
Hi, thanks for reaching out. This has been already implemented within #1015.
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/1494347/161098954-026e9ee4-89b5-4446-b595-658854158069.png">
