### ISSUE TITLE
Error when running behind a reverse proxy with a path prefix

### ISSUE THREAD

**Issue by anthares** [provectus/kafka-ui#1768]
**Describe the bug**

When using kafka-ui behind a reverse proxy (both nginx and trafik), trying to configure it on a sub-path (/kafka-ui) doesn't work without a trailing `/`.
Any attempt to reach kafka-ui ends up in a 404 through reverse proxy.
Reaching through direct port (8082) result in a json response with 404 message.
```json
{
  "code": 5000,
  "message": "404 NOT_FOUND",
  "timestamp": 1648462573453,
  "requestId": "936e888d-1",
  "fieldsErrors": null,
  "stackTrace": "org.springframework.web.server.ResponseStatusException: 404 NOT_FOUND\n\tat org.springframework.web.reactive.resource.ResourceWebHandler.lambda$handle$1(ResourceWebHandler.java:379)\n\tSuppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: \nError has been observed at the following site(s):\n\t*__checkpoint ⇢ com.provectus.kafka.ui.config.CustomWebFilter [DefaultWebFilterChain]\n\t*__checkpoint ⇢ com.provectus.kafka.ui.config.ReadOnlyModeFilter [DefaultWebFilterChain] (...)"
}
```

**Set up**

Docker for Windows with image `provectuslabs/kafka-ui:latest` (f1e30cd9d423)

**Steps to Reproduce**

1. Clone kafka-ui repo
2. Remove trailing `/` in `PathPrefix` in `documentation/compose/traefik/kafkaui.yaml`
3. Run `cd documentation/compose && docker compose --file kafka-ui-traefik-proxy.yaml up -d` in terminal
4. Browsing to `http://localhost/kafka-ui` results in 404

(Same issue with `kafka-ui-reverse-proxy.yaml`; its not a traefik config issue)

**Expected behavior**

We should be able to run kafka-ui on a sub-path behind a reverse proxy with or without trailing `/`.
It's quite dumb, but I searched several hours to figure out my 404 was due to missing forward slash.
I'm pretty sure I'm not the first to shoot himself with this :)

**Additional context**

My use case is a development docker compose, with multiple UI's (our webapp, pgadmin, kafka-ui, ...) on different path prefix behind traefik.

I found this because my traefik rule is ``PathPrefix(`/kafka-ui`)``.

Looking at the stacktrace and current code on master branch, I think [`CustomWebFilter`](https://github.com/provectus/kafka-ui/blob/master/kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/CustomWebFilter.java#L19) does not handle request properly when path is empty.

Thank you for your time :)

Best regards

**Comment by Haarolean** [comment]
Hey, thanks for reaching out. I'll investigate.

**Comment by mhorlacher** [comment]
Any updates on this? I'm encountering a similar problem. 

Here's my nginx config for kafka-ui:

```
  location /kafka-ui/ {
    proxy_set_header X-Script-Name /kafka-ui;

      proxy_pass http://kafka-ui:8081;
  }
```

Here's the error:
![image](https://user-images.githubusercontent.com/37439882/163708590-94c633f2-f648-45aa-aac7-a40c80d37efb.png)

**Comment by Haarolean** [comment]
Will be fixed within #1874 and will be a part of 0.4 release (or you can always pull the `master`-labeled image).

**Comment by anthares** [comment]
A bit late, but thank you @Haarolean for fixing this :)

**Comment by Haarolean** [comment]
> A bit late, but thank you @Haarolean for fixing this :)

You're welcome :)

**Comment by mhorlacher** [comment]
I'm still running into this issue - which nginx configuration()s) are you using @Haarolean @anthares ?

**Comment by anthares** [comment]
I have not tested with nginx, since I'm using traefik as reverse proxy.
It do works with 0.4.0 with standard configuration, nothing fancy.

Maybe make sure you pulled the latest image, or check examples as they provide working configurations.
