### ISSUE TITLE
KSQLDB: Support Basic Auth

### ISSUE THREAD

**Issue by niyatidoshi** [provectus/kafka-ui#1775]
Hi Team,

I'm trying to connect KSQL DB which is on Confluent Cloud but I'm getting error "Failed to fetch tables and streams".

I've added below property in Docker-Compose file,
KAFKA_CLUSTERS_0_KSQLDBSERVER: https://test-db-xxx.confluent.cloud

To connect that DB, I guess we need to provide a Key/Secret and I don't see properties to provide the same.

Could you pls advise, what am I missing here?

Thank you.

**Comment by Haarolean** [comment]
Hey, thanks for reaching out.

If your ksqldb server uses basic auth, unfortunately we currently do not support auth. We're planning on implementing this in future releases.

**Comment by niyatidoshi** [comment]
Hey Haarolean,

Thanks for the update. Our KSql DB is in Confluent Cloud. Here is the doc that was followed https://docs.confluent.io/cloud/current/get-started/ksql.html and for the 1st step (Access Control) we chose Granular access.  For the connectivity, an additional Key/Secret was created. Hope this helps.

Could you pls include this feature in your future release?


Thank you.

**Comment by Haarolean** [comment]
@niyatidoshi we'll try to for sure :) thanks for the instructions

**Comment by Diyaa1** [comment]
When will this be released :/
