### ISSUE TITLE
Topic not loading on Kafka UI

### ISSUE THREAD

**Issue by Mindgap1** [provectus/kafka-ui#1782]
**Describe the bug**
When i try to see the list of topics, the page loading but nothing happen. Then i receive "no topics found".
Everything is working in the Kafka UI. Only topics are not listed.

**Set up**
I run Kafka UI (38c4cf7) with docker-compose and kafka istance is running with Bitnami image with latest version of kafka(3.1) and zookeeper(3.7).

This is kafka ui compose file:
![Immagine 2022-03-31 101026](https://user-images.githubusercontent.com/37620232/161009908-927ecc5f-7db8-48ac-8cd6-6fa134303e05.png)

**Steps to Reproduce**
I start the kafka ui container with "docker-compose up" then i go to localhost:8080 and click on "topics" then this happened
![Immagine 2022-03-31 100208](https://user-images.githubusercontent.com/37620232/161009643-d2b306e8-a203-42c2-9b50-52e8533f42e3.png)
After loading it goes in timeout with this: 
![Immagine 2022-03-31 100246](https://user-images.githubusercontent.com/37620232/161009723-b4827c32-0800-44af-abdc-4487d2811339.png)

**Expected behavior**
On container terminal i receive: "HV000254: Missing parameter metadata for TopicColumnsToSortDTO(String, int, String), which declares implicit or synthetic parameters. Automatic resolution of generic type information for method parameters may yield incorrect results if multiple parameters have the same erasure. To solve this, compile your code with the '-parameters' flag"

![Immagine 2022-03-31 100923](https://user-images.githubusercontent.com/37620232/161009788-754a4826-a624-4237-8e43-cdb7fe403e92.png)

On network tab in my browser i receive ERROR 500
![Immagine 2022-03-31 100408](https://user-images.githubusercontent.com/37620232/161009833-ea830642-ce7c-485e-9f1b-627c4bf48afd.png)

I don't know really where to add this -parameters flag and i don't know how to fix this error.

**Additional context**
The strange things is that everything is fine with kafka ui except for topics. KSQL DB and connect are working too!

**Comment by Haarolean** [comment]
Hey, thanks for reaching out. Please share the full application log, there should be a stacktrace. Also, some details (request URL for example) from browser's developer console would be nice to see.

**Comment by Mindgap1** [comment]
I edited my message with screenshots, hope they'll be useful

**Comment by Haarolean** [comment]
@Mindgap1 thanks, they are. We'll take a look.

**Comment by Mindgap1** [comment]
> Hi @Mindgap1 ! can you please share full docker-compose file that you run (excluding secrets and non-kafka-related services)?

Yeah sure! Here it is the compose file (TXT - Because can't format correctly and paste here doesn't work properly due to bad format) for kafka environment:

[kafka-compose.txt](https://github.com/provectus/kafka-ui/files/8389619/kafka-compose.txt)

**Comment by iliax** [comment]
Hello @Mindgap1, applied couple of fixes that can solve your problem - pls check docker image with `master` tag

**Comment by jrione** [comment]
I have a similar issue while opening the "topic" menu. I'm using kafka 3.9.0 (with systemd) and kafka-ui 0.7.2 (docker compose).

![Image](https://github.com/user-attachments/assets/ec171563-b2b3-43c6-84be-954bd4584d42)

**Comment by Haarolean** [comment]
This repo is not maintained (#4255), raise your issues at https://github.com/kafbat/kafka-ui
