### ISSUE TITLE
SPRING_LDAP_DN_PATTERN 

### ISSUE THREAD

**Issue by djakupovic** [provectus/kafka-ui#1783]
Hey,

first of all: great work!
the documentation is not helpful regarding this setting. If this variable is set to the DN of the user with:
CN={0},OU=GroupA,OU=OU2,OU=OU3,DC=DC1,DC=DC2 everything works fine. 
In the search filter SPRING_LDAP_USERFILTER_SEARCHFILTER we check if the login user is memberOf another group. However, every user has a different DN so e.g.
User 1: CN=user1,OU=GroupA,OU=OU2,OU=OU3,DC=DC1,DC=DC2  login works
User 2: CN=user2,OU=GroupB,OU=OU2,OU=OU3,DC=DC1,DC=DC2  login does not work

What to set in SPRING_LDAP_DN_PATTERN if the DN in the AD is different for every user? Wildcards are not functioning

**Comment by Haarolean** [comment]
@djakupovic it's not a mandatory field in any way, it should work fine without it. Have you tested it?

**Comment by djakupovic** [comment]
"ERROR [main] o.s.b.SpringApplication: Application run failed


org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'globalErrorWebExceptionHandler' defined in URL [jar:file:/kafka-ui-api.jar!/BOOT-INF/classes!/com/provectus/kafka/ui/exception/GlobalErrorWebExceptionHandler.class]: Unsatisfied dependency expressed through constructor parameter 3; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.web.reactive.WebFluxAutoConfiguration$EnableWebFluxConfiguration': Unsatisfied dependency expressed through method 'setConfigurers' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.security.config.annotation.web.reactive.ServerHttpSecurityConfiguration': Unsatisfied dependency expressed through method 'setAuthenticationManager' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ldapSecurityConfig': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'spring.ldap.dn.pattern' in value "${spring.ldap.dn.pattern}"" 

I need to start the docker container with SPRING_LDAP_DN_PATTERN, so its kinda mandatory. If i keep it blank like SPRING_LDAP_DN_PATTERN="" the same error occurs.

**Comment by Haarolean** [comment]
@djakupovic which version are you on?

**Comment by djakupovic** [comment]
you were right, with the newest version everything functions right. LDAP_DN_PATTERN is an optional value. LDAPs works! Thank you!

**Comment by djakupovic** [comment]
with current version LDAP functions without DN parameter

**Comment by eblis** [comment]
I'm trying to configure LDAP authentication in Kafka UI and I have the same problem, the users have different DNs.
I stopped specifying the `SPRING_LDAP_DN_PATTERN` variable but then authentication isn't working at all.

```
kafka-ui   | 2023-01-19 10:31:17,540 DEBUG [boundedElastic-1] o.s.s.l.a.BindAuthenticator: Failed to bind with any user DNs []
kafka-ui   | 2023-01-19 10:31:17,549 DEBUG [boundedElastic-1] o.s.s.w.s.a.AuthenticationWebFilter: Authentication failed: Bad credentials
kafka-ui   | 2023-01-19 10:31:17,550 DEBUG [boundedElastic-1] o.s.s.w.s.DelegatingServerAuthenticationEntryPoint: Trying to match using org.springframework.security.config.web.server.ServerHttpSecurity$HttpBasicSpec$$Lambda$819/0x00000008015accc0@30aac93

```

**Comment by Haarolean** [comment]
@eblis please raise a new issue
