### ISSUE TITLE
Log out button

### ISSUE THREAD

**Issue by djakupovic** [provectus/kafka-ui#1784]
### Is your proposal related to a problem?

logout button after LDAP/SSO login
### Describe the solution you'd like
Right corner a small button with logout

### Describe alternatives you've considered
Session timeout after N seconds

**Comment by Haarolean** [comment]
Hey, thanks for reaching out. We were planning on implementing this within #1021, but I guess we can do it quicker.

**Comment by Haarolean** [comment]
#1175
