### ISSUE TITLE
can't support IPV6

### ISSUE THREAD

**Issue by mosaicwang** [provectus/kafka-ui#1790]
**Describe the bug**

kafka and zk started and connect by IPV6

kafka-ui can't connect to kafka with IPV6,only connect to IPV4 kafka

**Set up**

**Steps to Reproduce**

1. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Haarolean** [comment]
Greetings, please fill out the "set up" paragraph described in the issue template. As mentioned there, we won't be able to help you unless we know the details of your setup.
