### ISSUE TITLE
Too many connections to Zookeeper

### ISSUE THREAD

**Issue by imoisey** [provectus/kafka-ui#180]
I have a problem with many connections to Zookeeper from kafka-ui.

Zookeeper logs:

![image](https://user-images.githubusercontent.com/2510489/107490229-aa3a1180-6b9a-11eb-9994-55bc960908c3.png)

docker-compose.yml

Kafka UI:
![image](https://user-images.githubusercontent.com/2510489/107490589-22083c00-6b9b-11eb-85b0-3b20935aeba0.png)

Zookeeper:
![image](https://user-images.githubusercontent.com/2510489/107490633-2fbdc180-6b9b-11eb-995c-995e667fa25d.png)

What am I doing wrong?

**Comment by germanosin** [comment]
@imoisey thank you for your issue. This bug will be fixed soon by https://github.com/provectus/kafka-ui/pull/185

**Comment by imoisey** [comment]
Thanks
