### ISSUE TITLE
UI: connectors , order topics

### ISSUE THREAD

**Issue by raphaelauv** [provectus/kafka-ui#1809]
![Screenshot from 2022-04-06 19-15-20(1)](https://user-images.githubusercontent.com/10202690/162033378-f158a003-ec47-4120-93cf-92b010a6c644.png)
### Is your proposal related to a problem?

the current UI of connectors show the topics that consume or produce the connectors , but they are not ordered by name , that mean if I it refresh the order of the topics change

and also two connectors with the same topics can show the topics in a different order

### Describe the solution you'd like

topics by each connector sort by name in the UI

### Additional context

Thanks :+1:

**Comment by Haarolean** [comment]
Hey, thanks for the suggestion!
