### ISSUE TITLE
Topics and Consumers views are stuck loading while cluster metrics are being updated

### ISSUE THREAD

**Issue by shmyer** [provectus/kafka-ui#1835]
**Describe the bug**

Updating the metrics is taking a while for my kafka cluster when specifying the JMX port. During that time the UI views "Topics" and "Consumers" are stuck in loading state. When opening the developer tools in chrome I can see that the HTTP request is stuck in pending state until the backend finishes updating the metrics.

Edit:
This seems to be the case for the Brokers endpoint aswell: /api/clusters/xyz/brokers

**Set up**

I am running the app locally in a docker container (tag: master, commit: d79412fe26fb71e651c447697dd5619c061ed576). I could see that this issue is present in tag 0.3.3 aswell.

**Steps to Reproduce**

1. Configure kafka cluster with jmx port in kafka-ui
2. Maybe have enough topics in order to provoke a long load time for metrics? I am running about 230 topics.
3. Open UI and go to Topics/Consumers view while backend's last log message was "Start getting metrics for kafkaCluster: xyz"

**Expected behavior**

The UI's request should not be blocking while metrics are being updated in the backend. Just get the last known metrics and don't wait for the update to finish.

**Additional context**

Maybe a synchronization issue in the backend?

**Comment by Haarolean** [comment]
Hey, thanks for reaching out.
We're currently working on something like this (#1689). Let's wait for solution for that issue and we'll see how it goes for you.

cc: @iliax

**Comment by Haarolean** [comment]
@shmyer changes are available in master-labeled docker image. Please let us know if the problem persists.

**Comment by shmyer** [comment]
@Haarolean can confirm that it is working as expected now. Thanks a lot!

**Comment by Haarolean** [comment]
@shmyer that's great! Glad it works.
