### ISSUE TITLE
Future naming issue ?

### ISSUE THREAD

**Issue by BDeus** [provectus/kafka-ui#1837]
Hi, i love kafka-ui i think it will be the best UI for Kafka when all features roadmap will be implemented.

Just a quick remark, 
i think you will have an issue in the future with the "kafka" naming in your project (like Kafka manager (CMAK) and Kafka HQ (AKHQ) before you). [CMAK issue](https://github.com/yahoo/CMAK/issues/713)
The apache kafka community will probably ask you to rebrand your project.

I think sooner is better, before it's becoming the most used open source UI for kafka 👍

**Comment by Haarolean** [comment]
Hey, thanks for your kind words. Glad you like it :)

Regarding the naming, we're [well aware ](https://github.com/provectus/kafka-ui/discussions/1468), and it seems to be okay for now. Thanks for letting us know, tho.

**Comment by BDeus** [comment]
sorry for the duplicate.
continue the good work !
