### ISSUE TITLE
Kafka Connect page. Navigation by breadcrumbs is not working

### ISSUE THREAD

**Issue by IldarAlmakaev** [provectus/kafka-ui#1852]
**Describe the bug**

**Set up**

**Steps to Reproduce**
Please see the attached [GIF](https://gyazo.com/e148d0dd001f6a8ec663d4d44e5e9bdf)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Haarolean** [comment]
@simonyandev let's see what has happened since we fixed it within #1193

**Comment by Haarolean** [comment]
@IldarAlmakaev it works fine on latest master, try running the latest version (`master`-labeled image)
