### ISSUE TITLE
Display source/sink connector version along with type, plugin, etc

### ISSUE THREAD

**Issue by IldarAlmakaev** [provectus/kafka-ui#1853]
### Describe the solution you'd like
As a user, I'd like to see what version of a connector is deployed on my cluster along with type, plugin, etc.

### Additional context

<img width="1721" alt="Screenshot 2022-04-18 at 16 21 39" src="https://user-images.githubusercontent.com/11831199/163814232-a7131b30-cc27-4b54-9fbd-39f3951cfbe8.png">

**Comment by Haarolean** [comment]
Considering you're on 0.3.3, there's more info on latest master:
<img width="911" alt="image" src="https://user-images.githubusercontent.com/1494347/163883195-f18ca7e8-35f7-4d32-9569-11e17d776911.png">
<img width="827" alt="image" src="https://user-images.githubusercontent.com/1494347/163883208-3014dfd4-42a6-4ece-8569-8892d53f37da.png">

Is there anything important missing?
