### ISSUE TITLE
Topic list : add filter

### ISSUE THREAD

**Issue by giom-l** [provectus/kafka-ui#187]
Hi, 

That would be a really good improvement to be able to filter the list of topics.
Currently, all topics name are displayed within the page, which can be very heavy to load for large clusters.

A filter bar with dynamic filtering would be a great thing

Version used : 0.0.9

**Comment by workshur** [comment]
AC: 
- Add search by name query
- Filter:
  - Internal topic on BE
- Order By
  - Name
  - Out of sync replicas
  - Total Partitions
