### ISSUE TITLE
Topic list : paginate list

### ISSUE THREAD

**Issue by giom-l** [provectus/kafka-ui#188]
Hi, 

Currently, all cluster topics are loaded in the page, which can be inconvenient for large clusters with thousand of topics (scroll is our friend :) )
A pagination could be helpful to limit the number of topics displayed.

Version used : 0.0.9

**Comment by germanosin** [comment]
@giom-l thank you for your contribution, could you please share some details of your kafka installation? How many topics, partitions do you have?

**Comment by giom-l** [comment]
Hi, 
the cluster I tested kafka-ui against has 6 brokers, 788 topics and 3853 partitions.
