### ISSUE TITLE
Hiding the content of messages

### ISSUE THREAD

**Issue by felix-roo** [provectus/kafka-ui#1882]
### Is your proposal related to a problem?
We run this in both staging and prod environments but do not want to display the message data in production just yet. There doesn't seem to be a clean way to toggle this off so for now we run a version with this hardcoded off (i.e. code for preview is literally deleted)

### Describe the solution you'd like
Some kind of configuration setting to disable message previews similar to READ_ONLY_MODE

### Describe alternatives you've considered
The only other option is revoking the ACL to read messages but we still want to show the messages for a topic + keys, etc. just not the content of a message.

**Comment by Haarolean** [comment]
Hey, thanks for reaching out. This has to be done after we implement RBAC (#753). 
Please follow #1027 for updates.
