### ISSUE TITLE
The result of Clear Messages is not displayed in Topic overview

### ISSUE THREAD

**Issue by agolosen** [provectus/kafka-ui#1884]
**Describe the bug**

When you click Clear Messages on the Topic overview page you still see the topic`s messages like nothing happened but if you refresh the page or go to the topic you see that messages are cleared.

**Set up**

https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to local/Topics
2. Choose some topic
3.  Click on the sandwich menu and choose Clear Messages
4. Observe: 1) there is no Warning message to Confirm clearing
                    2) Messages are still in the topic
                    3) However, if you refresh the page or click on the topic - messages are cleared.

**Expected behavior**

1) Display the Warning message to Confirm the action
2) Clear messages of the topic in the table Topic overview.

**Screenshots**

**Additional context**

**Comment by armenuikafka** [comment]
Update with Clear Messages available in Topic's Overview tab only after refreshing, please check the attached video:

https://user-images.githubusercontent.com/104780608/170261514-df248abf-dc73-4e64-9eeb-236ecf9f402a.mov

_**Note**: Works correctly with Clearing messages from all Topics page_
