### ISSUE TITLE
Success message should be shown after Recreate Topic

### ISSUE THREAD

**Issue by agolosen** [provectus/kafka-ui#1887]
**Describe the bug**

If you click Recreate Topic it`s not obvious that the action has done.

**Set up**

https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to local/Topics
2. Choose some topic and click on sandwich menu
3. Click Recreate Topic
4. Observe: Messages updated to 0 but without Success message it`s not clear that it worked well.

**Expected behavior**

Show Success message on the page after action completed.

**Screenshots**

**Additional context**

**Comment by agolosen** [comment]
If you Click on Recreate Topic inside the topic the messages don`t disappear after the action, you must refresh page to see the result.

**Comment by simonyandev** [comment]
Is fixed on https://github.com/provectus/kafka-ui/pull/1830
