### ISSUE TITLE
UI : read-only option

### ISSUE THREAD

**Issue by giom-l** [provectus/kafka-ui#189]
Hi, 

I really like the look and feel of you UI (which is more sexier than landoop UI that I use currently)
However, one thing that I really like from them is that I can't modify anything on the cluster.
And that is very convenient to offer my user an user-friendly UI to browse their topic content.

Would that be possible to have an option to set that would deactivate all modification possibilities (like topic settings, topic creation and so on) ? 

Version used : 0.0.9

**Comment by germanosin** [comment]
@giom-l , thank you for your question. This feature is already in our roadmap will be fixed soon. 
https://github.com/provectus/kafka-ui/issues/164
