### ISSUE TITLE
Topics view jumpy rendering on mouse over

### ISSUE THREAD

**Issue by rrva** [provectus/kafka-ui#1891]
**Describe the bug**

Topics list moves sideways a bit when mouse focus is moved over it

**Set up**

https://github.com/provectus/kafka-ui/commit/a7d3f1d

**Steps to Reproduce**

See recording, or:

1. Have some topics (widest topic name in my setup is 36 chars)
2. Go to the topics view
3. Move mouse focus to the topics list

**Expected behavior**

Rendering does not move sideways

**Screenshots**

https://user-images.githubusercontent.com/887132/165025456-288989e0-2cce-4c56-b789-ec5e56c3aada.mov

**Comment by Haarolean** [comment]
Hey, thanks for raising the issue. This has been actually fixed already (#1473)
