### ISSUE TITLE
BE: Fix sonar code smells

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#1911]
https://sonarcloud.io/project/issues?resolved=false&id=com.provectus%3Akafka-ui_backend

**Comment by Haarolean** [comment]
blocked by #1537

**Comment by dshubhadeep** [comment]
@Haarolean is this issue still open to work on ?

**Comment by Haarolean** [comment]
@dshubhadeep yes

**Comment by Haarolean** [comment]
@dshubhadeep any luck?

**Comment by dshubhadeep** [comment]
@Haarolean will submit a PR by this weekend
