### ISSUE TITLE
Broker and cluster shows offline even though its up and running in local

### ISSUE THREAD

**Issue by Chaithraasmoto** [provectus/kafka-ui#1918]
**Describe the bug**
Broker and cluster shows offline even though its up and running in local

**Set up**
I'm uisng official docker image in local - https://hub.docker.com/r/provectuslabs/kafka-ui and running the below command for docker
docker run -p 8080:8080 -e KAFKA_CLUSTERS_0_NAME=local -e KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=127.0.0.1:9092 -d provectuslabs/kafka-ui:master

**Steps to Reproduce**
Running the above steps loads kafka UI but both Broker and Cluster is offline 

**Expected behavior**
I should be able to see the local broker and topic details in Kafka UI

**Screenshots**
![image](https://user-images.githubusercontent.com/104765814/166224173-b0612fd2-4026-415b-b331-94631d255840.png)

**Additional context**
My zookepeer is running in port 9092 in local

**Comment by Chaithraasmoto** [comment]
Hi,
Please help with above issue

Thanks

**Comment by azatsafin** [comment]
Hi @Chaithraasmoto 

Port 9092 is used for kafka brokers, and in KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS you should provide Kafka broker endpoint. If you want to provide Zookeeper endpoint (for monitor Zookeeper status), you must provide additionall env KAFKA_CLUSTERS_0_ZOOKEEPER with respective value to the Zookeeper endpoint, actually Zookeeper not required for KafkaUI functionality.

**Comment by Haarolean** [comment]
Hey @Chaithraasmoto, thanks for reaching out. 
Please use the correct issue template next time, this is not related to k8s or helm.

Your problem is that you're running kafka on bare metal and trying to access it via localhost IP, which, in turn, is kafka-ui container's host. You have to follow [this guide](https://github.com/provectus/kafka-ui/discussions/1081) to access your bare-metal kafka installation from inside a docker container. Feel free to join us on discord if you won't be able to solve it.

**Comment by vijaykumar78** [comment]
<img width="932" alt="kafka-ui-error" src="https://user-images.githubusercontent.com/48557262/213453468-774b8f05-42bc-4c6c-82d2-ddff2d232f38.png">

i have installed kafka-UI by using below  helm commands :

helm repo add kafka-ui https://provectus.github.io/kafka-ui
helm install kafka-ui kafka-ui/kafka-ui --set envs.config.KAFKA_CLUSTERS_0_NAME=local --set envs.config.KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092

but as shown in below screenshot it shows the online clusters "0" show offline"1" but in cluster kafka is running fine able to create topics etc kindly help me on this

**Comment by Haarolean** [comment]
@vijaykumar78 please raise a new issue

**Comment by hyungkishin** [comment]
병신같은 카프카 ui
