### ISSUE TITLE
Display build date instead of full commit hash in version info

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#1933]
1. Remove VITE_TAG
1. Remove VITE_COMMIT
1. fetch info from Spring API `/actuator/info` `{commit, tag, buildDate: timestamp}`
1. If tag is a version (v0.5.0) fetch latest version from github and compare with tag.
6. If tag is a commit we need to display formatted timestamp (`/api/info/timestampformat/iso`)
7. if tag contains `-SNAPSHOT` - display formatted timestamp
9. Keep the short one with the link

**Comment by Haarolean** [comment]
`{"git":{"commit":{"id":"c8306f5"}},"build":{"artifact":"kafka-ui-api","name":"kafka-ui-api","time":"2022-09-15T02:31:12.047Z","version":"0.0.1-SNAPSHOT","group":"com.provectus"}}`
#2583

**Comment by habrahamyanpro** [comment]
7th point is unclear

**Comment by Haarolean** [comment]
> 7th point is unclear

a short commit contains a link, let's keep it
