### ISSUE TITLE
Dashboard table is messed up

### ISSUE THREAD

**Issue by akamensky** [provectus/kafka-ui#1938]
**Describe the bug**

When many clusters are defined in configuration, the dashboard looks messed up:

- multiple tables instead of 1
- cluster ordering is out-of-order (that was fixed earlier for left side list)
- columns are not aligned

**Set up**
- Docker-compose with configuration set via environment variables (v0.4.0 tag from Docker Hub)

**Steps to Reproduce**

1. Add 10+ clusters to the list
2. Look at the dashboard

**Expected behavior**
Dashboard looks clean (single table, columns aligned, clusters ordered same as in configuration)

**Screenshots**
![Screenshot from 2022-05-10 13-56-03](https://user-images.githubusercontent.com/985805/167540497-a9c27bea-cbc4-4b80-8ff9-95a3c7222f6a.png)

**Additional context**
- Screenshot cannot show ordering issue due to needing to mask cluster names for privacy

**Comment by akamensky** [comment]
PS: thanks for working on this project, it is the best UI for looking at Kafka cluster data I've seen so far.

**Comment by Haarolean** [comment]
Hey Alex, thanks for the feedback, glad you like the new release :)

We'll take a look into the problem. We've done a lot of frontend refactoring recently, so this might be the reason.
