### ISSUE TITLE
Multiple users with different permission 

### ISSUE THREAD

**Issue by smeana** [provectus/kafka-ui#1947]
Hello!

Does Kafka UI support in some way having multiple users with differrent ACLs, monitoring the cluster?
Filtering in some way what topics can be read depending on the user you have to access kafka ui?

Regards

**Comment by Haarolean** [comment]
Hey, thanks for reaching out. It seems like you need #753. That's the feature planned for the next release, we're gonna start working on it soon. Feel free to subscribe to that issue and upvote :)
