### ISSUE TITLE
Cannot search across all messages in topic

### ISSUE THREAD

**Issue by maxonline** [provectus/kafka-ui#2001]
**Describe the bug**
When i have a topic with a large number of messages (over 1m) the search failed to return a result which we know is in the topic. When we specified offset to 500k we found the message. 

**Set up**

version: v0.0.1-SNAPSHOT [a7d3f1d](https://github.com/provectus/kafka-ui/commit/a7d3f1d)

**Steps to Reproduce**
1.  Have a large topic
2. Search for a key of a message that you know exists in the later part of the topic

**Expected behavior**
Find message with the correct key  without specifying offset

**Comment by maxonline** [comment]
@rrva

**Comment by Haarolean** [comment]
Hey, could you try it with a latest version? We've made some changes which might fix your issue (literally last commit). You can pull docker image tagged with `master` label.
