### ISSUE TITLE
UI: Dark theme

### ISSUE THREAD

**Issue by Nilsiker** [provectus/kafka-ui#2003]
### Is your proposal related to a problem?

No - it is merely an aesthetic addition, with the possible benefit of being an accessibility feature for some people.

### Describe the solution you'd like

Enabling a dark mode theme by a toggle slider in the header, utilizing styled-components to apply the theme (draft screendumps at the bottom).

### Describe alternatives you've considered

Since the project is already using styled-components, it is not a major feat to add an additional dark theme for the React app.

I have a base (and maybe somewhat naive, since I'm not strictly a frontend developer) fork where I've added a toggle in the header, that enables and disables Dark mode. The theme choice is stored as a simple localStorage variable.

Link to fork: [https://github.com/Nilsiker/kafka-ui](https://github.com/Nilsiker/kafka-ui)

### Additional context

If there are any better ways to handle multiple themes (mine is simply a duplication of the theme object, and a toggle between the light and dark theme objects), I would love hearing them.

Furthermore, I won't pretend I'm good at mix'n'matching color schemes, so any suggestions for a dark mode color scheme following the Theme object, would be highly appreciated.

Additionally, I'm unsure about how to handle the css-manipulation for the Ace webeditor.

![image](https://user-images.githubusercontent.com/34456840/169653569-bc1018b8-0f48-49fa-8c66-160a39d53cb8.png)
![image](https://user-images.githubusercontent.com/34456840/169653558-572dc7f0-0831-401f-9528-8e4c3fc6a8c3.png)

**Comment by Haarolean** [comment]
Hey, thanks for the suggestion! We'll discuss it soon, I'll let you know once I have more details :)

**Comment by sw-tracker** [comment]
+1
