### ISSUE TITLE
Please change Connects to be Connectors in Kafka connect

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#2037]
**Describe the bug**
Connectors should be instead of Connects within Kafka connects

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to Kafka connect

**Expected behavior**
Connectors, Failed Connectors, Failed Tasks should be displayed

**Screenshots**
<img width="1717" alt="connects vc connectors" src="https://user-images.githubusercontent.com/104780608/170475292-58c1849e-cead-4d42-9ba9-4de19dcc77ab.png">

**Comment by doomcrewinc** [comment]
I'll take this one.

**Comment by Haarolean** [comment]
@doomcrewinc hey, thanks!
