### ISSUE TITLE
Prepare documentation with required permissions

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#2043]
We need a documentation with a clear list of required permissions:
1) Kafka ACL mapping to app features, which perms are required for which actions; minimum set of perms required to run the app
2) The same for AWS MSK

related: #1452

**Comment by beatstream69** [comment]
Based on errors in kafka-authorizer.log I figured out that minimum required permissions are Describe and DescribeConfigs on cluster and all topics. With that permissions UI can list brokers and topics, but can't read and write messages.
```
export KAFKA_OPTS=-Djava.security.auth.login.config=/opt/kafka/config/server-kafka-jaas.conf
./bin/kafka-acls.sh --bootstrap-server kafka:9092 --command-config config/admin-client.properties --add --allow-principal User:kafka-ui --cluster --operation Describe --operation DescribeConfigs
./bin/kafka-acls.sh --bootstrap-server kafka:9092 --command-config config/admin-client.properties --add --allow-principal User:kafka-ui --topic '*' --operation Describe --operation DescribeConfigs
```
For read and write you can set standard consumer and producer rights:
```
./bin/kafka-acls.sh --bootstrap-server kafka:9092 --command-config config/admin-client.properties --add --allow-principal User:kafka-ui --topic 'mytopic' --consumer --group '*'
./bin/kafka-acls.sh --bootstrap-server kafka:9092 --command-config config/admin-client.properties --add --allow-principal User:kafka-ui --topic 'mytopic' --producer
```

**Comment by laser** [comment]
> With that permissions UI can list brokers and topics, but can't read and write messages.

FWIW, that set of ACLs was not sufficient for me to render the broker and topic-views properly. 

Does there happen to be a current, authoritative list of the ACLs required to load kafka-ui?

**Comment by laser** [comment]
After some experimentation, I was able to get the kafka-ui to load in read-only mode using the following ACLs:

```
    Principal    | Permission |    Operation     | ResourceType | ResourceName  | PatternType
-----------------+------------+------------------+--------------+---------------+--------------
  User:sa-xxxxxx | ALLOW      | READ             | TOPIC        | *             | LITERAL
  User:sa-xxxxxx | ALLOW      | DESCRIBE_CONFIGS | TOPIC        | *             | LITERAL
  User:sa-xxxxxx | ALLOW      | DESCRIBE         | GROUP        | *             | LITERAL
  User:sa-xxxxxx | ALLOW      | DESCRIBE         | CLUSTER      | kafka-cluster | LITERAL
  User:sa-xxxxxx | ALLOW      | DESCRIBE_CONFIGS | CLUSTER      | kafka-cluster | LITERAL
  ```

We are using Confluent, which means that we needed to set the `KAFKA_CLUSTERS_0_DISABLELOGDIRSCOLLECTION` environment variable to `true` (see the README.md). Without that environment variable set to `true`, the `StatisticsService#getLogDirInfo` would fail to obtain the required data.

**Comment by Haarolean** [comment]
Updated docs [here](https://docs.kafka-ui.provectus.io/configuration/permissions/required-acls)
Feel free to raise PRs (every page has a "edit on github" button)
