### ISSUE TITLE
Read only mode allow users to read the message content.

### ISSUE THREAD

**Issue by nikhilsuryan-sky** [provectus/kafka-ui#2051]
**Describe the bug**

Hi guys. I really like what you're doing, not sure if that is on pupose, but in readonly mode you can watch messages. I was wondering if you can have a option to hide the messages in read only mode. We wanted to give the access to clients, but anyone can look at anyone else message which is not great. Also, the produce message option is enable in read only mode.

As there is only two mode read or admin, not sure if we are missing something.

**Set up**

 Docker container v0.4.0.

**Steps to Reproduce**

1. NA

**Expected behavior**

I was wondering if you can have a option to hide the messages in read only mode. We wanted to give the access to clients, but anyone can look at anyone else message which is not great. Also, the produce message option is enable in read only mode.

**Screenshots**

NA

**Additional context**

**Comment by Haarolean** [comment]
Hey, thanks for the feedback!

Yes, this is intended, "read-only" just disables modifying actions.
We're planning to implement a granular access within #753, #1352, #1027.
#1027 you're interested in will be implemented after #753, but, most certainly, in the same, current, release. 

Regarding the button: yea, it seems it's visible, but you won't be able to produce a message anyway. I've raised an issue for that -- #2052.

Let me know if you have any other questions.

**Comment by nikhilsuryan-sky** [comment]
Thanks @Haarolean for the update, this is amazing. Do you know when these feature will be available? or when you are planning to release the new version with these features?

**Comment by Haarolean** [comment]
> Thanks @Haarolean for the update, this is amazing. Do you know when these feature will be available? or when you are planning to release the new version with these features?

@nikhilsuryan-sky each feature in particular -- no clue, it depends on our bandwidth. The release might be out in a few months or less. Anyway, RBAC is the main feature on this release.
