### ISSUE TITLE
Ability to run KSQL queries directly from UI

### ISSUE THREAD

**Issue by IldarAlmakaev** [provectus/kafka-ui#207]

**Comment by Flyur** [comment]
Hi guys, this feature can be implemented by adding routing from kafka-ui backend to ksqldb server or creating endpoints in the kafka-ui backend itself. @IldarAlmakaev @workshur @germanosin any thoughts?

**Comment by burusha16** [comment]
I've merged to master backend side of this ticket
cc @workshur
