### ISSUE TITLE
Implement connectors sorting

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#2076]
1. Migrate table to new table component
2. Implement sorting
3. Related issue https://github.com/provectus/kafka-ui/issues/2325
The list is unsorted at all

<img width="299" alt="image" src="https://user-images.githubusercontent.com/1494347/171179908-5447271c-e17d-4921-abfe-3a7e4239756a.png">

**Comment by Haarolean** [comment]
Implement sorting by: name, connect, type and status.

**Comment by armenuikafka** [comment]
Sorting by Name, Connect, Type, Plugin, Status implemented.
