### ISSUE TITLE
Linked Consumer is not displayed within Topic/Consumers tab

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#2080]
**Describe the bug**
Linked Consumer is not displayed within Topic profile /Consumers tab

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to Consumers
2. Open the Consumer profile
3. Click on linked Topic
4. Turn to Consumers tab

**Expected behavior**
Linked Consumer should display within Topic/Consumer

**Screenshots**

https://user-images.githubusercontent.com/104780608/171190816-083adac5-a1b7-445e-97ee-0a2905c83709.mov

**Additional context**

**Comment by iliax** [comment]
Checked this issue - on "latest" image its works fine, so we need to review changes applied to master.
