### ISSUE TITLE
KSQL view data doesn't load

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#2083]
**Describe the bug**
Sometimes KSQL DB data is not loading and 422 error appears

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to KSQL DB

**Expected behavior**
All the data should display within KSQL DB

**Screenshots**

https://user-images.githubusercontent.com/104780608/171206802-370b2991-75e7-43e8-b137-5bd15c397c9d.mov

**Additional context**
Happens not every time

**Comment by iliax** [comment]
need to make UI use new API

**Comment by armenuikafka** [comment]
Seems the issue already exists. 

<img width="1718" alt="ksql new" src="https://user-images.githubusercontent.com/104780608/172543231-8b47ca56-58f4-4089-97b2-6a6bd2fcb807.png">

**Comment by iliax** [comment]
@armenuikafka this is not connected with ksql, your cognito session just closed

**Comment by armenuikafka** [comment]
@iliax thanks, will take a look
