### ISSUE TITLE
Not functional Compare Versions for Schema

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#2084]
**Describe the bug**
Compare versions for Schema is not working 

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to Schema Registry
2. Open the Schema
3. Press 'Compare Versions'

**Expected behavior**

- The right path should be displayed
- Comparing should be available

**Screenshots**

https://user-images.githubusercontent.com/104780608/171213052-3ebc5a23-bf15-47bd-b195-893f292c3cc1.mov

**Comment by Haarolean** [comment]
#1961

**Comment by Haarolean** [comment]
#2128
