### ISSUE TITLE
Connector't tasks count update is not available without refreshing

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#2088]
**Describe the bug**
Connector tasks count update avaIlable only after refresh

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to Kafka connect
2. Open the Connector
3. Edit config
4. Change Topics count
5. Turn to Tasks tab

**Expected behavior**
Tasks updated count update should be available without refreshing the Connector

**Screenshots**

https://user-images.githubusercontent.com/104780608/171347945-66ce9bb7-c97c-4b1d-8e50-7bdc5f425d75.mov

**Comment by armenuikafka** [comment]
Seems works as the same 


https://user-images.githubusercontent.com/104780608/172350115-6edab037-7477-4096-ac07-8d96f73f44c7.mov

**Comment by iliax** [comment]
@armenuikafka unfortunately Kafka-connect API is asynchronous in case of configuration changes applying. After you edit number of tasks - this change will be applied by kafka-connect asynchronously (and it is not specified when actually). So, I think the best thing we can do is to show UI disclaimer popup like "Changes will be applied asynchronously, refresh connector's page to see updates".

cc @Haarolean
