### ISSUE TITLE
Issue related responsive view of Topic/Schema/Connector profile

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#2096]
**Describe the bug**
In case of setting responsive view information is not displayed fully within Topic/Schema/Connector profiles

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to Topic/Schema/Connector profile
2. Make the browser window smaller

**Expected behavior**
If the window becomes smaller, all the information/buttons should be displayed fully as in default view

**Screenshots**

https://user-images.githubusercontent.com/104780608/171427320-b4b1ed17-4a2f-465e-b7cb-3b37a0caadc4.mov

**Comment by Haarolean** [comment]
#1392
