### ISSUE TITLE
Underscore line is present even for deselected tabs

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#2122]
**Describe the bug**
Overview tab always highlighted within component profile (Topic, Connector)

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to Topic/Connector
2. Turn other than Overview tab

**Expected behavior**
Overview tab kept highlighted with turning to the other tab

**Screenshots**
<img width="1718" alt="ui for tab" src="https://user-images.githubusercontent.com/104780608/172115126-3600c542-24c9-428f-b86a-9afd0cd187bd.png">

**Comment by Haarolean** [comment]
Seems being fixed.
