### ISSUE TITLE
Breadcrumb and title looks weird on Create new topic page 

### ISSUE THREAD

**Issue by workshur** [provectus/kafka-ui#2124]
**Describe the bug**

1. BreadCrumb component renders `create-new` chunk of url without transformation
2. Title looks weird
3. The form should be centered on the page. Just like the topic edit page

**Steps to Reproduce**

1. Go to Create new topic page

**Expected behavior**

All of these errors must be corrected. And the component should look the way the Figma markup requires.

**Screenshots**

<img width="421" alt="Screenshot 2022-06-06 at 12 21 41" src="https://user-images.githubusercontent.com/365855/172133597-c9fdd093-ef3c-4591-9acd-46ba84083bb5.png">

**Additional context**

**Comment by armenuikafka** [comment]
Please change the Breadcrumb component to be like in Figma:  

<img width="1725" alt="breadcrumb component" src="https://user-images.githubusercontent.com/104780608/179900366-f0c18c4c-8da5-4c40-892a-a32d9b4fb9fa.png">
