### ISSUE TITLE
Compare schema button is broken

### ISSUE THREAD

**Issue by workshur** [provectus/kafka-ui#2128]
**Describe the bug**

Compare button on schema page leads to a page that does not exist. Something bad with method to generate href of the button
Now it generates:
```
https://localhost:3000/ui/clusters/local/schemas/123/:subject/diff?leftVersion=2&rightVersion=2
```

**Set up**

**Steps to Reproduce**

1. 

**Expected behavior**

Compare button should works as expected

**Screenshots**

**Additional context**

**Comment by Haarolean** [comment]
#2084 regression

**Comment by Haarolean** [comment]
> #2084 regression

seems like a duplicate, not a regression
