### ISSUE TITLE
krb5.conf loading failed

### ISSUE THREAD

**Issue by sufiyansaboowala** [provectus/kafka-ui#2132]
Placed krb5.conf under /etc/krb5.conf

Docker Image versions
provectuslabs/kafka-ui:latest

Config I am using:
volumes:
        - ./data/secrets:/opt/inventory/security
        - ./data/secrets:/etc/krb5.conf
    ports:
      - 8080:8080
    depends_on:
      - kafka0
      - kafka-connect0
    environment:
      KAFKA_CLUSTERS_0_NAME: name
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: server1:39092,server2:39092,server3:39092
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_SSL
      KAFKA_CLUSTERS_0_READONLY: true
      # KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: SCRAM-SHA-256
      KAFKA_CLUSTERS_0_ZOOKEEPER: zk1-server:2181
      KAFKA_CLUSTERS_0_JMXPORT: 9997
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_KERBEROS_SERVICE_NAME: kafka
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: com.sun.security.auth.module.Krb5LoginModule required useKeyTab=true storeKey=true debug=true keyTab="/opt/inventory/security/user.keytab" principal="user@server" serviceName="kafka";
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: server1-sr:39092,server2-sr:39092,server3-sr:39092
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: first
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect0:8083/
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_TYPE: JKS
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_LOCATION: /opt/inventory/security/trust-store.jks
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_PASSWORD: password

**Comment by Haarolean** [comment]
Hi, what's the issue exactly?

**Comment by sufiyansaboowala** [comment]
Hi Haarolean,
The issue I see is its unable to detect krb5.conf which has no issues itself.

**Comment by Haarolean** [comment]
Can you provide the error you experience? Container logs maybe?
