### ISSUE TITLE
Not possible to add message for a topic

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#2140]
**Describe the bug**
Error appears with creating a message for a Topic

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to Topic profile
2. Turn to Messages tab
3. Produce message
4. Add Key/Content/Headers
5. Press Send

**Expected behavior**
Message should be added without any error in a console and error message for ui.

**Screenshots**

https://user-images.githubusercontent.com/104780608/172389686-f2be6421-b083-4984-9e99-eb7dee910643.mov

**Comment by Haarolean** [comment]
"partition" selector value is not sent unless specified explicitly by user
the same behavior for #1725
