### ISSUE TITLE
Topic message info layout is broken

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#2144]
<img width="416" alt="image" src="https://user-images.githubusercontent.com/1494347/172599553-28a0079f-ac6c-443d-82e1-e2d6721bfa7c.png">

**Comment by ymlai87416** [comment]
Hello, I am newbies and I am willing to help.

I checked the code, the Label box is hardcoded in 50px. Is this you are referring as broken UI?

[  width: 50px;](https://github.com/provectus/kafka-ui/blob/e4dc1134abe45ee72c10d454eb7e4e326c52e194/kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessageContent/MessageContent.styled.ts#L59)

**Comment by Haarolean** [comment]
@ymlai87416 hi and welcome! Feel free to tackle this.
Yes, "timestamp" and "content" labels are being wrapped.
