### ISSUE TITLE
Schema registry: Should not be possible to change a schema type during editing

### ISSUE THREAD

**Issue by kshpilchyna** [provectus/kafka-ui#2152]
Steps:
1. Schema 'AVRO' created
2. Open created schema
3. Select 'Edit Schema'
4. Try to change a type

Actual result:
3. It's possible to change a type of schema

<img width="1541" alt="Screenshot 2022-06-10 at 18 20 42" src="https://user-images.githubusercontent.com/79516954/173110078-89cf8ec9-8897-40be-bad8-2574301f7bca.png">

Expected result:
3. Should not be possible to change a type, so it's better to remove 'Type' from editing

**Comment by Haarolean** [comment]
@VladSenyuta fyi. We had an e2e test for this or something.
