### ISSUE TITLE
Change message timestamp format

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#2162]
US locale: mm/dd/yyyy
any other locale: dd-mm-yyyy

<img width="319" alt="image" src="https://user-images.githubusercontent.com/1494347/173567067-9b50a673-dc42-4946-859c-7bf355935447.png">

**Comment by hyzyla** [comment]
I will try to fix that issue ✋

**Comment by Haarolean** [comment]
> I will try to fix that issue ✋

hey, thanks for the interest, I've assigned the issue to you

**Comment by germanosin** [comment]
I think this should be formated locale-based. You could use Date.toLocaleDateString(). @workshur any suggestions?

**Comment by Haarolean** [comment]
> I think this should be formated locale-based. You could use Date.toLocaleDateString(). @workshur any suggestions?

that's the next step (#2163). At this point it'd be nice to see dd.MM

**Comment by germanosin** [comment]
I think we could use localestring for now and then switch to configurable version

**Comment by Haarolean** [comment]
@hyzyla as far as I remember, the timestamp is being formatted on frontend. Can you format it with taking user browser's preferences into consideration?

**Comment by hyzyla** [comment]
> @hyzyla as far as I remember, the timestamp is being formatted on frontend. Can you format it with taking user browser's preferences into consideration?

Yes, sure

**Comment by hyzyla** [comment]
So, after some investigation, I found that formatting to user locale is challenging, because `dayjs` doesn't support [autodetecting](https://github.com/iamkun/dayjs/issues/732) locale. For that reason, I decided to just change locale to `DD.MM.YYYY`. 

Let me know if you think [that snippet](https://github.com/iamkun/dayjs/issues/732#issuecomment-554383261)  is OK to use for detecting locale

**Comment by Haarolean** [comment]
> So, after some investigation, I found that formatting to user locale is challenging, because `dayjs` doesn't support [autodetecting](https://github.com/iamkun/dayjs/issues/732) locale. For that reason, I decided to just change locale to `DD.MM.YYYY`.
> 
> Let me know if you think [that snippet](https://github.com/iamkun/dayjs/issues/732#issuecomment-554383261) is OK to use for detecting locale

@provectus/kafka-frontend need opinions

**Comment by workshur** [comment]
I would suggest getting rid of `dayjs`. We only use it in two places. So, let's create an helper function to parse the server date and convert it into a localized format.

```ts
try {
  date = new Date('2022-06-06T12:44:42.118Z');
  date.toLocaleString();
} catch ....
```

**Comment by hyzyla** [comment]
> I would suggest getting rid of `dayjs`. We only use it in two places. So, let's create an helper function to parse the server date and convert it into a localized format.
> 
> 
> 
> ```ts
> 
> try {
> 
>   date = new Date('2022-06-06T12:44:42.118Z');
> 
>   date.toLocaleString();
> 
> } catch ....
> 
> ```
> 
> 
> 
> 

Problem with toLocaleString is that function isn't not consistent within different browsers [1]. For example, I have "uk" locale, but Firefox decide to format in en-US, while Chrome format in some weird format 18/06/2022

1. https://stackoverflow.com/a/66578542

**Comment by workshur** [comment]
From my point of view, there is no right solution. Let's wait until BE for the custom locale is ready. Let the user decide which format is more convenient for him

**Comment by Haarolean** [comment]
@hyzyla wanna tackle this? we have everything ready on BE

**Comment by Haarolean** [comment]
@hyzyla actually are you sure your browser locales are 'uk'? It seems like both are us
