### ISSUE TITLE
Handle error message for schemas

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#2164]
**Describe the bug**
Not user friendly error message appears with submitting wrong data in Schema

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to Schema Registry 
2. Open the schema
3. Edit the schema
4. Let any field empty or input wrong data
5. Press submit

**Expected behavior**
Error message about wrong data should be user friendly to indicate which data is wrong 

**Screenshots**
<img width="1718" alt="error message schema" src="https://user-images.githubusercontent.com/104780608/173566018-8e125a64-c4dc-48e3-ab3c-950f3ef45b51.png">

**Comment by daching-provectus** [comment]
@armenuikafka I tried to reproduce this issue, although, I'm getting this error:
![Screen Shot 2022-08-31 at 12 15 57](https://user-images.githubusercontent.com/110129035/187750536-a96905db-6fef-4ea8-b71c-160f01884fce.png)

Could you confirm if you still get the ugly error using the latest codebase? I wonder if I'm doing something wrong or if it's already fixed.

**Comment by armenuikafka** [comment]
@daching-provectus hey, the error still actual on master. 

Steps to reproduse:
- Use the avro schema type
- edit the schema
- delete any property
- submit
