### ISSUE TITLE
Incorrect order of requests for changing SR compatibility lvl and schema itself

### ISSUE THREAD

**Issue by tcortega** [provectus/kafka-ui#2167]
TODO:
https://github.com/provectus/kafka-ui/issues/2167#issuecomment-1158835488

**Describe the bug**
When attempting to edit a schema within the schema registry screen, I get an error that does not give me any information.

**Set up**
If needed I can provide later-on, but we basically set up a simple kafka cluster and the schema registry itself, using confluent's docker image. 

**Steps to Reproduce**

1.  Open the Schema registry screen
2.  Create a new AVRO schema, the one we created is the following:
`{
  "type" : "record",
  "namespace" : "DataFlair",
  "name" : "Student",
  "fields" : [
     { "name" : "Name" , "type" : "string" },
     { "name" : "Age" , "type" : "int" }
  ]
}`

3. Try to edit it, choosing any compatibility mode.

**Expected Behavior**
An error message should appear, saying no useful information.

**Screenshots**
![image](https://user-images.githubusercontent.com/60912483/173689737-7603bc17-733e-444c-968e-b106e7bfa9b4.png)

**Comment by iliax** [comment]
Hello @tcortega ,
change that you are doing is not backward compatible, since you don't provide new field default. 
you can either change subject compatibility (to forwards for example) or make change backward compatible. 

As for error message I agree that it is not informative, we will check how it can be fixed.

**Comment by tcortega** [comment]
> Hello @tcortega , change that you are doing is not backward compatible, since you don't provide new field default. you can either change subject compatibility (to forwards for example) or make change backward compatible.
> 
> As for error message I agree that it is not informative, we will check how it can be fixed.

The same error happens when the compatibility level is set to forward

![image](https://user-images.githubusercontent.com/60912483/173867069-b1d041e4-1b29-4dfa-a3ba-b6a79ed44295.png)

**Comment by Haarolean** [comment]
@provectus/kafka-frontend 

When changing a schema, if both compatibility level and the schema itself are changed, there are two requests sent to backend:
1. update schema
2. update compatibility level

and the order of these is incorrect. It should be vice versa.
