### ISSUE TITLE
Unnecessary line within KSQL DB / query

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#2169]
**Describe the bug**
There is an Unnecessary line within KSQL DB / query

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to KSQL DB
2. Press 'Execute KSQL Request'

**Expected behavior**
The line is not necessary
Display: 3456 × 2234

**Screenshots**
<img width="1718" alt="line within ksql db" src="https://user-images.githubusercontent.com/104780608/173776414-5e0062e7-b804-4418-8ac2-66c1e414dcfa.png">

**Comment by Haarolean** [comment]
@provectus/kafka-frontend is that a 80 symbols line delimiter?
