### ISSUE TITLE
It's not clear that KSQL and Stream properties are required

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#2173]
**Describe the bug**
Not displayed asterisks for KSQL, Stream properties and not displayed validation message in case of letting the Stream properties empty

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to KSQL DB
2. Execute KSQL Request 
3. Press Submit

**Expected behavior**
Asterisks for KSQL and Stream properties should be displayed
Message about Stream properties requiredness should appear

**Screenshots**
<img width="1718" alt="required field for ksql" src="https://user-images.githubusercontent.com/104780608/173863918-89f01a16-fa31-4b6d-9717-6d75d5da80c2.png">

**Comment by Haarolean** [comment]
stream properties is not a required field
