### ISSUE TITLE
KafkaConnect restarting tasks does nothing

### ISSUE THREAD

**Issue by akamensky** [provectus/kafka-ui#2175]
**Describe the bug**

Using "restart all tasks" and "restart failed tasks" does nothing. Likely due to UI using a native methods for connector, however those methods do not work. The only way to actually restart tasks is to iterate through tasks and call a a method for each task individually.

**Set up**
* 3 node KafkaConnect cluster
* UI running in docker container (v0.4.0)

**Steps to Reproduce**

1. Have a connector with a task failed
2. Try to either restart all tasks or restart failed tasks

**Expected behavior**
Expected that tasks are restarted (they are not)

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Haarolean** [comment]
hey Alex, that's what we actually do -- we call a restart for each of the tasks. Are you sure that nothing happens? Have you tried waiting for some time and refreshing the page?

**Comment by akamensky** [comment]
@Haarolean thank you for the feedback, if that's the case then I think it is fine. I guess it perhaps failed too quick so I did not see it being actually restarted. Maybe some additional feedback on this would be good, i.e. show timestamp when the last restart happened (tho that would need to be tracked in the app itself since KC does not provide such information over API). Can keep this issue closed I guess.
