### ISSUE TITLE
Support AWS MSK Serverless

### ISSUE THREAD

**Issue by SergKam** [provectus/kafka-ui#2185]
**Describe the bug**
The kafka-ui is working but the cluster is shown as "offline" and without topics.

 
**Set up**
I'm trying to use kafka-ui vv0.4.0(521ba0c) as a frontend for AWS MSK Serverless cluster mostly to create and manage topics.
I started a EC2 instance that uses IAM role with full access to the MSK cluster. 
Basically,I just follow the tutorial https://docs.aws.amazon.com/msk/latest/developerguide/serverless-getting-started.html
I tested the setup with a standard kafka-topic.sh tools to make sure the cluster is accessible from the instance and IAM role allows all operations with the cluster.

then I downloaded latest kafka-ui jar from github, and created application.yaml
```
logging.level.root: DEBUG
kafka:
  clusters:
    - name: local
      bootstrapServers: boot-ivd3n3is.c1.kafka-serverless.eu-central-1.amazonaws.com:9098
      properties:
        security.protocol: SASL_SSL
        sasl.mechanism: AWS_MSK_IAM
        sasl.client.callback.handler.class: software.amazon.msk.auth.iam.IAMClientCallbackHandler
        sasl.jaas.config: software.amazon.msk.auth.iam.IAMLoginModule required awsDebugCreds=true
```

and started it
`java -jar kafka-ui-api-v0.4.0.jar`

The web server is starting and working, but with no connection to Kafka.

in console, I see the error
```
2022-06-18 01:47:16,045 DEBUG [parallel-1] o.a.k.c.a.i.AdminMetadataManager: [AdminClient clientId=adminclient-84] Setting bootstrap cluster metadata Cluster(id = null, nodes = [boot-ivd3n3is.c1.kafka-serverless.eu-central-1.amazonaws.com:9098 (id: -1 rack: null)], partitions = [], controller = null).
2022-06-18 01:47:16,045 INFO  [parallel-1] o.a.k.c.m.Metrics: Metrics scheduler closed
2022-06-18 01:47:16,045 INFO  [parallel-1] o.a.k.c.m.Metrics: Closing reporter org.apache.kafka.common.metrics.JmxReporter
2022-06-18 01:47:16,045 INFO  [parallel-1] o.a.k.c.m.Metrics: Metrics reporters closed
2022-06-18 01:47:16,045 ERROR [parallel-1] c.p.k.u.s.MetricsService: Failed to collect cluster local info
java.lang.IllegalStateException: Error while creating AdminClient for Cluster local

```

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/3240529/174418764-33dbf007-ca53-4bfd-97b9-fa3243e13494.png)

**Additional context**

java 18.0.1.1 2022-04-22
Amazon linux 5.10 118-111.515.amzn2.x86_64
[log.txt.gz](https://github.com/provectus/kafka-ui/files/8932807/log.txt.gz)

**Comment by Haarolean** [comment]
Hey, thanks for reaching out.

There's your problem in your logs:
`Caused by: java.lang.IllegalArgumentException: JAAS config entry not terminated by semi-colon`
Here's an [example](https://github.com/provectus/kafka-ui/blob/master/documentation/compose/kafka-ui-sasl.yaml#L20)

**Comment by SergKam** [comment]
Unfortunately still not working. now the error
```
Caused by: org.apache.kafka.common.errors.InvalidRequestException: Amazon MSK Serverless doesn't support fetching broker or broker-logger configurations.
```

**Comment by Haarolean** [comment]
Okay, thanks. That's a totally different issue, it seems like we have to adjust some code to support _serverless_ MSK.

**Comment by YashKumarVerma** [comment]
is it supported now?

**Comment by Haarolean** [comment]
> is it supported now?

not yet :(

**Comment by advissor** [comment]
When is the plan to release version 0.5 @Haarolean ?

**Comment by Haarolean** [comment]
> When is the plan to release version 0.5 @Haarolean ?

@advissor as soon as roadmap features are done. I'm not sure this will be a part of 0.5, but it has a high priority on our list as well.

**Comment by iliax** [comment]
Hello @SergKam , can you pls attach full log for latest exception?

**Comment by SergKam** [comment]
> Hello @SergKam , can you pls attach full log for latest exception?

@iliax No, sorry. It was just an experiment, we decided not to use AWS MSK and switch to Confluent instead, so I deleted evrething.
But you can try to set it up yourself using AWS MSK guide https://docs.aws.amazon.com/msk/latest/developerguide/serverless-getting-started.html

**Comment by iliax** [comment]
> > Hello @SergKam , can you pls attach full log for latest exception?
> 
> @iliax No, sorry. It was just an experiment, we decided not to use AWS MSK and switch to Confluent instead, so I deleted everything. But you can try to set it up yourself using AWS MSK guide https://docs.aws.amazon.com/msk/latest/developerguide/serverless-getting-started.html

ok, we will create cluster and check how it goes, thank you

**Comment by Haarolean** [comment]
Please note that we need some frontend changes as well (#2739), hopefully will get them live soon as well.

**Comment by harish944072** [comment]
Hai team added msk cluster not getting data what i did mistake here geeting same error as above
