### ISSUE TITLE
ALTER_PARTITION_REASSIGNMENT unavailable for kafka 2.3.1

### ISSUE THREAD

**Issue by ddud2nn** [provectus/kafka-ui#2189]
**Describe the bug**

The version of kafka I am using is 2.3.1. 
Altering Partition Reassignments does not work when this is associated with kafka-ui.

**Set up**

Docker image version : provectuslabs/kafka-ui:master

**Expected behavior**

I expect all the features of kafka-ui to work successfully even if kafka version is 2.3.1.

**Screenshots**

![image](https://user-images.githubusercontent.com/37402084/174738909-677ccf13-4f3c-48fa-9adc-4aeb364806be.png)

**Comment by Haarolean** [comment]
#947
