### ISSUE TITLE
Make a separate endpoint for updating schemas

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#2197]
Currently there's just one endpoint for both creating and updating a schema. Schema type param shouldn't be available when updating an existing schema.

**Comment by Haarolean** [comment]
#2152

**Comment by shubhwip** [comment]
Can I work on this please ?

**Comment by Haarolean** [comment]
@shubhwip sure!

**Comment by shubhwip** [comment]
@Haarolean Having looked at #2152 I think we can solve this problem just by disabling the `schema type` during edit. This way we can stop users to change schema type during schema edit.
Also I checked if there is any PUT endpoint on schema registry service but seems like there is nothing.
https://docs.confluent.io/platform/current/schema-registry/develop/api.html#subjects

Submitted the PR for the above change #2495

**Comment by Haarolean** [comment]
wontfix: https://github.com/provectus/kafka-ui/pull/2495#issuecomment-1231478236
