### ISSUE TITLE
Error message stays in a system, although it's not actual

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#2200]
**Describe the bug**
System keeps error message although it's not actual

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to any form (f.ex.HSQL query execution)
2. Input data in a wrong format
3. Press Execute
4. Make sure that error message appears
5. Correct the data format
6. Press Execute again

**Expected behavior**
The error message should disappear if it's not actual

**Screenshots**

https://user-images.githubusercontent.com/104780608/174954612-0e55618d-bc87-494b-9816-742e14feff55.mov

**Additional context**

**Comment by Haarolean** [comment]
Fixed in #2312
