### ISSUE TITLE
Implement a flow to publish temporary docker images

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#2212]
In some cases we need to build an image within a PR to let others test them out. Would be nice to build and publish them automatically.

**Comment by azatsafin** [comment]
@Haarolean is it OK to push it to internal ECR ? we can re-use our branch-deployment logic to build image only. How you would like to trigger such logic ?

**Comment by Haarolean** [comment]
Yes, yes, and, the same way, via labels.
