### ISSUE TITLE
Topic view: show broker replicas

### ISSUE THREAD

**Issue by nikobearrr** [provectus/kafka-ui#2224]
### Is your proposal related to a problem?

When I am moving topic/replica from broken to broker I would like to see which are the current brokers having a particular partition

### Describe the solution you'd like

In the topic view, next to the `Broker Leader` column, add a new column `Replicas`. It can also be 2 columns: `Preferred Replica` and `Current Replica` as they are separate things.

### Describe alternatives you've considered

I can currently see it in the kafka logs

### Additional context

CMAK provides such information and I think it is very useful

**Comment by Haarolean** [comment]
Hey, thanks for the suggestion :)

**Comment by nikobearrr** [comment]
I am using the latest version 0.4.0
Is there a newer one?

**Comment by Haarolean** [comment]
There's no major release out, but this has been implemented later (#705), so you can try `master` labeled image instead. Or you can wait for 0.5 :)
