### ISSUE TITLE
Multiple Protobuf Files via URL

### ISSUE THREAD

**Issue by sw-tracker** [provectus/kafka-ui#2228]
### Linking to multiple Protobufs via URL

We deploy kafka-ui to OpenShift and would like to be able to use protobufs without having to setup a PVC.

- We would like to link 1 protobuf file per topic. How does one do this?
- Topic names have dots ( . ) in them, i.e. `this.is.my.topic.name`. Can we do this with env variables? What would the env variable look like?
- We would like to link to protobuf files via URL. How does one do this?
- We would like to link an `application.yaml` via URL. How does one do this?

### Describe the solution you'd like

- We would like to be able to provide an `application.yaml` via URL.
- We would like to provide a protobuf file per topic via URL.

### Describe alternatives you've considered

We considered doing this in our pipeline:

- create a PVC
- create a side container that binds itself to the PVC, this container copies the application.yaml and protobufs to the PVC, then container shuts down
- bind PVC to kafka-ui

### Additional context

The documentation [here](https://github.com/provectus/kafka-ui/blob/master/documentation/guides/Protobuf.md) does not specify how we can configure 1 protobuf file per topic.

**Comment by Haarolean** [comment]
related #2298

**Comment by iliax** [comment]
This is implemented within https://github.com/provectus/kafka-ui/issues/2298, usage examples can be found [here](https://github.com/provectus/kafka-ui/blob/e07ce28b2c021e4e572f639be7ff6b7c10bf9cb2/documentation/compose/kafka-ui-serdes.yaml) and [here](https://github.com/provectus/kafka-ui/blob/e07ce28b2c021e4e572f639be7ff6b7c10bf9cb2/documentation/guides/Protobuf.md)  . 

Also here is a open [PR](https://github.com/provectus/kafka-ui/pull/3039) that adds support for cross files references and directory scanning.
