### ISSUE TITLE
[e2e] Prepare steps for topic

### ISSUE THREAD

**Issue by kshpilchyna** [provectus/kafka-ui#2287]
create a separate Class with steps src/test/java/com/provectus/kafka/ui/steps/kafka (TopicSteps.java)

 1. create steps such createTopic, deleteTopic, isTopicExist etc
See tests that should be automated https://docs.google.com/spreadsheets/d/1Vf6yZSqCYwh33t-pTy1PiYewk-jFSfPZppzIuUVVyO0/edit#gid=0
2. Remove all sleeps, if needed to some wait, all asserts should be in test

Refactor test class src/test/java/com/provectus/kafka/ui/tests/TopicTests.java with new steps

**Comment by VladSenyuta** [comment]
is not actual as we agreed with the team due to useless of Steps class on current framework stage
