### ISSUE TITLE
[e2e] Create all blank test methods 

### ISSUE THREAD

**Issue by kshpilchyna** [provectus/kafka-ui#2289]
Due to tests from Qase.io need to create a blank methods with annotation @AutomationStatus(status = Status.TO_BE_AUTOMATED)

1. For naming new class use name of suite from the Qase.io
2. create all methods , add annotation of @Suite and @AutomationStatus
3. Add methods in existing tests class if needed
4. Add annotation @CaseId 
5. For new tests need to run tests and after a test will be created in Qase.io also add annotation @CaseId

**Comment by armenuikafka** [comment]
Waiting for refactoring of auto tests (integration Qase.io).
