### ISSUE TITLE
Consumer overview: topic label padding looks weird

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#2329]
<img width="653" alt="image" src="https://user-images.githubusercontent.com/1494347/180576596-28801e82-bde0-474e-b9c0-5f8ff1339327.png">

**Comment by prateekvarma** [comment]
Hi @Haarolean , I can try and fix the padding. 

- Is there any specific amount of padding we're looking at?
- Any other detail?

(participate in the spirit of Hacktoberfest)

**Comment by Haarolean** [comment]
@prateekvarma thank you.
Please use [this](https://www.figma.com/file/ZkvysdRUmt9p2PDNU3a9WU/Kafka-UI?node-id=117%3A2644) as a reference

**Comment by Haarolean** [comment]
@David-DB88 https://www.figma.com/file/ZkvysdRUmt9p2PDNU3a9WU/Kafka-UI?node-id=117%3A2644
