### ISSUE TITLE
Unify tabs placement

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#2332]
e.g. connector overview page:
<img width="831" alt="image" src="https://user-images.githubusercontent.com/1494347/180577153-3eaa5d32-9d3a-4c99-b470-81db2759a803.png">
tabs are placed above the panes and the page looks empty and weird. Let's unify **all the views** with this approach:
<img width="671" alt="image" src="https://user-images.githubusercontent.com/1494347/180577197-385faf9c-1500-4fb0-836a-52d87191eed8.png">
broker overview page panes are located below the tabs therefore "overview" tab is no longer required

**Comment by BulatKha** [comment]
Tabs are still on top for topics:
![image](https://user-images.githubusercontent.com/112083452/192267959-a6ef8be9-7886-4d1f-b3c5-bd2a17a08b67.png)

Needs a fix.

**Comment by BulatKha** [comment]
@Haarolean considering the comment from Oleg in #2637 , can this considered to WAD for the topics and therefore closed?

**Comment by BulatKha** [comment]
@Haarolean there is still Overview tab with old layout on the Connector details page:
![image](https://user-images.githubusercontent.com/112083452/195011557-8fcf4112-02a7-4e23-b470-f239288b3c22.png)

Should this defect be reopened?
