### ISSUE TITLE
Consumer Group reset/change offset in specific partition

### ISSUE THREAD

**Issue by ommr101** [provectus/kafka-ui#234]
I would like to ask adding support for moving the offset for specific partition (so we can set using the ui replaying/skipping messages)

**Comment by germanosin** [comment]
@ommr101 thank you for your issue. For now you can select specific partition and set starting offset. Could you please describe a lit more what is expected behaviour?

**Comment by ommr101** [comment]
@germanosin Hi sure. 
Let's take a use case where I have a topic with one partition and I have sent 100 msg to it. Some consumer, consumed all messaged and commit the last offset (100). I would like a support for resetting this offset to a specific location (e.g 50, so the consumer will have to reconsume all message starting from the offset 50).

In the same manner, if I have 100 msg in that mentioned partition, I would like to be able setting the starting offset.

Does the ui supports offset setting? can't find it anywhere...

**Comment by germanosin** [comment]
@ommr101 , as far as I understand you are looking for reseting offset for particular consumer group. This feature is not available now. We would be happy to add in the next releases.

**Comment by germanosin** [comment]
waiting frontend
