### ISSUE TITLE
Search for consumers works not the same way as for other pages

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#2340]
**Describe the bug**
Search for consumers works for each inputed letter and refresh needs for adding new letter, but for the other pages search keeps focused with filling letters

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to Consumers
2. Input one letter into Search

**Expected behavior**
Search should stay focused to add another letter and should work the same way for all the pages

**Screenshots**

https://user-images.githubusercontent.com/104780608/180857372-82e27d38-08a1-458d-bb84-364c80829069.mov

**Comment by workshur** [comment]
Fixed in context of https://github.com/provectus/kafka-ui/pull/2444
