### ISSUE TITLE
Purge Messages is not functional for the Topic messages

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#2347]
**Describe the bug**
The messages of the Topic stay after Purge messages action

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to Topics
2. Create a Topic
3. Set "Compact, Delete" for "Cleanup policy"
4. Produce a couple of messages for a Topic
5. Turn to Topics page
6. Select the newly created Topic
7. Press "Purge messages of selected topics"

**Expected behavior**
The messages count of the Topic should become 0 after Purge messages

**Screenshots**

https://user-images.githubusercontent.com/104780608/181172950-bcfb4884-b5bd-4b69-81c7-f3642cdbbe29.mov

**Comment by Haarolean** [comment]
The button has been hidden properly on topic overview page, but not from the dropdown action menu on topics list page.
#1542
