### ISSUE TITLE
No warning about filling the invalid data in case of editing the Schema / Producing the Message

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#2353]
**Describe the bug**
It's possible to submit data filled not in {} in case of Schemas editing

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to Schema Registry
2. Select the Schema
3. Edit the Schema 
4. Add the data after {}
5. Press "Submit"

**Expected behavior**
Warning should appear to say that invalid data was filled or should not be possible to submit if data added not in {} scope

**Screenshots**
<img width="1726" alt="invalid data within json" src="https://user-images.githubusercontent.com/104780608/181295973-3e1a4e01-cb7e-4e54-9810-22a577479758.png">

**Comment by Haarolean** [comment]
Considering #2354 it seems like we have validation bound to producing messages. There should be one for creating/updating schemas as well.
