### ISSUE TITLE
Add the possibility to not specify the image.registry value

### ISSUE THREAD

**Issue by joseacl** [provectus/kafka-ui#2367]
**Describe the bug**
It's not a bug but an improvement on how the docker image of the kafka-ui application is built which will allow us to have less values in our deployment.

We're using that application in several environments (dev, qa, prod, etc...) for each environment we have configured docker/containerd to use a default mirror. 
The fact that the image is using `.Values.image.registry` as mandatory is making that we need to define this value per environment, overcomplicating the maintance of these values.

If we simply set the `.Values.image.registry` to an empty string, the deployment generated does not work
**Set up**

**Steps to Reproduce**

1. Set this default value:
   `image:
           registry: ""` 
2. Execute `helm template .`

**Expected behavior**
Generate a valid image to be pulled:

`
provectuslabs/kafka-ui:latest
`

Right now the value generated is `/provectuslabs/kafka-ui:latest` which generate that error

`
git pull /provectuslabs/kafka-ui:latest
fatal: '/provectuslabs/kafka-ui:latest' does not appear to be a git repository
fatal: Could not read from remote repository.
`

**Comment by Haarolean** [comment]
@joseacl thank you. We'll take a look soon.
