### ISSUE TITLE
Smart filters multiple conditions not working

### ISSUE THREAD

**Issue by as93717913** [provectus/kafka-ui#2375]
**Describe the bug**

For Smart Filter, it will work for only one condition, like `value.eventData.dutyDepartment == "VQA"`
but when their comes multiple condition, second, third and other condition wouldn't work properly like `value.eventData.dutyDepartment == "VQA"  && value.eventData.moSapPlant =="123456"`

The second part `value.eventData.moSapPlant` will be ignored, the result will only match dutyDepartement condition

**Set up**

Docker 

**Steps to Reproduce**

1. 

**Expected behavior**

**Screenshots**

one condition
![image](https://user-images.githubusercontent.com/16937091/182339375-b438bb9f-7154-40e1-a230-e4c4e33868ea.png)
result
![image](https://user-images.githubusercontent.com/16937091/182339521-98939bba-b4a1-4109-86a1-df82b43c3b0f.png)

two condition
![image](https://user-images.githubusercontent.com/16937091/182339714-f72cd911-a3d1-4cc4-8ea5-d27840701db9.png)
 result
![image](https://user-images.githubusercontent.com/16937091/182339788-72367bc2-f727-4924-b680-2353e7489dff.png)

change condition step
![image](https://user-images.githubusercontent.com/16937091/182340026-3e1685aa-6f34-476e-91a7-741710eaa46a.png)
 result
![image](https://user-images.githubusercontent.com/16937091/182340139-e2884c31-f661-49ca-b1a3-7a9e99092d16.png)
The result only will match on first condition

**Comment by Haarolean** [comment]
1. Fix character escaping for the filter query
2. New line symbols should be present as well

**Comment by mk-khan** [comment]
Is there a work around for this at this moment?

**Comment by Haarolean** [comment]
> Is there a work around for this at this moment?

unfortunately, no. But we're planning to fix this one soon.
