### ISSUE TITLE
[Question] What are competitive advantages over Kafdrop

### ISSUE THREAD

**Issue by Kamil-Zakiev** [provectus/kafka-ui#238]
Hey guys! 
I'm really interested in Kafka UI, could you please clarify what features it has that existing solutions like [Kafdrop](https://github.com/obsidiandynamics/kafdrop) doesn't provide?

**Comment by IldarAlmakaev** [comment]
Hello, @Kamil-Zakiev 
Comparing to **Kafdrop** app, Kafka UI provides you multi-cluster management
