### ISSUE TITLE
Last try and I give up - how to start Kafka-ui

### ISSUE THREAD

**Issue by gosforth** [provectus/kafka-ui#2380]
In server.properties:

```
listeners=PLAINTEXT://localhost:9092
advertised.listeners=PLAINTEXT://localhost:9092
```

I get Kafka-ui for docker (no idea why 'host.docker.internal' not localhost makes difference - still same IP):

`docker run -p 8080:8080 -e KAFKA_CLUSTERS_0_NAME=local -e KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=host.docker.internal:9092 -d provectuslabs/kafka-ui:latest `

![obraz](https://user-images.githubusercontent.com/20846275/182591558-eee5b131-dad7-4d98-8be9-61057872bce2.png)

And in log:

`2022-08-03 10:53:17,454 WARN  [kafka-admin-client-thread | adminclient-1] o.a.k.c.NetworkClient: [AdminClient clientId=adminclient-1] Connection to node 0 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.`

Some additional parameters in 'docker run ' required?

**Comment by gosforth** [comment]
I've just installed new version of Kafka - works. Just need to solve problem with:

zookeeper-shell.bat localhost:2181 ls /brokers/ids

By the way, it's interesting that many people, companies allegedly worked without any problems on a version that ... did not work :-)

**Comment by Haarolean** [comment]
>no idea why 'host.docker.internal' not localhost makes difference - still same IP
it shouldn't be and never is:

```
~ % docker run -it alpine sh
/ # ping host.docker.internal
PING host.docker.internal (192.168.65.2): 56 data bytes
```
but it's platform-dependant thing, on linux `host.docker.internal:host-gateway` should be used.

**Comment by Haarolean** [comment]
So, is the problem solved?

**Comment by gosforth** [comment]
Yes, the problem was Kafka version that did not work correctly. Thank you very much indeed for your assistance!

**Comment by Haarolean** [comment]
> Yes, the problem was Kafka version that did not work correctly. Thank you very much indeed for your assistance!

which version was that?

**Comment by gosforth** [comment]
kafka_2.13-3.2.0
BWT:
On my host 'localhos't and 'host.docker.internal' returns same IP

**Comment by Haarolean** [comment]
This version should work fine.
It depends on the host OS, you might need to use host-gateway instead.

**Comment by vladfaust** [comment]
FYI (helped me, I'm on Windows, Docker WSL):

```sh
# Connect to the container's bash (find out the id with 'docker ps')
docker exec -it --user=root <id-of-kafka-ui-container> /bin/sh
# Now, we are connected to the container's bash.
# Let's install 'socat'
apk add socat
# Use socat to create the port forwarding
socat tcp-listen:9092,fork tcp:host.docker.internal:9092
# This will lead to a running process that we don't kill as long as the container's running
```

Keep the `exec` container running and navigate to the UI:

<img width="587" height="176" alt="Image" src="https://github.com/user-attachments/assets/527b3e33-1dac-4ee9-96da-780ef9e29cfb" />

<img width="519" height="99" alt="Image" src="https://github.com/user-attachments/assets/36e109cc-7f2f-479c-b71c-3c44069eb35c" />

It works! 🎉

Credit: https://www.baeldung.com/apache-kafka.
