### ISSUE TITLE
Topics: Messages filtering broken after live mode, offset and timestamp filtering broken, Empty Offset/Timestamp filter value on refresh

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#2394]
**Describe the bug**
1. Messages filtering broken after live mode, 
2. Offset and timestamp filtering broken, 
3. Offset/Timestamp filter value disappears on page refresh

**Set up**

**Steps to Reproduce**

1. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by armenuikafka** [comment]
**Messages search is broken after live mode stopping**

https://user-images.githubusercontent.com/104780608/183007492-20592d14-b37a-40a2-aa00-b6afa4cba284.mov

**Comment by armenuikafka** [comment]
**Filtering by offset and timestamp is not functional**

https://user-images.githubusercontent.com/104780608/183009157-d1322104-3c8b-4ea6-9145-7c3f1f5c3c17.mov

https://user-images.githubusercontent.com/104780608/183009328-8e07e0f1-eefd-4fbb-b725-bc01ea0b105d.mov

**Comment by armenuikafka** [comment]
**Offset/Timestamp field value disappears with refreshing the page**

https://user-images.githubusercontent.com/104780608/183010449-066b103f-4e8d-4d52-a48f-fcb3f3fdfe16.mov

**Comment by Haarolean** [comment]
@armenuikafka let's create separate issues for each bug and please check if the problem persists with v2 messages

**Comment by Haarolean** [comment]
> **Offset/Timestamp field value disappears with refreshing the page**

this one looks outdated, the rest have their corresponding separate issues.
