### ISSUE TITLE
Replace connectors buttons with a sandwich menu

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#2403]
<img width="762" alt="image" src="https://user-images.githubusercontent.com/1494347/183078567-0a423956-0f58-4f9c-86a9-104d1c5a3f24.png">

**Comment by ThienBNguyen** [comment]
Hi, I would like to work on this issue.

**Comment by Haarolean** [comment]
Hey @ThienBNguyen, thanks for the interest! I've assigned the issue to you

**Comment by Haarolean** [comment]
hey @ThienBNguyen, any luck?
