### ISSUE TITLE
How to monitor Zookeeper Status

### ISSUE THREAD

**Issue by AmiDavidW** [provectus/kafka-ui#242]
I tried to use this command below to monitor a Kafka cluster and it works very well.
```bash
docker run -p 8080:8080 \
	-e KAFKA_CLUSTERS_0_NAME=local \
	-e KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092 \
	-d provectuslabs/kafka-ui:latest
```

I just noticed that the Zookeeper status is offline:
![image](https://user-images.githubusercontent.com/47610659/110801536-59761100-824b-11eb-8f3d-d7fc73ddb4d4.png)

I tried to add the zookeeper URL as:
```bash
docker run -p 8080:8080 \
	-e KAFKA_CLUSTERS_0_NAME=local \
	-e KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092 \
	-e KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181 \
	-d provectuslabs/kafka-ui:latest
```

Nothing changes and the Zookeeper status is still offline.

What should we do to fix it?

Thanks,
David

**Comment by germanosin** [comment]
Hi, @AmiDavidW 

Thanks for creating this issue. Could you please provide more details. What version do you use, and what configs do you use.
From issue I see that you try to connect kafka/zookeeper inside docker network, but it's not clear where is kafka/zookeeper running.

**Comment by AmiDavidW** [comment]
Thanks @germanosin 

All the kafka, zookeeper, kafka-ui are running under the same K8S namespace. I put the Internal Endpoints of Kafka and Zookeeper in the command to start kafka-ui. 

It seems it works for Kafka, but not Zookeeper.

**Comment by StefanBilliet** [comment]
Hi

We have the same issue where the zookeeper status is always labelled as "offline". We followed the wiki; this is our docker-compose file so far:

version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:ush
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "9000:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=localhost:2181

**Comment by germanosin** [comment]
> Hi
> 
> We have the same issue where the zookeeper status is always labelled as "offline". We followed the wiki; this is our docker-compose file so far:
> 
> ```
> version: '2'
> services:
>   zookeeper:
>     image: confluentinc/cp-zookeeper:latest
>     environment:
>       ZOOKEEPER_CLIENT_PORT: 2181
>       ZOOKEEPER_TICK_TIME: 2000
>     ports:
>       - 22181:2181
>   
>   kafka:
>     image: confluentinc/cp-kafka:latest
>     depends_on:
>       - zookeeper
>     ports:
>       - 29092:29092
>     environment:ush
>       KAFKA_BROKER_ID: 1
>       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
>       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
>       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
>       KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
>       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
> 
>   kafka-ui:
>     image: provectuslabs/kafka-ui
>     container_name: kafka-ui
>     ports:
>       - "9000:8080"
>     restart: always
>     environment:
>       - KAFKA_CLUSTERS_0_NAME=local
>       - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
>       - KAFKA_CLUSTERS_0_ZOOKEEPER=localhost:2181
> ```

@StefanBilliet in your case looks like you passed zookeeper connect incorrect.
You should replace 
```
KAFKA_CLUSTERS_0_ZOOKEEPER=localhost:2181
```
with
```
KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
```
