### ISSUE TITLE
read-only users for kafka-ui

### ISSUE THREAD

**Issue by ravindraprasad85** [provectus/kafka-ui#2427]
Hi All, You are requested to add feature where we can create read-only user along with admin user , We do have existing feature to make read-only cluster but thats not full filling my need with having larger team/users.

If i am choosing read-only cluster than no-one would be able to perform Kafka Cluster operation (topic/message/etc).

**Comment by ravindraprasad85** [comment]
Sure, Thank you. Please help to get this fixed.

**Comment by Haarolean** [comment]
Hey, thanks for reaching out.

We're planning to implement this exact functionality within #753 (in current release). Stay tuned :)
