### ISSUE TITLE
How to enable read only mode?

### ISSUE THREAD

**Issue by andormarkus** [provectus/kafka-ui#245]
Hi All,

How to enable real only mode in docker?
Based on #218 PR it is enable with `readOnly` environment variable.

In docker I have tried the following configuration:
```
-e readOnly=True
-e readOnly=true
-e readOnly='True'
-e readOnly='true'
-e KAFKA_CLUSTERS_0_READONLY=true
-e KAFKA_CLUSTERS_0_READONLY=True
``` 

In every cases "Add topic" and "edit setting" button on the UI was still active. When I click on these buttons I dont get any error message. In the "edit settings" menu when I click on the "submit" button I got no error message. 

Thanks,
Andor

**Comment by germanosin** [comment]
Hi, @andormarkus 

```-e KAFKA_CLUSTERS_0_READONLY=true``` should work for backend in version 0.0.10, frontend will be released in next version.

**Comment by andormarkus** [comment]
Hi @germanosin 

I have adjusted the documentation according it. See my PR #247 

Thanks,
Andor
