### ISSUE TITLE
Improvement for the pagination "Go to page" field logic

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#2451]
**Describe the bug**
Not allowed to decrease the "Go to page" value from 1, but possible to delete the value

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to Topics
2. Delete the "Go to page" value

**Expected behavior**
Let to not allow too delete the "Go to page" fields value

**Screenshots**

https://user-images.githubusercontent.com/104780608/184827833-f3dfe350-7c97-4209-aded-f66108f4a232.mov

**Additional context**

**Comment by shubhwip** [comment]
@Haarolean can you please assign this to me ?

**Comment by BulatKha** [comment]
Checked ok on http://master.internal.kafka-ui.provectus.io/ui/clusters/local/schemas
Works ok.
