### ISSUE TITLE
Failed to show Schema Registry

### ISSUE THREAD

**Issue by laivu266** [provectus/kafka-ui#2463]
**Describe the bug**

When I click to Schema Registry, I got the error as below:
![image](https://user-images.githubusercontent.com/96401818/185294340-4e26e65d-d5ff-4908-8996-c5a1489c882a.png)
Maybe I have a subject with name "google/protobuf/any.proto" in my schema registry and that is causes of error

**Set up**

I used Helm chart to install Kafka-UI

**Comment by Haarolean** [comment]
Hi, thanks for reporting the issue!

This is a known issue (#1995), unfortunately we haven't fixed it yet. Feel free to subscribe/upvote the original issue. Stay tuned!
