### ISSUE TITLE
Cluster with 4 nodes but only 3 are listed under brokers section

### ISSUE THREAD

**Issue by OpenCoderX** [provectus/kafka-ui#2474]
- Cluster with 4 nodes but only 3 are listed under brokers section.
- In the call to /stats there is only disk usage returned for 3 brokers, the broker that is not returned in disk stats is the missing broker
- There are 4 brokers returned in the json response from GET http://localhost:8080/api/clusters/sensor/brokers

**Set up**
App version: [UI for Apache Kafka](http://kube1.semanticfact.com:8080/)
vv0.4.0(
[521ba0c](https://github.com/provectus/kafka-ui/commit/521ba0c)
)

Kafka version: 3.2.0 in kraft mode

**Screenshots**
https://cdn.discordapp.com/attachments/897805035122077719/1010777595882782750/unknown.png

**Comment by iliax** [comment]
relates to https://github.com/provectus/kafka-ui/issues/2738, should be fixed when https://github.com/provectus/kafka-ui/pull/2903 merged
