### ISSUE TITLE
No docker image for appVersion in Helm Chart

### ISSUE THREAD

**Issue by nbrns** [provectus/kafka-ui#2511]
**Describe the bug**

When deploying the helm chart I receive backoffs as the appVersion in the helm chart does not relate to any available docker image tag.

**Set up**

Running in a GitOps setup using flux CD. Helm chart is installed with version 4.2.0 and appversion 4.0.0.
Manual helm install resulted in the same error.

**Steps to Reproduce**

```
helm repo add kafka-ui https://provectus.github.io/kafka-ui
helm install my-kafka-ui kafka-ui/kafka-ui --version 0.4.2
```

**Expected behavior**

Deployment with an available image version.

**Screenshots**

**Additional context**

I could fix it by overwriting the image tag to latest, however for a production deployment I would prefer a pinned version.

Thanks!

**Comment by Haarolean** [comment]
Hey, thanks for reaching out.

We'll get this fixed, meanwhile you could use this tag: `provectuslabs/kafka-ui:v0.4.0`

**Comment by alyvusal** [comment]
after deploy do
```shell
kubectl set image deployment/kafka-ui kafka-ui=docker.io/provectuslabs/kafka-ui:v0.4.0
```

**Comment by Haarolean** [comment]
Fixed
