### ISSUE TITLE
Implement Search within Consumer group profile

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#2531]
**Describe the bug**
Please implement Search by Topic Name within Consumer group profile

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to Consumer group profile

**Expected behavior**
Should be available Search by Topic Name

**Screenshots**
<img width="1326" alt="search within consumer" src="https://user-images.githubusercontent.com/104780608/188561560-c59178b9-33c2-42da-ac4a-27bf87e5d882.png">

**Additional context**

**Comment by Haarolean** [comment]
/api/clusters/<cluster>/topics/<topicName>/consumer-groups
topicName should be an exact one
