### ISSUE TITLE
Rename "Relevant" version of a schema to "Actual"

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#2533]
**Describe the bug**
Update "Relevant" version of Schema to be "Actual"

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to Schema Registry
2. Open the Schema

**Expected behavior**
Should be 'actual version" instead of "Relevant version"

**Screenshots**
<img width="1717" alt="relevant version" src="https://user-images.githubusercontent.com/104780608/188567076-82590b28-f3f0-49ca-b65a-cc0862b8ceae.png">

**Additional context**

**Comment by winnie-chiu** [comment]
Is this issue taken? If not, I want to do it.

**Comment by Haarolean** [comment]
No, it’s not. Please go ahead:)
