### ISSUE TITLE
Add "Num of Topics" to Topic/Consumer tab

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#2537]
**Describe the bug**
"Num of Topics" should be displayed within Topic/Consumer tab

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to Topics
2. Open the Topic
3. Turn to Consumers tab

**Expected behavior**
The "num of Topics" should be displayed 

**Screenshots**
<img width="1717" alt="num of topics" src="https://user-images.githubusercontent.com/104780608/188837318-c4392509-87fc-4005-bc10-a9a97b40a023.png">

**Comment by Haarolean** [comment]
`/api/clusters/<cluster>/topics/<topic>/consumer-groups`, field "topics".

**Comment by winnie-chiu** [comment]
I'd like to take this issue.
