### ISSUE TITLE
Search consumers by name within topic details

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#2538]
**Describe the bug**
Implement the Search within Topic/Consumers tab

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to Topics
2. Open the Topic
3. Turn to Consumers tab

**Expected behavior**
Search by **consumer Name** should be available within Topic/Consumers tab

**Screenshots**
<img width="1717" alt="search topic:consumers" src="https://user-images.githubusercontent.com/104780608/188839052-d4e88426-4a19-4d93-aa56-6574a94e53ba.png">

**Comment by Haarolean** [comment]
/api/clusters//topics//consumer-groups
topicName should be an exact one

**Comment by shubhwip** [comment]
@Haarolean Can you please assign this to me ?

**Comment by shubhwip** [comment]
@Haarolean I will do it probably this weekend or next.
