### ISSUE TITLE
Make possible to edit the custom filter

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#2539]
**Describe the bug**

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to Topics
2. Open the Topic/messages tab
3. Apply custom filter
4. Click on filter

**Expected behavior**
Should open the filter to edit 

**Figma link**
https://www.figma.com/file/ZkvysdRUmt9p2PDNU3a9WU/Kafka-UI?node-id=1912%3A4544

**Comment by Haarolean** [comment]
Filters are editable now
