### ISSUE TITLE
Documentation: Java installation instruction does not work for brew 3.+

### ISSUE THREAD

**Issue by iliax** [provectus/kafka-ui#254]
Brew 3.+ does not support `cask` command anymore. 
Need to decide if instruction should be split for 2 brew versions or maybe just leave java version requirements and leave installation to developer.

BTW, I used following commands to install java 13 using brew 3.0.6
1. `brew tap adoptopenjdk/openjdk`
2. `brew install adoptopenjdk13`
and project successfully building with it.

**Comment by Haarolean** [comment]
#301
