### ISSUE TITLE
Improve ssl compose with client certs

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#2549]
kafka-ssl.yml: add `KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_PASSWORD` and `KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_LOCATION`

**Comment by FireNdIce3** [comment]
Can I work on this?

**Comment by Haarolean** [comment]
@FireNdIce3 hey, sorry, it's already done within #2574. Feel free to look at other issues on "up for grabs" board or via "good first issue"/"hacktoberfest" labels :)
