### ISSUE TITLE
Change the "Back to custom filters" link text within Saved filters

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#2550]
**Describe the bug**
Change the "Back to custom filters" link text to be "Back to create filter" within Saved filters of Topic/Messages tab

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to Topic/Messages tab
2. Add filter
3. Press Saved filters

**Expected behavior**
The "Back to custom filters" link text should be "Back to create filter"

**Screenshots**
<img width="1437" alt="back to create" src="https://user-images.githubusercontent.com/104780608/189111269-3884c52f-9c71-458a-a021-44a4adcd499f.png">

**Comment by winnie-chiu** [comment]
I like to work on this issue.
