### ISSUE TITLE
Upgrade kafka in compose files

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#2601]
1. Upgrade all kafka to newer versions with kraft mode
2. Drop zookeeper from everywhere
3. Create a separate compose with a kafka with zk

**Comment by raphaelauv** [comment]
some source of inspiration -> https://github.com/confluentinc/cp-all-in-one/blob/748c7033146f202eaf4d2dfecaabfc233b4741af/cp-all-in-one-kraft/docker-compose.yml#L6

**Comment by winnie-chiu** [comment]
I'd like to work on this task.
