### ISSUE TITLE
Support passing properties to Kafka Connect client

### ISSUE THREAD

**Issue by djboris9** [provectus/kafka-ui#2616]
### Which version of the app are you running?
Tag: `v0.4.0` and `master@d9e74deb287e7b81172c6988dd0f99b1a97d9036`

### Is your proposal related to a problem?
Currently it's not possible to configure a Kafka Connect component that has TLS Client Auth required but there could be also other settings that need to be passed to the Kafka Connect Client.

### Describe the solution you'd like
I would like to propose adding a `Properties` field to the `model.KafkaConnectCluster` class like the `model.KafkaCluster` and use the properties in the client instantiation.

Therefore the Kafka Connect component could be configured in the following way to allow TLS Client Auth:
```plaintext
KAFKA_CLUSTERS_0_KAFKACONNECT_0_PROPERTIES_SECURITY_PROTOCOL=SSL
KAFKA_CLUSTERS_0_KAFKACONNECT_0_PROPERTIES_SSL_TRUSTSTORE_LOCATION=ca.jks
KAFKA_CLUSTERS_0_KAFKACONNECT_0_PROPERTIES_SSL_TRUSTSTORE_PASSWORD=xxxx
KAFKA_CLUSTERS_0_KAFKACONNECT_0_PROPERTIES_SSL_KEYSTORE_LOCATION=foobar.jks
KAFKA_CLUSTERS_0_KAFKACONNECT_0_PROPERTIES_SSL_KEYSTORE_PASSWORD=xxxx
```

### Describe alternatives you've considered
N/A

### Additional context
This issue is propably related to #930.

If I get some spare time, I will have a look by myself at it and create a PR.

**Comment by Haarolean** [comment]
Hey, thanks for reaching out.

We'll add this to our backlog :)

**Comment by djboris9** [comment]
Working on this in #2833
