### ISSUE TITLE
Topic tests :  Unable to reproduce massege in topic after update topic.

### ISSUE THREAD

**Issue by ArthurNiedial** [provectus/kafka-ui#2625]
**Describe the bug**
Unable to reproduce massege in topic after update topic.

**Set up**
Build from current branch master.

**Steps to Reproduce**

1. Create topic
2. Update topic
3. Produce message in updated topic

**Expected behavior**
Message produced

**Screenshots**

![ProduceMessageError](https://user-images.githubusercontent.com/79512124/191534674-8806b9a7-6278-4169-866c-da9f4b48b6ac.PNG)

**Additional context**
Actual behavior: Error in sending a message to topic.

Log : 2022-09-22 14:36:24,344 WARN  [kafka-producer-network-thread | producer-6] o.a.k.c.p.i.Sender: [Producer clientId=producer-6] Got error produce response with correlation id 1179 on topic-partition New_TOPIC-0, retrying (2147482474 attempts left). Error: NOT_ENOUGH_REPLICAS

**Comment by Haarolean** [comment]
@ArthurNiedial logs?

**Comment by armenuikafka** [comment]
Still unable to produce message for updated topic

https://user-images.githubusercontent.com/104780608/199336211-6627c85c-e30d-4604-a668-d9bf827bce23.mov

**Comment by Haarolean** [comment]
@armenuikafka @VladSenyuta @ArthurNiedial 
minimal ISR can't be greater than replication factor, raise an issue to validate this (#3152)
You can try editing some other property for now :)

**Comment by ArthurNiedial** [comment]
Test fixed within the task - https://github.com/provectus/kafka-ui/pull/3271
