### ISSUE TITLE
Offset filter not working (d149d26)

### ISSUE THREAD

**Issue by nitin1677** [provectus/kafka-ui#2633]
**Describe the bug**

Switch to Cluster > Topics > Topic > Messages tab
For filter by offset, enter offset number to filter event for offset, and select right most, option Oldest first.

**Expected result**: in data grid, results should start from offset given in offset filter.

**Actual Result**: in data grid, results are being displayed from First Offset.

**Note: Also, cherry on cake, if I need only 1 event or next 10 events from filter offset, that will be nice to have a clear view of events in kafka.**

**Set up**

d149d26013a81e22e5d0c8b59db56ac0565b9e55
(
[d149d26](https://github.com/provectus/kafka-ui/commit/d149d26)
)

**Steps to Reproduce**

1.  as in describe the bug

**Expected behavior**

**Screenshots**

As in described the bug.

**Additional context**

tried with previous released version v0.4.0 also, but the results are same.

**Comment by iliax** [comment]
Hello @nitin1677, thank you for issues.
Currently timestamp/offsets seeks are broken in our master branch. Can you please try using image with "latest" tag?

**Comment by iliax** [comment]
should be fixed after https://github.com/provectus/kafka-ui/issues/2624 is done

**Comment by nitin1677** [comment]
> 

Yes, working with latest lag. but latest tag (v0.4.0) has other issues like smart filters not working or timeout exception with kafka clusters where very large number of topics and high volume events.

**Comment by th0ger** [comment]
Confirmed broken on master (using commit  [8717416](https://github.com/provectus/kafka-ui/commit/8717416))

**Comment by Haarolean** [comment]
@nitin1677 @th0ger fixed in #3057, please try a fresh master image. Or wait for the release (a few days).

**Comment by Haarolean** [comment]
#2624
