### ISSUE TITLE
kafka statistics: how to choose a statistical time period

### ISSUE THREAD

**Issue by yp19910928** [provectus/kafka-ui#2636]
![image](https://user-images.githubusercontent.com/3365444/191918473-183c9b7c-c033-42ec-8c8c-feea0ca576e3.png)
Hello, is it currently not supported to select a time period to generate statistics? Will there be support for generating statistics based on time periods in the future?

**Comment by iliax** [comment]
Hello @yp19910928, thank you for question.

Originally statistics were introduced as a method to inspect **whole topic** characteristics. So, timestamps that you can see is just one of that characteristics, not a analyze task parameters. 

Potentially we can run analysis on specific time ranges, can you please describe your use case more detailed? (Just to understand what problems such functionality can solve)

**Comment by yp19910928** [comment]
Hi, I need to analyze Kafka information over a period of time. Can it be done? Or what should I do? I see the "Restart Analysis" button on the UI, it doesn't seem to be able to select a time range.

**Comment by iliax** [comment]
@yp19910928, currently you can't choose time period for analysis. Analysis will run over whole topic. 

We will discuss your use case internally and maybe add such functionality in the future releases

**Comment by yp19910928** [comment]
Okay, thank you very much.

**Comment by iliax** [comment]
Further discussion about this request will be continued here: https://github.com/provectus/kafka-ui/discussions/2667. Closing issue
