### ISSUE TITLE
Improvement and unification of search and sort in KafkaUI

### ISSUE THREAD

**Issue by BulatKha** [provectus/kafka-ui#2651]
**Describe the bug**
Current implementation is not consistent in the terms of sorting. Some pages have it, some - not.
**Brokers:**
   -    Broker > Config tab:
   - - No sorting neither by the Key nor by the Value columns
   - - Search is only available be Key, not by Value (can be helpful for troubleshooting/maintenance)

**Topics:**
   - No sorting by Number of messages or replication factor. By design? Can it be helpful for maintenance or analyzation of performance issues?
   - Topic > Settings tab:
   - - No sorting neither by the Key nor by the Value columns (can be specifically helpful for maintenance and troubleshooting tasks)
   - - Search is not available. If they are supposed to fit on one page, then it's ok. Otherwise should be added by Key and Value. 

**Consumers:**
   - Consumer sorting not available by: "Num of Topics", "Messages Behind", "Coordinator". Might be good to allow that for "Messages behind".
   - Consumer > Topic preview:
   - - No sorting on visible values is applied, so the list looks as in random order (Partition would be the logical suggestion).  Of the "Partition", "Consumer ID", "Host", "Messages behind", "Current offset", "End offset" columns, first 4 can be valid candidates for sorting via click on the column headers.

**Schema registry:**
   - No sorting on the page right now. Subject column value can be used for that.
   - Column headers are not clickable for custom sorting. All columns seem like valuable for that purpose.
   - Might be good to extend the search from "Subject" to "Subject", "ID", "Type".
   - UX: Column "Id" might be renamed to "ID" and moved to the first position. It feels like standard approach, and something everyone is quite used to. Can be made grey, not to take too much attention from schema name.

**Kafka Connect**
Is handled by the [#2076 ](https://github.com/provectus/kafka-ui/issues/2076)

- Might be worth adding the plugin to sorting options, hypothetically for finding dependencies on the plugin or something like that.

**KSQL DB:**
Both for Tables and Streams tabs:
- No search available.
- No Default sorting is applied.
- No clickable columns area available for custom sorting.

**Set up**
Version [eb06235](https://github.com/provectus/kafka-ui/commit/eb06235)

**Comment by Haarolean** [comment]
Brokers configs:
>No sorting neither by the Key nor by the Value columns
raise an issue
>Search is only available be Key, not by Value (can be helpful for troubleshooting/maintenance)
raise an issue

Topics:
>No sorting by Number of messages or replication factor. By design? 
Yes, that's intended. #2678

Topic > Settings tab:
>No sorting neither by the Key nor by the Value columns 
>Search is not available. If they are supposed to fit on one page, then it's ok. Otherwise should be added by Key and Value.
We'll redesign this page in general, will consider these things.

Consumers:
>Consumer sorting not available by: "Num of Topics", "Messages Behind", "Coordinator". Might be good to allow that for "Messages behind".
Please raise an issue for sorting by num of topics and messages behind.

Consumer > Topic preview:
>No sorting on visible values is applied
Raise an issue, we'll see if we can do sorting in a nested table.

Schema registry:
>No sorting on the page right now. Subject column value can be used for that.
Create an issue to sort by subject, id and type at least.
>Might be good to extend the search from "Subject" to "Subject", "ID", "Type".
Raise an issue
>UX: Column "Id" might be renamed to "ID" and moved to the first position.
Id isn't important here at all. Keeping as is.

KSQL:
Raise an issue for everything at once.

**Comment by BulatKha** [comment]
Split into separate tasks, closing this one
