### ISSUE TITLE
Can't create connectors

### ISSUE THREAD

**Issue by 70G37H3R** [provectus/kafka-ui#2665]
The image that has been used is kafka-ui:latest. It show me message "Connector with name .. already exists" but I don't have any connector yet.

![image](https://user-images.githubusercontent.com/56068441/192742924-68a7765b-9f92-4fa1-b174-c6f22e4ecdab.png)

**Comment by Haarolean** [comment]
Hi, 

please follow the issue template. The one you've used (bug) has some requirements ("set up" block), which says `We might close the issue without further explanation if you don't provide such information.`.

Please fill out the report with all the required information.
