### ISSUE TITLE
Get rid of "Topic analysis successfully started" message

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#2668]
It makes no sense considering the page contents changes

**Comment by Karthik-PM** [comment]
can you assign me this issue

**Comment by Haarolean** [comment]
@Karthik-PM sure :)

**Comment by Haarolean** [comment]
@Karthik-PM any luck?

**Comment by Karthik-PM** [comment]
sorry can i get some more time?  i have been facing a lot of build errors
