### ISSUE TITLE
Save to file issues with bigdecimal

### ISSUE THREAD

**Issue by nitin1677** [provectus/kafka-ui#2669]
**Describe the bug**

when payload contains bigdecimal values, values are displayed as unicode characters like, 

"foreignExchangeRate": {
			"bytes": "#òoÁ\u0000\u0000"
		}

When we select "save as a file", the result in file is truncated after bytes string as no text after this string in output file. ,\"foreignExchangeRate\":{\"bytes\":\"

**Set up**

d149d26013a81e22e5d0c8b59db56ac0565b9e55
https://github.com/provectus/kafka-ui/commit/d149d26

**Steps to Reproduce**

1. 

**Expected behavior**

expected value to be displayed as  "foreignExchangeRate": 1.0000000000000000 instead of "foreignExchangeRate": {
			"bytes": "#òoÁ\u0000\u0000"
		} and payload should be downloaded as complete.

Note: with latest tag (v0.4.0), even the values are displayed as multi-byte, but save as a file copies the complete payload to file.

**Screenshots**

**Additional context**

**Comment by iliax** [comment]
Hello @nitin1677 , thank you for issue.

can you please share `foreignExchangeRate` field definition (like you have in avro schema) ?

**Comment by nitin1677** [comment]
{
						"name": "foreignExchangeRate",
						"type": [
							"null",
							{
								"type": "bytes",
								"logicalType": "decimal",
								"precision": 24,
								"scale": 16
							}
						],
						"doc": "foreign exchange rate",
						"default": null
					}

**Comment by iliax** [comment]
@nitin1677 , thank you for issue. 

There are two parts:
1. BE: currently kafka-ui doesnt support logical coversions (I created ticket for that, since it requires some time to implement https://github.com/provectus/kafka-ui/issues/2764) 
2. FE: I guess there is some error with downloading `#�òoÁ\u0000\u0000` symbols - lets check and fix that anyway

cc @Haarolean

**Comment by Haarolean** [comment]
@iliax can we get an example schema/topic on our dev env for our frontend engineers to reproduce it easily?

**Comment by iliax** [comment]
@Haarolean I created topic `issue-2669` and submitted message that reproduces this issue

**Comment by nitin1677** [comment]
The issue has been closed but still this issue exists from latest pull of master.

		"field1": {
			"bytes": "#òoÁ\\u0000\\u0000"
		},

		"field2": {
			"bytes": "#òoÁ\\u0000\\u0000"
		},

		"field3": {
			"com.avro.schema.common.BigAmount_30_10": {
				"amount": "\\u0013Ôg\\u0000",
				"currency": "USD"
			}
		},

**Comment by Haarolean** [comment]
@nitin1677 which commit are you on? left top corner in ui

**Comment by iliax** [comment]
@nitin1677 please note, that within this issue we only fixed file exportion. Logical type support is not implemented yet (https://github.com/provectus/kafka-ui/issues/2764)
