### ISSUE TITLE
Don't Dismiss Produce Message pane after `Send`

### ISSUE THREAD

**Issue by gabrieljones** [provectus/kafka-ui#2672]
### Which version of the app are you running?
vv0.4.0([521ba0c](https://github.com/provectus/kafka-ui/commit/521ba0c))

### Is your proposal related to a problem?
After clicking `Send` in Produce Message pane UI shift back to the Messages pane and resets the Produce Message field contents.

### Describe the solution you'd like
After clicking `Send` in Produce Message pane UI stays on the Produce Message pane and the field contents remain as entered without being reset to a new random lorem ipsum.

**Comment by Haarolean** [comment]
To do:
1. In the produce message pane add a new checkbox "Keep the contents", unchecked by default
2. If the checkbox is being checked, upon producing a message do the following:
1) do not close the pane upon producing the message
2) Do not alter key/value content in any way
