### ISSUE TITLE
Topic analysis improvements

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#2674]
<img width="351" alt="image" src="https://user-images.githubusercontent.com/1494347/193237442-2e91ab1c-cc49-40e1-b9de-935d381f08a0.png">

- Display percentage in %

- Display time passed since the start
- Split "scanned messages" to two lines: "scanned messages" and "scanned bytes"

**Comment by BulatKha** [comment]
@Haarolean it looks almost according the way you suggested. However the overall progress percentage and progress bar look a bit strange now:
![image](https://user-images.githubusercontent.com/112083452/200502621-64bee7cb-3947-4afa-9753-b741b14716e3.png)

Suggestion: Show the percentage above the progress bar, using a bigger font (most important info in the block, while the rest is additional info).
And the progress bar width to be matched to block width and it's alignment to the center. So it would be more consistent.

CC @armenuikafka

**Comment by pradyumnad** [comment]
![pct_statistics](https://github.com/provectus/kafka-ui/assets/894746/059ec5eb-c6ca-4d87-9f9e-79e95d1f3b8e)
Were you looking for something like this? @BulatKha

**Comment by Haarolean** [comment]
@pradyumnad that's better, yes

**Comment by pradyumnad** [comment]
@Haarolean PR submitted https://github.com/provectus/kafka-ui/pull/4123

**Comment by BulatKha** [comment]
@Haarolean @pradyumnad just a minor comment to fix the alignment of the progress bar, as it looks a bit sideways. Centered and stretched from the left edge of the text to the right border of the second column would look better.
Looks fine otherwise!

**Comment by pradyumnad** [comment]
@BulatKha yes, I was just fiddling with Pixelmator to kind of get the idea. The code was done to fix it.
