### ISSUE TITLE
Topic messages: rename "content" to "value"

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#2675]
Everywhere in the messages views rename "content" to "value". It's key/value in kafka, not key/content.

**Comment by asheerrizvi** [comment]
@Haarolean I can take this.

**Comment by adityabhattad2021** [comment]
Ready to take this issue.

**Comment by sahmed007** [comment]
So I started this, but not able to build the UI locally. I followed the instructions here:

https://github.com/provectus/kafka-ui/tree/master/kafka-ui-react-app#getting-started

My node_modules get installed and I launch the docker containers successfully. The command to start runs as well, and when I go to localhost:3000, I do not see the UI built after I made the changes.

Am I doing something wrong?

**Comment by Haarolean** [comment]
Oof, what a competition, folks. I'm not sure who should I assign this to -- the first person who asked or the one who decided to start anyway? Please check out our "up for grabs" board/project for other issues. We don't have much frontend ones right now, but there are still some left.

**Comment by Haarolean** [comment]
> So I started this, but not able to build the UI locally. I followed the instructions here:
> 
> https://github.com/provectus/kafka-ui/tree/master/kafka-ui-react-app#getting-started
> 
> My node_modules get installed and I launch the docker containers successfully. The command to start runs as well, and when I go to localhost:3000, I do not see the UI built after I made the changes.
> 
> Am I doing something wrong?

What do you observe there? Do you mean your changes are not reflected there? AFAIK vite does the rebuild in runtime just fine.

**Comment by asheerrizvi** [comment]
It's alright. I'll pass.

**Comment by Haarolean** [comment]
Anyone's willing to work on this?

**Comment by adityabhattad2021** [comment]
Me🤚

**Comment by Haarolean** [comment]
Yes, please :)On 12 Oct 2022, at 16:32, Aditya Bhattad ***@***.***> wrote:﻿
Do I also need to change MessagesV2 ?

**Comment by adityabhattad2021** [comment]
Hey, I am a little confused...
Are this the following files in kafki-ui-react-app where change is to be made?
`src/components/Topics/Topic/Messages/Message.tsx`
`src/components/Topics/Topic/Messages/MessagesTable.tsx`
`src/components/Topics/Topic/MessagesV2/ActionCell.tsx`
`src/components/Topics/Topic/MessagesV2/MessagesTable.tsx`

And sorry for being late.

**Comment by Haarolean** [comment]
@adityabhattad2021 if I'll start looking for all the files, I'd do the same work for the second time :)

These are the places on sshots, and there might be others.

![Untitled](https://user-images.githubusercontent.com/1494347/196151351-480c4a44-eac9-48fc-be80-73e68bab47d1.jpg)
![Untitled2](https://user-images.githubusercontent.com/1494347/196151412-b22a51cc-fc26-43bf-a418-ae5b060cade4.jpg)

**Comment by armenuikafka** [comment]
<img width="1725" alt="value" src="https://user-images.githubusercontent.com/104780608/196926364-fea26357-d826-47c4-9e72-92de597f12d1.png">

**Comment by adityabhattad2021** [comment]
Hey I was not able to run react app locally by following the documentation for Docker way
This was the error
![Screenshot 2022-10-24 180823](https://user-images.githubusercontent.com/93488388/197530668-d7904689-11aa-4891-9c27-08c6ac4dd325.png)

**Comment by Haarolean** [comment]
> Hey I was not able to run react app locally by following the documentation for Docker way This was the error ![Screenshot 2022-10-24 180823](https://user-images.githubusercontent.com/93488388/197530668-d7904689-11aa-4891-9c27-08c6ac4dd325.png)

it seems liek you don't have the docker installed?

**Comment by adityabhattad2021** [comment]
I did installed and setup docker.

**Comment by Haarolean** [comment]
> I did installed and setup docker.

I don't see the initial command which caused this error.

**Comment by DanielSmetanka** [comment]
I have found one more content label instead of value when downloading the Kafka msg. Is this intentional (not to break JSON parsers) or is it a bug?

```json
{
	"Content": "Lorem ipsum dolor sit amet",
	"Offset": 296897,
	"Key": "12345",
	"Partition": 0,
	"Headers": {},
	"Timestamp": "2023-01-17T12:00:02.437Z"
}
```

**Comment by Haarolean** [comment]
@DanielSmetanka probably a bug, I'll raise an issue
