### ISSUE TITLE
Add a space to all formatted sizes

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#2676]
All sizes in the app are displayed like this: "123KB". Please add a space between the numeric and size parts.

**Comment by asheerrizvi** [comment]
@Haarolean I can take this.

**Comment by haseeb-xd** [comment]
i wanna work on this

**Comment by Haarolean** [comment]
@haseeb-xd sure, go ahead. 
They might be formatted via the same function through the app. Topic statistics is one of the places with a lot of sizes.

**Comment by Haarolean** [comment]
@haseeb-xd any luck?
