### ISSUE TITLE
Docker Options Ignored

### ISSUE THREAD

**Issue by john-everden** [provectus/kafka-ui#2693]
Example portion of docker-compose file for kafka-ui

```
  kafka-ui:
    image: provectuslabs/kafka-ui
    restart: unless-stopped
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
```
      
  docker-compose logs kafka-ui 
  
app-kafka-ui-1  | Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: fetchMetadata
app-kafka-ui-1  | 2022-10-01 22:45:00,048 WARN  [kafka-admin-client-thread | adminclient-2] o.a.k.c.NetworkClient: [AdminClient clientId=adminclient-2] Connection to node 1 (/127.0.0.1:9092) could not be established. Broker may not be available.
app-kafka-ui-1  | 2022-10-01 22:45:00,951 WARN  [kafka-admin-client-thread | adminclient-2] o.a.k.c.NetworkClient: [AdminClient clientId=adminclient-2] Connection to node 1 (/127.0.0.1:9092) could not be established. Broker may not be available.
app-kafka-ui-1  | 2022-10-01 22:45:02,054 WARN  [kafka-admin-client-thread | adminclient-2] o.a.k.c.NetworkClient: [AdminClient clientId=adminclient-2] Connection to node 1 (/127.0.0.1:9092) could not be established. Broker may not be available.
app-kafka-ui-1  | 2022-10-01 22:45:02,956 WARN  [kafka-admin-client-thread | adminclient-2] o.a.k.c.NetworkClient: [AdminClient clientId=adminclient-2] Connection to node 1 (/127.0.0.1:9092) could not be established. Broker may not be available.
app-kafka-ui-1  | 2022-10-01 22:45:03,959 WARN  [kafka-admin-client-thread | adminclient-2] o.a.k.c.NetworkClient: [AdminClient clientId=adminclient-2] Connection to node 1 (/127.0.0.1:9092) could not be established. Broker may not be available.
app-kafka-ui-1  | 2022-10-01 22:45:04,861 WARN  [kafka-admin-client-thread | adminclient-2] o.a.k.c.NetworkClient: [AdminClient clientId=adminclient-2] Connection to node 1 (/127.0.0.1:9092) could not be established. Broker may not be available.
app-kafka-ui-1  | 2022-10-01 22:45:06,064 WARN  [kafka-admin-client-thread | adminclient-2] o.a.k.c.NetworkClient: [AdminClient clientId=adminclient-2] Connection to node 1 (/127.0.0.1:9092) could not be established. Broker may not be available.
app-kafka-ui-1  | 2022-10-01 22:45:07,268 WARN  [kafka-admin-client-thread | adminclient-2] o.a.k.c.NetworkClient: [AdminClient clientId=adminclient-2] Connection to node 1 (/127.0.0.1:9092) could not be established. Broker may not be available.
app-kafka-ui-1  | 2022-10-01 22:45:08,270 WARN  [kafka-admin-client-thread | adminclient-2] o.a.k.c.NetworkClient: [AdminClient clientId=adminclient-2] Connection to node 1 (/127.0.0.1:9092) could not be established. Broker may not be available.
app-kafka-ui-1  | 2022-10-01 22:45:09,373 WARN  [kafka-admin-client-thread | adminclient-2] o.a.k.c.NetworkClient: [AdminClient clientId=adminclient-2] Connection to node 1 (/127.0.0.1:9092) could not be established. Broker may not be available.
app-kafka-ui-1  | 2022-10-01 22:45:10,376 WARN  [kafka-admin-client-thread | adminclient-2] o.a.k.c.NetworkClient: [AdminClient clientId=adminclient-2] Connection to node 1 (/127.0.0.1:9092) could not be established. Broker may not be available.

Based on the documentation from my understanding it should be trying to connect to kafka:9092 not  127.0.0.1:9092. 
It's like it completely ignores options for 
KAFKA_CLUSTERS_0_NAME: local unless It is just trying to connect to slot 1 as well as zero and something else isn't working properly.

**Comment by Haarolean** [comment]
Hi, please share the full compose file with kafka settings in particular.

**Comment by jSierraB3991** [comment]
Hello good morning same problem
https://github.com/jSierraB3991/dotfiles/blob/main/Docker/kafka-compoe-with-ui.yml

`version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name:  kafka-ui
    ports:
      - 9094:8080
    depends_on:
      - zookeeper
      - kafka
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_NAME: kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181`

**Comment by jSierraB3991** [comment]
Hello good morning same problem

https://github.com/jSierraB3991/dotfiles/blob/main/Docker/kafka-compoe-with-ui.yml

**Comment by jSierraB3991** [comment]
Work
https://github.com/jSierraB3991/scripts/blob/main/bash/run_images_docker_host.sh#L152

**Comment by Haarolean** [comment]
@jSierraB3991 that won't work because your advertised host name is "localhost", which is invalid because you're connecting from another docker container.
Please take a look at our examples, there are plenty, e.g. with kafka in [kraft mode](https://github.com/provectus/kafka-ui/blob/master/documentation/compose/kafka-ui-arm64.yaml). `KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka0:29092,PLAINTEXT_HOST://localhost:9092`
