### ISSUE TITLE
[UI] Do not cache `serdes` endpoint results on frontend

### ISSUE THREAD

**Issue by iliax** [provectus/kafka-ui#2697]
**Description**

`serdes` endpoint responses should not be cached on frontend, because its responses relates to schema-registry state, which can be changed any time. Also, endpoint should work fast, so, there should be no performance impart on calling it .

**Comment by fMurugi** [comment]
Hi I would like to work on this.Would you assign  me please ?

**Comment by Haarolean** [comment]
Hey, sure.

**Comment by fMurugi** [comment]
i have a question, how are you caching these results.I cant figure out.

**Comment by Haarolean** [comment]
@iliax ?

**Comment by iliax** [comment]
@fMurugi 
I don't know where exact FE code in placed, but if you first go to some topic page FE will call `serdes` endpoints. After that if go back to Topics list page and go to same topic again - FE wont do any `serdes` calls anymore. (hard-refresh fixing this situation Ctr - shift - R)
