### ISSUE TITLE
Add an indicator for an active broker controller

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#2700]
like this
![image](https://user-images.githubusercontent.com/1494347/193820357-5665f6fe-6039-4608-85fe-d11f9c4c5a9e.png)

originally requested by DaveInSask on discord

**Comment by iliax** [comment]
BE is ready, FE part that should be done described here: https://github.com/provectus/kafka-ui/pull/2743#issuecomment-1278693863
