### ISSUE TITLE
Display In Sync Replicas (ISR) by Partition on Topic overview

### ISSUE THREAD

**Issue by DaveSlinn** [provectus/kafka-ui#2703]
### Which version of the app are you running?
0.4.0 for production use
Tu.10.2022 06:31:55 (c961344) for test and evaluation

### Is your proposal related to a problem?

It is helpful to identify which partitions for topics are not replicating properly, causing the In Sync Replicas number to be reduced in an otherwise normally functioning cluster (i.e. no brokers are down).

### Describe the solution you'd like

Currently, when viewing a topic that has under replicated partitions, the metrics at the topic highlight this by show the number of URP and ISR.

![image](https://user-images.githubusercontent.com/18301427/194098806-0d6929f2-fb3c-4870-bf0f-51689a5ac988.png)

On the latest build, on the Partition list for a topic, there is a Replicas column, with green showing which broker is the leader for that partition. 

![image](https://user-images.githubusercontent.com/18301427/194099133-196ee221-7cad-42e2-9635-edba167b5378.png)

If we could add a column that showed which replicas for each partition are in sync, it could highlight those that are out of sync, like this (taken from a different Kafka tool).

![image](https://user-images.githubusercontent.com/18301427/194099470-c2699447-f168-4cb7-8f23-2cafa596f509.png)

This helps identify if all the out of sync replicas are from a single broker, which they were in my case.  All URP issues were on broker 1, so we were able to focus our attention there.

**Comment by iliax** [comment]
@Haarolean, we already return if replica is sync or not from backend. So, we can easily implement it in UI. As for design - I think the simplest way is to highlight non-synced replicates with bold red.

**Comment by Haarolean** [comment]
- make the whole line red?
