### ISSUE TITLE
[UI] Topic search not working properly with pagination 

### ISSUE THREAD

**Issue by iliax** [provectus/kafka-ui#2705]
**Setup:**
version in c961344
 
**Description:**
1. Go to Topics page
2. move to page 2
3. enter something into topic search field
-> request sent with `page=2` parameter which will force BE to search **on the second page**, which will lead to wrong results 

<img width="904" alt="Screenshot 2022-10-06 at 10 59 46" src="https://user-images.githubusercontent.com/702205/194235461-dbd248e0-ef72-4079-9b6f-96ae37d54224.png">

**Expected behaviour:**
When something new was entered into search field pagination should be reset

---

**Note:** such behaviour should be fixed in all places where pagination is used: SchemaRegistry, Consumers

**Comment by Richard7111** [comment]
Hello, can you please assign this issue to me?

**Comment by Haarolean** [comment]
Hey, sure, go ahead :)On 8 Oct 2022, at 18:13, Richard Michalik ***@***.***> wrote:﻿
Hello, can you please assign this issue to me?
