### ISSUE TITLE
Deleting a consumer hangs the page 

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#2706]
https://user-images.githubusercontent.com/1494347/194282581-2387ac9f-bee4-4d09-a42a-3fdd312ffb2d.mov

**Comment by spike-spiegel-21** [comment]
Hey, @Haarolean I will be working on this issue. I think there is some problem with the middleware. Request you to assign me. Thank You!

**Comment by Haarolean** [comment]
@spike-spiegel-21 sure, go ahead :)

**Comment by spike-spiegel-21** [comment]
Hey, @Haarolean Currently I am able to run the [kafka-ui-react-app](https://github.com/provectus/kafka-ui/tree/master/kafka-ui-react-app) but I don't know how to create consumer group. Could you please help me?

**Comment by Haarolean** [comment]
@spike-spiegel-21 
you can install any KC connector which does consume messages.
Here's a bunch of [examples](https://github.com/provectus/kafka-ui/tree/master/documentation/compose/connectors), e.g. s3-sink will consume messages and post them to AWS S3, you can configure that one for example.
Here's a [compose file](https://github.com/provectus/kafka-ui/blob/master/documentation/compose/e2e-tests.yaml) which does install connectors for you.

**Comment by Haarolean** [comment]
@spike-spiegel-21 any luck?

**Comment by spike-spiegel-21** [comment]
Hey @Haarolean Sorry for being, was busy with some university stuff. I haven't tried it since prev comment. I will surely complete this task in the upcoming week. Thank you.

**Comment by spike-spiegel-21** [comment]
Hello @Haarolean I was trying to run [kafka-ui.yaml](https://github.com/provectus/kafka-ui/blob/master/documentation/compose/kafka-ui.yaml) with `sudo docker-compose -f docker-compose.yml up` and encounterd these warnings and errors:

1. `kafka0                        | ERROR: Did you forget the update_run.sh file that came with this docker-compose.yml file?
kafka1                        | ERROR: Did you forget the update_run.sh file that came with this docker-compose.yml file?
kafka0 exited with code 1
kafka1 exited with code 1
`
2. `WARN org.apache.kafka.clients.ClientUtils  - Couldn't resolve server kafka1:29092 from bootstrap.servers as DNS resolution failed for kafka1
`
Could you please help me resolve this, or should I create custom docker-compose file?

**Comment by Haarolean** [comment]
@spike-spiegel-21 which OS are you on? Did you run the docker-compose from the project directory or created your own? Do you have `update_run.sh` available at the path specified in volume binds list?
