### ISSUE TITLE
Add message about not existing offline clusters in Dashboard

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#2707]
**Describe the bug**
In case of missing offline clusters, user should see the corresponding message with toggling the offline clusters in Dashboard

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Turn the "Only offline clusters" on
2. Make sure no clusters are available

**Expected behavior**
Should be shown "No Offline Clusters" message

**Screenshots**

<img width="1719" alt="disk usage data" src="https://user-images.githubusercontent.com/104780608/194301856-133ce9ee-df79-4734-86d6-6150ac088839.png">

**Comment by winnie-chiu** [comment]
I reproduce the problem. It's showing like the screenshot down below. Is this issue still need to be modified? or it can be closed.
![image](https://user-images.githubusercontent.com/113582273/196322270-3d89b7fe-9708-4637-a667-11117adbb36d.png)
