### ISSUE TITLE
[UI] Unknown format "date-time" ignored in schema at path on topic with json schema

### ISSUE THREAD

**Issue by EverOwen** [provectus/kafka-ui#2710]
**Describe the bug**

Found in eb06235

I setup a stream using KSQLDB and associated with json schema from schema registry. If I attempt to submit the message to the topic it's rejected with the error.

"Unknown format "date-time" ignored in schema at path"

**Additional context**

Similar to the issue defined here in ajv.

https://github.com/ajv-validator/ajv/issues/1295

**Comment by Haarolean** [comment]
Hey, thanks for reaching out. We'll take a look

**Comment by Haarolean** [comment]
#2354

**Comment by Haarolean** [comment]
@EverOwen please provide an example schema to reproduce the problem
