### ISSUE TITLE
Invalid dates after a recent pull

### ISSUE THREAD

**Issue by nitin1677** [provectus/kafka-ui#2716]
**Describe the bug**

After i pulled the recent image from master branch, the dates are badly messed up and does not show in correct/readable format. for  e.g. top left, current commit shows like this, notice the date on left side before current commit in brackes.

Fr.10.2022 11:20:53 (7d5b7de)

Also from message viewer, the timestamp formats also messed up with format.
Offset	Partition	Timestamp				Key
10517	11	 		Fr.09.2022 17:30:21 	238087980

**Set up**

Commit Hash from top left corner in UI: Fr.10.2022 11:20:53 (7d5b7de)

**Steps to Reproduce**

1. docker pull provectuslabs/kafka-ui:master

**Expected behavior**

Results from Commit hash: d149d26013a81e22e5d0c8b59db56ac0565b9e55
(
[d149d26](https://github.com/provectus/kafka-ui/commit/d149d26)
)

Message Viewer:
Offset|Partition| Timestamp| Key
10389 | 1 | 09.23.22 07:39:30 pm | 238087985

**Screenshots**

**Additional context**

**Comment by Haarolean** [comment]
Hey, thanks for reaching out. We're aware, the fix will be available in a few days. Meanwhile, you can set the env variable `timestamp.format` to `DD.MM.YYYY HH:mm:ss`.

**Comment by nitin1677** [comment]
thx, adding environment variable for timestamp.format helped to correct the date format.

**Comment by Iceforestik** [comment]
> Hey, thanks for reaching out. We're aware, the fix will be available in a few days. Meanwhile, you can set the env variable `timestamp.format` to `DD.MM.YYYY HH:mm:ss`.

I don't understand how to do this, can you write in steps? what is the name of the variable itself and how to export it, this is done through the UI or inside the docker container or at startup
I tried docker exec
timestamp.format=DD.MM.YYYY HH:mm:ss timestamp_format=DD.MM.YYYY HH:mm:ss
