### ISSUE TITLE
KSQL: "Execute KSQL Request" Stream properties overlayed by KSQL query window

### ISSUE THREAD

**Issue by BulatKha** [provectus/kafka-ui#2721]
**Describe the bug**
Layout of the KSQL query window is broken and Stream properties input left border is way under the KSQL query window.

**Set up**
[0939d61](https://github.com/provectus/kafka-ui/commit/0939d61)

**Steps to Reproduce**
1. Open the KSQL tab.
2. Push the "Execute KSQL Request" button
**Actual behavior**
All the stream properties edit fields are under the query window (all the additional ones are as well)
https://user-images.githubusercontent.com/112083452/195013920-933b7580-5f80-4d2c-afab-84ae089d6324.mov

**Expected behavior**
Normal window layout for every field. Including all the additional stream properties.

**Additional context**
Additional stream properties are also under the query window.

**Comment by devils2ndself** [comment]
I'd like to give it a try! Could I get assigned to this task please?

**Comment by Haarolean** [comment]
Sure, please. On 22 Oct 2022, at 08:59, Artem Tanyhin ***@***.***> wrote:﻿
I'd like to give it a try! Could I get assigned to this task please?
