### ISSUE TITLE
Add KC quick actions into the sandwich menu

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#2722]
Add the following actions into this menu:
<img width="303" alt="image" src="https://user-images.githubusercontent.com/1494347/195043659-57b84a7f-c139-4ba0-bc34-8adefd149bf9.png">
1. restart connector
2. restart all tasks
3. restart failed tasks
All the actions are available in a connector overview, we can copy them

**Comment by corners2wall** [comment]
@Haarolean, can u assign on me?

**Comment by Haarolean** [comment]
> @Haarolean, can u assign on me?

sure, go ahead :)

**Comment by corners2wall** [comment]
@Haarolean  not started

**Comment by Haarolean** [comment]
@corners2wall are you planning to? We have a lot of people wishing to participate in hacktoberfest and we don't have that many frontend tasks available :)

**Comment by corners2wall** [comment]
@Haarolean yeap, I planning resolve this issue
