### ISSUE TITLE
Make topic bulk actions buttons always visible

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#2725]
<img width="747" alt="image" src="https://user-images.githubusercontent.com/1494347/195046352-d2b27d74-bbef-46a2-982c-c2aece1cb7df.png">

1. Make these buttons visible even if no topics are selected
2. Make the buttons disabled if no topics are selected

**Comment by yogesh-9999** [comment]
hey @Haarolean  assign me this issue

**Comment by Haarolean** [comment]
@yogesh-9999 any luck?

**Comment by vitalymatyushik** [comment]
@Haarolean can I take that issue?

**Comment by Haarolean** [comment]
@vitalymatyushik yeah it seems
