### ISSUE TITLE
AirGap: Remove internet dependency / google fonts

### ISSUE THREAD

**Issue by AydinChavez** [provectus/kafka-ui#2728]
Hi!

we are accessing latest kafka-ui via a corporate socks proxy, which does not have internet access.

Would it be possible to embed the fonts in the react-app (as part of static folder e.g.) instead of referencering those online?

https://github.com/provectus/kafka-ui/blob/master/kafka-ui-react-app/index.html#L10

```
    <!-- Google fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500&family=Roboto+Mono:wght@400;500&display=swap"
      rel="stylesheet"
    />

```

At the moment, our browser tries to reach following two google font online urls via socks proxy, which leads to a initial load of the kafka-ui of 30 seconds (browser gets a network timeout after 30 seconds):

https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@400;500&display=swap

https://fonts.googleapis.com/css2?family=Inter:wght@400;500&display=swap

**Comment by Haarolean** [comment]
Hey, thanks for reaching out. It seems like we already have a PR by a volunteer, we'll review it soon :)
