### ISSUE TITLE
Empty Metrics tab for Broker

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#2735]
**Describe the bug**
Metrics of Broker are not shown

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to Brokers
2. Open any Broker
3. Turn to Metrics tab

**Expected behavior**
Appropriate Metrics should be displayed 

**Screenshots**
<img width="1719" alt="broker's metrics" src="https://user-images.githubusercontent.com/104780608/195350626-32e219b2-2dcb-443d-97ec-62467ffeaf02.png">

**Comment by iliax** [comment]
Thank you @armenuikafka for noticing that. 
This happens because we changes configuration property name for metrics : need to change `KAFKA_CLUSTERS_0_JMX_PORT` to `KAFKA_CLUSTERS_0_METRICS_PORT` in application config.
Reassigning to @Narekmat

**Comment by Narekmat** [comment]
done
