### ISSUE TITLE
UI now showing broker list when DISABLELOGDIRSCOLLECTION=true

### ISSUE THREAD

**Issue by iliax** [provectus/kafka-ui#2738]
Currently, when log dir collection is disabled, UI not showing brokers list - I think it can be useful to see broker list anyway. Lets render list, but hide/(fill with N/A) columns with no values : segmentSize, segmentsCount. 

CC @Haarolean 

sample:
<img width="1528" alt="Screenshot 2022-10-13 at 10 35 40" src="https://user-images.githubusercontent.com/702205/195522479-de35a587-14f6-491f-a396-7da93e9be629.png">

How to reproduce locally:
run kafka-ui.yaml docker compose with `KAFKA_CLUSTERS_0_DISABLELOGDIRSCOLLECTION: 'true'` property added.

**Comment by Haarolean** [comment]
Good for grabs
