### ISSUE TITLE
UI support for MSK

### ISSUE THREAD

**Issue by iliax** [provectus/kafka-ui#2739]
Changes need to be done:

**Topic Create page**
1. Move `Replication Factor` down to the `Min In Sync Replicas` line, `Cleanup policy` goes up to the  `Number of partitions` level
2. By default `Replication Factor`, `Min In Sync Replicas`, `Maximum message size in bytes`, `Time to retain data (in ms)`  fields should not be filled. "Default" text should be rendered instead. If user didn't set any value to these fields, corresponding parameters should not be passed to backend.

**Edit setting page**
1. Topic properties (both explicit  fields and "Custom parameters") should only be rendered if `source = DYNAMIC_TOPIC_CONFIG`. This means that this parameter was explicitly set when topic was created and it should be shown. Explicit params fields should follow the same logic described in ( Topic create page. p2 ).

**Comment by Haarolean** [comment]
Good for grabs
