### ISSUE TITLE
No custom `annotations` on the level of the `Deployment` metadata

### ISSUE THREAD

**Issue by sherifkayad** [provectus/kafka-ui#2748]
**Describe the bug**

Not really a bug, however, a missing small feature. Deployment object `annotations` should be given as a configuration parameter to the users of the Helm Charts.

A PR can follow to work on that.

**Set up**

Using Helm

**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Haarolean** [comment]
Hey, thanks for reaching out.

We'll be glad to see a PR addressing this issue.

**Comment by sherifkayad** [comment]
@Haarolean PR added to this issue ;) Looking forward.
