### ISSUE TITLE
RBAC: Support github teams

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#2751]
Currently as of #753 we do support only usernames/organizations roles.

Please upvote if you're interested in roles via gh teams.

```
        - provider: oauth_github
          type: team
          value: "provectus/kafka-backend"
```

**Comment by timchenko-a** [comment]
Would be really nice to have

**Comment by mmasipgu** [comment]
It would be amazing!

**Comment by Haarolean** [comment]
Feel free to test the things out:
image: `public.ecr.aws/provectus/kafka-ui-custom-build:4093`
Config example:
```
        - provider: oauth_github
          type: team
          value: "provectus/kafka-backend"
```
