### ISSUE TITLE
Air Gap: Enhancement: Opt out of version check

### ISSUE THREAD

**Issue by LaurentDanti** [provectus/kafka-ui#2753]
Hello,

i'm using your great UI for kafka cluster instance and it's perfect : functionality, rapidity, installating in k8s world with helm.
But i try to install this UI in isolated network without internet access so github.com is not allow.

Is it possible to disable call from the ui to https://api.github.com/repos/provectus/kafka-ui/releases/latest and load the font inside the image ?
Like that the UI could be use in isolated network.

**Comment by iliax** [comment]
@LaurentDanti thank you for the issue!

@Haarolean I think we already have issue created for fonts, maybe we add github call handling to that issue?

**Comment by Haarolean** [comment]
hey @LaurentDanti, thanks for reaching out.
I know already at least a few cases in which people successfully use the app in the "air gap" environment (e.g. #1390).
We already have the fonts issue in progress (#2728), we'll keep this open for considering opting out of the version check.

**Comment by Fuou** [comment]
@Haarolean  hello, I also have the fonts issue, UI doesn't work in isolated network, would you give  workaround ?

**Comment by Haarolean** [comment]
@Fuou we're working on it (#2372)

**Comment by cassanellicarlo** [comment]
@Haarolean what's the status here?

**Comment by Haarolean** [comment]
@cassanellicarlo it's up for grabs for the 3rd-party contributors since we don't have enough capacity to address this issue.

**Comment by joelpavlovsky** [comment]
Hey 🙏 what is the status woth the opt out option?

**Comment by David-DB88** [comment]
ok
