### ISSUE TITLE
Wrong actuator path with custom SERVER_SERVLET_CONTEXT_PATH

### ISSUE THREAD

**Issue by vliska** [provectus/kafka-ui#2758]
**Describe the bug**

When settings SERVER_SERVLET_CONTEXT_PATH to /kafka-ui, actuator is deployed 
with /kafka-ui/actuator/info, but application asks for /actuator/info.

This is a regression from v0.4.0 (which we used before) - it works fine on v0.4.0 (maybe because v0.4.0 does not seem to be asking for /actuator/info endpoint).

**Set up**
Install latest version (c22b6b468c61da1d1a647352405f63cd0670e493335743de6c7f24a519264b35) with
SERVER_SERVLET_CONTEXT_PATH: /kafka-ui

**Steps to Reproduce**

1. go to the landing page

**Expected behavior**
Landing page works and asks for acutator in correct path (/kafka-ui/actuator/info).

**Screenshots**
Not working (c22b6b468c61da1d1a647352405f63cd0670e493335743de6c7f24a519264b35) :
![image](https://user-images.githubusercontent.com/23450695/196111995-150274fa-9415-483e-a28d-78447b8943e7.png)

**Comment by Haarolean** [comment]
Hey, thanks for reaching out. We'll take a look
