### ISSUE TITLE
The Message count is not updating with Clearing message for partition 

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#2778]
**Describe the bug**
Message count stays the same after clearing message for partition in Topic's overview page.
Needs refreshing the page.

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to Topic's overview 
2. Open the menu for partition
3. Press Clear Messages

**Expected behavior**
Messages count should be updated immediately

**Screenshots**

https://user-images.githubusercontent.com/104780608/196624761-0847ba39-4c30-4562-8890-31af9ec985c8.mov

**Additional context**

**Comment by Haarolean** [comment]
@Drex72 any luck?

**Comment by David-DB88** [comment]
@Haarolean this can be checked by QA

**Comment by armenuikafka** [comment]
Bug still exists on master, let's make status ready after merging.
