### ISSUE TITLE
Create connector button is unavailable until the 2nd click

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#2802]
1. Click create connector button
2. Enter valid json config
3. Switch to the name field, enter the name
4. The button is still unavailable until you click inside the config text area again

**Comment by BinniesLite** [comment]
Hi, I love your site. Would you mind if I work on this?

**Comment by Haarolean** [comment]
Hey, sure. Please. On 22 Oct 2022, at 10:44, Binnny ***@***.***> wrote:﻿
Hi, I love your site. Would you mind if I work on this?
