### ISSUE TITLE
BE: Error converting Protobuf schema with recursive references

### ISSUE THREAD

**Issue by iliax** [provectus/kafka-ui#2824]
How to reproduce:
1. create topic 
2. create schema in SR for new topic. Schema should contain circular refs like  
```
syntax = "proto3";
package com.acme;

message MyRecord {
  string f1 = 1;
  OtherRecord f2 = 2;
}
message OtherRecord {
  int32 other_id = 1;
  oneof optionalField {
    string name = 2;
    uint64 size = 3;
    OtherRecord innerRec = 4; 
  }
}
```
3. go to Topics -> select topic -> Messages 
-> BE will fail with StackOverflowException

--- 

Root cause: ProtobufSchemaConverter.java does not take circular refs into account

**Comment by m-kay** [comment]
I just analyzed this issue and this seems to be fixed with #3088.
