### ISSUE TITLE
INFRA: Install kafka-connect-datagen connector to provectus test env

### ISSUE THREAD

**Issue by iliax** [provectus/kafka-ui#2825]
To provide consistent traffic on testing env we can use [kafka-connect-datagen ](https://github.com/confluentinc/kafka-connect-datagen) that will generate test data with specified rates. 

Installation instructions here: 
https://www.confluent.io/hub/confluentinc/kafka-connect-datagen
basically we just need to extract connector archive to kakfa-connect instance volume (directory specifed with kafka-connect `plugin.path` property)

**Comment by Narekmat** [comment]
Datagen plugin has added in Kafka Connect
