### ISSUE TITLE
0.4.0 Image Tag Does Not Match

### ISSUE THREAD

**Issue by treyhendon** [provectus/kafka-ui#2829]
**Steps to Reproduce**

1. Deploy current main helm chart

**Expected behavior**
The chart defaults that if no tag is defined, the chart app version is used.  

Published Docker Tag: `v0.4.0`

Helm Helper:
```
{{- $tag := .Values.image.tag | default .Chart.AppVersion -}}
```

Chart Value:
```
appVersion: 0.4.0
```

**Screenshots**
Docker:
![image](https://user-images.githubusercontent.com/3513589/198065920-feb93aef-254c-49d4-851d-e2c800a0a4a0.png)

Deployed Tag:
<img width="356" alt="image" src="https://user-images.githubusercontent.com/3513589/198065992-6d6370ce-f14b-43a3-bd25-cfb68280f858.png">

**Additional context**
Not sure if you'd rather update the appVersion in chart to be `"v0.4.0"` or publish a new tag to Docker.

**Comment by Haarolean** [comment]
Done in #2842, thank you
