### ISSUE TITLE
Messages querying enhancement 

### ISSUE THREAD

**Issue by iliax** [provectus/kafka-ui#284]
Currently GET messages API only supports simple `contains substring ` queries. 
I think it can be useful if some more advanced queries were supported.

Suggestions are 
1. [JsonPath](https://jsonpath.com/)
2. [JSON Pointer ](https://tools.ietf.org/html/rfc6901) 

In case of using such kind of querying result can contain original message body and query result.

**Comment by germanosin** [comment]
@iliax we already have this feature in our roadmap: #127
