### ISSUE TITLE
RBAC: Implement generic OAuth2 authority extractor

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#2844]
See OauthAuthorityExtractor

**Comment by Haarolean** [comment]
@Jacuo hey, that's gonna take about 1.5 weeks, it's a pretty easy one, I just need to get my hands on it :-)

**Comment by Jacuo** [comment]
> @Jacuo hey, that's gonna take about 1.5 weeks, it's a pretty easy one, I just need to get my hands on it :-)

Thx @Haarolean

**Comment by azotcsit** [comment]
+1 to this feature request.

**Comment by Jacuo** [comment]
Any progress in this issue ?

**Comment by maxpschonder** [comment]
It would be great to have something like this. 👍

**Comment by Haarolean** [comment]
We'd need volunteers who can help to test it out.
[The thread](https://discord.com/channels/897805035122077716/897805035122077719/1100761806462529546) in discord

**Comment by woiza** [comment]
@azotcsit I am struggling with RBAC and Azure AD. Could you please share your config?

I think the code does not read the subject correctly:

`[33mo.s.s.w.s.u.m.PathPatternParserServerWebExchangeMatcher[0;39m: Request 'GET /assets/usePermission-a0d11f59.js' doesn't match 'null /oauth2/authorization/{registrationId}'`

I tried everything mentioned in the following discussion:
https://github.com/provectus/kafka-ui/discussions/3814

**Comment by Haarolean** [comment]
@woiza https://discord.com/channels/897805035122077716/1100761806462529546/1103385500791885825
