### ISSUE TITLE
[UI] Timestamp value overlaps with dropdown field icon within Topic/Messages

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#2858]
**Describe the bug**
The selected value of Timestamp overlaps with dropdown field icon within Topic/Messages

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to Topic/Messages tab
2. Select Timestamp for Seek Type field
3. Choose the date for Timestamp filed

**Expected behavior**
Dropdown filed icon should not overlap with selected value

**Screenshots**
<img width="1728" alt="timestamp value" src="https://user-images.githubusercontent.com/104780608/199179175-1554c741-48cc-4623-a31a-5693b41ba8ac.png">

**Comment by Haarolean** [comment]
as a workaround we could display a short month name instead and keep the field the same width

**Comment by Pranav-yadav** [comment]
https://github.com/provectus/kafka-ui/blob/70cdeea819e812ccf38bb1daa1dd27ba6296d28a/kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/Filters.tsx#L422-L430

```jsx
dateFormat="MMM D, YYYY HH:mm" //Nov 7, 2022 10:45
```
should be okay?

**Comment by Haarolean** [comment]
> @Haarolean
> 
> https://github.com/provectus/kafka-ui/blob/70cdeea819e812ccf38bb1daa1dd27ba6296d28a/kafka-ui-react-app/src/components/Topics/Topic/Messages/Filters/Filters.tsx#L422-L430
> 
> ```js
> dateFormat="MMM D, YYYY HH:mm" //Nov 7, 2022 10:45
> ```
> 
> should be okay?

yeah, thanks
