### ISSUE TITLE
Unchecking the already checked Topics from main checkbox is not available 

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#2869]
**Describe the bug**
Unchecking the already checked Topics from main checkbox is not working 

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to Topics page
2. Check the main checkbox for all Topics
3. Make sure all topics are checked
4. Uncheck the main checkbox

**Expected behavior**
All the Topics should became unchecked

**Screenshots**

https://user-images.githubusercontent.com/104780608/199652821-94339eab-2552-47f7-933d-0f312b614211.mov

**Additional context**

**Comment by Haarolean** [comment]
The important precondition is to have "show internal topics" on

**Comment by armenuikafka** [comment]
Seems not fixed, unchecking is not available.
