### ISSUE TITLE
"Select filter" button is active without selecting any saved filter within Topic/Messages/Saved filters

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#2870]
**Describe the bug**
"Select filter" is active in case of not selected filter within Saved filters in Topic/Messages

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to Topic/Messages
2. Press "+Add Filters"
3. Click on "Saved Filters"
4. Press active "Select filter"

**Expected behavior**
"Select filter" should not be functional until selecting any saved filter 

**Screenshots**

https://user-images.githubusercontent.com/104780608/199660167-7aed650d-2527-43f3-8020-d01826e28c44.mov

**Comment by Haarolean** [comment]
Don't forget v2
