### ISSUE TITLE
[FE] Fix cleanup policy submit/display

### ISSUE THREAD

**Issue by akamensky** [provectus/kafka-ui#2885]
**Describe the bug**
All of our topics have a custom retention.ms (usually 1h-10h). When using this UI to edit topic settings, the UI always shows cluster default for retention.ms (604800000), which we need to remember to set to correct value (even if this field not supposed to change).

**Set up**
1. Running current stable release (0.4.0) as docker-compose service

**Steps to Reproduce**

1. Create topic with retention.ms different from cluster default
2. Go to edit topic settings
3. Check the retention.ms field value

**Expected behavior**
Expected behavior -- the field always show the retention.ms of the topic correctly.

**Actual behavior**
The field always show cluster default value.

**Screenshots**

![Screenshot from 2022-11-07 14-05-32](https://user-images.githubusercontent.com/985805/200218070-2eabd56f-4ee2-4b44-aede-fd8386b7b021.png)
![Screenshot from 2022-11-07 14-05-14](https://user-images.githubusercontent.com/985805/200218073-3bb3417b-03c7-47cf-88de-f41d5cc126c6.png)

**Note**
After more testing, same behavior is for `max.message.bytes`, `min.insync.replicas` and `cleanup.policy`. Which makes it seems that all non "custom parameters" behave like this.

**Comment by akamensky** [comment]
For context -- we had an outage where the topic config was edited, but the person did not notice that this field was showing value different from the one was actually intended for the topic, therefore on "save" topic retention.ms was changed from 60s to 7d.

**Comment by Haarolean** [comment]
Hey Alex,

could you check if that's still an issue on `master`-labeled image? I think we've done fixing something like this previously. 
Thanks.

**Comment by akamensky** [comment]
@Haarolean Yes this appears to be fixed at [fce4c23](https://github.com/provectus/kafka-ui/commit/fce4c23276ebd798f182a2af7150cabffb2d63db).

Can this please be backported to 0.4.x. We can't use unstable release in our production environment and current stable release can easily cause outage.

**Comment by Haarolean** [comment]
@akamensky hey, I can build a new image just for you, since we don't have workflows to do a minor release branch.
The new release is gonna be out soon (once we're done with #753 frontend and testing)

**Comment by akamensky** [comment]
@Haarolean BTW, we found an issue with the fix. In the form it will show correct value (i.e. cleanup.policy == compact), but when submitting form it will submit "default" value there.

**Comment by Haarolean** [comment]
@akamensky thanks, we'll investigate.
