### ISSUE TITLE
Frontend: Segment size calculation error

### ISSUE THREAD

**Issue by andormarkus** [provectus/kafka-ui#289]
Hi Team,

Bases on my testing when a topic segment size is larger than 1gb it wont calculate its values in `mb` or `gb` just returns it in `bytes`.

![Screenshot 2021-03-22 at 08 10 10](https://user-images.githubusercontent.com/51825189/111952883-15ee9300-8ae6-11eb-8721-0ae0073faa8d.png)

Thanks,
Andor

**Comment by germanosin** [comment]
@andormarkus thank you for creating this issue. Will try to fix it asap
