### ISSUE TITLE
Drop deprecated protobuf single file property

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#2893]
TODO drop deprecated protobuf single file property

_Originally posted by @Haarolean in https://github.com/provectus/kafka-ui/pull/2874#discussion_r1015295797_

**Comment by joschi** [comment]
@Haarolean What's the deprecation policy in Kafka UI?

Should this be done within the 0.5 milestone or one version after?

**Comment by Haarolean** [comment]
@joschi in 0.6 :)

**Comment by Haarolean** [comment]
@joschi wanna nuke it?
