### ISSUE TITLE
Change default message polling limit

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#2928]
it's 500 rn, make it 100

**Comment by mouli-jr** [comment]
Hey @Haarolean,

I would like to start contributing to this project and take this issue up as my first one.

I just had a clarification, are you talking about the `max.poll.records` consumer configuration on Kafka?

Thanks!

**Comment by Haarolean** [comment]
@mouli-jr hey! Not sure it's still actual, but might be ok to take a look into that.
We use a dummy consumer when reading topic messages to display them on UI.

@iliax do we still need this?

**Comment by Haarolean** [comment]
The default value stays the same, but since #3334 can be adjusted
