### ISSUE TITLE
Unable to get kubernetes ingress to work

### ISSUE THREAD

**Issue by Subetov** [provectus/kafka-ui#2934]
**Describe the bug**
Trying to deploy helm chart with ingress enabled on subpath.
Getting this error in browser:
`"code":5000,"message":"404 NOT_FOUND"`

**Set up**
1. App version: v0.4.0(521ba0c)
2. Helm chart version: kafka-ui/kafka-ui	0.4.5

**Steps to Reproduce**
1. Run helm command
```
helm upgrade -i kafka-ui -n kafka kafka-ui/kafka-ui \
--set envs.config.KAFKA_CLUSTERS_0_NAME=kafka \
--set envs.config.KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-bootstrap.kafka.svc.cluster.local:9092 \
--set ingress.enabled=true \
--set ingress.path=/kafka-ui
```
2. Open link http://CLUSTER_IP/kafka-ui

**Expected behavior**
Web interface is up and running

**Screenshots**
![image](https://user-images.githubusercontent.com/5689355/201867322-e95cc169-4c06-4cb6-9553-f789aab38bc2.png)

**Additional context**
Also I've tried rewrite rules, with no luck =(
Could you please tell what is the right way to make ingress work.
Thank you.

**Comment by Haarolean** [comment]
Hi, please follow the issue template and provide the requested information.

**Comment by Subetov** [comment]
@Haarolean , sorry, updated.

**Comment by Haarolean** [comment]
@Subetov can you try adding an env variable `SERVER_SERVLET_CONTEXT_PATH` as `/kafka-ui`?

**Comment by Subetov** [comment]
@Haarolean , thank you a lot !
Adding **"--set envs.config.SERVER_SERVLET_CONTEXT_PATH=/kafka-ui"** worked for me:
```
helm upgrade -i kafka-ui -n kafka kafka-ui/kafka-ui \
--set envs.config.KAFKA_CLUSTERS_0_NAME=kafka \
--set envs.config.KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-bootstrap.kafka.svc.cluster.local:9092 \
--set ingress.enabled=true \
--set ingress.path=/kafka-ui \
--set envs.config.SERVER_SERVLET_CONTEXT_PATH=/kafka-ui
```

**Comment by Haarolean** [comment]
@Subetov glad to hear :)
