### ISSUE TITLE
Fields with logical type as decimal displays unicode values instead of original numeric values.

### ISSUE THREAD

**Issue by nitin1677** [provectus/kafka-ui#2943]
**Describe the bug**

Fields with logical type as decimal are not showing correct numeric values from topics with schema registry. details for fields display value and schema registry definition is given below in addl context.

**Set up**

11.15.2022 07:05:35
(
[5900f8e](https://github.com/provectus/kafka-ui/commit/5900f8e)
)

**Steps to Reproduce**

1. 

**Expected behavior**

**Screenshots**

**Additional context**

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/nigupta/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/nigupta/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Data | SchemaRegistry
-- | --
"field1":   {      "bytes":   "#òoÁ\u0000\u0000"     }, | {           "name":   "field1",           "type": [            "null",            {             "type":   "bytes",             "logicalType":   "decimal",             "precision":   24,             "scale": 16            }           ],           "doc": "this is   field1.",           "default": null          },
"field2":   {      "bytes":   "#òoÁ\u0000\u0000"     }, | {           "name":   "field2",           "type": [            "null",            {             "type":   "bytes",             "logicalType":   "decimal",             "precision":   24,             "scale": 16            }           ],           "doc": "this is   field2.",           "default": null          },
"field3":   {      "string":   "L"     }, |  
"field4":   {      "string":   "0"     }, |  
"field5":   {      "boolean": false     }, |  
"field6":   {      "com.avro.schema.common.BigAmount_30_10":   {       "amount":   "\u000e3â\"\u0000",       "currency":   "USD"      }     }, | {           "name":   "field6",           "type": [            "null",            {             "type":   "record",             "name":   "BigAmount_30_10",             "namespace":   "com.avro.schema.common",             "fields": [              {               "name":   "amount",               "type": {                "type": "bytes",                "logicalType":   "decimal",                "precision":   30,                "scale":   10               }              },              {               "name":   "currency",               "type": {                "type":   "string",                  "avro.java.string": "String"               }              }             ]            }           ],           "doc": "this is   field6.",           "default": null          },
"field7":   {      "com.avro.schema.common.BigAmount_20_8":   {       "amount":   "$[Ü",       "currency":   "USD"      }     }, | {           "name":   "field7",           "type": [            "null",            {             "type":   "record",             "name":   "BigAmount_20_8",             "namespace":   "com.avro.schema.common",             "fields": [              {               "name":   "amount",               "type": {                "type": "bytes",                "logicalType":   "decimal",                "precision":   20,                "scale": 8               }              },              {               "name":   "currency",               "type": {                "type":   "string",                  "avro.java.string": "String"               }              }             ]            }           ],           "doc": "this is   field7.",           "default": null          },
"field8":   {      "com.avro.schema.common.BigAmount_30_10":   {       "amount":   "\u000e3â\"\u0000",       "currency":   "USD"      }     }, | {           "name":   "field8",           "type": [            "null",              "com.avro.schema.common.BigAmount_30_10"           ],           "doc": "this is   field8.",           "default": null          },

</body>

</html>

**Comment by Haarolean** [comment]
Thanks for raising an issue

**Comment by tkaszuba** [comment]
You are missing config setting on the kafka avro deserializer. 

Specifically AVRO_USE_LOGICAL_TYPE_CONVERTERS_CONFIG should be set to true

 `  
 protected void configure(KafkaAvroDeserializerConfig config) {
    configureClientProperties(config, new AvroSchemaProvider());
    useSpecificAvroReader = config
        .getBoolean(KafkaAvroDeserializerConfig.SPECIFIC_AVRO_READER_CONFIG);
    avroReflectionAllowNull = config
        .getBoolean(KafkaAvroDeserializerConfig.AVRO_REFLECTION_ALLOW_NULL_CONFIG);
    avroUseLogicalTypeConverters = config
            .getBoolean(KafkaAvroSerializerConfig.AVRO_USE_LOGICAL_TYPE_CONVERTERS_CONFIG);
  }
   `

**Comment by iliax** [comment]
@tkaszuba thank you for suggestion, but unfortunately it is not so simple (we know about that properties).
1. we need to implement json string -> avro record translation to support serialization. Currently we use ` AvroSchemaUtils.toObject(json,  schema)` , but that does not support logical types.
2. we need to support avro schema -> json schema translation (used for samples generation in UI). And that code is now written from scratch (`AvroJsonSchemaConverter`),  so it also need to support logical types. 

So, there is some non-trivial things to be done 😃

**Comment by tkaszuba** [comment]
ok, I have it working so I guess we'll just fork it for the time being
while we wait for a proper fix.

Either way I'm sending over my patch, perhaps it will come in handy.

btw: Thank you for this wonderful product! It's way better than confluent
control center! Congrats!
