### ISSUE TITLE
Topics - Data masking: Support regexp for fields

### ISSUE THREAD

**Issue by BulatKha** [provectus/kafka-ui#2962]
**Describe the bug**

Masking (REMOVE | REPLACE | MASK) configuration for the field names in message key/value does not support regular expressions, e.g.:

```
      KAFKA_CLUSTERS_0_MASKING_0_FIELDS_0: "personal.data.*"
      KAFKA_CLUSTERS_0_MASKING_0_FIELDS_1: ".*password.*"
```

So the value and key patter could be set like below and apply to all the topics within a cluster

```
KAFKA_CLUSTERS_0_MASKING_0_TOPICKEYSPATTERN: ".*"
      KAFKA_CLUSTERS_0_MASKING_0_TOPICVALUESPATTERN: ".*"
```

**Set up**

**Steps to Reproduce**

1. Add an environment variable to set up the field value for masking, using the RegEx.
2. Install the Kafka UI
**Actual behavior**
Masking will apply only the field name exactly matching the field, including the '.' and '*' chars.

**Expected behavior**

Ability to use regular expressions to the field names as well, for something obviously confidential, or fields with the same prefix or suffix

**Comment by Shawcs** [comment]
This would be a nice feature. In a wild cluster you can't specify the exact field name you could want to mask or replace. Having just a kind of blacklisted words list that are searched in field name could be a great feature and easy to use.

**Comment by andyhuynh3** [comment]
It would be great if this feature can also be used to provide a regex that says "exclude all fields except certain ones I care about". That way, it would function more so as an allowlist.
