### ISSUE TITLE
Deleting a "custom parameter" of topic doesn't take effect

### ISSUE THREAD

**Issue by iblislin** [provectus/kafka-ui#2968]
**Describe the bug**

Deleting a "custom parameter" of topic doesn't reflect deletion to the broker at the page `/ui/clusters/local/all-topics/mytopic/edit`.

**Steps to Reproduce**

I have kafka v3.3.1 cluster with 3 broker nodes in kraft mode.

1. I use the docker image `provectuslabs/kafka-ui:7e82e7434ea2d555d881e03a230e5e21db0636d4`
2. Go to the topic edit page, e.g. `/ui/clusters/local/all-topics/mytopic/edit`.
3. Add a custom parameter, `compression.type` and set the value to `gzip`.
4. Go to the topic settings page and verify the modification (`/ui/clusters/local/all-topics/mytopic/settings`)
5. Go to the topic edit page and delete the custom parameter, then click "Update topic" button.
6. Go to the topic settings page but found the parameter not changed back to default value (`producer`).

**Expected behavior**

In step6, the parameter `compression.type` should be set to the default value `producer`.

I expected the deleting a custom parameter mimics the behaviour of 
```
$ bin/kafka-configs.sh --bootstrap-server localhost:9092 --entity-type topics --entity-name mytopic --alter --delete-config compression.type
```

**Comment by Haarolean** [comment]
Hey, thanks for reaching out. We'll take a look!
