### ISSUE TITLE
Page layout bug of Content column values in the Messages tab of the topic

### ISSUE THREAD

**Issue by antipova926** [provectus/kafka-ui#300]
**Pre-conditions:** 
Kafka has a Topic
The topic has messages

**Steps:** 
1. Open Topic 
2. Navigate to the Messages tab 

**Actual:** Please take a look at the attached file 

<img width="1153" alt="pageLayoutbug" src="https://user-images.githubusercontent.com/44370201/112186345-16844800-8c12-11eb-811a-9a2633efd569.png">

**Comment by germanosin** [comment]
@antipova926 could you please elaborate on it. Not sure that this is a bug.

**Comment by antipova926** [comment]
> @antipova926 could you please elaborate on it. Not sure that this is a bug.

My point is that  fields contents should be on the same height
<img width="1151" alt="Screenshot 2021-03-23 at 20 35 53" src="https://user-images.githubusercontent.com/44370201/112192326-eb045c00-8c17-11eb-9edb-722483a2a49a.png">

**Comment by workshur** [comment]
Thank you @antipova926! I see the cause
