### ISSUE TITLE
Local setup documentation is very very limited.

### ISSUE THREAD

**Issue by aav789** [provectus/kafka-ui#3017]
There is very limited documentation for local setup of kafka ui. 
Most of the examples I see are for docker. can you please add corresponding examples for the local setup.
For e.g. there is practically no documentation for SSL connections using local setup.
cc @hasankhadra

**Comment by aav789** [comment]
Linking issue raised few days back - https://github.com/provectus/kafka-ui/issues/2956

**Comment by hasankhadra** [comment]
I was not given any instructions to fix this before or any details that something is missing here.

**Comment by Haarolean** [comment]
I've replied regarding your case in the original [issue](https://github.com/provectus/kafka-ui/issues/2956#issuecomment-1336973790).
Regarding the documentation, we're planning to get rid of docker-compose examples and use mostly yaml config in the future within documentation overhaul.

**Comment by aav789** [comment]
@Haarolean  - please update this ticket when the documentation has been updated.

**Comment by Haarolean** [comment]
Updated docs [here](https://docs.kafka-ui.provectus.io/configuration/quick-start)
Feel free to raise PRs (every page has a "edit on github" button)
