### ISSUE TITLE
Upgrade openapi dependency

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#3034]

**Comment by dshubhadeep** [comment]
@Haarolean could I work on this ?

**Comment by Haarolean** [comment]
@dshubhadeep hey, sure!

**Comment by dshubhadeep** [comment]
Thanks @Haarolean 

Just wanted to confirm the expectations for this - 
Do we need to just upgrade the `openapi-generator-maven-plugin.version` to the latest version i.e., 6.2.1?

Also, I'm facing import errors for classes belonging to `com.provectus.kafka.ui.api`, is there a prerequisite step that I need to do to get it to work?

**Comment by Haarolean** [comment]
@dshubhadeep yep, to the latest possible.

Yeah, the trick is to build them via openapi-generator :D try running clean install with maven to get it done.

**Comment by Haarolean** [comment]
@dshubhadeep any luck?

**Comment by dshubhadeep** [comment]
@Haarolean apologies for the delay. It seems like the bulk of work is already done.
I've updated current version i.e., 6.5.0 to 6.6.0

**Comment by Haarolean** [comment]
@dshubhadeep yep, it seems it's been done within #3624. Thanks
