### ISSUE TITLE
Search is case-sensitive for Brokers configs and Topics

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#3043]
**Describe the bug**
Search is case-sensitive only for Brokers configs and Topics

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to Brokers/Broker configs
2. Fill value within "Search by key"
3. Navigate to Topics
4. Fill value within Search by Topic Name
5. Navigate to Schema Registry/Consumers
6. Fill value within search field

**Actual result:**
Search is case-sensitive only for Brokers configs and Topics

**Expected behavior**
Search should work the same way for all components to keep consistency 

**Screenshots**

https://user-images.githubusercontent.com/104780608/206407320-08eb2ab2-c5d5-4078-8dbe-1aa6970a9710.mov

**Comment by Haarolean** [comment]
@David-DB88 check FE part first, let me know which BE endpoints we have to fix as well

**Comment by David-DB88** [comment]
and i think this one for the broker get const response = await this.request({
            path: `/api/clusters/{clusterName}/brokers/{id}/configs`.replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BrokerConfigFromJSON));
    }

**Comment by armenuikafka** [comment]
https://github.com/provectus/kafka-ui/issues/3346 added for Broker configs search
