### ISSUE TITLE
System redirects to Brokers after Topic delete from profile

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#3044]
**Describe the bug**
System redirects to Brokers after Topic delete

**Set up**

https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to Topics
2. Add a topic
3. Select "Remove topic" from 3dot menu within topic profile

**Actual result:** System redirects to Brokers

**Expected behavior**
System should redirect back to Topics

**Screenshots**

https://user-images.githubusercontent.com/104780608/206436487-27e48413-828b-4a8d-8c74-b44e36caa687.mov

**Additional context**
relates to https://app.qase.io/case/KAFKAUI-207

**Comment by BulatKha** [comment]
@Haarolean should it be moved to QA 0.6 or will it be done in Release 0.5?
