### ISSUE TITLE
Can we add support to integrate monitoring data like kminion etc ?

### ISSUE THREAD

**Issue by kaps1981** [provectus/kafka-ui#3047]
Is there a plan to add Kafka health monitoring to the same dashboard? Also supporting modification so if we have additional prometheus metrics related to kafka consumers that can be added to the same dashbaords

**Comment by Haarolean** [comment]
Hey, thanks for reaching out.

We have metrics visualization planned for future releases (#942), I'll add your suggestion into that issue. Please follow the original issue and let me know if you have any questions.

Closing as a duplicate.
