### ISSUE TITLE
Support Well Known types for Protobuf -> Json schemas

### ISSUE THREAD

**Issue by iliax** [provectus/kafka-ui#3087]
In protobuf there is a set of [predefined (aka Well Known) types  ](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf). These types have their separate rules of how they should be converted to(and from) json format. Ex. 'Timestamp' type is treated as a string with  RFC 3339-formatted date.

Protobuf -> JsonSchema converter should take into account these types, and convert them into proper JsonSchema types.

**Comment by BulatKha** [comment]
@armenuikafka please check test cases for this and add, if it is not there.
