### ISSUE TITLE
Messages: reset timestamp value w/ Clear all filters

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#3110]
**Describe the bug**
Messages tab refreshing with Clear all filters instead of removing Timestamp filter

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Login
2. Open the Topic
3. Turn to Messages
4. Apply Timestamp filter
5. Press Clear all

**Actual behavior**
The seek type changes to Offset automatically and the Timestamp value keeps 

**Expected behavior**
With click on Clear All the current filter values should be removed and messages list should be updated

**Screenshots**
https://user-images.githubusercontent.com/104780608/208837242-9cc6d514-f11b-41aa-9a0d-d530fa40a378.mov

**Comment by vikasrajputin** [comment]
Hi @Haarolean Can I pick this up?

**Comment by Haarolean** [comment]
@vikasrajputin sure, please

**Comment by vikasrajputin** [comment]
Hello @Haarolean I've fixed the issue and raised the PR -> https://github.com/provectus/kafka-ui/pull/3923
