### ISSUE TITLE
[FE] Update display of key/value format

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#3117]
![image](https://user-images.githubusercontent.com/1494347/209088893-23812066-914d-47b8-9059-b0bad9be8c3b.png)
key/value types are not displayed, they're currently being fetched from `keyFormat` and `valueFormat` fields, but:
![image](https://user-images.githubusercontent.com/1494347/209088998-3d1dd995-34fc-4c5f-a4c1-48d7a69b6e44.png)

**Comment by Haarolean** [comment]
@David-DB88 Implementation is invalid.
#3117 clearly states that the value should be fetched from API (the second screenshot is of deprecated fields in API response).

```
const keyFormat = searchParams.get('keySerde') || '';
  const valueFormat = searchParams.get('valueSerde') || '';
```
This will display the currently selected serdes no matter which serde is used for the message itself.

**Comment by David-DB88** [comment]
Got it. Thank you for pointing out.
