### ISSUE TITLE
"Show Internal Topics" not working

### ISSUE THREAD

**Issue by joschi** [provectus/kafka-ui#3135]
TODO: make the "internal" flag prefix configurable, default it to a single underscore character

///

**Describe the bug**

After updating to Kafka UI 0.5.0 (using the Docker image [provectuslabs/kafka-ui:v0.5.0](https://hub.docker.com/layers/provectuslabs/kafka-ui/v0.5.0/images/sha256-cd0fdd18d7d18dd2ba86c237507d7979778405de3e74377fed7582e6a60297d1?context=explore)), the "Show Internal Topics" toggle in the "Topics" view isn't working anymore.

Internal topics are always shown, no matter the state of the toggle.

**Set up**

Docker image [provectuslabs/kafka-ui:v0.5.0](https://hub.docker.com/layers/provectuslabs/kafka-ui/v0.5.0/images/sha256-cd0fdd18d7d18dd2ba86c237507d7979778405de3e74377fed7582e6a60297d1?context=explore) deployed on Kubernetes (no Helm), using the configuration from Kafka UI 0.4.0.

> check commit hash in the top left corner in UI

There is no commit hash shown in the web UI anymore.

**Steps to Reproduce**

1. Open Kafka UI 0.5.0.
2. Click on the configured Kafka cluster.
3. Go to "Topics" page.
4. Click on "Show Internal Topics" toggle.

**Expected behavior**

Internal topics (starting with two underscores: `__`) should be hidden when the "Show Internal Topics" toggle is disabled.

**Screenshots**

<img width="1074" alt="Show Internal Topics disabled" src="https://user-images.githubusercontent.com/43951/209367014-c916520e-0207-4275-acd6-9c88517d2d0e.png">
<img width="1079" alt="Show Internal Topics enabled" src="https://user-images.githubusercontent.com/43951/209367073-d5518e1f-cbef-48fc-8580-325c325c02f4.png">

**Comment by Haarolean** [comment]
Hey Jochen, thanks for raising the issue.

We've recently changed this behavior (#2755). If you suggest that it should be implied that internal topics start with *double* underscore, shouldn't we count "_schemas" (single underscore) as internal topic for example?
I'm not sure about correct behavior here. Also there's an "internal" flag in kafka via AC, which we use as well (you can see tha pr for #2755).

**Comment by joschi** [comment]
> If you suggest that it should be implied that internal topics start with _double_ underscore, shouldn't we count "_schemas" (single underscore) as internal topic for example?

A single underscore as an indicator is fine (topics starting with two underscores also start with 1 underscore 😉).

We're using Amazon MSK and MSK Connect which is using the convention with two underscore characters as an indicator for internal topics.

Confluent also seems to follow the convention with a single underscore character:
https://docs.confluent.io/platform/current/control-center/topics/overview.html#topics-page

> Internal topics names start with an underscore (_) and should not be individually modified. Modifying an internal topic could adversely impact your Confluent Platform installation and result in unexpected behavior.

The Javadoc of [``](https://kafka.apache.org/33/javadoc/org/apache/kafka/clients/admin/TopicDescription.html#isInternal--) also hints to a similar convention:

> Whether the topic is internal to Kafka. An example of an internal topic is the offsets and group management topic: `__consumer_offsets`.

And here's another indicator:
https://github.com/apache/kafka/blob/3.3.1/clients/src/main/java/org/apache/kafka/common/internals/Topic.java#L29-L36

**Comment by Haarolean** [comment]
The internality flag is being defaulted to a single underscore character now. Can be overridden with "kafka_clusters_internalTopicPrefix" property.
