### ISSUE TITLE
Kafka UI version and commit hash not showing in web UI

### ISSUE THREAD

**Issue by joschi** [provectus/kafka-ui#3137]
**Describe the bug**

The commit hash and release version of Kafka UI is not shown anymore in the header of the web UI.

This was still the case in Kafka UI 0.4.0 and the text is missing in Kafka UI 0.5.0.

**Set up**

Docker image [provectuslabs/kafka-ui:v0.5.0](https://hub.docker.com/layers/provectuslabs/kafka-ui/v0.5.0/images/sha256-cd0fdd18d7d18dd2ba86c237507d7979778405de3e74377fed7582e6a60297d1?context=explore) deployed on Kubernetes (no Helm), using the configuration from Kafka UI 0.4.0.

**Steps to Reproduce**

1. Open Kafka UI 0.5.0.
2. Check the header (next to the Kafka UI logo) of the web UI.

**Expected behavior**

The commit hash and release version of the respective build of Kafka UI should be shown.

**Screenshots**

<img width="551" alt="Header of Kafka UI 0.5.0" src="https://user-images.githubusercontent.com/43951/209368504-44773660-8e99-40ca-aa0b-269639e54f28.png">

**Comment by Haarolean** [comment]
Hey, how do you provide the config into the app?

**Comment by joschi** [comment]
I'll check the configuration beginning of next when I'm back at work. 😄

**Comment by Haarolean** [comment]
@joschi an update, please? :-)

**Comment by joschi** [comment]
@Haarolean Thanks for the ping. 😅

We're running Kafka UI 0.5.0 in Kubernetes and provide the configuration as a YAML file (`ConfigMap` mounted into a "directory" of the pod/container) and set the specific path to this configuration file via the `SPRING_CONFIG_LOCATION` environment variable.

This was working with Kafka UI 0.4.0 which showed the commit hash and its version in the header.

**Comment by Haarolean** [comment]
@joschi that's exactly what I've been suspecting.
Using the `SPRING_CONFIG_LOCATION` overrides the default config we have inside a jar and, ultimately, removes [these lines
](https://github.com/provectus/kafka-ui/blob/cf4571b964d2276b5385b7c46d71612c2296c925/kafka-ui-api/src/main/resources/application.yml#L6-L9).
Can you replace `SPRING_CONFIG_LOCATION` with `spring.config.additional-location`? It will append your stuff to the default config.

**Comment by joschi** [comment]
@Haarolean That worked, thanks a lot!

<img width="290" alt="image" src="https://user-images.githubusercontent.com/43951/212369610-9244e766-0bd5-44b9-a2a6-f87c1904552f.png">

Instead of using the property `spring.config.additional-location`, I've opted to add the missing configuration settings to our own configuration file, so that we only have a single source of truth for it.

🔗 https://docs.spring.io/spring-boot/docs/2.7.x/reference/html/features.html#features.external-config.files

**Comment by Haarolean** [comment]
Nice, glad it works :)
