### ISSUE TITLE
RBAC: Support Keycloak

### ISSUE THREAD

**Issue by sookeke** [provectus/kafka-ui#3138]
### Which version of the app are you running?
 latest

### Is your proposal related to a problem?

Kafka-ui RBAC

### Describe the solution you'd like

 We are running the Openshift AMQ Stream Kakfka Cluster with OAuth authentication and Authorization using Red Hat SSO i.e Keycloak

we want to use Kafka ui with to access Kafka cluster with authorization enabled via Red hat SSO i.e keycloak

Users with certain ACL permission are allowed access to the broker's resource i.e topic read, create, etc

I see we already have support for RBAC for kafka ui but this is only for oauth_google, oauth_github, and oauth_cognito providers. Is there a plan to support other providers like Azure AD or Keycloak?

Provider: oauth_AzureAD or Oauth_Keycloak

This will allow kakka-ui to integrate with the Red hat SSO and ready users or client role/group or permission

Kafka-ui users should login with keycloak cred and should only see resources they have access to see

**Comment by Haarolean** [comment]
Hey, thanks for the suggestion. I was about to create one myself once I've seen your feedback in #753 :)

We have LDAP/LDAP_AD planned already and we'll do the keycloak for sure.

**Comment by sookeke** [comment]
@Haarolean 
Just for more clearification. We want to use the same ACL authorization from Kafka to authrorize users to the Kafka ui. A proposed solution might be take the principal from the authentication mechanism i.e Oauth from the Kafka ui and propagate that same principal when making a request to the Kafka broker with authorization enabled.

**Comment by sookeke** [comment]
I think Principal Propagation means re-authenticating Kafka UI with the broker at every client/user authentication with the Kafka UI. That doesn't sound like an Ideal or optimal solution probably difficult to implement in my opinion but a better workaround could be to authenticate and authorize the Kafka UI and the broker with a super user and then apply RBAC between Kafka UI and OAuth clients/users using keycloak client Authorization.

All the Kafka UI RBAC configurations like Resource, scope, permission, and policies should be managed in Keycloak and not in the Kafka UI container using the keycloak client authorization. This will allow keycloak to serve as a centralized manager for all authentication and authorization for the KAFKA UI 

@Haarolean

**Comment by Haarolean** [comment]
@sookeke let's raise a separate issue for this. We'll implement a keycloak extractor within this task, like we have one for oauth2.

**Comment by sookeke** [comment]
@Haarolean right and hopefully the role config will be stored and managed in keycloak other than in Kafka UI

**Comment by jasmdk** [comment]
May I suggest making generic OIDC support instead to support a wider scope of identity providers. Most OIDC providers support adding roles to the access token by adding a "groups" scope or Keycloak may provide roles by default in the "realm_access.roles" claim. It could be configurable which claim to use for the groups.

**Comment by Haarolean** [comment]
@jasmdk This is what is planned actually. Most likely #2844 would be enough.

**Comment by Haarolean** [comment]
Implemented a generic oauth provider within #2844.
Comment here or raise a new issue if you have any further questions.
