### ISSUE TITLE
Version 0.5.0 cannot connect to kafka JMX 9997

### ISSUE THREAD

**Issue by marcelomrwin** [provectus/kafka-ui#3140]
After upgrade my kafka-ui docker image to the last version I'm unable to get metrics from kafka. The exception is always *Connection Refused*. 
I rollback my docker image to v0.4.0 and everything works as expected.

**Comment by Haarolean** [comment]
Hi, please share your configOn 24 Dec 2022, at 19:28, github-actions[bot] ***@***.***> wrote:﻿
Hello there marcelomrwin! 👋
Thank you and congratulations 🎉 for opening your very first issue in this project! 💖
In case you want to claim this issue, please comment down below! We will try to get back to you as soon as we can. 👀

**Comment by marcelomrwin** [comment]
Hello, for sure

```yaml
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:v0.4.0
    restart: unless-stopped
    ports:
      - 9080:8080
    depends_on:
      zookeeper:
        condition: service_started
      kafka:
        condition: service_healthy
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      LOGGING_LEVEL_ROOT: error
    networks:
      - kafka_network
```yaml

**Comment by marcelomrwin** [comment]
if i change the above configuration to version v0.4.0 everything works normally

**Comment by luas10c** [comment]
same problem.

**Comment by Haarolean** [comment]
@marcelomrwin can you share the full stacktrace you have as well?

**Comment by marcelomrwin** [comment]
Just try to start a container with kafka, zookeeper and kafka-ui, kafka ui
cannot connect to port 9997.

Em seg., 26 de dez. de 2022 às 09:57, Roman Zabaluev <
***@***.***> escreveu:

**Comment by Haarolean** [comment]
This config can't possibly enable JMX with v0.4.0 because `KAFKA_CLUSTERS_0_METRICS_PORT` has been introduced later, the properties required to enable JMX are different in 0.4.0.
<img width="686" alt="image" src="https://user-images.githubusercontent.com/1494347/210347178-adeb70dc-fd92-446f-a4e4-9d116c31ad6c.png">
Please verify that your JMX port is open.

**Comment by iliax** [comment]
closing due to lack of response
