### ISSUE TITLE
Prometheus basic auth missing in PrometheusMetricsRetriever (V.0.5.0)

### ISSUE THREAD

**Issue by wanisfahmyDE** [provectus/kafka-ui#3143]
**Describe the bug**
when specifying the metrics type as prometheus, the metrics username/password are not passed down to the [PrometheusMetricsRetriever](https://github.com/provectus/kafka-ui/blob/master/kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/metrics/PrometheusMetricsRetriever.java#L36). unlike the JMX implementation [here](https://github.com/provectus/kafka-ui/blob/master/kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/metrics/JmxMetricsRetriever.java#L57-L58) 

**Set up**
running docker-compose on `V.0.5.0`, with the below configs:

```bash     
      KAFKA_CLUSTERS_0_METRICS_TYPE: "PROMETHEUS"
      KAFKA_CLUSTERS_0_METRICS_USERNAME: 'user'
      KAFKA_CLUSTERS_0_METRICS_PASSWORD: 'password'
      KAFKA_CLUSTERS_0_METRICS_SSL: 'true'
      KAFKA_CLUSTERS_0_METRICS_PORT: 9273
      JAVA_OPTS: >-
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
        -Djavax.net.ssl.trustStore=/jmx/client.truststore.jks
        -Djavax.net.ssl.trustStorePassword=changeit
        -Djavax.net.ssl.keyStore=/jmx/client.keystore.p12
        -Djavax.net.ssl.keyStorePassword=changeit
        -Djavax.net.debug=ssl
    volumes:
      - ./avn/client.truststore.jks:/jmx/client.truststore.jks
      - ./avn/client.keystore.p12:/jmx/client.keystore.p12 
```

**Steps to Reproduce**

1. Configure prometheus as a metrics type secured with basic auth
2. Start kafka-ui
3. Application logs are throwing 401 unauthorized

**Expected behavior**

Connection is established with passed credentials
**Screenshots**

**Additional context**

basic auth aside, it would be nice to have the capability to optionally skip the TLS verification.
this is done by passing the --insecure attribute, reference: https://prometheus.io/docs/guides/tls-encryption/#testing

**Comment by theurichde** [comment]
@wanisfahmyDE and I are going to work on this :-)
