### ISSUE TITLE
Consumers: performance loading topic consumers 

### ISSUE THREAD

**Issue by EI-Joao** [provectus/kafka-ui#3148]
**Describe the bug**
When loading consumers for a selected topic, it takes 30/40 sec. I had a look into the logs and it seems to be loading all the consumers

**Set up**

Using version v0.5.0

**Steps to Reproduce**

1. Add a cluster with a considerable ammount of consumers (I am using +- 150)
2. Go to Cluster -> Topics -> Select a topic -> Consumers

**Expected behavior**

It should only load the information of the consumers connected to the selected topic 

**Additional context**

It will take the same time whether or not the topic has consumers

**Comment by iliax** [comment]
Hello @EI-Joao, 
is issue still actual for latest version (0.6.x)?

**Comment by Haarolean** [comment]
Might be fixed within #3188. Please respond if the problem persists.

**Comment by iliax** [comment]
ok, good, closing issue
