### ISSUE TITLE
NEW SSO parameters in version 0.5.0

### ISSUE THREAD

**Issue by Iceforestik** [provectus/kafka-ui#3153]
earlier on version 0.4.0 I used keycloak+kafka ui

I was running a docker container this way
`sudo docker run --net=host -e KAFKA_CLUSTERS_0_NAME=production -e KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=brokerakafka:9092-e AUTH_TYPE=OAUTH2 -e SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_AUTH0_CLIENTID=monitoring -e SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_AUTH0_CLIENTSECRET=******* -e SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_AUTH0_ISSUER_URI=https://*.*.com/auth/realms/mon -e SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_AUTH0_SCOPE=openid -d provectuslabs/kafka-ui:latest`

now the settings have changed and in the examples it is not entirely clear how to use keycloak, I tried using the example of cognito, it did not work, google and github too

`sudo docker run --net=host -e KAFKA_CLUSTERS_0_NAME=production -e KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=brokerakafka:9092 -e AUTH_TYPE=OAUTH2 -e AUTH_OAUTH2_CLIENT_keycloak_CLIENTID=monitoring -e AUTH_OAUTH2_CLIENT_keycloak_CLIENTSECRET=**** -e AUTH_OAUTH2_CLIENT_keycloak_ISSUER_URI=https://*.*.com/auth/realms/mon -e AUTH_OAUTH2_CLIENT_keycloak_SCOPE=openid -e AUTH_OAUTH2_CLIENT_keycloak_PROVIDER=keycloak -e AUTH_OAUTH2_CLIENT_keycloak_CUSTOM-PARAMS_TYPE=keycloak -e AUTH_OAUTH2_CLIENT_keycloak_CUSTOM-PARAMS_LOGOUTURL=http://*.*.*.com/logout -d provectuslabs/kafka-ui:latest`

how do I set it up?

**Comment by Iceforestik** [comment]
mistake in AUTH_OAUTH2_CLIENT_keycloak_ISSUER_URI
AUTH_OAUTH2_CLIENT_keycloak_ISSUER-URI

**Comment by maxemann96** [comment]
Can this be documented somewhere in the sso readme's? I had the same problem, that with the upgrade to 0.5.0 the sso login broke. I can make a pr for that, but then I need to know where I can find the documentation for configuring the `AUTH_OAUTH2_CLIENT_...` settings? I can only find the spring security docs for the `SPRING_SECURITY_OAUTH2_CLIENT_...` configuration.

**Comment by Haarolean** [comment]
@maxemann96 hey, all the docs are located [here](https://github.com/provectus/kafka-ui/tree/docs), other sources are deprecated and to be removed soon.
I believe [this one](https://github.com/provectus/kafka-ui/blob/docs/configuration/authentication/sso-guide.md) is outdated, dunno about the rest.
Also config you're probably looking for are [here](https://provectus.gitbook.io/kafka-ui/configuration/authentication/oauth2).
