### ISSUE TITLE
Can't add custom parameter to a topic on v0.5.0

### ISSUE THREAD

**Issue by Rmaan** [provectus/kafka-ui#3162]
In new version, I can't add any custom parameter to a topic using UI like I was able before. All items in drop down are disabled (except the ones that are already present).

When I switch to version v0.4.0 I can add custom parameters normally.

<img width="712" alt="image" src="https://user-images.githubusercontent.com/1183449/209810152-63a28bb6-5a9d-411a-9c7d-e6a0d4bd01a1.png">

**Comment by Haarolean** [comment]
Hey, thanks for reporting! We've already fixed this but haven't merged yet, ETA -- 0.5.1
#3071
