### ISSUE TITLE
Broker: Config: Implement search by the Value

### ISSUE THREAD

**Issue by BulatKha** [provectus/kafka-ui#3163]
**Actual behavior**

It is not possible to search by the config Value and only works for the Key now.

**Expected behavior**
Search by the config Value can be useful for maintenance and troubleshooting.

**Set up**

[f4e6afe](https://github.com/provectus/kafka-ui/commit/f4e6afe)

**Steps to Reproduce**

1. Login to Kafka UI
2. Navigate to Borkers
3. Select broker and switch to Configs tab.

**Screenshots**

**Additional context**

Discussed with @Haarolean to be created as a separate issue from #2651

**Comment by malavmevada** [comment]
@Haarolean I would like to contribute to this issue.

**Comment by Haarolean** [comment]
@malavmevada any updates?
