### ISSUE TITLE
Consumers: Add sorting by additional columns

### ISSUE THREAD

**Issue by BulatKha** [provectus/kafka-ui#3164]
**Describe the bug**

Sorting only possible by the Num of messages and State. Not possible by the Num of topics or Messages behind

**Expected behavior**

Sorting by the "Num of topics" and "Messages behind" should be possible as well.

**Set up**

[f4e6afe](https://github.com/provectus/kafka-ui/commit/f4e6afe)

**Steps to Reproduce**

1. Log in to Kafka UI and navigate to the Consumers page.

**Screenshots**

![image](https://user-images.githubusercontent.com/112083452/209812552-3e868093-2a51-4d59-9e67-7680b07d7fc1.png)

**Additional context**

@Haarolean requested to create a separate issue from the #2651 "Please raise an issue for sorting by num of topics and messages behind."

**Comment by nisanohana3** [comment]
Sorting by "Num of Topics" and by "messages Behind" was added and merged to the master. 
I am adding references to the relevant PRs:
[https://github.com/provectus/kafka-ui/pull/3633](url)
[https://github.com/provectus/kafka-ui/pull/3527](url)

I think this issue can be closed
