### ISSUE TITLE
KSQL: Implement sorting

### ISSUE THREAD

**Issue by BulatKha** [provectus/kafka-ui#3171]
**Describe the bug**

1. Neither Tables nor Streams tab have any options to Search, default sorting or user defined sorting by clicking the column names.
2. Not possible to see the Table or Stream details by clicking the row in the table ([task #790](https://github.com/provectus/kafka-ui/issues/790)).

**Expected behavior**

1. Add search by the tab columns.
2. Add the Default sorting for the tab (by the Name?).
3. Add custom sorting by the column names.
4. Table and Stream detailed info is handled in a separate task #790

**Set up**

[f4e6afe](https://github.com/provectus/kafka-ui/commit/f4e6afe)

**Steps to Reproduce**

1. Log in to Kafka UI and navigate to the KSQL DB.

**Screenshots**

![image](https://user-images.githubusercontent.com/112083452/209829037-c31bc295-bf22-4aeb-9119-83e006d39d12.png)

**Additional context**

@Haarolean requested to create a separate issue from the #2651

**Comment by michal-cesek** [comment]
Hey @Haarolean! I've been using kafka-ui at my job for a few months and would like to contribute. Would you assign the issue to me?

**Comment by Haarolean** [comment]
@michal-cesek hey, sure! 
You can refer to [contributing](https://provectus.gitbook.io/kafka-ui/development/contributing) guide as a start
