### ISSUE TITLE
Consumers: performance loading consumers 

### ISSUE THREAD

**Issue by EI-Joao** [provectus/kafka-ui#3176]
**Describe the bug**

When loading consumers it takes 30/35 seconds. This time is related to the number of consumers. 
E.g. if a cluster has x consumers it wil take y time and if a cluster has x1 consumers it will take y1 time.

**Set up**

version v0.5.0

**Steps to Reproduce**

1. Add a cluster 
2. Go to Cluster -> Consumers 

**Expected behavior**

When loading the consumers for a page. Only the number of consumers in that page should be loaded in the backed. 
E.g. if a cluster has 1000 consumers we can not load 1000 consumers every time a page is changed. 

**Screenshots**

**Additional context**

This is applicable to the other pages that have pagination e.g. topics

**Comment by Haarolean** [comment]
Thanks, we'll take a look at this

**Comment by Haarolean** [comment]
@EI-Joao hey, can you try pulling `public.ecr.aws/provectus/kafka-ui-custom-build:3188` image? Is it any way better?

**Comment by EI-Joao** [comment]
Hi @Haarolean 
It is much better now taking 3/4 seconds 😊
It would be really helpful if we could get the same for this one [https://github.com/provectus/kafka-ui/issues/3148](url)

**Comment by iliax** [comment]
@EI-Joao thanks for confirmation! How many consumers do you have btw?

**Comment by EI-Joao** [comment]
The cluster that has more consumer groups is having +-220. It is not a lot but to describe them all every time a page is changed takes some time 😊
