### ISSUE TITLE
Consumers: spinner does not show while loading consumers

### ISSUE THREAD

**Issue by EI-Joao** [provectus/kafka-ui#3177]
**Describe the bug**

Spinner does not show while loading consumers

**Set up**

 Version v0.5.0

**Steps to Reproduce**

1. Add a cluster 
2. Go to Cluster -> Consumers 

**Expected behavior**

Should show a the spinner while loading the consumers. Even if the consumers are cached should show some information while it is loading the consumers 

**Screenshots**

**Additional context**

**Comment by Haarolean** [comment]
Thanks, we'll take a look

**Comment by Haarolean** [comment]
Done within #3508
