### ISSUE TITLE
getting invalid credentials on google authentication

### ISSUE THREAD

**Issue by abhinavgautam07** [provectus/kafka-ui#3182]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/49569646/210081833-e092951c-6e0d-4b9d-9d77-f54ed3d82f71.png">

**Comment by Haarolean** [comment]
Hi, please follow the issue template and fill out the required info.

The template exists for a reason and it's clearly stated there:
`We might close the issue without further explanation if you don't provide such information.`

**Comment by abhinavgautam07** [comment]
IAAC configs.
[configs.zip](https://github.com/provectus/kafka-ui/files/10325267/configs.zip)
