### ISSUE TITLE
Custom URN for logout button for 0.5.0

### ISSUE THREAD

**Issue by AlexeyGA** [provectus/kafka-ui#3206]
When connecting oauth2 via the keycloak provider I did not find the possibility of determining the URN of the exit button in the interface.

Very often, a user path is used to access the user interface, and it is very different from `/`, so exit is not possible. So I would like to have an environment setting/variable responsible for that path in order to be able to log out properly.

The launch is carried out in kubernetes. Additionally, the `SERVER_SERVLET_CONTEXT_PATH : /kafka-ui` parameter is passed

**Comment by Haarolean** [comment]
@anushkabishnoi hey, sorry for the delay! We've been already working on it.
If you wish to contribute please refer to [contributing guide](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) as a start, thanks!
