### ISSUE TITLE
Topics: Not possible to change the Topic name with Edit settings

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#3214]
**Describe the bug** (Actual behavior)
Not possible to change Topic name with editing Topic settings as the field is frozen 

**Expected behavior**
 Should be possible to change Topic name

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Turn to Topics
2. Open already existing Topic
3. Select "Edit settings" from 3dot menu on right

**Screenshots**
<img width="1724" alt="topic name" src="https://user-images.githubusercontent.com/104780608/211798094-66b88515-0358-4017-b83b-27a28d1998cf.png">

**Comment by Haarolean** [comment]
It's a unique identificator and can't be changed.
Let's update the test cases.
