### ISSUE TITLE
Kafka Connect Doesn't work

### ISSUE THREAD

**Issue by DineshSanklecha** [provectus/kafka-ui#3243]
Hi Team,

I have an issue with Kafka Connect parameter. After reaching 450+ connectors I have ran into an issue where I am unable to view the list of connectors. The Kafka connect works fine in the back end, I am able to access it through postman without any issues.
I am using jar version 4.0 (running without building).  I have tried using jar version 5.0. However, in the latest version it doesn't even load my cluster. 

I am running a test cluster of 3 nodes connected to same network. 

Kindly let me know if anything can be done. 

Screenshot attached for reference. 
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/73770671/213091357-588b4465-ce0c-4e12-84be-04c5f667650b.png)

**Comment by iliax** [comment]
Hello @DineshSanklecha, 
can you please provide kafka-ui backend logs?

**Comment by DineshSanklecha** [comment]
@iliax Kindly find the attached log.
![Kafka_UI log](https://user-images.githubusercontent.com/73770671/213100945-c992805e-4813-420e-be75-6700d0f471e7.png)

**Comment by iliax** [comment]
@DineshSanklecha 
ok, understood.

Please try to set `WEBCLIENT_MAX_IN_MEMORY_BUFFER_SIZE: 50MB` environment variable. It will increase buffer size that is used for fetching connects data. 

Also, I would recommend you use version 0.5. (We can check why it is not working for you - send logs in this case)

**Comment by DineshSanklecha** [comment]
@iliax Thanks for your quick response.
Just to be clear, do I have to set the above said property in application.yml file or in my connector config file?

**Comment by iliax** [comment]
@DineshSanklecha 
You can do either
1. add to kafka-ui application.yml :
```
webclient:
  max-in-memory-buffer-size: 50MB
 ```
2. set environment variable in kafka-ui container `WEBCLIENT_MAX_IN_MEMORY_BUFFER_SIZE: 50MB`

**Comment by DineshSanklecha** [comment]
![appyml](https://user-images.githubusercontent.com/73770671/213111391-3790192b-6be5-48b8-9cb4-8333decb130c.png)
@iliax I am still facing the same issue making the said changes. Please find the screenshot of my yml file for reference.

**Comment by iliax** [comment]
@DineshSanklecha 
I think your indent level is not right - `webclient` should be on with zero ident. 
Also if it is applied properly error message in logs (if any) should contain 100mb buffer size error

**Comment by DineshSanklecha** [comment]
![1](https://user-images.githubusercontent.com/73770671/213114409-24bd2fc4-3716-435c-9c04-82065e72d64e.png)
![2](https://user-imag@iliax s.githubusercontent.com/73770671/213114419-36458bb9-d497-41d9-9b9a-f384ec1ce603.png)
@iliax  I have declared the above config in the attached formats. But still the issue persists.

**Comment by DineshSanklecha** [comment]
![Uploading 2.png…]()

**Comment by iliax** [comment]
@DineshSanklecha 
ok, lets try couple of things:
1. set `webclient.max-in-memory-buffer-size: 100MB` property in yaml (as a single line, no line breaks
2. sent backend logs afther p1. applied
3. try version 0.5

**Comment by DineshSanklecha** [comment]
@iliax  The above config worked for me with latest jar (0.5)(works with latest chrome browser version). The issue still remains with earlier jar(0.4). 
Also, I observed that while deleting a connector in Kafka-UI it stays on 'cancel'/ 'submit' pop-up window and throws an error:500 internal server error. However, the connector gets deleted when I refresh the page and check. 

Thanks for your quick assistance. Appreciate it. Cheer!

**Comment by Haarolean** [comment]
@DineshSanklecha glad it works. Feel free to raise a separate issue for the other problem.
