### ISSUE TITLE
kafka-ui helm chart doesn't set any limits by default

### ISSUE THREAD

**Issue by wallhided** [provectus/kafka-ui#3273]
**Describe the bug**

Kubernetes pod with kafka-ui application had enormous memory consumption after 10 days uptime.
By default helm chart doesn't set any cpu/memory limits for deployment and also example of usage doesn't contain info about setting those limits.

**Set up**

I use kafka-ui-0.3.3 helm chart version. Deployment of pod has ```image: docker.io/provectuslabs/kafka-ui:latest``` as image version. Node with this pod had 10 days uptime. I could guess that node took latest version of image 10 days ago. 

**Steps to Reproduce**

1. Deploy helm chart with using usage example from this [page](https://github.com/provectus/kafka-ui/tree/master/charts/kafka-ui)(Perhaps it is mostly related to our setup of Kafka cluster with its resources/data.)

**Expected behavior**

**Screenshots**

<img width="593" alt="Снимок экрана 2023-01-26 в 16 18 45" src="https://user-images.githubusercontent.com/42974336/214845768-f44f1186-5f89-427a-8ea5-ab10bb7adb6e.png">
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/42974336/214846014-04a961c4-a527-44f5-807b-dcc6c007f409.png">

**Comment by Narekmat** [comment]
Hello @wallhided
You can provide limit by adding them in values.yaml or you can provide them in command line.
Here is the example.
helm install kafka-ui kafka-ui/kafka-ui --set envs.config.KAFKA_CLUSTERS_0_NAME=local --set envs.config.KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092 --set resources.limits.cpu=200m --set resources.limits.memory=512Mi

**Comment by wallhided** [comment]
@Narekmat Thank you. My suggestion is to enhance documentation and add some info about setting those limit since that case could happen in other environments. Setting them by default its not a good option, since node types could vary.

**Comment by Haarolean** [comment]
Documentation is present [here](https://docs.kafka-ui.provectus.io/configuration/helm-charts/resource-limits)
