### ISSUE TITLE
K8s secret is created even if no secret is provided as a value.

### ISSUE THREAD

**Issue by cpapad** [provectus/kafka-ui#3299]
**Describe the bug**

This is not exactly a bug but I felt the `K8s/Helm` section is the appropriate to post this issue.
The chart's secret template renders every time and the resource is created, even when no secrets are provided it is just created with no data.
This may not be a big issue but we faced some conflicts while deploying which have been dealt with some workarounds.
For deploying `kafka-ui` we use both the official chart and a `common` chart we have developed to handle thing like ingress, `istio` routing and `sealed-secrects`. Since our `common` chart has the same naming conventions we ran into a conflict when `sealed-secrets` was trying to unseal and create the k8s secret with the same name.
To overcome this we performed a fullnameoverride in the `kafka-ui` chart but then the network routing broke due to breaking the `kubernetes` service naming convention assumed by our common chart.
We solved this by adding a second service template which works but it is messy because we create 2 services, but only one is used.

So I would like to ask if we could make the secret resource optional if no values are required.
If this is something that we can agree I can work on this and contribute.

**Set up**

1. App version `0.5.0` 
2. Chart version `0.5.1`

**Steps to Reproduce**

1. Create secret with name matching the release name

**Expected behavior**

Failure to create secret

**Comment by Haarolean** [comment]
Hey, thanks for reporting this. We'll take a look

**Comment by cpapad** [comment]
> Hey, thanks for reporting this. We'll take a look

Thank you for your quick reply.
I'm more than happy to contribute.

**Comment by Haarolean** [comment]
@cpapad you can raise a PR if you wish!
