### ISSUE TITLE
RBAC: Unmask passwords in connector configs

### ISSUE THREAD

**Issue by xie-shujian** [provectus/kafka-ui#3313]
**Describe the bug** (Actual behavior)

**Expected behavior**

**Set up**

**Steps to Reproduce**

1. 

**Screenshots**

**Additional context**

Please replace ****** with the real credential values to avoid accidentally breaking your connector config!
I want to see the database pasword but got *****, if there a environment vairable to show the password

**Comment by Haarolean** [comment]
Hi, that's on purpose.

We might implement this as a part of RBAC, thanks for a suggestion.

**Comment by iliax** [comment]
@Haarolean @xie-shujian 
also you can set `KAFKA_CONFIG_SANITIZER_ENABLED=false` to disabled configs satitizing (NOTE: configs will be visible for all roles who have access to connect's configs)

**Comment by xie-shujian** [comment]
> @Haarolean @xie-shujian also you can set `KAFKA_CONFIG_SANITIZER_ENABLED=false` to disabled configs satitizing (NOTE: configs will be visible for all roles who have access to connect's configs)

thank you very much
