### ISSUE TITLE
Topics: UI minor fixes for Create new Topic form

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#3318]
**Describe the bug** (Actual behavior)
Error message about Topic Name requiredness is "name is a required field"
"e" letter is not fully displayed within "Maximum message size in bytes" field's placeholder
Error message of "Number of Partitions" starts with lower case

**Expected behavior**
Display all placeholders fully
Error messages should include the field name fully and start with upper cases\

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Login to kafka-ui
2. Navigate to Topics
3. Press "Add a Topic"

**Screenshots**

<img width="1724" alt="typos topic profile" src="https://user-images.githubusercontent.com/104780608/217455251-4c05bd83-a246-4e17-98e0-b3b15a1caa4a.png">

**Comment by pvmsikrsna** [comment]
@Haarolean I would like to contribute to this issue.
