### ISSUE TITLE
Topics: Number of partitions field validation should not allow `.` and `,`

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#3319]
**Describe the bug** (Actual behavior)
It's possible to fill "," within Number of partitions field

**Expected behavior**
Let's not allow to add "," as there can be only integers from 1  

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to Topics
2. Add a Topic
3. Fill "Number of Partitions" with copy pasting ",77" or add "1,5"

**Screenshots**

https://user-images.githubusercontent.com/104780608/217461981-bc94e309-7bd1-4386-b8ba-0b5a413ab9e4.mov

**Comment by BulatKha** [comment]
I guess that not only `.`, but also `,` should not be allowed and not only for partitions, but for in sync replicas, time to retain data and maximum message size. They all should not accept decimal values.
