### ISSUE TITLE
Reducing logging in docker?

### ISSUE THREAD

**Issue by getorca** [provectus/kafka-ui#333]
Is there an env variable to set to reduce the logging for docker? I can't find the actual docker image...

**Comment by c-v-ya** [comment]
Highly support this feature! Maybe at least add ability to change the logging level? Because it's spamming like crazy if the broker is down. Could easily eat up gigabytes in the span of couple days (if there is no logging policy set).

**Comment by germanosin** [comment]
Hi, @getorca , @c-v-ya you could pass 
```LOGGING_LEVEL_ROOT=error``` 
env variable to reduce it

**Comment by c-v-ya** [comment]
Well warnings are gone, but it's now spamming with `DEBUG` logs :sweat_smile: I've tried setting both `error` and `ERROR` env.

`[parallel-2] DEBUG com.provectus.kafka.ui.service.MetricsUpdateService - Start getting metrics for ...`

It would be great to have all the available envs somewhere in the docs, though.

**Comment by germanosin** [comment]
@c-v-ya could you please share full rows with debug level messages with this config?

**Comment by c-v-ya** [comment]
Sure, this is the latest output and the list goes on.
```
14:15:11.427 [parallel-1] DEBUG com.provectus.kafka.ui.service.MetricsUpdateService - Start getting metrics for kafkaCluster: local
14:15:41.390 [parallel-2] DEBUG com.provectus.kafka.ui.service.MetricsUpdateService - Start getting metrics for kafkaCluster: samolet
14:15:41.446 [parallel-2] DEBUG com.provectus.kafka.ui.service.MetricsUpdateService - Start getting metrics for kafkaCluster: local
14:16:09.577 [boundedElastic-4] DEBUG org.springframework.http.codec.json.Jackson2JsonEncoder - [c23ba017] Encoding [[class Cluster {
    name: samolet
    defaultCluster: null
    status: offline
    brokerCount: nul (truncated)...]
14:16:11.390 [parallel-3] DEBUG com.provectus.kafka.ui.service.MetricsUpdateService - Start getting metrics for kafkaCluster: samolet
14:16:11.427 [parallel-3] DEBUG com.provectus.kafka.ui.service.MetricsUpdateService - Start getting metrics for kafkaCluster: local
14:16:41.390 [parallel-4] DEBUG com.provectus.kafka.ui.service.MetricsUpdateService - Start getting metrics for kafkaCluster: samolet
14:16:41.426 [parallel-4] DEBUG com.provectus.kafka.ui.service.MetricsUpdateService - Start getting metrics for kafkaCluster: local
```

Container envs:
![image](https://user-images.githubusercontent.com/11807205/113583980-ff425300-9632-11eb-9574-314406f5ee2d.png)

**Comment by getorca** [comment]
same, still getting debug errors.

**Comment by RustamGimadiev** [comment]
Hi, to turn off debug messages from logs please set the next environment variables: 
- `LOGGING_LEVEL_ROOT=error`
- `LOGGING_LEVEL_COM_PROVECTUS=error`

**Comment by c-v-ya** [comment]
That seems to work for me! Cool, thanks a lot :pray:

But as I proposed earlier, it would be great to have all the available envs somewhere in the docs
