### ISSUE TITLE
MSK Serverless : fails to collect cluster info

### ISSUE THREAD

**Issue by droot-intel** [provectus/kafka-ui#3331]
**Describe the bug** (Actual behavior)
We have several Kafka clusters including a serverless instance.  The instance never comes on line and the pod logs contain this error:
ERROR [parallel-1] c.p.k.u.s.StatisticsService: Failed to collect cluster msk-svrless info
org.apache.kafka.common.errors.UnsupportedVersionException: The broker does not support DESCRIBE_LOG_DIRS

**Expected behavior**
Previous closed bugs like https://github.com/provectus/kafka-ui/issues/2185 suggest that AWS MSK serverless is supported.  We expected the serverless instance to be online.

**Set up**
1. Using the latest docker image ([027d9b4](https://github.com/provectus/kafka-ui/commit/027d9b4))
2. EKS cluster
3. Connects fine to a provisioned MSK cluster using IAM

**Steps to Reproduce**
Pretty simple setup
1. EKS in same VPC as kafka serverless cluster
2. Deploy the above image
3. UI shows cluster as offline
4. Above error periodically repeats

**Screenshots**
NA

**Additional context**
We tested with 2 clusters:  
1. Provisioned kafka cluster (IAM)
2. Serverless kafka cluster (IAM)
1st cluster connects as expected.  2nd serverless cluster has above error and shows as offline in the ui.

**Comment by droot-intel** [comment]
Curious to find out if AWS MSK Serverless is supported.  I know the issue has been opened previously and fixed by [2737](https://github.com/provectus/kafka-ui/pull/2737) but there may still be an issue.

**Comment by Haarolean** [comment]
Hi, can you try running `master`-labeled docker image?

**Comment by droot-intel** [comment]
Hi @Haarolean,
It works!  Was able to successfully connect.   Thanks!

**Comment by Haarolean** [comment]
@droot-intel gotcha, you can use the `KAFKA_CLUSTERS_0_DISABLELOGDIRSCOLLECTION: true` property with `0.5.0` version, which has been already removed and no more needed with recent versions.
