### ISSUE TITLE
deploy helm chart into artifacthub.io

### ISSUE THREAD

**Issue by survivant** [provectus/kafka-ui#334]
it could be useful to have the Helm chart available in artifacthub.io instead of having to download the repo to install the chart.

https://artifacthub.io/packages/search?page=1&ts_query_web=kafka

**Comment by RustamGimadiev** [comment]
Hi, @survivant! Thanks for creating this issue, we already store our helm chart under GitHub pages, so you can use the following command to install the application: 
``` bash 
helm repo add kafka-ui https://provectus.github.io/kafka-ui
helm install kafka-ui kafka-ui/kafka-ui
```

**Comment by RustamGimadiev** [comment]
We published on https://artifacthub.io/packages/helm/kafka-ui/kafka-ui
