### ISSUE TITLE
Error Connecting to Node with FQDN

### ISSUE THREAD

**Issue by BenBurge** [provectus/kafka-ui#3344]
When trying to setup a docker container with Kafka-UI 0.5.0 it doesn't appear to be taking the fully qualified domain name (FQDN). 

Here is the docker run command example.

`docker run -p 8080:8080 -e KAFKA_CLUSTERS_0_NAME=Development -e KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka1.example.com:9092 -d provectuslabs/kafka-ui:latest`

As you can see, I am using the FQDN version of the bootstrap server. However, when container starts up, I see the following error without the FQDN.

`Error connecting to node kafka1:9092 (id: 1 rack: null)  java.net.UnknownHostException: kafka1`
`at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:801)`
`at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1519)`
`at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1377)`
`at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1305)`
`at org.apache.kafka.clients.DefaultHostResolver.resolve(DefaultHostResolver.java:27)`
`...`

In version 0.3.0 which is the current version, which we are currently using, we do see the FQDN in some of the logs.

Is the newest version stripping out the FQDN part of the bootstrap servers or is there some new configuration I am missing to get this to work right?

**UPDATE 1** 
After writing this I decided to spin up a 0.3.0 version using the same run command from above. It also is unable to connect, and the logs show the non-FQDN version of the URL.

Our development environment using the 0.3.0 version is actually running docker compose instead of a docker run command. I'm unsure how this could affect it from accessing the cluster.

I also went into the container and if I use the FQDN version of the URL with ping it is able to see the cluster servers.

**Comment by Haarolean** [comment]
Hi, it does work fine for me:

```
%  docker run -p 8080:8080 -e KAFKA_CLUSTERS_0_NAME=Development -e KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka1.example.com:9092 -d provectuslabs/kafka-ui:master

ESC[30m2023-02-15 13:36:35,390ESC[0;39m ESC[31mWARN ESC[0;39m [ESC[34mparallel-1ESC[0;39m] ESC[33mo.a.k.c.ClientUtilsESC[0;39m: Couldn't resolve server kafka1.example.com:9092 from bootstrap.servers as DNS resolution failed for kafka1.example.com
```

Might be an issue with your environment. I can also recommend trying docker-compose instead.

**Comment by BenBurge** [comment]
> Hi, it does work fine for me:
> 
> ```
> %  docker run -p 8080:8080 -e KAFKA_CLUSTERS_0_NAME=Development -e KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka1.example.com:9092 -d provectuslabs/kafka-ui:master
> 
> ESC[30m2023-02-15 13:36:35,390ESC[0;39m ESC[31mWARN ESC[0;39m [ESC[34mparallel-1ESC[0;39m] ESC[33mo.a.k.c.ClientUtilsESC[0;39m: Couldn't resolve server kafka1.example.com:9092 from bootstrap.servers as DNS resolution failed for kafka1.example.com
> ```
> 
> Might be an issue with your environment. I can also recommend trying docker-compose instead.

I've used the following docker compose with some information redacted. 

![image](https://user-images.githubusercontent.com/13814339/219127448-86bd02d1-ec00-45e8-b656-03ab59d5cc00.png)

![image](https://user-images.githubusercontent.com/13814339/219128174-3467ed30-7f0b-4891-bc1f-5d8b43aa6495.png)



We are using Docker Swarm but again if I enter the container and run the ping with the full domain it works fine.


We are using the newest Kafka version with KRaft instead of zookeeper. Is that perhaps the issue instead of the URL?

**Comment by Haarolean** [comment]
The app works [perfectly fine](https://github.com/provectus/kafka-ui/blob/master/documentation/compose/kafka-ui-arm64.yaml) in kraft mode.

Can you run `echo $KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS` in the container?

**Comment by BenBurge** [comment]
> The app works [perfectly fine](https://github.com/provectus/kafka-ui/blob/master/documentation/compose/kafka-ui-arm64.yaml) in kraft mode.
> 
> Can you run `echo $KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS` in the container?

Of course! I appreciate the the time you've taken so far to help out.

![image](https://user-images.githubusercontent.com/13814339/219405594-8876f31f-74f7-43af-a0be-8302e1213c18.png)

**Comment by Haarolean** [comment]
Please take a look at your kafka' advertised listeners, you might have the wrong hosts there.

**Comment by BenBurge** [comment]
> Please take a look at your kafka' advertised listeners, you might have the wrong hosts there.

I was finally able to get access to the servers. It looks like it doesn't have the FQDN in the addr setting

![image](https://user-images.githubusercontent.com/13814339/221020946-e9517ad0-22a7-4924-895f-f84add550d81.png)

Would this need the FQDN instead of just the host name?

**Comment by Haarolean** [comment]
This should contain the host which can be accessible from inside the container of kafka-ui.

**Comment by BenBurge** [comment]
> This should contain the host which can be accessible from inside the container of kafka-ui.

This completely fixed my issue. We didn't have the DNS servers on the container so using the FQDN on the advertised listeners worked perfectly.

Thank you @Haarolean
