### ISSUE TITLE
Brokers - Configs: No info on hover over source info icon

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#3345]
**Describe the bug** (Actual behavior)
There is no information with hover on Broker source within Configs tab

**Expected behavior**
The info about Broker config source should appear with hover on info icon

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to Brokers
2. Open the Broker
3. Turn to Configs tab
4. Hover on info icon of Source column

**Screenshots**

https://user-images.githubusercontent.com/104780608/218946127-0966982b-6c88-4115-a72e-69bad2366e42.mov

**Comment by David-DB88** [comment]
@Haarolean i requested to check the 
Pull requests

**Comment by David-DB88** [comment]
@Haarolean can by checked by QA
