### ISSUE TITLE
Brokers:  Broker's configs search by key is case-sensitive

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#3346]
**Describe the bug** (Actual behavior)
Search in Broker configs is case-sensitive

**Expected behavior**
Search of Broker's configs should work as in other components and should not be case- sensitive 

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to Brokers
2. Select the Broker
3. Turn to Configs tab
4. Search for config

**Screenshots**

https://user-images.githubusercontent.com/104780608/218951551-e8c528e1-72dc-477a-b474-7d5bd1989e6a.mov

**Comment by RaajuKanuri** [comment]
Hi, Can I work on this issue

**Comment by RaajuKanuri** [comment]
Hi @Haarolean , this issue seems to be front-end issue. Probably we need to change the label. to front-end instead of back-end. I did fix the issue already. I will raise the PR.
