### ISSUE TITLE
When creating a new stream from stream records are not fetched.

### ISSUE THREAD

**Issue by myrulezzz** [provectus/kafka-ui#3378]
I am creating a ksqldb stream from 
Topic and is working fine.However when i am creating a second stream on top of stream is not loading the data on the second stream.I execute the same stream on ksqldb container and is working fine.I have tried to reset offset to earliest but still not able to fetch data in to the second stream even if i set offset to earliest.
My kafka environment has ssl sasl enabled however my ksqldb user is superadmin.

Expected Behaviour:
The second stream to include data.

Reproduce:
1. Create a sample topic test with fields id, name, account
2. create a stream:
create stream teststream (id string, name string, account string) with (KAFKA_TOPIC='test', VALUE_FORMAT='JSON');
select * from teststream should return results of topic.
3. Create stream from previous stream: create stream teststream2 as select * from teststream; It should return the same results.
If you login on the ksqldb-server container and connect to ksqldb with the command ksql you need to set offset to earliest in order to be able to create the second stream and fetch all data from the first stream with the command SET 'auto.offset.reset' = 'earliest';
If you dont specify offset it will create the second stream empty.
I think from the ui something is wrong when setting SET 'auto.offset.reset' = 'earliest';
This parameter is also available in confluent control center ksqldb ui.

Let me know if you need somethinf else @Haarolean

**Comment by Haarolean** [comment]
Hi, please follow the issue template you've chosen (the bug one), which clearly states that we might close the issue if you don't provide the requested information.

**Comment by myrulezzz** [comment]
@Haarolean closing ticket as i just realized the properties at the right side of ksqldb ui. setting the key auto.offset.reset and value earliest fixed the issue
