### ISSUE TITLE
How to connect AWS - MSK (Managed Kafka) ? SSL 

### ISSUE THREAD

**Issue by aswathsaru** [provectus/kafka-ui#338]
How do I connect to my AWS SSL Enabled Managed Kafka? 
I had deployed the docker image in Kubernetes. 

After the successful deployment - the dashboard shows offline cluster only. 

--snippet--
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-web-ui-cm
  namespace: kafka-web-ui
data:
  KAFKA_CLUSTERS_0_NAME: "QA"
  KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "b-1.xyx:9094,b-2.xyc:9094"
  KAFKA_CLUSTERS_0_ZOOKEEPER: "z-1.xyvcom:2181,z-2.xyvcom:2181"
  KAFKA_SECURITY_PROTOCOL: "SSL"
  security.protocol: "SSL"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-web-ui
  namespace: kafka-web-ui
  labels:
    app: kafka-web-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-web-ui
  template:
    metadata:
      labels:
        app: kafka-web-ui
    spec:
      restartPolicy: Always
      containers:
      - name: kafka-web-ui
        image: provectuslabs/kafka-ui:latest
        ports:
          - containerPort: 8080
            protocol: TCP
        envFrom:
          - configMapRef:
              name: kafka-web-ui-cm
        # resources:
        #   requests:
        #     cpu: "10m"
        #     memory: "10Mi"
        #   limits:
        #     cpu: "50m"
        #     memory: "100Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-web-ui-svc
  namespace: kafka-web-ui
  labels:
    app: kafka-web-ui
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
  selector:
    app: kafka-web-ui

**Comment by germanosin** [comment]
Hi, @aswathsaru. Thank you for creating issue.

Configuring SSL is on per cluster level.

```
KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "b-1.xyx:9094,b-2.xyc:9094"
KAFKA_CLUSTERS_0_ZOOKEEPER: "z-1.xyvcom:2181,z-2.xyvcom:2181"
KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: "SSL"
```

Please let us know if it helps you.

**Comment by aswathsaru** [comment]
Awesome Thx. It Worked for me :)
