### ISSUE TITLE
The logout func causes 404

### ISSUE THREAD

**Issue by JiepingLi** [provectus/kafka-ui#3387]
The logout button has some problems with the href attribute, cuz the base path of  the target website has been omitted. It caused 404, just like the image shows:
![image](https://user-images.githubusercontent.com/19572644/220581447-458d4918-6a69-4067-bf6e-5b2c2d553e18.png)

The same problem occurs when I reach the logout confirmation page.

**Comment by Haarolean** [comment]
Hi, thanks for reaching out.

Please follow the issue template. A little bit of attention is needed around the `WE MIGHT CLOSE THE ISSUE without further explanation IF YOU DON'T PROVIDE THIS INFORMATION.` sentence.

**Comment by JiepingLi** [comment]
Describe the bug(Actual behavior)
I have more than one app run in the same server, so I need to change the context path of the Kafka-UI.
But when I changed the configuration "server.servlet.context-path" in the file "application.yml"(you can refer the first page of the screenshots), it worked with the back-end, but not with the front-end. I can't find any way to do the same change with the front-end.
What I have changed caused several problems as below:
1. The CSS stylesheet lost when I open the login page.
2. The logout func navigates to 404 page.

Expected behavior
I can logout without any problem.

Set up

How do you run the app? Please provide as much info as possible.
1. App version: v0.5.0(027d9b4)
2. Helm chart version, if you use one
3. Any IAAC configs



Steps to Reproduce
1. change the "application.yml" configuration, modify the "server.servlet.context-path" into "/kafka_prod"
2. restart the app
3. add the context path when you login the Kafka-UI

Screeshots
![image](https://user-images.githubusercontent.com/19572644/220872294-541626d6-5968-4e48-a9fa-e1ad33b948ab.png)
![image](https://user-images.githubusercontent.com/19572644/220872393-df5b5e9d-0a5e-49eb-b35c-dcc0b6aea8b0.png)
![image](https://user-images.githubusercontent.com/19572644/220872559-89a3e0b3-f044-47a3-91a6-0bffe811ba44.png)
![image](https://user-images.githubusercontent.com/19572644/220872691-b16fef3b-c6f8-41f3-b67d-5b302d48b0b3.png)

**Comment by Haarolean** [comment]
Thanks. Looks like it's been resolved within #3206. 

Considering that you're running a jar file, you have to build one on master since we build jars just for the release versions.
Let me know if you need help building a master jar, or I can do that for you.

**Comment by JiepingLi** [comment]
> 

Thanks for your reply. I'll try to build the project by myself. Btw, what is the java version used in this project ?

**Comment by Haarolean** [comment]
@JiepingLi 17
https://provectus.gitbook.io/kafka-ui/development/building/prerequisites

**Comment by JiepingLi** [comment]
What should I do to change the base path of the project?
I tried to change the env "SERVER_SERVLET_CONTEXT_PATH", it worked at the first step which means I can jump to the logout page correctly, but if I clicked the "Log Out" button at the logout page, it still navigated to 404.
Is there any thing wrong about what I have done to change the base path?
I think maybe I should change the baseUrl of the front-end too, but I'm not really good at React, so I can't find a good way to make it.

**Comment by Haarolean** [comment]
@JiepingLi which version are you on rn? Which type of authentication do yo use? Which URL do you get redirected to?

**Comment by JiepingLi** [comment]
@Haarolean 
Version: v0.5.0(027d9b4)
Type of authentication: LOGIN_FORM
Redirected to URL: http://172.31.36.98:30001/logout
<img width="1396" alt="image" src="https://user-images.githubusercontent.com/19572644/221502049-33bde504-aa8c-4912-83ee-de04594f7ee8.png">

**Comment by Haarolean** [comment]
@JiepingLi I mean it's the same URL in your URL tab, how can it be 404?..

**Comment by JiepingLi** [comment]
@Haarolean 
Sorry for mislead you, I have token the wrong screenshot for this problem.
![image](https://user-images.githubusercontent.com/19572644/223072210-802763dc-308e-423c-a297-64c5fb99735a.png)
When I clicked the Log out button, it navigate to http://172.31.36.98:30001/logout, which cause 404.
And then I added the context path "kafka_shanglv_prod", the final url is "http://172.31.36.98:30001/kafka_shanglv_prod/logout", then it showed the following page:
![image](https://user-images.githubusercontent.com/19572644/223073771-649d4d76-f316-4bdc-848a-fc2a7a2732d7.png)

**Comment by Haarolean** [comment]
Running this compose:
```
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:master
    ports:
      - 8080:8080
    depends_on:
      - kafka0
      - schema-registry0
      - kafka-connect0
    environment:
      // the rest omitted
      AUTH_TYPE: "LOGIN_FORM"
      SPRING_SECURITY_USER_NAME: admin
      SPRING_SECURITY_USER_PASSWORD: pass
      SERVER_SERVLET_CONTEXT_PATH: /kafkaui
```
The logout URL is valid:
<img width="499" alt="image" src="https://user-images.githubusercontent.com/1494347/223079298-b7d63523-444d-4aa1-bbc8-3355193b76f4.png">
