### ISSUE TITLE
Wizard: Submit button not set to active after removing Schema registry, Metrics, KSQL

### ISSUE THREAD

**Issue by BulatKha** [provectus/kafka-ui#3397]
**Describe the bug** (Actual behavior)

'Submit' button is not set active after removal of some components in cluster config wizard, like Schema registry, Metrics, KSQL.
It does set active after removal of 'Kafka Connect' though.

**Expected behavior**

Every change of the cluster configuration should trigger the activation of 'Submit' button.
**Set up**

[dac023e](https://github.com/provectus/kafka-ui/commit/dac023e)
the 'wizard' branch

**Steps to Reproduce**

1. Set up the Kafka UI with a setting 
`DYNAMIC_CONFIG_ENABLED: true`
2. Open dashboard and click 'Configure' for and existing cluster.
3. Remove components e.g. Schema registry, Metrics, KSQL

**Screenshots**

**Additional context**

**Comment by BulatKha** [comment]
Fixed in #3241

**Comment by BulatKha** [comment]
@armenuikafka can you please add the test cases for wizard and this particular one as well?

**Comment by armenuikafka** [comment]
https://app.qase.io/case/KAFKAUI-333 test case is created !
