### ISSUE TITLE
OAuth2: Add filters allowing CORS

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#3401]
https://discord.com/channels/897805035122077716/897805035122077719/1077852545168445440
![Uploading image.png…]()

**Comment by prdpx7** [comment]
Hey! This is still causing issues.
The frontend client is not adding CORS header while initializing google oauth client as you can see in the network tab(in screenshot)

![image](https://github.com/provectus/kafka-ui/assets/10064324/5cacb32b-21df-42f2-820d-5113a6ec04cf)

**Comment by Haarolean** [comment]
@prdpx7 could you please try this image?
`public.ecr.aws/provectus/kafka-ui-custom-build:3957`
Let me know how it goes.

**Comment by prdpx7** [comment]
> @prdpx7 could you please try this image? `public.ecr.aws/provectus/kafka-ui-custom-build:3957` Let me know how it goes.

Hey! The new build is working fine. Appreciate the help 🙏
