### ISSUE TITLE
[Topics] We are using kraft mode now, and when any node is down, kafka-ui will report error and refuse to show topics

### ISSUE THREAD

**Issue by MajorAdam** [provectus/kafka-ui#3416]
**Describe the bug** (Actual behavior)
We are using kraft mode now, and when any node is down, kafka-ui will report error and refuse to show topics

**Expected behavior**
show topics correctly

**Set up**
How do you run the app? Please provide as much info as possible:
1. App version : <provectuslabs/kafka-ui:latest>

**Steps to Reproduce**
1. stop random node

**Screenshots**
![image](https://user-images.githubusercontent.com/14068516/221747836-15ad2840-fedd-4fb8-a54f-527170034815.png)

**Comment by Haarolean** [comment]
Hey, thanks for reporting the issue. We'll take a look.
