### ISSUE TITLE
Wizard: Not able to add a new Connector for online cluster

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#3420]
**Describe the bug** (Actual behavior)
Not possible to add a new Connector for local online cluster

**Expected behavior**
Should be possible to add a new Connector for cluster

**Set up**

- The 'wizard' branch
- DYNAMIC_CONFIG_ENABLED: true (kafka-ui-arm64.yaml)

**Steps to Reproduce**

1. Navigate to Kafka Connect for local online cluster
2. Create Conector
3. Fill Name and Config
4. Press Submit

**Screenshots**

https://user-images.githubusercontent.com/104780608/222047881-41904938-0565-4421-8eac-71e2407143d9.mov

**Additional context**

**Comment by iliax** [comment]
@armenuikafka this is not connected with wizard. By default connect dows not contain Reddit connector installed.
To check behavior:
- edit compose file. Set  `CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components,/usr/local/share/kafka/plugins,/usr/share/filestream-connectors"`
- create connector with config 
```
{
	"connector.class": "org.apache.kafka.connect.file.FileStreamSinkConnector",
	"file": "/tmp/tst.json",
	"topics": "test"
}
```
