### ISSUE TITLE
View broker skew in kafka-ui

### ISSUE THREAD

**Issue by wanisfahmyDE** [provectus/kafka-ui#3427]
Hi there,
is there a way to see if there is a broker skew in kafka ui?

screenshot from conduktor.

<img width="1465" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/51237742/222124221-865dcf40-3a9c-49a4-a60f-60359bde667e.png">

Cheers

**Comment by Haarolean** [comment]
TODO, brokers page:
add:
- partitions count per broker (+skew %)
- leaders count per broker (+skew %)
