### ISSUE TITLE
Topics/Message browser: Unable to display Topic messages when clicking on "Submit" button.

### ISSUE THREAD

**Issue by habuitrago** [provectus/kafka-ui#3458]
**Describe the bug** (Actual behavior)

Using a Kafka cluster provided on a private network using Aiven Kafka via SSL. No Kafka cluster inside the Docker container.

When fetching messages nothing is displayed with the "No messages found".
What I could see in the browser network tab is that while performing a GET call the following error is visible in the browser (Chrome Version 110.0.5481.178 (Official Build) (64-bit))

HTTP Request
Request GET URL: http://localhost:8080/api/clusters/aiven/topics/sltc-uat-inbound-messages/messages?filterQueryType=STRING_CONTAINS&attempt=10&limit=100&page=0&seekDirection=BACKWARD&keySerde=String&valueSerde=String&seekType=LATEST&seekTo=0%3A%3A212%2C1%3A%3A2933

HTTP Response
Type: Eventsource
(failed)net::ERR_INCOMPLETE_CHUNKED_ENCODING

**Expected behavior**
A list of Kafka messages is expected with the different filters functional.

**Set up**

How do you run the app? Please provide as much info as possible:
1. App version: v0.5.0 [027d9b4](https://github.com/provectus/kafka-ui/commit/027d9b4)
2. Aiven kafka server not the container one.
3. SSL setup using a keystore (p12) and JKS trustore

    environment:
      KAFKA_CLUSTERS_0_NAME: aiven
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SSL
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: <aiven_cluster_url>:<aiven_cluster_port>
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_LOCATION: /client.truststore.jks
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_PASSWORD: ****
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_LOCATION: /client.keystore.p12
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_PASSWORD: ****
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: '' # DISABLE COMMON NAME VERIFICATION
    volumes:
      - ./ssl/client.truststore.jks:/client.truststore.jks
      - ./ssl/client.keystore.p12:/client.keystore.p12

-->

**Steps to Reproduce**

**Comment by Haarolean** [comment]
Hi, do you have any anti-virus software installed? If yes, can you try disabling one and trying again? Also, can you try doing that within the browser's incognito mode (+without enabled extensions)?
