### ISSUE TITLE
Topics: Edit settings - Not possible to change "Delete" cleanup policy

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#3465]
**Describe the bug** (Actual behavior)
Not possible to change Cleanup policy from "Delete" to "Compact" and "Compact,Delete"

**Expected behavior**
Should be possible to change Topic's cleanup policy from "Delete" to "Compact" and "Compact,Delete"

**Set up**
https://www.kafka-ui.provectus.io/

https://github.com/provectus/kafka-ui/commit/6313d4c

**Steps to Reproduce**

1. Create a Topic with "Delete" cleanup policy
2. Edit settings
3. Try to change Cleanup policy

**Screenshots**

https://user-images.githubusercontent.com/104780608/223964386-7ece8df4-3c5b-4962-bda0-2863ee7e22b4.mov

**Additional context**

**Comment by Haarolean** [comment]
Outdated as of 0.6.1
