### ISSUE TITLE
Sort consumer groups by messages behind

### ISSUE THREAD

**Issue by yardenshoham** [provectus/kafka-ui#3468]
### Discussed in https://github.com/provectus/kafka-ui/discussions/3467

<div type='discussions-op-text'>

<sup>Originally posted by **yardenshoham** March  9, 2023</sup>
In the UI we can sort by `Group ID`, `Num Of Members` or `State` but not `Num of Topics`, `Messages Behind` nor `Coordinator`.
![image](https://user-images.githubusercontent.com/20454870/224008985-f275e71d-44b6-4234-bb58-e6400ce6d719.png)
</div>

I suppose one would need to add logic here? https://github.com/provectus/kafka-ui/blob/334ba3df99dfc84385faace167f6410c8ce0be91/kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ConsumerGroupService.java#L134-L160

**Comment by yardenshoham** [comment]
@Haarolean can you hint at how this could be achieved? I want to try

**Comment by yardenshoham** [comment]
I opened a PR with @nisanohana3, #3527

**Comment by Haarolean** [comment]
@yardenshoham yep, I've seen it, thanks! Just assigning the issue
