### ISSUE TITLE
[FE] Static resource in asserts directory need cache-control and gzip options

### ISSUE THREAD

**Issue by tiyee** [provectus/kafka-ui#3474]
### Which version of the app are you running?
v0.6.0 (docker env)

### Describe the solution you'd like
It has more performance if set cache-control and gzip options when require static file

**Comment by Haarolean** [comment]
Hi, thanks for reaching out.

You can either:
- use a reverse proxy
or
- set the required spring properties, they're listed [here](https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.web.spring.web.resources.cache.cachecontrol.cache-private) and are prefixed with `spring.web.resources.cache.cachecontrol.*`.
