### ISSUE TITLE
[Oauth] Support configurable claim to show in the UI

### ISSUE THREAD

**Issue by krumft** [provectus/kafka-ui#3491]
Hi there!

I would like to first thank you for creating this great tool, which is indeed quite helpful.

### Which version of the app are you running?

We are deploying the Docker container of the tool `provectuslabs/kafka-ui:latest` in ECS and putting it behind an Okta authentication. For that purpose we are using the Oauth capabilities of the app, discussed [here](https://github.com/provectus/kafka-ui/discussions/3136).

### Is your proposal related to a problem?

This is just an improvement proposal, it is not related to a problem. Thus, it should be treated with low priority.

### Describe the solution you'd like

When getting logged in, using the Oauth login journey the app provides with Okta, what is being shown in the UI is the principal name from the authentication response, which in our case is a random meaningless string `00u1nae2ajxtZBYxE357`: 

<img width="1433" alt="Screenshot 2023-03-13 at 11 57 27" src="https://user-images.githubusercontent.com/120662172/224668754-625eb36a-fa3b-4bb3-8094-7f026d371d1e.png">

Here is an example log showing the full authentication token that the app receives from Okta:

`[30m2023-03-12 09:49:22,563[0;39m [39mDEBUG[0;39m [[34mreactor-http-epoll-2[0;39m] [33mo.s.s.w.s.c.WebSessionServerSecurityContextRepository[0;39m: Found SecurityContext 'SecurityContextImpl [Authentication=OAuth2AuthenticationToken [Principal=Name: [00u1nae2ajxtZBYxE357], Granted Authorities: [[ROLE_USER, SCOPE_email, SCOPE_name, SCOPE_offline_access, SCOPE_openid, SCOPE_profile]], User Attributes: [{at_hash=oB9gR997mj1tAyRUI1qu7g, sub=00u1nae2ajxtZBYxE357, zoneinfo=America/Los_Angeles, ver=1, email_verified=true, amr=[otp, mfa, pwd], iss=<...>, last_name=Bakalsky, preferred_username=krum.bakalsky<...>, locale=BG, given_name=Krum, nonce=kc0xQ38p7JzMsbc7iehzqBKzzbAVv82zF80_gPn_2Ak, aud=[<...>], updated_at=2023-03-10T11:48:42Z, idp=<...>, auth_time=2023-03-12T09:33:59Z, name=Krum Bakalsky, exp=2023-03-12T10:34:00Z, family_name=Bakalsky, first_name=Krum, iat=2023-03-12T09:34:00Z, email=krum.bakalsky<...>, jti=ID.s-GN5eHiWmkfV_aMi-9UfmJu2x3al1egEnlNj-gTat0}], Credentials=[PROTECTED], Authenticated=true, Details=null, Granted Authorities=[ROLE_USER, SCOPE_email, SCOPE_name, SCOPE_offline_access, SCOPE_openid, SCOPE_profile]]]' in WebSession: 'org.springframework.web.server.session.InMemoryWebSessionStore$InMemoryWebSession@624c117c'`

It would be great if the user that has logged in is taken from a different, perhaps configurable, claim from that Oauth response. Perhaps the safest choice would be `email`, but I guess the most flexible solution would be to pull this out as a configurable parameter/environment variable of the app.

For example, the [Oauth support of pgAdmin](https://www.pgadmin.org/docs/pgadmin4/6.21/oauth2.html) offers an environment variable called `OAUTH2_USERNAME_CLAIM` which I believe serves the same (or very similar) purpose.

**Comment by Haarolean** [comment]
Hi, thanks for the kind words :)

This is easily achievable via `user-name-attribute` property.
There are some examples [here](https://docs.kafka-ui.provectus.io/configuration/authentication/oauth2).
Let me know if it helps

**Comment by krumft** [comment]
Hello!

Thank you so much for the quick answer! I just added the `AUTH_OAUTH2_CLIENT_AUTH0_USERNAMEATTRIBUTE=email` environment variable and it worked perfectly!

Apologies for the noise.

Have a lovely week,
Krum.
