### ISSUE TITLE
Release docker image with new releases

### ISSUE THREAD

**Issue by nikobearrr** [provectus/kafka-ui#3507]
Is it possible to push a new version of the docker image https://hub.docker.com/r/provectuslabs/kafka-ui with the new releases? In this case I am looking for the 0.6.0 one.

**Comment by Haarolean** [comment]
Hi, they're published automatically with each release.
<img width="546" alt="image" src="https://user-images.githubusercontent.com/1494347/225591971-03e491f0-6507-40cc-a46d-221b576c4cc8.png">
