### ISSUE TITLE
SEEK ERROR with all partitions selected

### ISSUE THREAD

**Issue by p-eye** [provectus/kafka-ui#3525]
### Which version of the app are you running?

v0.6.0

### Is your proposal related to a problem?

When I seek messages in topic with Offset OR Timestamp, the request is sent without a seekTo paramater.
And I got the error "seekTo should be set if seekType is OFFSET (TIMESTAMP)"

- request without seekTo parameter
![image](https://user-images.githubusercontent.com/50516754/226543127-17cae004-9194-4cb8-8ce9-c4da74876565.png)

- error 
![image](https://user-images.githubusercontent.com/50516754/226543225-d21665fd-2422-47dc-ab9b-a76282406304.png)

### Describe the solution you'd like

This error occurs after the commit https://github.com/provectus/kafka-ui/commit/aeda502b09d1dcf132f825d4b0779972037f74e9 (add a new condition disabling to select all partitions)
So removing the condition is a one way.

### Describe alternatives you've considered

I guess your commit is for blocking long parameters with GET request.
So this is an alternative i suggest after removing above condition.

AS-IS
- seekType: TIMESTAMP
- seekTo: 1::1679324400000,2::1679324400000,3::1679324400000,4::1679324400000,5::1679324400000

TO-BE
- seekType: TIMESTAMP
- seekTo: 1679324400000
- seekPartition: 1,2,3,4,5

### Additional context

if these solutions are ok, can i develop it? 
1. only remove condition
2. remove condition and change seekTo parameter 

I would be grateful for your another suggestion.

Thank you.

**Comment by p-eye** [comment]
@[Haarolean](https://github.com/Haarolean) hi, any review? 
I got https://github.com/provectus/kafka-ui/issues/3115, 
but I think only blocking all-partitions(240/240) is little bit unfair because 239/240 partitions is a still long parameter.

**Comment by Haarolean** [comment]
@p-eye Hi, can you verify it works now with `latest` docker image?

**Comment by vcanuel** [comment]
Hi, as mentioned in https://github.com/provectus/kafka-ui/issues/3568 with 0.6.1 it is working with timestamp but not with offset.

**Comment by p-eye** [comment]
same as [vcanuel](https://github.com/vcanuel)

**Comment by Haarolean** [comment]
@p-eye 
>So this is an alternative i suggest after removing above condition.

We've implemented something like that within messages v2 API (#3537), but, unfortunately, that won't work with pagination because you'll have to apply all the offsets for all the partitions.

**Comment by p-eye** [comment]
@Haarolean
thanks for review, hoping for other ideas 😄

**Comment by Haarolean** [comment]
offset/timestamp filtering fixed within #3568 
for the fix regarding long url follow #3115
