### ISSUE TITLE
Messages: delete from the drop down menu while filtering by offset is not working in Firefox v. 111.0, Windows 10 Pro

### ISSUE THREAD

**Issue by jrpathfinder** [provectus/kafka-ui#3532]
**Actual behavior)**

When select topic, review mesaages of the topic, sort by Newest first and filter messages by offset value 
delete messages from the drop down menu is not working. 
Nothing happens. 
Filtered messages remain in the result list.
Number of messages remains the same.

**Expected behavior**

Messages should be deleted, the result list of messages should be empty.
 
**Set up**

1. OS: Windows 10 Pro 64 bit
2. Browser: FF 111.0 64 bit 

**Steps to Reproduce**

1. Open one of the **Topic**.
3. Go to **Messages**
4. Sort by **Newest First** Enter **offset** filter's value. Hit **submit**.
5. Select **Delete** from the drop down menu of one of the row. Hit **Yes** in pop-up dialog window.
6. Messages are not **deleted**.

**Screenshots**

Please see error message in the **Network** console of the browser.

![Delete_MSGS](https://user-images.githubusercontent.com/2234606/226813833-d9cd0d95-a549-4df1-9bff-ac9ee16272a4.png)

**Additional context**

**Comment by Haarolean** [comment]
Hi, thanks for reaching out.

Please provide the info requested in the bug template: which app version are you using and which type of installation?

**Comment by Haarolean** [comment]
well you're running some fork of the app and deleting messages thing has never existed in the first place
