### ISSUE TITLE
"Copy to clipboard" doesn't work

### ISSUE THREAD

**Issue by c-v-ya** [provectus/kafka-ui#355]
In "Topic/Messages" when pressing on a cog and clicking on "Copy to clipboard" nothing happens.

Also, it would be nice to have the ability to toggle standard message view to a JSON representation. Something like on the screenshot below
![image](https://user-images.githubusercontent.com/11807205/113713765-607c2c00-96f0-11eb-9384-05123bb5a02d.png)

I know there is "save as file" but it's not very convenient. And if "Copy to clipboard" is supposed to copy JSON message, then fixing this issue would be enough for a feature request above.

**Comment by workshur** [comment]
Hi @c-v-ya, thank you for creating this issue. Could you add information about the browser you are using? ✌️

**Comment by c-v-ya** [comment]
Oh, sorry about that. I've tried it in Chrome Version 89.0.4389.114 (Official Build) (64-bit) and Firefox 87.0 (64-bit), both on Arch Linux

**Comment by workshur** [comment]
@c-v-ya We are not able to reproduce the bug. Could you please try to build `kafka-ui` using master image instead of latest and confirm the bug is still reproducible? :v: 
```diff
# docker/kafka-ui.yaml
kafka-ui:
-   image: provectuslabs/kafka-ui:latest
+   image: provectuslabs/kafka-ui:master
```

**Comment by c-v-ya** [comment]
Nope, still not working. Just nothing happens, the clipboard is empty.

But I can see the content as a JSON now. That is great and works best, at least for me. Thanks a lot! So if "copy to clipboard" works on your side then I guess it's just me. Though, I'm not sure why. And I'm okay with closing this issue.
