### ISSUE TITLE
Messages filtering by offset & timestamp doesn't work

### ISSUE THREAD

**Issue by seralyzh** [provectus/kafka-ui#3568]
![1](https://user-images.githubusercontent.com/75166592/228173520-d2fa1a0b-183d-4a4c-aec4-f53396f6ba99.JPG)
![2](https://user-images.githubusercontent.com/75166592/228173528-52b58854-1e51-402f-b0a2-0b5a5fb2a78f.JPG)

when we use all partitions, the filter does not work.
when we use certain partitions, the filter works

**Comment by Haarolean** [comment]
Hi, can you verify that it works now with `latest` tag?

**Comment by vcanuel** [comment]
Hi,

It works now for the timestamp filter now.
But the seek by offset is still broken 
`{"code":4002,"message":"seekTo should be set if seekType is OFFSET....}.`

Also paging does not work : going to next page always returns the same page (got an NS_ERROR_ABORT and then reload) Should I create a new bug for this ?
Thanks.
