### ISSUE TITLE
Dark theme: 404: Text is black

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#3572]
with a dark theme, the text on the 404 page (page not found) is black. Please adapt.

**Comment by Mano-Liaoyan** [comment]
Could you assign this to me? I finished it rn, just need to find how to make a pr that satisfied the rules

**Comment by Mano-Liaoyan** [comment]
Great! I've already published a pr, however, I can not add labels and assign myself to the pr or add reviewers to the pr as the contributing documentation says. Could you help me with that?
