### ISSUE TITLE
Diff overlay of Avro schemas in comparision doesn't display anymore

### ISSUE THREAD

**Issue by fredrikorrje** [provectus/kafka-ui#3590]
**Describe the bug** 
Diff overlay of Avro schemas in comparision doesn't display anymore.

**Expected behavior**
Diff overlay of Avro schema in comparision show changes between versions.

**Set up**
**Steps to Reproduce**

1. Enter a schema registry with avro schemas.
2. Open a avro schema with multiple version of it.
3. Enter comparision and select different versions of the avro schema.

**Additional context**
Introduced in version 0.6.1, works in version 0.6.0.

**Comment by Haarolean** [comment]
Related: #3576

0.5.0:
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/1494347/232004306-ad152297-ed7b-4987-874c-e72d1c164a86.png">
master:
<img width="983" alt="image" src="https://user-images.githubusercontent.com/1494347/232004357-30db3e4d-3e54-46ff-afbe-fb17530c44a4.png">
