### ISSUE TITLE
Kafka-UI is displaying default messages out of order, per the timestamp

### ISSUE THREAD

**Issue by zachgius9** [provectus/kafka-ui#3595]
**Describe the bug** (Actual behavior)
Kafka-UI is displaying messages out of order, per the timestamp.
This behavior can lead a person to misinterpret the results by thinking that the messages at the top (if viewing Newest first) indicates that a message has not arrived in the queue. 

**Expected behavior**
Kafka-UI is displaying messages in chronological order, whether that be (newest/oldest first) per the timestamp

**Set up**
vv0.4.0

**Steps to Reproduce**
1. Open the Kafka-UI
2. In the Dashboard, select 'Topics'
3. Navigate to a Kafka topic
4. Within the selected Kafka topic, navigate to Messages tab
5. Set the filter to 'Newest First' and the messages timestamp should reflect the newest messages first. 
6. With filter applied, incorrect result is shown
7. Refer to screenshot attached
![KafkaUI Issue](https://user-images.githubusercontent.com/88344211/228916377-7ba418a0-d3d9-45ee-a4ee-10a7c5d740d4.JPG)

Thank you. If you need anything else, please let us know.

**Comment by Haarolean** [comment]
Hi, thanks for reaching out.
We're aware (#3382), looking forward to get it fixed in the future.

Please follow the original issue.
