### ISSUE TITLE
Where is the consumer lag resolved?

### ISSUE THREAD

**Issue by sirmspencer** [provectus/kafka-ui#3596]
This API resolves some really helpful information /api/clusters/{clusterName}/topics/{topicName}/consumer-groups.  I would like to insert that into some other projects status checking without going through the web UI.  I tried looking through the code, and I can seem to find where the information is pulled from. 

Can anyone with more more knowledge of the code base point me there?

**Comment by iliax** [comment]
Hello @sirmspencer . Thank you for your interest to the project. 
Code entrypoint that you are looking for is here https://github.com/provectus/kafka-ui/blob/master/kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ConsumerGroupService.java#L66. 

Btw, for such questions - please use `Discussions` next time.

**Comment by sirmspencer** [comment]
Thank you!  Will do next time.
