### ISSUE TITLE
Helm chart version is still 5.0.

### ISSUE THREAD

**Issue by zigbang-yeezy** [provectus/kafka-ui#3598]
**Describe the bug**

**Set up**

❯ `helm search repo kafka-ui`
NAME             	CHART VERSION	APP VERSION	DESCRIPTION
kafka-ui/kafka-ui	0.5.2        	v0.5.0     	A Helm chart for kafka-UI

**Steps to Reproduce**

`helm install kafka-ui kafka-ui/kafka-ui -f ./my-values.yaml --version=0.6.1`
Error: INSTALLATION FAILED: failed to download "kafka-ui/kafka-ui" at version "0.6.1"

**Expected behavior**
artifacthub.I can see has version 0.6.1 but I still can't upload it to version 0.6.1. I hope to upgrade to 0.6.1 version.

**Comment by Haarolean** [comment]
Works for me

```
% helm repo add kafka-ui https://provectus.github.io/kafka-ui
"kafka-ui" has been added to your repositories

% helm install my-kafka-ui kafka-ui/kafka-ui --version 0.6.1
NAME: my-kafka-ui
LAST DEPLOYED: Mon Apr  3 13:18:05 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=kafka-ui,app.kubernetes.io/instance=my-kafka-ui" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace default port-forward $POD_NAME 8080:8080
```

**Comment by zigbang-yeezy** [comment]
After removing the repo, register it again and execute the command, it works. Thank you.

```
% helm repo remove kafka-ui
and then,
% helm repo add kafka-ui https://provectus.github.io/kafka-ui
% helm install my-kafka-ui kafka-ui/kafka-ui --version 0.6.1
```
