### ISSUE TITLE
Active controller badge on invalid node

### ISSUE THREAD

**Issue by iliax** [provectus/kafka-ui#3614]
In `/api/clusters/local/stats` endpoint `activeControllers` **is an id of a node** that is _Active controller_ node. Now green badge is rendered on another node or not even shown sometimes.

Version: master commit [de21721](https://github.com/provectus/kafka-ui/commit/de21721)

<img width="1540" alt="Screenshot 2023-04-03 at 12 24 34" src="https://user-images.githubusercontent.com/702205/229454092-15bbf5f2-6585-473d-bdc3-b6a0be8e7bfe.png">

**Comment by Ksj14-kumar** [comment]
Hi @iliax, can you assign it to me? I want to work on it.

**Comment by iliax** [comment]
@Ksj14-kumar sure, go ahead

**Comment by Haarolean** [comment]
@Ksj14-kumar any updates?

**Comment by Haarolean** [comment]
@Ksj14-kumar any updates?

**Comment by Ksj14-kumar** [comment]
@Haarolean, Can you unassign me this task, I can't  solve it. Sorry for that.

**Comment by Haarolean** [comment]
@Ksj14-kumar no worries
