### ISSUE TITLE
Search filter

### ISSUE THREAD

**Issue by seralyzh** [provectus/kafka-ui#3629]
Hi!
When searching, if we do not select a partition, there is a request without q.
If we select a pair of partitions, then the query will simply be &q=
If after that we change the search again, then everything works correctly
![1](https://user-images.githubusercontent.com/75166592/230385256-e62f5c30-bf0e-4e25-8223-d3dccb4b4529.JPG)

**Comment by Haarolean** [comment]
Hi, please follow the bug issue template
