### ISSUE TITLE
Introduce (continuous?) security / vulnerability scans

### ISSUE THREAD

**Issue by mkielar** [provectus/kafka-ui#3658]
### Which version of the app are you running?
Currently, we run 0.4.0, but version 0.6.1 is also affected by the issue.

### Is your proposal related to a problem?
I'd like to start a discussion on vulnerabilities are being checked and patched in `kafka-ui`, especially the vulnerabilities introduced by Maven Dependencies and Linux Distro used for docker builds.

We're currently using `kafka-ui` in read-only mode, and host it on AWS ECS behind ALB. Our deployment process involves repackaging of the image from DockerHub. We do this for two reasons:
1. To bypass DockerHub quota with AWS ECR
2. To be able to "harden" the image (i.e. install/upgrade Linux Packages to fix their vulnerabilities).

We also use Snyk (https://snyk.io) to scan our re-packaged images for new vulnerabilities. This is part of our CICD pipeline, and we have [snyk-cli](https://docs.snyk.io/snyk-cli) wrapped with some additional logic that makes the pipeline fail if it detects any vulnerability that can be fixed, but was not.

Recently, Snyk introduced scanning of application dependencies within docker images. This caused our pipelines to report _"fixable"_ vulnerabilities in `kafka-ui` Spring / Java dependencies.

`snyk-cli` is open-source, and [Snyk](https://snyk-io) has a free tier. You can run the following command to list the vulnerabilities present in latest `0.6.1` version of the Docker Image available via DockerHub:
```sh
snyk test --docker provectuslabs/kafka-ui:v0.6.1
```
See: [snyk.out.txt](https://github.com/provectus/kafka-ui/files/11208078/snyk.out.txt)

### Describe the solution you'd like
1. Integrate Snyk (or any other security scanning tool) into your build/release process. There's even [snyk-maven-plugin](https://docs.snyk.io/integrations/ci-cd-integrations/maven-plugin-integration) that you could integrate directly into your `pom.xml`, and [Snyk](https://snyk-io) has a free tier, and is [generally free for open-source projects](https://snyk.io/open-source-projects/).
2. Introduce (preferably continuous) rebuilds of published Docker Images with updated versions of Maven Dependencies.

### Describe alternatives you've considered
We're already patching some of the Linux Packages (like `openssl`) using custom `Dockerfile` and `apk`. However, while the _"fixable"_ vulnerabilities in Linux packages can be simply patched (by upgrading them using `apk`, which comes with the Docker Image) while re-packaging the Docker Image, upgrading Spring / Java dependencies inside of already built docker image is much trickier to implement on the _receiving end_. This, I believe, it better suited in build phase of the image. 

We're currently considering following options to handle issues with Java Dependencies reported by Snyk:
1. Upgrade to 0.6.1 (this does not remove the issue, as 0.6.1 also reports some vulnerabilities in Java Dependencies, but there's less of them than in 0.4.0, so they're easier to manage)
2. Configure snyk to (temporarily) ignore vulnerabilities in `kafka-ui` Java Dependencies, and then check again in few weeks / upon next `kafka-ui` release.
3. Disable _application dependency_ checks entirely when running Snyk in our CICD. We'd really prefer to avoid that last option.

### Disclaimer
I am **not** affiliated with Snyk.io in any way. Just think it's a great tool, and suggest it because it has a free tier and special plans for Open-Source Projects like yours.

**Comment by Haarolean** [comment]
Hey, thanks for raising the issue.

I see you've put a lot of effort into describing the problem and solutions. Unfortunately, I have to tell you that we already have such a mechanism set in place.

The workflow is [here](https://github.com/provectus/kafka-ui/actions/workflows/cve.yaml), we have scheduled scans which we periodically check and open the issues to fix (like [this](https://github.com/provectus/kafka-ui/issues/3144), for example), the thing is we don't always have enough bandwidth for these issues (some contain minor/unaffected vulnerabilities, or it requires a lot of effort just to get rid of them).

Let me know if you have any further suggestions or ways to improve this transparency.

**Comment by Haarolean** [comment]
@mkielar 
[Done](https://github.com/provectus/kafka-ui/releases/tag/v0.6.2), also you can always use master-labeled image.
