### ISSUE TITLE
UI: Refactor the toggle component

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#3677]
<img width="213" alt="image" src="https://user-images.githubusercontent.com/1494347/232467567-5c09bd3d-c138-4ed7-bca8-8813e6e25d28.png">
<img width="210" alt="image" src="https://user-images.githubusercontent.com/1494347/232467822-b67ece0a-5c73-4168-8965-209ddd1a5130.png">
The toggle state in the current implementation of the component is hardly distinguishable between "off" and "on".
Implement the new one: https://www.figma.com/file/ZkvysdRUmt9p2PDNU3a9WU/Kafka-UI?node-id=2051-6715&t=nOA9ZBMnJjZxRvZk-0

**Comment by inanc-can** [comment]
Hello @Haarolean 

https://user-images.githubusercontent.com/55583718/234350864-01cfaee5-f812-46aa-8060-9c8c1d874bad.mov

I made the changes according to Figma File. Is this acceptable?

**Comment by Haarolean** [comment]
@inanc-can looks nice, please raise a PR :)
