### ISSUE TITLE
FE: Message content (headers/key/value) selection not visible

### ISSUE THREAD

**Issue by dmaes** [provectus/kafka-ui#3686]
**Describe the bug** (Actual behavior)
When in the Topics > Messages view and expanding a message, when selecting text in the Key/Value/Headers box, you can see the cursor move, and text is selected (confirmed with Ctrl+C, Ctrl+V), but the selected text is not (visibly) highlighted in one way or another.

**Expected behavior**
When selecting text, it should be hightlighted by a blue/grey/... background to show that that text is selected

**Set up**
Version: [b0c367c](https://github.com/provectus/kafka-ui/commit/b0c367c) v0.6.2
Self-build RPM's, which comes down to downloading jar from releases page, adding systemd service, example config and /usr/bin/... wrapper script, after-install script to create user. Config is further managed by puppet.

**Steps to Reproduce**

1. Run the jar with java 17
2. Connect to cluster that contains topics with messages
3. Open a topic, open a message
4. Select text in the message's key/value/header box

**Screenshots**

**Additional context**

This is on our dev setup. Issue is not present in prod setup on v0.4.0. Issue was already present in dev setup on v0.6.1.

This seems similar to #3576

**Comment by p-eye** [comment]
same problem here, only hightlighted when running `pnpm dev` command. 
- not visible with port 8080 (docker-compose or helm install)
- visible with port 3000 (`pnpm dev` with above server)


https://user-images.githubusercontent.com/50516754/232758523-e06dc052-86b0-4404-8df1-ebba73209e3a.mov

**Comment by Haarolean** [comment]
Hi, thanks for raising the issue. This has been fixed in master already.

<img width="547" alt="image" src="https://user-images.githubusercontent.com/1494347/233025270-450767f4-35f3-4230-9369-f4aad620a749.png">
