### ISSUE TITLE
404 on brocker/metrics

### ISSUE THREAD

**Issue by godjil** [provectus/kafka-ui#3701]
`/opt/kafka/bin/kafka-run-class.sh kafka.tools.JmxTool --object-name kafka.server:type=BrokerTopicMetrics,name=MessagesInPerSec --jmx-url service:jmx:rmi:///jndi/rmi://stg-kafka-20.ae-rus.net:9010/jmxrmi
Trying to connect to JMX url: service:jmx:rmi:///jndi/rmi://stg-kafka-20.ae-rus.net:9010/jmxrmi.
"time","kafka.server:type=BrokerTopicMetrics,name=MessagesInPerSec:Count","kafka.server:type=BrokerTopicMetrics,name=MessagesInPerSec:EventType","kafka.server:type=BrokerTopicMetrics,name=MessagesInPerSec:FifteenMinuteRate","kafka.server:type=BrokerTopicMetrics,name=MessagesInPerSec:FiveMinuteRate","kafka.server:type=BrokerTopicMetrics,name=MessagesInPerSec:MeanRate","kafka.server:type=BrokerTopicMetrics,name=MessagesInPerSec:OneMinuteRate","kafka.server:type=BrokerTopicMetrics,name=MessagesInPerSec:RateUnit"
1682153193848,6,messages,0.005804658647543145,0.013305188056659104,0.012880531610742577,0.01562025632583821,SECONDS
1682153195854,6,messages,0.005804658647543145,0.013305188056659104,0.012825315176032272,0.01562025632583821,SECONDS
1682153197849,6,messages,0.005804658647543145,0.013305188056659104,0.012770831672715794,0.01562025632583821,SECONDS`

`2023-04-22 08:42:36,240 INFO  [parallel-1] o.a.k.c.u.AppInfoParser: Kafka version: 3.3.1
2023-04-22 08:42:36,240 INFO  [parallel-1] o.a.k.c.u.AppInfoParser: Kafka commitId: e23c59d00e687ff5
2023-04-22 08:42:36,240 INFO  [parallel-1] o.a.k.c.u.AppInfoParser: Kafka startTimeMs: 1682152956239
2023-04-22 08:42:36,307 DEBUG [parallel-1] c.p.k.u.s.ClustersStatisticsScheduler: Start getting metrics for kafkaCluster: STG
2023-04-22 08:42:36,307 INFO  [parallel-1] o.a.k.c.a.AdminClientConfig: AdminClientConfig values:
	bootstrap.servers = [stg-kafka-11.ae-rus.net:9092, stg-kafka-12.ae-rus.net:9092, stg-kafka-13.ae-rus.net:9092, stg-kafka-14.ae-rus.net:9092, stg-kafka-15.ae-rus.net:9092]
	client.dns.lookup = use_all_dns_ips
	client.id = kafka-ui-admin-1682152956-2
	connections.max.idle.ms = 300000
	default.api.timeout.ms = 60000
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	receive.buffer.bytes = 65536
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 30000
	retries = 2147483647
	retry.backoff.ms = 100
	sasl.client.callback.handler.class = null
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.login.callback.handler.class = null
	sasl.login.class = null
	sasl.login.connect.timeout.ms = null
	sasl.login.read.timeout.ms = null
	sasl.login.refresh.buffer.seconds = 300
	sasl.login.refresh.min.period.seconds = 60
	sasl.login.refresh.window.factor = 0.8
	sasl.login.refresh.window.jitter = 0.05
	sasl.login.retry.backoff.max.ms = 10000
	sasl.login.retry.backoff.ms = 100
	sasl.mechanism = GSSAPI
	sasl.oauthbearer.clock.skew.seconds = 30
	sasl.oauthbearer.expected.audience = null
	sasl.oauthbearer.expected.issuer = null
	sasl.oauthbearer.jwks.endpoint.refresh.ms = 3600000
	sasl.oauthbearer.jwks.endpoint.retry.backoff.max.ms = 10000
	sasl.oauthbearer.jwks.endpoint.retry.backoff.ms = 100
	sasl.oauthbearer.jwks.endpoint.url = null
	sasl.oauthbearer.scope.claim.name = scope
	sasl.oauthbearer.sub.claim.name = sub
	sasl.oauthbearer.token.endpoint.url = null
	security.protocol = PLAINTEXT
	security.providers = null
	send.buffer.bytes = 131072
	socket.connection.setup.timeout.max.ms = 30000
	socket.connection.setup.timeout.ms = 10000
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.3]
	ssl.endpoint.identification.algorithm = https
	ssl.engine.factory.class = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.certificate.chain = null
	ssl.keystore.key = null
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLSv1.3
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.certificates = null
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS`

`2023-04-22 08:48:28,458 DEBUG [boundedElastic-6] c.p.k.u.s.m.JmxMetricsRetriever: 15786 metrics collected for service:jmx:rmi:///jndi/rmi://stg-kafka-20.ae-rus.net:9010/jmxrmi`

<img width="293" alt="Screenshot 2023-04-22 at 11 51 19" src="https://user-images.githubusercontent.com/4816332/233774013-90c2b85e-01ae-4f2f-b813-841deaa4775e.png">

**Comment by Haarolean** [comment]
https://github.com/provectus/kafka-ui/blob/master/.github/ISSUE_TEMPLATE/bug_report.md?plain=1#L12
