### ISSUE TITLE
Blank web page appears when I tried to access the home page of kafka-ui

### ISSUE THREAD

**Issue by superkaiy** [provectus/kafka-ui#3712]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

When I deployed the kafka-ui with docker image, I found that I could not access the home page. It will show a blank page.
I inspected via browser, and I found that it will try to fetch some js.files and configuration files through Internet. But my develop environment is without Internet. So could you help to release docker images including these depend files

### Your installation details

NA

### Steps to reproduce

NA

**Comment by Haarolean** [comment]
<img width="642" alt="image" src="https://user-images.githubusercontent.com/1494347/234465085-13630947-62cb-4c6c-a4ed-a6309a2d825d.png">
<img width="374" alt="image" src="https://user-images.githubusercontent.com/1494347/234465118-db84658c-d73c-4e5d-a330-37bac8e36d4e.png">
