### ISSUE TITLE
Web page seems to be abnormal when I tried to access the home page of kafka-ui without Internet connection

### ISSUE THREAD

**Issue by superkaiy** [provectus/kafka-ui#3717]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [ ] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

1. deploy kafka-ui via docker image
2. disconnect to Internet
3. enter into web page
4. web page seems to be abnormal
![Screenshot from 2023-04-26 18-08-21](https://user-images.githubusercontent.com/45934483/234544029-8873e76b-240c-49b7-b6f1-87e4bb28d682.png)

### Expected behavior

web page can be like as following picture even without Internet connection
![Screenshot from 2023-04-26 18-00-57](https://user-images.githubusercontent.com/45934483/234543284-b900c850-29a0-4b81-aeb2-955c284a8f67.png)

### Your installation details

the attachment is my docker file, and my command is : docker-compose up -d
[docker-compose_bak_yml.txt](https://github.com/provectus/kafka-ui/files/11331583/docker-compose_bak_yml.txt)

### Steps to reproduce

1. deploy kafka-ui with docker-compose
2. disconnect to Internet
3. try to access the web page

**Comment by superkaiy** [comment]
@Haarolean  Can you help to review it?
I inspect on the browser. And I find that it will try to fetch resources(https://api.github.com/repos/provectus/kafka-ui/releases/latest & https://fonts.googleapis.com/css2?family=Inter:wght@400;500&family=Roboto+Mono:wght@400;500&display=swap)

**Comment by Haarolean** [comment]
@superkaiy hey, both are fixed within #2728 and #2753. Can you try `    image: provectuslabs/kafka-ui:master`?

**Comment by vliska** [comment]
Just encountered the same issue. It seems fixed if I use provectuslabs/kafka-ui:master.
