### ISSUE TITLE
RBAC: KC: Impl restart permissions

### ISSUE THREAD

**Issue by fl0wx** [provectus/kafka-ui#3720]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md) and the feature is not present there

### Describe the feature you're interested in

I do want a new permission for connector / connector task restarts. As i deploy and manage connectors via strimzi, i dont want the frontend user to edit or remove the tasks. But in case of an issue / tests it would be helpful if tasks could be restarted via UI with a separate permission.

### Version you're running

0.6.2

**Comment by Haarolean** [comment]
Forgot frontend lol

**Comment by Haarolean** [comment]
@David-DB88 

TODO:
Change RBAC permissions: For `ResourceType.CONNECT` all restart actions should have `Action.RESTART` instead of `Action.EDIT`
