### ISSUE TITLE
`q` is initiated when other parameters are changed

### ISSUE THREAD

**Issue by p-eye** [provectus/kafka-ui#3722]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

bug: 
Query paramter `q` is initiated when other parameters are changed (for example page, seekDirection, seekType...)
So I have to retype the value to correct a result.

cf)
i'm sorry for my carelessness. i found [the contributing guide](https://docs.kafka-ui.provectus.io/development/contributing) later, and my PR was rash.
so i'm going to start over.

thank you for your teams consideration on this issue !

### Expected behavior

1. searching parameter `q` is updated and saved when typing it
2. updated `q` exists when other parameters are changed.

### Your installation details

App version: [601bd6b](https://github.com/provectus/kafka-ui/commit/601bd6b) and v0.6.2

### Steps to reproduce

https://user-images.githubusercontent.com/50516754/234600998-84da24cc-e2dd-48d3-b4f5-e646c95b5b7c.mov

**Comment by Haarolean** [comment]
All messages-related bugs and issues are to be fixed within #3504 -- a rework of messages API.
