### ISSUE TITLE
Consumers: replace empty row with consumer lag with "N/A"

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#3728]
also in per consumer view
<img width="1099" alt="image" src="https://github.com/provectus/kafka-ui/assets/1494347/0cb6a7c3-ab38-4c18-a7d6-7558570e6c2d">

**Comment by shraddha761** [comment]
Hye 
please give some about the issue

**Comment by Haarolean** [comment]
@shraddha761 we need to replace empty cells with "N/A"
<img width="1099" alt="image" src="https://github.com/provectus/kafka-ui/assets/1494347/1403a0d8-16c6-4017-8146-eb7338761b74">

**Comment by shraddha761** [comment]
I am unable to find where to do changes.

**Comment by nilling4** [comment]
Hi, could I work on this?

**Comment by nilling4** [comment]
@Haarolean Hi, I'm trying to setup my environment for windows but there's no instructions for windows on this page, could you help? https://docs.kafka-ui.provectus.io/development/building/prerequisites

**Comment by Haarolean** [comment]
@nilling4 you can use WSL
