### ISSUE TITLE
v0.6.2 - oauth scope bug 

### ISSUE THREAD

**Issue by koorlan** [provectus/kafka-ui#3744]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [ ] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

While upgrading from 0.6.1 (ran without error) to 0.6.2 i faced a problem after oauth2 authentication, asked scope seems not transiting righlty to context because it says missing fields

After switching to v0.6.2

<img width="957" alt="image" src="https://user-images.githubusercontent.com/3740701/234866380-e43a6044-7ee0-41e5-8168-d4a31ee06468.png">

corresponding compose part of oauth conf :
<img width="312" alt="image" src="https://user-images.githubusercontent.com/3740701/234867301-3c11e4e6-b87a-427e-99e1-2c3ddd8a9cd5.png">

Hope it help your teams and thanks for keep updating kafka ui , it's very powerful and easy to use :)

Korlan.

 

### Your installation details

[ef0dacb](https://github.com/provectus/kafka-ui/commit/ef0dacb)

### Steps to reproduce

working oauth2 conf on v0.6.1 and update to v0.6.2 and try to authenticate again

**Comment by Haarolean** [comment]
Hi, thanks for reaching out.

That's not a bug, but rather a configuration issue. It says the `email` field is not present in your OAuth2 response. Had the same issue when cognito decided to rename the attribute.
