### ISSUE TITLE
Topic message filter is displayed but not applied

### ISSUE THREAD

**Issue by michal-cesek** [provectus/kafka-ui#3745]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

The active message filter component is displayed but no filtering is applied to the topic message list

### Expected behavior

The filter is applied to the topic message list

### Your installation details

1. b0c367c - v0.6.2

### Steps to reproduce

**1.** Set up the filter by using the "Add filters" functionality

![filter](https://user-images.githubusercontent.com/2612817/234866765-50adf24c-bd12-4f59-9a9b-1479a619d4d0.png)

![ok](https://user-images.githubusercontent.com/2612817/234863606-9e6fcf2e-121a-443b-9b2c-14518fe3aeb7.png)

**2.** Leave the "Messages" view. E.g. click on the "Brokers" link from the left panel

**3.** Return to the view from the first step

**RESULT:** The filter is not applied and the unexpected topic message is shown

![notok](https://user-images.githubusercontent.com/2612817/234864596-f827732d-d877-40b0-8328-d72a8b673824.png)

**Comment by iliax** [comment]
Hello @michal-cesek 
thank you for raising this!

Currently we assume that `value` is a json (obj/string/integer). If value is not valid json ( like string `123notajson` ) we set it to null. So, there can be 2 cases then `value` is null in filter: 
- kafka-record's value is null 
- kafka-record's value can't be represented as json after deserialization 

This is why you see false-positive filters. 

We will discuss it internally and think how to fix this. For now, you can use `valueAsText` variable in filter that will be null only if kafka-record's value is null.

**Comment by michal-cesek** [comment]
@iliax thank you for taking care of this. In addition, I wanted to point out that there is inconsistency in the UI. The second screenshot shows an active filter and the search box input filled with the code -> Ok. The third screenshot shows the same active filter, but the search box is not prefilled -> Not Ok / Confusing

![screenshot](https://user-images.githubusercontent.com/2612817/236838774-027c6452-2ff7-48fe-94b6-31dedb55e1cc.png)

cc @Haarolean

**Comment by Haarolean** [comment]
@michal-cesek we have a huge messages view refactoring planned -- #3504
