### ISSUE TITLE
Version 0.6.2 breaks our Okta integration

### ISSUE THREAD

**Issue by krumft** [provectus/kafka-ui#3765]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

We are consuming the application via its Docker containers and putting it behind a corporate Okta tenant. Upgrading it to the latest version - `0.6.2` - broke our Okta integration. I have just tested back with `0.6.1` and this version seems to be working fine.

### Your installation details

We are pulling the Docker image of the app from Docker hub.

### Steps to reproduce

The Okta SSO login journey for version `0.6.2` ends with an Okta 404 error screen and a message stating that the redirect uri is invalid.

### Logs

I am not finding anything suspicious in the application logs.

### Additional context

We are using the same environment variables for the app when testing with both versions:
```
KAFKA_CLUSTERS_0_NAME=<our cluster name>
KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=<our Kafka brokers>
AUTH_OAUTH2_CLIENT_AUTH0_CLIENTID=<id>
AUTH_OAUTH2_CLIENT_AUTH0_CLIENTSECRET=<secret>
AUTH_TYPE=OAUTH2
AUTH_OAUTH2_CLIENT_AUTH0_SCOPE=openid,email,name,offline_access,profile
AUTH_OAUTH2_CLIENT_AUTH0_ISSUER_URI=<corporate Okta URI>
AUTH_OAUTH2_CLIENT_AUTH0_PROVIDER=okta
AUTH_OAUTH2_CLIENT_AUTH0_USERNAMEATTRIBUTE=email
SERVER_FORWARDHEADERSSTRATEGY=native
DYNAMIC_CONFIG_ENABLED=true
```

On Okta level the redirect URI is configured as follows:
```
"<host>/login/oauth2/code/auth0"
```

**Comment by Haarolean** [comment]
Hi, can you try this [thing](https://docs.kafka-ui.provectus.io/faq/common-problems#urls-are-invalid-contain-ports-when-behind-a-reverse-proxy)? 
`server.forward-headers-strategy=FRAMEWORK`

**Comment by krumft** [comment]
Hello, thank you so much for this suggestion.

I confirm that this has solved the problem! You can close the issue :)

**Comment by vikas-falconx** [comment]
i am getting 400 BAD Request on my app. Any idea why?

**Comment by Haarolean** [comment]
@vikas-falconx please don't hijack unrelated issues. Raise a discussion or better reach out on discord, the invite link is availble in the readme.

**Comment by edeno1** [comment]
@krumft hey Can you explain me how you solved the problem I can't apply okta to kafka-ui

**Comment by krumft** [comment]
@edeno1 Apologies for the very late reply! What are exactly the issues you are facing with integrating KafkaUI with Okta?

**Comment by krumft** [comment]
Our setup targets MSK clusters, and is put behind load balancers because KafkaUI is actually deployed as an ECS service. We are using following environment variables:
```
KAFKA_CLUSTERS_0_NAME=<value>
KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=<MSKBrokers>
AUTH_OAUTH2_CLIENT_AUTH0_CLIENTID=<clientId>
AUTH_OAUTH2_CLIENT_AUTH0_CLIENTSECRET=<clientSecret>
AUTH_TYPE=OAUTH2
AUTH_OAUTH2_CLIENT_AUTH0_SCOPE=openid,email,name,offline_access,profile
AUTH_OAUTH2_CLIENT_AUTH0_ISSUER_URI=<YourCompanysOktaURI>
AUTH_OAUTH2_CLIENT_AUTH0_PROVIDER=okta
AUTH_OAUTH2_CLIENT_AUTH0_USERNAMEATTRIBUTE=email
DYNAMIC_CONFIG_ENABLED=true
server.forward-headers-strategy=FRAMEWORK
```
