### ISSUE TITLE
Enable HTTPS 

### ISSUE THREAD

**Issue by elade9977** [provectus/kafka-ui#3770]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md) and the feature is not present there

### Is your proposal related to a problem?

Unable to Run the UI with https and domain

### Describe the feature you're interested in

A way to run the UI with https and a domain in docker container

### Version you're running

v0.6.2

**Comment by Haarolean** [comment]
Hi, take a look at [this](https://github.com/provectus/kafka-ui/issues/479#issuecomment-1001041589)
