### ISSUE TITLE
Messages are not visible in the KafkaUI on some Kafka topics, when messages should be present

### ISSUE THREAD

**Issue by zachgius9** [provectus/kafka-ui#3772]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

The main issue that we are facing, is that after we are getting a success log on a message being published, on a given Kafka topic, in theKafka UI, we are not seeing the message there, nor any messages.

Furthermore- on random topics, some messages are visible, and others are not. The behavior is very sporadic across all environments within the UI. 

### Expected behavior

After we receive a success log on a message being published, on a given Kafka topic, in theKafka UI, we should see the message there, and the rest of the messages.

### Your installation details

Current commit- (
[521ba0c](https://github.com/provectus/kafka-ui/commit/521ba0c)
)

Version- vv0.4.0

### Steps to reproduce

https://user-images.githubusercontent.com/88344211/236013348-02dd2199-c927-4fd3-9ba7-a1a718c19ad4.mp4

### Logs

![Message issue](https://user-images.githubusercontent.com/88344211/236013832-66924254-a8e9-45c1-8bac-f67d5d0e28ed.png)
![Kafka ui message issue in UI](https://user-images.githubusercontent.com/88344211/236013848-ab329439-a503-47cc-b60b-8564542177e2.png)

**Comment by iliax** [comment]
Hello @zachgius9, thank you for providing full context. 

While polling messages, kui uses couple of properties that controls polling behaviour. By default we assume that kui is installed in the same DC as kafka cluster and latencies are quite low. However for various reasons (different DC installation, slow cluster/network, etc) that settings need to be overriden. 

[Here](https://github.com/provectus/kafka-ui/issues/3485#issuecomment-1489898841) I described what polling-related properties we have and what are defaults. 

For your case you can also try to increase values - that should help. 
as an example, you can set
```
KAFKA_POLLING_POLLTIMEOUTMS = 2000
KAFKA_POLLING_PARTITIONPOLLTIMEOUT = 500
KAFKA_POLLING_NODATAEMPTYPOLLS = 4
```
please try and provide feedback - we will really appreciate it!
