### ISSUE TITLE
 Message key deserialization issue since upgrading Kafka-ui versions across all environments

### ISSUE THREAD

**Issue by zachgius9** [provectus/kafka-ui#3792]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

We are seeing a  message key deserialization issue since upgrading Kafka-ui versions, across all environments, on all topics. 

### Expected behavior

 Message key should deserialize when opening a topic.

### Steps to reproduce

1. Open Kafka UI
2. Select a topic with messages on it
3. You will see the message key is not deserialized, and when clicking on the actual message key, it still shows the special chars.

**Comment by Haarolean** [comment]
Hi, 

when you expand the message, which serdes are displayed there?

Also, have you tried different serdes (key serde, value serde fields)?

**Comment by immutablesemaphore** [comment]
First off, I just want to thank everyone involved in this wonderful project!!!

@zachgius9 and I work together. Adding the following for context. Hope this helps.

- We recently upgraded from v0.4.0 to v0.6.2
    - Prior to the upgrade keys and values were able to deserialize
- The schema registry is configured and schemas are visible when on the "Schema Registry" tab.
- Both the Key and Value Serdes are listed as `SchemaRegistry`, see screenshot below
- We are using the Confluent Schema Registry
- We are using Confluent's [schema contexts](https://docs.confluent.io/platform/current/schema-registry/schema-linking-cp.html#using-a-base-context-path), e.g. `https://psrc-id.region.provider.confluent.cloud/contexts/.my-context` as the REST URL in the config
- Keys seem to be having issues, but values deserialize without a problem
- It is possible that we missed something when upgrading the config for Kafka-UI. We are seeing some messages in the bootup logs (attached)

Thank you!!!

![image](https://github.com/provectus/kafka-ui/assets/90645466/eb303a1b-9216-43c4-9b6f-f4321f5151e9)

[kafka-ui-66966458db-h2gtb.log](https://github.com/provectus/kafka-ui/files/11442722/kafka-ui-66966458db-h2gtb.log)

**Comment by immutablesemaphore** [comment]
After some additional research, here are the findings

- The previous info is not fully accurate as the instance of Kafka-UI was passing through a proxy
- Kafka-UI fails to list schemas when on the "Schema Registry" tab when using a Schema Registy URI containing a Confluent Schema Context
    - example Schema Registry URI with a schema context `https://psrc-id.region.provider.confluent.cloud/contexts/.my-context`
- Kafka-UI fails to deserialize keys when using a Schema Registry URI containing a Confluent Schema Context
    - example Schema Registry URI with **NO** schema context `https://psrc-id.region.provider.confluent.cloud`
- Kafka-UI has no issues when using a Confluent Schema Registry URI with **NO** schema context
- This seems like a parsing issue for the URL due to schema contexts containing the following characters, `/.:`
- It is desirable that Kafka-UI support schema context URI's so that a user's view is limited to only schemas within a particular context rather than schemas in all contexts

Hope this helps clarify the root issue. Kafka-UI does not correctly support Schema Registry URI's using a Confluent Schema Context.

Thank you!

**Comment by iliax** [comment]
@immutablesemaphore thank you for deep investigation, we will take a look and provide fix soon!

**Comment by iliax** [comment]
@immutablesemaphore we discussed your issue internally - we will provide contexts support with UI in next versions.

For now we suggest you
1. Set schemaRegistry url to default context to see all subjects in UI table
2. For each context configure separate serde like this:
```
      kafka.clusters.0.serde.0.name: SchemaRegistry (ctx 1)
      kafka.clusters.0.serde.0.className: com.provectus.kafka.ui.serdes.builtin.sr.SchemaRegistrySerde
      kafka.clusters.0.serde.0.properties.url: http://schema-registry0:8085/contexts/.myctx1

      kafka.clusters.0.serde.1.name: SchemaRegistry (cxt 2)
      kafka.clusters.0.serde.1.className: com.provectus.kafka.ui.serdes.builtin.sr.SchemaRegistrySerde
      kafka.clusters.0.serde.1.properties.url: http://schema-registry0:8085/contexts/.myctx2
```
for other serdes configs you can check [serialization configuration doc](https://app.gitbook.com/o/K1556JopX8z7AJFlXE6V/s/2CXuRaPQ1tzsM1sIg2wn/configuration/serialization-serde)

**Comment by immutablesemaphore** [comment]
@iliax Thank you!
