### ISSUE TITLE
Okta Doesnt work on version 0.6.2 works fine on 0.6.1

### ISSUE THREAD

**Issue by tejavegesna** [provectus/kafka-ui#3796]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

Redirect URI
https://example.com:80/login/oauth2/code/okta

### Expected behavior

Redirect URI should be 
https://example.com/login/oauth2/code/okta

### Your installation details

[b0c367c](https://github.com/provectus/kafka-ui/commit/b0c367c) v0.6.2

    "AUTH_TYPE": "OAUTH2",
    "AUTH_OAUTH2_CLIENT_OKTA_CLIENTID": "12ey9dsahd0931u4ey0sa",
    "AUTH_OAUTH2_CLIENT_OKTA_CLIENTSECRET": "123sdajh0231409uas",
    "AUTH_OAUTH2_CLIENT_OKTA_SCOPE": "openid,email,profile",
    "AUTH_OAUTH2_CLIENT_OKTA_PROVIDER": "okta",
    "SERVER_FORWARDHEADERSSTRATEGY": "native",
    "AUTH_OAUTH2_CLIENT_OKTA_ISSUER_URI": "https://example.okta.com/oauth2/asd890213hh0oasd",
    "AUTH_OAUTH2_CLIENT_OKTA_REDIRECT_URI": "https://example.okta.com/oauth2/r8fewhnakojcasd",
    "DYNAMIC_CONFIG_ENABLED": "true"
    
### Steps to reproduce

Use version 0.6.2 instead of 0.6.1

### Additional context

 Reverting to 0.6.1 fixed this issue

**Comment by Haarolean** [comment]
[Literally the first result with a search "okta"](https://github.com/provectus/kafka-ui/issues/3765)
