### ISSUE TITLE
set up validation connection between backend and frontend

### ISSUE THREAD

**Issue by Gataniel** [provectus/kafka-ui#38]
case: When u create a topic with an existing name, there will be response with error from backend, but front will freeze, and will not show any error

expected: backend errors must be represented in UI

**Comment by Haarolean** [comment]
Seems like this has been fixed.
![image](https://user-images.githubusercontent.com/1494347/135851116-037b8a4c-aa3b-4f9a-a24c-a60121702ef2.png)
