### ISSUE TITLE
LDAP: Unexpected config param names changes

### ISSUE THREAD

**Issue by pawellrus** [provectus/kafka-ui#3830]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

When I try to authenicate via LDAP, I got an error "Invalid Credentials"
There is a message in debug log about unablement to bind any DN for user.

### Expected behavior

Succesfull authentication.

### Your installation details

Version is 0.7.0 (fdd9ad9)
Application is running in k8s with my costom manifests.

### Steps to reproduce

Run application with these environment variables config:

```
            - name: AUTH_TYPE
              value: "LDAP"
            - name: SPRING_LDAP_URLS
              value: "ldap://url:389"              
            - name: SPRING_LDAP_USERFILTER_SEARCHBASE
              value: "ou=people,dc=company,dc=com"
            - name: SPRING_LDAP_USERFILTER_SEARCHFILTER
              value: "(&(uid={0})(objectClass=inetOrgPerson))"
            - name: SPRING_LDAP_ADMINUSER
              value: "uid=admin,ou=people,dc=company,dc=com"
            - name: SPRING_LDAP_ADMINPASSWORD
              value: "${ADMIN_LDAP_PASSWORD}"   

```

### Additional context

This config works well in version 0.6.2 but not with 0.7.0.

**Comment by sm-shevchenko** [comment]
@pawellrus please see my comment on other issue and probably You will resolve Your LDAP issue - https://github.com/provectus/kafka-ui/issues/3803#issuecomment-1547498508

**Comment by pawellrus** [comment]
> @pawellrus please see my comment on other issue and probably You will resolve Your LDAP issue - [#3803 (comment)](https://github.com/provectus/kafka-ui/issues/3803#issuecomment-1547498508)


Thank you. Uou were right.
Changing variables name resolved the issue.

```
SPRING_LDAP_USERFILTER_SEARCHBASE -> SPRING_LDAP_USER_FILTER_SEARCH_BASE
SPRING_LDAP_USERFILTER_SEARCHFILTER -> SPRING_LDAP_USER_FILTER_SEARCH_FILTER
SPRING_LDAP_ADMINUSER -> SPRING_LDAP_ADMIN_USER
SPRING_LDAP_ADMINPASSWORD -> SPRING_LDAP_ADMIN_PASSWORD
```

**Comment by Haarolean** [comment]
https://docs.kafka-ui.provectus.io/configuration/authentication/ldap-active-directory
Current settings here
env vars are, well, flaky, and sometimes spring's [relaxed binding](https://github.com/spring-projects/spring-boot/wiki/Relaxed-Binding-2.0) could be lost.
