### ISSUE TITLE
Kafka-UI homepage redirects to 404(hosted in K8S with Istio) 

### ISSUE THREAD

**Issue by Sumanth-A** [provectus/kafka-ui#3837]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

The app is deployed in K8S and almost everything works as expected. Only when we initially hit the URL https://example.com/kafka-ui it is redirecting to https://example.com/404

<img width="1119" alt="image" src="https://github.com/provectus/kafka-ui/assets/133888604/dd1545e8-7250-4224-bf44-193e304dd445">

But after I click on back to dashboard button, everything else is normal.

### Expected behavior

App is not expected to redirect to https://example.com/404

### Your installation details

Using version 0.7.0
Using istio

 - name: "KAFKA_CLUSTERS_0_NAME"
   value: "dev"
 - name: "KAFKA_CLUSTERS_0_SCHEMAREGISTRY"
   value: "https://example.confluent.cloud"
 - name: "KAFKA_CLUSTERS_0_SCHEMAREGISTRYAUTH_USERNAME"
   value: "user"
 - name: "KAFKA_CLUSTERS_0_SCHEMAREGISTRYAUTH_PASSWORD"
   value: "pass"     
 - name: "KAFKA_CLUSTERS_0_READONLY"
   value: "true"
 - name: "KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS"
   value: "example.confluent.cloud:9092"
 - name: "KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL"
   value: "SASL_SSL"
 - name: "KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM"
   value: "PLAIN"    
 - name: "KAFKA_CLUSTERS_0_PROPERTIES_CLIENT_DNS_LOOKUP"
   value: "use_all_dns_ips"
 - name: "KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG"
   value: "org.apache.kafka.common.security.plain.PlainLoginModule required username='user' password='pass';"
 - name: "KAFKA_CLUSTERS_0_DISABLELOGDIRSCOLLECTION"
   value: "true"      

### Steps to reproduce

Install the app using Helm in AKS. Add default routes in Istio virtual service for it to start working, open the browser and type host/service-name to access the UI of the app where it reports 404.

### Screenshots

<img width="1112" alt="image" src="https://github.com/provectus/kafka-ui/assets/133888604/81fd0781-cf31-43f5-9d67-c569cf00ddbd">

**Comment by Haarolean** [comment]
Hi, you're missing `SERVER_SERVLET_CONTEXT_PATH` property. Set it to `/kafka-ui`.

**Comment by Haarolean** [comment]
@Sumanth-A the app doesn't restart "itself" randomly. That's an issue with your infra, again. Take a look at your healthiness and readiness probes.

**Comment by Sumanth-A** [comment]
@Haarolean, I fixed the probes and app is running. But it still reports 404, this happens only on homepage when we open the UI for the first time. All other functionality works just fine.

**Comment by Haarolean** [comment]
@Sumanth-A means that you're accessing some invalid URI within react-app, like `https://master.internal.kafka-ui.provectus.io/ui/test`, which will show 404 within react. Unfortunately, I can't help further since it's your infra, but we had multiple users running with custom context path, even in k8s and w/ helm, I haven't heard about such a problem.

With our [reverse-proxy docker-compose example](https://github.com/provectus/kafka-ui/blob/master/documentation/compose/kafka-ui-reverse-proxy.yaml) it works fine without any weird 404s.
`http://localhost:8080/kafka-ui`
