### ISSUE TITLE
RBAC : Github Organizations could be more than 30

### ISSUE THREAD

**Issue by seono** [provectus/kafka-ui#3852]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md) and the feature is not present there

### Is your proposal related to a problem?

I think organizations for authenticated user can be more than 30.

https://github.com/provectus/kafka-ui/blob/ab9d0e2b3f6fc54344ecb1912d974f139020ca48/kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/rbac/extractor/GithubAuthorityExtractor.java#L84-L94

https://docs.github.com/en/enterprise-server@3.6/rest/orgs/orgs#list-organizations-for-the-authenticated-user
It response only 30 organizations if you request without `per_page` parameter.

So, if i use 31st organization for rbac it will not work.

### Describe the feature you're interested in

I want RBAC with `oauth_github` provider and `organization` type works even if there are more than 30 organizations for authenticated user.

### Version you're running

902f11a

**Comment by Haarolean** [comment]
Hi, has this happened to you?

With over ten years of using github I don't remember encountering a single user with over than 15 organizations, that's half of 30.

Unless there are users affected by this already, this is a low priority issue.

**Comment by seono** [comment]
@Haarolean thanks for reply.

I agree with you that a single user has under 15 organizations in github.
It happened to me in my company's github enterprise.

So if you don't mind, can i try this issue? I want fix this myself.
