### ISSUE TITLE
Allow selection of IsolationLevel ReadCommitted or ReadUncommitted

### ISSUE THREAD

**Issue by Brunni** [provectus/kafka-ui#3859]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md) and the feature is not present there

### Is your proposal related to a problem?

I wanted to understand how transactions in Kafka work, but this Kafka-UI also shows uncommitted messages (aborted transactions).

### Describe the feature you're interested in

A switch would be nice, so I can decide if I also want to see uncomitted messages or not.

### Version you're running

fdd9ad9

**Comment by iliax** [comment]
Hello @Brunni, kafka-ui uses default isolation level (which is read_uncommitted). To alter this setting you can edit "properties" which kafka-ui uses when connecting to cluster. 
ex.
```
KAFKA_CLUSTERS_0_PROPERTIES_ISOLATION_LEVEL: "read_committed"
```
