### ISSUE TITLE
UI is unusable without internet access even for localhost

### ISSUE THREAD

**Issue by uaeink** [provectus/kafka-ui#3865]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [x] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

1. deploy kafka-ui via docker image
2. disconnect Internet
3. enter into web page
4. web page Empty
<img width="1728" alt="Screenshot 2023-05-25 at 9 02 32 AM" src="https://github.com/provectus/kafka-ui/assets/134577692/4dbf4019-91df-46c1-86c3-e69a489d51b7">

### Expected behavior

web page working fine with Internet connection

<img width="1728" alt="Screenshot 2023-05-25 at 9 04 50 AM" src="https://github.com/provectus/kafka-ui/assets/134577692/a5de8d27-006b-4985-a714-1ee91377fb63">

### Your installation details

[docker-compose.yml.txt](https://github.com/provectus/kafka-ui/files/11561295/docker-compose.yml.txt)
garen node server.properties
[server.properties.txt](https://github.com/provectus/kafka-ui/files/11561312/server.properties.txt)
leesin node server.properties
[server.properties.txt](https://github.com/provectus/kafka-ui/files/11561316/server.properties.txt)
zookeeper.properties
[zookeeper.properties.txt](https://github.com/provectus/kafka-ui/files/11562024/zookeeper.properties.txt)

### Steps to reproduce

    1. deploy kafka-ui with docker-compose
    2. disconnect from Internet
    3. try to access the web page

**Comment by uaeink** [comment]
@Haarolean Can you help to review it?
I inspect on the browser. And I find that it will try to fetch resources(https://api.github.com/repos/provectus/kafka-ui/releases/latest & https://fonts.googleapis.com/css2?family=Inter:wght@400;500&family=Roboto+Mono:wght@400;500&display=swap)

**Comment by Haarolean** [comment]
@uaeink please share the output from `http://localhost:8080/api/info` endpoint

**Comment by Haarolean** [comment]
@uaeink the actual problem's scope is bigger here: you won't see any clusters available without internet access (even if it's localhost, yes). We'll take a look into this.
