### ISSUE TITLE
The 'all-topics' view does not display according to the RBAC filter

### ISSUE THREAD

**Issue by javihernanp** [provectus/kafka-ui#3872]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

I was working with RBAC to filter permissions by topics, and the issue I'm facing is that in the "all-topics" URI, unlike with schemas or other tabs, it doesn't display the filtered topic unless I search for them in the search bar.

### Expected behavior

It should display, like in the rest of the tabs, only the topics that comply with the RBAC configuration.

### Your installation details

1 - 7.0 version
2 - Im not using it
3 - This is the RBAC that I'm using

resource: topic
        value: "dev.*"
        actions: all

### Steps to reproduce

Simply modify the configuration file in the topic permissions section to allow access only to specific topics.

### Screenshots

![image](https://github.com/provectus/kafka-ui/assets/60904917/eee159da-cbd5-45a5-8cd6-6ecd9a7cb8c3)
![image](https://github.com/provectus/kafka-ui/assets/60904917/2ec68880-8d26-44ec-9886-00f8cb82e275)

### Additional context

1 - I have tried all the methods listed in the documentation to define permissions on a topic

**Comment by Haarolean** [comment]
Hey, it seems to be working for me:
```yaml
        - resource: topic
          value: "dev.*"
          actions: all
```

<img width="940" alt="image" src="https://github.com/provectus/kafka-ui/assets/1494347/84eb9b78-665e-47d4-824c-4800d2624f41">

Please provide your full config and responses for `/api/authorization` and `/api/clusters/local/topics` requests, could be found in network tab within browser's dev console.

**Comment by Haarolean** [comment]
@javihernanp 

>I would like to ask if you are using the release 0.7
Even better, master branch.

Which cluster stores the topic in question? Your screenshots are cropped, no way to determine that.
Is that the same cluster that returns `topics: []`?

**Comment by javihernanp** [comment]
Hello,

Indeed, the cluster I obtain for topic[] is the same as the one I have configured, namely "NON_PROD_AWS_EU-WEST-3". I have continued testing, and it works correctly with a Confluent Cloud Basic cluster. However, if I configure a Confluent Cloud Dedicated cluster, such as "NON_PROD_AWS_EU-WEST-3", it doesn't work correctly. I have checked the Service Accounts I am using, and they have the same permissions in both types of clusters.

**Comment by javihernanp** [comment]
Hello,

Do you have these topics available if RBAC is disabled (no roles specified in config)?

 -  Yes

Are there any cluster/topic authorization errors in logs? 

 - I could not see configuring different levels of logs, nothing related to authorization errors

Kind regards

**Comment by Haarolean** [comment]
@javihernanp please try running this image:
`public.ecr.aws/provectus/kafka-ui-custom-build:3914`
with the following config property:
`logging.level.com.provectus.kafka.ui.service.rbac=TRACE`
Open the topic list page, also try searching by the topic name as you did, and extract the logs after that.

**Comment by javihernanp** [comment]
Hello @Haarolean,

I have been testing by modifying the log level as you indicated, and I have used that version, but I still haven't been able to see anything different in the console output. Would it be possible to have a quick meeting to explain in detail the issue and the different tests we have been conducting?

Kind regards

**Comment by Haarolean** [comment]
@javihernanp Sure, let's talk. Got discord? The invite link [here](https://discord.gg/4DWzD7pGE5).

**Comment by dmalik16** [comment]
@Haarolean, we have seen the same/similar behavior, but can add a bit more context.  In our case, we RBAC topic filter on "a.*" and "B.*" as a test.  What happens is we still see 39 pages of topics as if there was no RBAC topic filter but most pages are blank.  Topics "B.*" show up on page #1 and topics "a.*" show up on pages 10-11.  So sorted by case and the filter just prevents the topics from showing on the page were it would be.  If you do try to add a non-allowed topic name to the URL directly, you do get a 403.

**Comment by javihernanp** [comment]
Hello @Haarolean,

I'm sorry, but at that time I was already disconnected and couldn't see that you sent me a link. I have been testing what @dmalik16 mentioned in the previous comment, and indeed, that is the cause of the error. I have been testing it, and it does show up on the original pages as if all the topics were displayed, just as explained. Since we already know the origin of the issue, I believe it is no longer necessary to have a call to further investigate the issue. Please let me know if you need more information. I would like to know an estimated time for the resolution of the issue., and thank you very much for the support and work done so far.

Best regards.

**Comment by Haarolean** [comment]
@javihernanp @dmalik16 could you please try this docker image and tell me if you experience any problems now?
`image: public.ecr.aws/provectus/kafka-ui-custom-build:3946`

**Comment by dmalik16** [comment]
@Haarolean, we pulled that image down and tested it out.  It now displays as expected.  In our case the filtered topics appeared over 2 pages total as if they were the only topics.
Thanks!

**Comment by javihernanp** [comment]
Hello @Haarolean ,

I have tested the changes, and now it is working correctly with the applied RBAC configuration. Thank you very much for resolving the issue promptly. I was wondering if these changes will be included in the main branch in the next patch. If so, could you please let me know the estimated release date for that patch? Once again, I would like to express my appreciation for the work done and the speed at which it was resolved.

Best regards.
