### ISSUE TITLE
Consumer lag - view by partition

### ISSUE THREAD

**Issue by joelpavlovsky** [provectus/kafka-ui#3913]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md) and the feature is not present there

### Is your proposal related to a problem?

Today we can only see the consumer lag per topic, and we need the option to see the consumer lag per partition

### Describe the feature you're interested in

We want  to see the consumer lag per partition in the

Today the view is:
 "Consumers" section --> consumer group list 
--> select "consumer-group-example" --> topic list --> view messages behind/lag per topic

Future view:
 "Consumers" section --> consumer group list 
--> select "consumer-group-example" --> topic list --> see the messages behind per topic --> select "topic-example" --> view the messages behind/lag per partition in the current topic

### Version you're running

0.7

**Comment by Haarolean** [comment]
As @korjek stated, this thing is already available in the UI.
