### ISSUE TITLE
Always show at least 2 or 3 digits for broker disk usage

### ISSUE THREAD

**Issue by jonaslb** [provectus/kafka-ui#3959]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md) and the feature is not present there

### Is your proposal related to a problem?

We have some brokers with storage in the "a few TB" range. My challenge is that disk usage says "1 TB" or "2 TB" on the broker overview (note: even for smaller brokers in the "a few GB" range, I guess the problem would be the same). This is not very informative, so in practice I have to look elsewhere (on the server, or other monitoring tools) to determine the actual (more precise) disk usage.

### Describe the feature you're interested in

I'd like for the disk usage overview in the UI to always show 2 or 3 digits. E.g. if usage is between 1 and 10 GB (or TB), a decimal number with 1 or 2 decimals should be shown instead of an integer. (and if choosing 3 digits, also between 10 and 100 units). 

Ie:

- Instead of "1 GB" show "1.4 GB" (or "1.43 GB")
- Optionally instead of "11 GB" show "11.3 GB" (if choosing 3 digits)

### Describe alternatives you've considered

Looking in other monitoring tools / ssh on server and `df`

### Version you're running

fdd9ad9

**Comment by Haarolean** [comment]
Hey, thanks for the suggestion!
