### ISSUE TITLE
Catch 500 code error when LDAP return many items

### ISSUE THREAD

**Issue by waitspring** [provectus/kafka-ui#3960]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md) and the feature is not present there

### Is your proposal related to a problem?

When we use LDAP in Kafka-UI, we have to make sure our `user-filter-search-filter` just only return on user item. If we write a simple rule like `user-filter-search-filter: "(objectClass=inetOrgPerson)"`, Kafka-UI get many users item and return 500 error code directly. This 500 code gives us a lot of trouble.

### Describe the feature you're interested in

If Kafka-UI get many users item from LDAP, please return a warning string in UI, like ___"Your user-filter-search-filter is not precision so that we find many users from LDAP."___ That's better than return 500 code.

### Describe alternatives you've considered

Look for spring ldap code find answers.
And thanks @Haarolean for his help!

### Version you're running

fdd9ad9

### Additional context

No response.

**Comment by Haarolean** [comment]
That's pretty obvious that LDAP queries should return just one entity in case of authenticating.
Different configuration issues could generate you 500s, that doesn't mean we should wrap all of them to make things even more obvious.
