### ISSUE TITLE
Helm install commands do not work; missing charts folder

### ISSUE THREAD

**Issue by abhinavkulkarni** [provectus/kafka-ui#3968]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

Hi,

The `helm install` command with custom `values.yaml` no longer works. I notice that the `charts` folder has been removed after past few commits.

```bash
$ helm repo add kafka-ui https://provectus.github.io/kafka-ui-charts
"kafka-ui" already exists with the same configuration, skipping

$ helm install kafka-ui charts/kafka-ui -f values.yml
Error: INSTALLATION FAILED: failed to download "charts/kafka-ui"
```

Thanks!

### Your installation details

Latest commit

### Steps to reproduce

Commands are noted above

**Comment by agungardiyanta** [comment]
I got the same error when trying to install the charts previously this command works 
`helm repo add kafka-ui https://provectus.github.io/kafka-ui-charts`
`helm install kafka-ui kafka-ui/kafka-ui -f /kafka/kafka-ui.yaml`
`Error: INSTALLATION FAILED: failed to fetch https://provectus.github.io/kafka-ui/kafka-ui-0.7.0.tgz : 404 Not Found`

**Comment by Haarolean** [comment]
Charts have been moved to this repo: https://provectus.github.io/kafka-ui-charts
the according documentation has been updated right after. If there are any outdated links, please let us know.
