### ISSUE TITLE
FE: Logout button link is bound to a wrong div

### ISSUE THREAD

**Issue by jadhavnitind** [provectus/kafka-ui#4016]
### Issue submitter TODO list

- [x] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

When I tried to logout from Kafka UI that was not working but latter on I realized that the the logout button doesn't work. Only the word written as logout works (hyperlink).
I have attached screenshot out signout button and highlighted section which works.
Also when signed out it askes "Are you sure you want to log out?" that doesn't make sense. I wanted signout that is why I have clicked on signout.

### Expected behavior

The entire button should work for logout

### Your installation details

App version: [56fa824](https://github.com/provectus/kafka-ui/commit/56fa824) v0.7.1
Helm chart version, v0.7.1
Your application config. Please remove the sensitive info like passwords or API keys.
{REDACTED}

### Steps to reproduce

Just install Kafka UI app.

### Screenshots

![image](https://github.com/provectus/kafka-ui/assets/17820833/adf60bfa-5f75-4a95-b5a5-90e086eb3ae8)

**Comment by abhisheksharma886** [comment]
Hello, I would like to work on this, can it be assigned to me

**Comment by Haarolean** [comment]
@abhisheksharma886 hi, it's already assigned, sorry. Feel free to pick any other issue
