### ISSUE TITLE
How can you manage users on the interface?

### ISSUE THREAD

**Issue by diyorbekrustamjonov** [provectus/kafka-ui#4046]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md) and the feature is not present there

### Is your proposal related to a problem?

Now I have to create several users and restrict access for them in the UI of other services! Now I can not such a feature has not found yet!

### Describe the feature you're interested in

Like if there could be such a thing at the entrance asked login and password about the user and then skipped and they could be attached to the role to so see was like say the company has 3 admins they have access for all services but other users only view the topics have access!

### Describe alternatives you've considered

The service confluent-cc has such a thing user management at login asks for username and password, and can we implement this thing for this project kafka-ui?

### Version you're running

latest in docker

**Comment by papirosko** [comment]
You can manage users with oauth2. We are mapping user roles to OKTA groups. Works very well

**Comment by Haarolean** [comment]
Hi,

editing RBAC within UI is planned within #3073.
Creating several users within the app is not possible, we support login form with a single user, otherwise you have to use OAuth/LDAP.
Let me know if you have any other questions.
