### ISSUE TITLE
Query metrics for messages viewer

### ISSUE THREAD

**Issue by patrickpang** [provectus/kafka-ui#4052]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md) and the feature is not present there

### Is your proposal related to a problem?

The messages viewer is genuinely powerful. However, we would like to find a way to monitor the query latency and understand the usage pattern. This will help monitor the additional traffic on our Kafka clusters. Given that a new consumer is created for each query, we think this would be important for us to keep an eye on how many queries are executed, which topics are the most popular, etc.

### Add more metrics

On each query for messages, we should record metrics of number of messages queried (counter), total time taken (counter). This is inspired by `http.server.requests` provided out of the box by Spring Boot. In terms of metrics API, we can leverage the Micrometer registry built-in for Spring Boot apps. Tags can be topic names to allow more granular analysis on topic level.

### Add Prometheus as metrics export interface

Spring Boot 3 has native integration with Prometheus to allow us export metrics at `/actuator/prometheus`, which allows us to collect and visualize metrics via Prometheus. This is useful for creating dashboard and track historical trends. 

Ref: https://docs.spring.io/spring-boot/docs/current/actuator-api/htmlsingle/#prometheus

### Log scraping

Log does provide some metrics of topic queried, and number of messages queried. However, it is not efficient to scrape log, extract keywords, and analyze every time.

### Actuator metrics endpoint

Spring Boot provides `/actuator/metrics` to quickly check what metrics are available. However, this is only useful for ad-hoc analysis. Long term metrics storage is not possible.

### Version you're running

56fa824

**Comment by iliax** [comment]
Hello @patrickpang. Thank you for your proposal. 

It sounds good to expose messages querying metrics. But from what you wrote it sounds like you need some traffic contol settings like `maxConsumersCount` or smth like this. (btw, now we have `pollingThrottleRate` setting per cluster).

Please provide list of metrics (with potential tags) that seem reasonable for you.

**Comment by patrickpang** [comment]
Oh thanks @iliax for the pointers. Yes traffic control is one aspect of this, and `pollingThrottleRate` is definitely interesting. Do we have doc about it yet? 

The other aspect is understanding query patterns - either for reporting or auditing. Inspired by `http.server.requests`, I would suggest below metrics:

`messages.polling.seconds`: timer {topic, outcome="SUCCESS" / "CLIENT_ERROR" / "SERVER_ERROR" }
`messages.polling.records`: counter {topic, outcome="SUCCESS" / "CLIENT_ERROR" / "SERVER_ERROR" }

Thank you!

**Comment by iliax** [comment]
@patrickpang 
1. here is link [to poll throttle setting doc](https://docs.kafka-ui.provectus.io/configuration/misc-configuration-properties). 
2. I think we can also add max consumers per cluster property
3. we already have [Audit functionality merged](https://github.com/provectus/kafka-ui/pull/3831) into master (for now we will just write audit records into kafka itself). It will be release in 0.8. But there is no info about how many records were queried (what topic was queried only)
