### ISSUE TITLE
Disk space full - DiskSpaceHealthIndicator: Free disk space at path '/xxx/xxx/.' below threshold

### ISSUE THREAD

**Issue by kalavt** [provectus/kafka-ui#4053]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

`
2023-07-16 21:45:50,085 WARN  [boundedElastic-190] o.s.b.a.s.DiskSpaceHealthIndicator: Free disk space at path '/xxx/xxx/.' below threshold. Available: 8179712 bytes (threshold: 10485760B)
`

### Expected behavior

customizable data folder

### Your installation details

0.7.0

### Steps to reproduce

run application long time without reboot.

### Screenshots

<img width="1475" alt="image" src="https://github.com/provectus/kafka-ui/assets/443311/27c8b327-7057-47fc-9460-424d7c947bff">

### Logs

`
2023-07-16 21:45:50,085 WARN  [boundedElastic-190] o.s.b.a.s.DiskSpaceHealthIndicator: Free disk space at path '/xxx/xxx/.' below threshold. Available: 8179712 bytes (threshold: 10485760B)
`

### Additional context

No

**Comment by iliax** [comment]
Hello @kalavt, thank you for raising it. 

Just to clarify - do you run kui in docker? If so, base directory should be root and it seems reasonable for me to have such alerts for that.

**Comment by kalavt** [comment]
I'm running it in k8s cluster with only specified kafka cluster and serde of protobuf

**Comment by Haarolean** [comment]
@kalavt hi, what's the path of `/xxx/xxx/`? There's no point in redacting path name as it's inside the docker container unles you've done a volume mount.
