### ISSUE TITLE
[bug] Messages tab not showing keys and headers

### ISSUE THREAD

**Issue by akamensky** [provectus/kafka-ui#407]
I consider this a bug, because Key is important part of the message and should be visible in "Messages" tab.

Same is for Headers, which can contain useful information. Those should also be displayed.

Both currently not accessible via this UI.

**Comment by Haarolean** [comment]
Hi Alexey, thanks for reporting the issue.
As far as I understand both `key` and `headers` are present in the current version.
![image](https://user-images.githubusercontent.com/1494347/135850588-56090a9d-1360-457c-9497-31b4c14cc9ad.png)
Let us know if there are any problems with that.
