### ISSUE TITLE
Investigate dateTimeHelpers.spec.ts linter error

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#4087]
@Haarolean i think we need to open an issue to investigate [dateTimeHelpers.spec.ts](https://github.com/provectus/kafka-ui/pull/3969/files#diff-3944835013941011f6e5cc58d818815553b691f0a67c3149561451253f90f5c9) linter error.

_Originally posted by @Mgrdich in https://github.com/provectus/kafka-ui/issues/3969#issuecomment-1663830373_

**Comment by techpordentro** [comment]
Hello, is this still open? Can I help with something?

**Comment by Haarolean** [comment]
@techpordentro we already have a PR for this (#4090), thank you though! Feel free to pick any other issue from up for grabs board.
