### ISSUE TITLE
Filtering large topics is extremely slow

### ISSUE THREAD

**Issue by andreaippo** [provectus/kafka-ui#4107]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md) and the feature is not present there

### Is your proposal related to a problem?

Filtering large topics is extremely slow

### Describe the feature you're interested in

I have a topic with lots of messages (tens of millions, don't ask... LOL )
I have noticed that filtering is extremely slow when compared against Offset Explorer.
Maybe it's because OE allows to specify how many messages you want to fetch (e.g. newest/oldest 1k).
For some kind of analysis (e.g. duplicate search) you don't need a thorough search that yields ALL the messages, it could be enough to have a search performed on the last X messages.

So I guess that what I'm asking is, could we have a way to limit the scope of a search to the oldest (or newest) n (user-defined) messages of a topic?

Thanks

### Version you're running

56fa824 v0.7.1

**Comment by andreaippo** [comment]
Screenshot from OE:

![image](https://github.com/provectus/kafka-ui/assets/801070/a8cae762-d6c2-4556-85c0-011d5b81067d)

**Comment by Haarolean** [comment]
@andreaippo can you take a look at the master-tagged image? Does it improve there?

**Comment by andreaippo** [comment]
> @andreaippo can you take a look at the master-tagged image? Does it improve there?

Hi! Yes, thanks, it's considerably better!

For reference it took 48secs to Offset Explorer to do that search, with a limit on the newest 10k messages per partition (with 9 partitions on my topic that means 90k messages read, I suppose).

On kafka-ui it took also 48-49secs to complete the search, but it returned MORE results when compared to OE.

I think that OE forcing you to choose the amount of messages per partition beforehand will actually limit the scope of the search, which also means not seeing matching results. I like kafka-ui's approach better, since as far as I understand it will scan the full contents of all partitions for the selected topic.

Could you please confirm if that is the case? Since I don't see any option to specify the amount of messages to fetch (see previous screenshot from OE asking for Max Messages (per partition).

That would clearly make kafka-ui the superior choice :)

Meanwhile thanks for your reply :)

**Comment by Haarolean** [comment]
Yes, we do not have a straight-obvious limit like in other tools, rather we have a pagination (which is currently broken, to be solved within #3504). We've considered getting rid of pagination in favor of a fetch limit, which actually does make sense, it's not like you'd need to scroll through 500+ messages within one search, but that's another story.

Regarding the modes, no, it's not just ordering, it affects the search as well, oldest meaning we're gonna scan the topic from the oldest offsets to newest and vice versa for "newest first".
These modes on the right side are actually tied to the modes on the left, in v2 it's gonna look like this:
<img width="517" alt="image" src="https://github.com/provectus/kafka-ui/assets/1494347/ee7d937a-af6d-461d-adcf-97c27f28b800">

**Comment by andreaippo** [comment]
> Yes, we do not have a straight-obvious limit like in other tools, rather we have a pagination (which is currently broken, to be solved within #3504). We've considered getting rid of pagination in favor of a fetch limit, which actually does make sense, it's not like you'd need to scroll through 500+ messages within one search, but that's another story.
> 
> Regarding the modes, no, it's not just ordering, it affects the search as well, oldest meaning we're gonna scan the topic from the oldest offsets to newest and vice versa for "newest first". These modes on the right side are actually tied to the modes on the left, in v2 it's gonna look like this: <img alt="image" width="517" src="https://user-images.githubusercontent.com/1494347/266989290-ee7d937a-af6d-461d-adcf-97c27f28b800.png">

Ok thanks a lot, it's clear!
