### ISSUE TITLE
Logout returning 404

### ISSUE THREAD

**Issue by dev-pasa** [provectus/kafka-ui#4127]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

The logout button returns a 404.

uri + /auth?logout seems to work but not uri + /logout

logoutSuccessHandler.setLogoutSuccessUrl(URI.create(LOGOUT_URL));

  public static final String LOGIN_URL = "/auth";
  public static final String LOGOUT_URL = "/auth?logout";

UserInfo.tsx to reflect /auth?logout

      <DropdownItem href={`${window.basePath}/logout`}>
        <S.LogoutLink>Log out</S.LogoutLink>
      </DropdownItem>
    </Dropdown>
  ) : null;

### Expected behavior

uri + /logout should logout the user

### Your installation details

version: 0.7.1 (latest)

### Steps to reproduce

logout user after dropdown logout button is clicked under user

### Logs

org.springframework.web.server.ResponseStatusException: 404 NOT_FOUND
org.springframework.web.reactive.resource.ResourceWebHandler.lambda$handle$1(ResourceWebHandler.java:406)
Suppressed: The stacktrace has been enhanced by Reactor, refer to additional information below: 
Error has been observed at the following site(s):
com.provectus.kafka.ui.config.CorsGlobalConfiguration$$Lambda$1016/0x000000801637118 [DefaultWebFilterChain]
com.provectus.kafka.ui.config.CustomWebFilter [DefaultWebFilterChain]
com.provectus.kafka.ui.config.ReadOnlyModeFilter [DefaultWebFilterChain]
AuthorizationWebFilter [DefaultWebFilterChain]
ExceptionTranslationWebFilter [DefaultWebFilterChain]
LogoutWebFilter [DefaultWebFilterChain]
ServerRequestCacheWebFilter [DefaultWebFilterChain]
SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
AuthenticationWebFilter [DefaultWebFilterChain]
ReactorContextWebFilter [DefaultWebFilterChain]
HttpHeaderWriterWebFilter [DefaultWebFilterChain]
ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFlterChain]
org.springframework.web.filter.reactive.ServerHttpObservationFilter [DefultWebFilterChain]
HTTP GET "/logout" [ExceptionHandlingWebHandler]
Original Stack Trace:
org.springframework.web.reactive.resource.ResourceWebHandler.lambda$handle$1(ResourceWebHandler.java:406)
reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
reactor.core.publisher.Mono.subscribe(Mono.java:4485)
reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:82)
reactor.core.publisher.MonoFlatMap$FlatMapMain.onComplete(MonoFlatMap.java:189)
reactor.core.publisher.MonoNext$NextSubscriber.onComplete(MonoNext.java:102)
reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onComplete(FluxConcatMapNoPrefetch.java:240)
reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:357)
reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:294)

### Additional context

The previous version worked for logout, but not version: 0.7.1 (latest)

**Comment by dev-pasa** [comment]
Please look into AbstractAuthSecurityConfig.java?

  protected static final String[] AUTH_WHITELIST = {
      "/css/**",
      "/js/**",
      "/media/**",
      "/resources/**",
      "/actuator/health/**",
      "/actuator/info",
      "/actuator/prometheus",
      "/auth",
      "/login",
      "/logout",
      "/oauth2/**",
      "/static/**"
  };

}

**Comment by Haarolean** [comment]
Hi, please provide your config leaving out authentication secrets

**Comment by dev-pasa** [comment]
kafka:
  clusters:
    - name: VM-SandBox
      bootstrapServers: *****.com:9092
      zookeeper: *****.com:2181
      schemaRegistry: http://*****:8080
      ksqldbServer: http://localhost:8088
      kafkaConnect:
        - name: first
          address: http://*****:8440
      metrics:
        port: 9997
        type: JMX
    - name: VM-PreProd
      bootstrapServers: ****:9093
      properties:
        security.protocol: SSL
        ssl.keystore.location: ${SSL_KEYSTORE_LOCATION}
        ssl.keystore.password: ${SSL_KEYSTORE_PASSWORD}
        ssl.truststore.location: ${SSL_TRUSTSTORE_LOCATION}
        ssl.truststore.password: ${SSL_TRUSTSTORE_PASSWORD}
        ssl.key.password: ${SSL_KEY_PASSWORD}
      zookeeper: *****.com:2181
      schemaRegistry: http://*****:8080
      ksqldbServer: http://localhost:8088
      kafkaConnect:
        - name: first
          address: *****:8443
          keystoreLocation: ${SSL_KEYSTORE_LOCATION}
          keystorePassword: ${SSL_KEYSTORE_PASSWORD}
      metrics:
        port: 9997
        type: JMX
    - name: VM-Prod
      bootstrapServers: *****:9093
      properties:
        security.protocol: SSL
        ssl.keystore.location: ${SSL_KEYSTORE_LOCATION}
        ssl.keystore.password: ${SSL_KEYSTORE_PASSWORD}
        ssl.truststore.location: ${SSL_TRUSTSTORE_LOCATION}
        ssl.truststore.password: ${SSL_TRUSTSTORE_PASSWORD}
        ssl.key.password: ${SSL_KEY_PASSWORD}
      zookeeper: *****:2181
      schemaRegistry: http://******:8080
      ksqldbServer: http://localhost:8088
      kafkaConnect:
        - name: first
          address: https://*******:8443
          keystoreLocation: ${SSL_KEYSTORE_LOCATION}
          keystorePassword: ${SSL_KEYSTORE_PASSWORD}
      metrics:
        port: 9997
        type: JMX

  #    -
  #      name: prod
  #      bootstrapServers: localhost:9093
  #      zookeeper: localhost:2182
  #      schemaRegistry: http://localhost:18085
  #      kafkaConnect:
  #        - name: first
  #          address: http://localhost:8083
  #      metrics:
  #        port: 9998
  #        type: JMX
  #      read-only: true
  #    -
  #      name: localUsingProtobufFile
  #      bootstrapServers: localhost:9092
  #      protobufFile: messages.proto
  #      protobufMessageName: GenericMessage
  #      protobufMessageNameByTopic:
  #        input-topic: InputMessage
  #        output-topic: OutputMessage

dynamic:
  config:
    enabled: true
    
spring:
  jmx:
    enabled: true
  security:
    user:
      name: admin
      password: ${SECURITY_USER_PASSWORD}
#spring:
#  ldap:
#    urls: "ldap://*****"
#    dn:
#      pattern: "OU=people,O=***.com"
#    adminUser: "admin"
#    adminPassword: "admin"
#auth:
#  type: "LDAP"

auth:
  type: "LOGIN_FORM"

server:
  port: 8080 #- Port in which kafka-ui will run.

**Comment by Haarolean** [comment]
@dev-pasa thank you, fixed

**Comment by dev-pasa** [comment]
@Haarolean Thanks a lot
