### ISSUE TITLE
UI remove topic in dropdown menu hidden

### ISSUE THREAD

**Issue by ludex15** [provectus/kafka-ui#4152]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

Cannot remove topic from Topics menu because button is hidden. If I scroll fast enough, I can barely see it.
<img width="301" alt="bug" src="https://github.com/provectus/kafka-ui/assets/50924873/603a5b15-10c4-4338-b9ce-6da98fac460a">

### Expected behavior

To be able to delete topics from main topics menu.

### Your installation details

kafkaui v0.7.1.jar and Java jdk-17.0.2

### Steps to reproduce

Just cannot delete from topics menu, only from topic page alone.

### Screenshots

<img width="301" alt="bug" src="https://github.com/provectus/kafka-ui/assets/50924873/603a5b15-10c4-4338-b9ce-6da98fac460a">

### Additional context

If table has enough rows, you can see remove topic button
<img width="226" alt="ok" src="https://github.com/provectus/kafka-ui/assets/50924873/f830fbf2-6805-48a5-b8df-66c760320d94">

Tested in Chrome and Edge

**Comment by Haarolean** [comment]
Hi, this has been fixed in #3896. I guess I'll cherry-pick this into the upcoming 0.7.2. Thanks!
