### ISSUE TITLE
Allow different trust stores for schema-registry/connect/ksqldb

### ISSUE THREAD

**Issue by yoniwg** [provectus/kafka-ui#4154]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md) and the feature is not present there

### Is your proposal related to a problem?

Now you can only have one trust store for all kafka components, assigned through:
`KAFKA_CLUSTERS_0_SSL_TRUSTSTORELOCATION` and `KAFKA_CLUSTERS_0_SSL_TRUSTSTOREPASSWORD`
This does not work when you have separate trust store for each service

### Describe the feature you're interested in

Adding TRUSTORE_LOCATION and TRUSTSTORE_PASSWORD properties for each service separately.

### Version you're running

56fa824

**Comment by Haarolean** [comment]
Hi, this kind of migration was the whole point of not having a truststore per each service.
You have to create one truststore and put all of your certificates in it.

**Comment by yoniwg** [comment]
Hi @Haarolean, 
Thanks for the fast response.
It is not always possible when you get your truststore from an external provider which produce the truststore for you and do it for every service separately (In my case Strimzi operators).

If I want to use Kafka-UI as part of the K8S cluster, instead of simply refer to the generated secrets of each service, I need to extract the certificate for each service and to create a new truststore then pass it to the cluster as a new secret.

**Comment by Haarolean** [comment]
Unfortunately, we can't possibly support all the possible scenarios users might encounter. We've already placed a bet on the behavior I've described above -- one truststore per cluster. You'll have to put all the certs into one truststore, sorry.
