### ISSUE TITLE
Avro logical type decimal not shown correctly in the kafka ui

### ISSUE THREAD

**Issue by ffahadr** [provectus/kafka-ui#4155]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

Here is a sample avro of amount.
```
{
    "name" : "amount",
    "type" : {
      "type" : "bytes",
      "logicalType" : "decimal",
      "precision" : 10,
      "scale" : 2
    }
  }
```
  
  But in the kafka ui when browsing through messages this is displayed like so 
  ```
"amount": {
    "bytes": "\u000fÚ"
  }
```

Kafka UI version 0.7.1
Avro version 3.1.1

### Your installation details

App version hash: [56fa824](https://github.com/provectus/kafka-ui/commit/56fa824)

### Steps to reproduce

Written in the description above

### Screenshots

<img width="198" alt="image" src="https://github.com/provectus/kafka-ui/assets/107856337/bddb05bc-7946-450f-95a0-83ddff8371b5">

**Comment by iliax** [comment]
Hello @ffahadr, can you please provide full message schema? (you can obfuscate field names)

**Comment by ffahadr** [comment]
> Hello @ffahadr, can you please provide full message schema? (you can obfuscate field names)

the avro schema or the event as seen in kafka UI?

**Comment by iliax** [comment]
@ffahadr avro schema, but event also can be useful

**Comment by ffahadr** [comment]
```
{
  "type": "record",
  "name": "Item",
  "namespace": "com.sample",
  "fields": [
    {
      "name": "id",
      "type": {
        "type": "string",
        "logicalType": "uuid"
      }
    },
    {
      "name": "quantity",
      "type": "int"
    },
    {
      "name": "price",
      "type": {
        "type": "record",
        "name": "PriceItem",
        "fields": [
          {
            "name": "netPrice",
            "type": {
              "type": "bytes",
              "logicalType": "decimal",
              "precision": 10,
              "scale": 2
            }
          },
          {
            "name": "vat",
            "type": {
              "type": "bytes",
              "logicalType": "decimal",
              "precision": 10,
              "scale": 2
            }
          },
          {
            "name": "currency",
            "type": "string"
          }
        ]
      }
    }
  ]
}

```
