### ISSUE TITLE
hello, my kafka server is after ssh Tunnel,so i can't direct connect

### ISSUE THREAD

**Issue by CodingJzy** [provectus/kafka-ui#4191]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

hello, my kafka server is after ssh Tunnel,so i can't direct connect

### Expected behavior

hello, my kafka server is after ssh Tunnel,so i can't direct connect

### Your installation details

1、hello, my kafka server is after ssh Tunnel,so i can't direct connect
2、1212
3、333

### Steps to reproduce

hello, my kafka server is after ssh Tunnel,so i can't direct connect

### Screenshots

hello, my kafka server is after ssh Tunnel,so i can't direct connect

**Comment by CodingJzy** [comment]
I think I should make it clear that the address of my Kafka cannot be directly connected and requires an SSH tunnel proxy to connect. The code can add a proxy, but how can your UI add a proxy? Here is my Redis GUI, which supports SSH tunnel connection, but how does your Kafka UI connect?
![image](https://github.com/provectus/kafka-ui/assets/44855157/f962a445-d840-4d94-b457-d8ce1b1d1cde)

**Comment by CodingJzy** [comment]
@Haarolean do you understand?

**Comment by CodingJzy** [comment]
@Haarolean  Didn't your kafka ui provide this proxy option?

**Comment by Haarolean** [comment]
@CodingJzy no, that's completely unrelated to the app's functionality.

**Comment by CodingJzy** [comment]
I think it matters. Now how can I use your Kafka UI to connect to my Kafka server? That IP cannot be directly connected, it can only be through a tunnel.

**Comment by CodingJzy** [comment]
@Haarolean

**Comment by Haarolean** [comment]
@CodingJzy I've already explained, you have to use SSH port forwarding:
`ssh -L 1234:localhost:<kafka_port>`
Then, your bootstrap servers property will look like this: `localhost:1234`.

Please understand, that this is a part of _your_ infrastructure and it has nothing to do with the app itself. 
To provide an exaggerated example, your kafka instance might be firewalled away completely, that's not the app's problem in creating VPN tunnels for you.
