### ISSUE TITLE
Kafka Broker's certificate expiry date monitoring

### ISSUE THREAD

**Issue by mannbadal** [provectus/kafka-ui#4195]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md) and the feature is not present there

### Describe the feature you're interested in

It would be great if you could add the Kafka server's certificate validity column in the "Brokers" tab. This will help proactively monitor and renew certs before they expire.
It would also help if the date of expiry could turn red when expiring within 30 days or something like that and could be null or '-' if using PLAINTEXT

### Version you're running

56fa824

**Comment by Haarolean** [comment]
Hi, thanks for sharing your idea.

However, after some discussion, we've decided that adding this feature might not be the best fit for the app, as certificate monitoring falls a bit outside our scope. Moreover, monitoring which certificate belongs to which kafka cluster would require introducing a lot of unrelated code.

I suggest you explore other solutions aimed at specifically certificate monitoring that could work for you.

If you have any other ideas or questions, feel free to share them.
