### ISSUE TITLE
Add Versioned Docker Image Tags to Docker Hub

### ISSUE THREAD

**Issue by daviddyball** [provectus/kafka-ui#4206]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md) and the feature is not present there

### Is your proposal related to a problem?

I am frustrated when there are no tags in the public Docker Hub images that match release versions and have to manually map commit refs to version numbers in order to mirror the images into my own infrastructure.

### Describe the feature you're interested in

Please publish version number tags for image builds (e.g. `provectuslabs/kafka-ui:0.7.1`) to Docker Hub.

### Version you're running

0.7.1

**Comment by Haarolean** [comment]
https://hub.docker.com/r/provectuslabs/kafka-ui/tags?page=1&name=v
<img width="641" alt="image" src="https://github.com/provectus/kafka-ui/assets/1494347/0d26444a-22f0-4917-9b19-96fd369cd9f1">

**Comment by daviddyball** [comment]
Apologies, I had anticipated that the image tags in Docker would match the branch tags in GitHub. It seems there is a `v` prefix 👍
