### ISSUE TITLE
kafka-ui oauth with keycloak  desnot work 

### ISSUE THREAD

**Issue by csuryac** [provectus/kafka-ui#4208]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

The Issuer "https://keycloaktest.ssnc-corp.cloud/auth/realms/kafka-ui-realm" provided in the configuration metadata did not match the requested issuer "https://keycloaktest.ssnc-corp.cloud/auth/realms/kafka-ui-realm/"

### Expected behavior

The Issuer "https://keycloaktest.ssnc-corp.cloud/auth/realms/kafka-ui-realm" provided in the configuration metadata did not match the requested issuer "https://keycloaktest.ssnc-corp.cloud/auth/realms/kafka-ui-realm/"

### Your installation details

used the helm charts provide and used the chart version .6.2 and 0.7.2 both are giving same problem 

### Steps to reproduce

  auth:
    type: OAUTH2
    oauth2:
      client:
        keycloak:
          clientId: kafka-ui
          clientSecret: reacted
          scope: openid
          issuer-uri: https://reacted/auth/realms/kafka-ui-realm/
          user-name-attribute: preferred_username
          client-name: keycloak
          provider: keycloak
          custom-params:
            type: keycloak

### Logs

Caused by: java.lang.IllegalStateException: The Issuer "https://reacted /auth/realms/kafka-ui-realm" provided in the configuration metadata did not match the requested issuer "https://reacted/auth/realms/kafka-ui-realm/"

**Comment by Haarolean** [comment]
You have an extra slash at the end of your `issuer-uri` configuration property
