### ISSUE TITLE
KIP-875: First-class offsets support in Kafka Connect

### ISSUE THREAD

**Issue by yeikel** [provectus/kafka-ui#4289]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md) and the feature is not present there

### Describe the feature you're interested in

[KIP-875](https://cwiki.apache.org/confluence/display/KAFKA/KIP-875%3A+First-class+offsets+support+in+Kafka+Connect) just debuted on Kafka 3.6 and it would be great to be able to leverage this feature using the UI

<span style="color: rgb(0, 0, 0); font-family: Roboto, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Provides first-class admin support for offsets in Kafka Connect. KIP-875 Part 1 added endpoints to get offsets and a new STOPPED state for connectors. The alter offsets and reset offsets endpoints have now been added.</span>

Action | Description
-- | --
GET /connectors/{connector}/offsets | Retrieve the offsets for a connector; the connector must exist
PATCH /connectors/{connector}/offsets | Alter the offsets for a connector; the connector must exist, and must be in the STOPPED state
DELETE /connectors/{connector}/offsets | Reset the offsets for a connector; the connector must exist, and must be in the STOPPED state
PUT /connectors/{connector}/pause | Pause the connector; the connector must exist

### Version you're running

56fa824

**Comment by acristu** [comment]
`PUT /connectors/{connector}/pause` was supported before KIP-875, the support for `stop` is needd `PUT /connectors/{connector}/stop`

[KIP-875](https://docs.confluent.io/platform/current/connect/references/restapi.html#put--connectors-(string-name)-stop)

**Comment by acristu** [comment]
if a connector is stopped Kafka Connect page in kafka-ui is broken:
```
{
    "code": 5000,
    "message": "JSON decoding error: Cannot construct instance of `com.provectus.kafka.ui.connect.model.ConnectorStatusConnector$StateEnum`, problem: Unexpected value 'STOPPED'",
    "timestamp": 1709289310142,
    "requestId": "c6e97ec9-923",
    "fieldsErrors": null,
    "stackTrace": "org.springframework.core.codec.DecodingException: JSON decoding error: Cannot construct instance of `com.provectus.kafka.ui.connect.model.ConnectorStatusConnector$StateEnum`, problem: Unexpected value 'STOPPED'\n\tat org.springframework.http.codec.json.AbstractJackson2Decoder.processException(AbstractJackson2Decoder.java:275)\n\tSuppressed: The stacktrace has been enhanced by Reactor, refer to additional information below: \nError has been observed at the following site(s):\n\t*__checkpoint ⇢ Body from GET http://some-host:8083/connectors/xyzt/status [DefaultClientResponse]\n\t*__checkpoint ⇢ Handler com.provectus.kafka.ui.contr
    .   .   .  .
