### ISSUE TITLE
how to run kafka-ui as API without opening UI

### ISSUE THREAD

**Issue by jainpratik163** [provectus/kafka-ui#4306]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

how we can run this tool as API. lets say we are not allow to use UI .

### Your installation details

NA

### Steps to reproduce

NA

**Comment by emad-eldeen** [comment]
I don't understand why you opened this as a bug. 
You also consciously checked the box "I've looked up my issue in FAQ" even though the answer is actually there https://docs.kafka-ui.provectus.io/faq/faq#can-i-use-the-app-as-api

**Comment by jainpratik163** [comment]
sorry my bad
