### ISSUE TITLE
User is able to change cluster configuration in Read Only mode

### ISSUE THREAD

**Issue by ravindraprasad85** [provectus/kafka-ui#4400]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

I am running the Kafka cluster in read only mode in kafka-ui config. However, user is able to change the cluster configuration.
Yes, Topics are fine in read only mode .
There is no such feature to add user with view rights till now . IT would be really great if that feature can be added and release in upcoming version.

### Expected behavior

All the cluster should be in read only mode for kafka-ui user .

### Your installation details

Kafla-ui 0.7.1 

### Steps to reproduce

Run the Kafka-ui in Read Only mode

**Comment by ravindraprasad85** [comment]
It was my mistake , Everything running as expected.


Thanks
Ravindra Prasad
7827979144

**Comment by shobitgg** [comment]
> I am running the Kafka cluster in read only mode in kafka-ui config. However, user is able to change the cluster configuration.
> Yes, Topics are fine in read only mode .
> There is no such feature to add user with view rights till now . IT would be really great if that feature can be added and release in upcoming version.

@Haarolean what changes should we make in the config to make sure the cluster config option is not visible for all users , can we also have admin and read only users directly from uiforkafka config ..
can you pls give detailed steps changes to be made to see the UI in read only mode

**Comment by shobitgg** [comment]
@ravindraprasad85 what changes did you make to enable pure read only , currently I have enabled read only , but the users are able to see the configure option
