### ISSUE TITLE
Search with groovy fails

### ISSUE THREAD

**Issue by HStoyanov-augglobal** [provectus/kafka-ui#4437]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

Even the simplest ones fail - `keyAsText != null`, as taken from actual example. It doesn't display errors, no progress is evident (i.e. messages being counted/consumed).

When i hit the Submit button, the only things that changes on the page are:

* the Submit button turning to Cancel, then back to Submit;
* there is a `DONE` message, it is displayed near the text showing how many messages were consumed, download size, timing. That `DONE` message changes to `Polling partitions: [0, 1, 2]`, then back to `DONE`.

Both changes happen for less than a second on topics of any size.

### Expected behavior

When i add a new filter, it should be obvious that is doing the search - count messages being consumed, count download size...

### Your installation details

83b5a60 v0.7.2

### Steps to reproduce

1. Choose topic
2. Click `Add Filters` button
3. Use filter like `keyAsText != null` (from example) or just about anything else whose results you can verify
4. It will start search automatically, but can also hit the `Submit` button, behavior is the same

**Comment by Haarolean** [comment]
Hey, this repo is not maintained (#4255), but we've replaced groovy with CEL (and fixed the related CVE) here: https://github.com/kafbat/kafka-ui . I'll be glad to answer your questions there if any.

**Comment by MatthiasGabriel** [comment]
@HStoyanov-augglobal You can set the configuration property "filtering.groovy.enabled" to true to re-enable groovy filtering.

**Comment by oxie** [comment]
> @HStoyanov-augglobal You can set the configuration property "filtering.groovy.enabled" to true to re-enable groovy filtering.

mate can you give more info where we have to set it as i dont see this option on any of the chart values.yaml or documentations about this option

**Comment by HStoyanov-augglobal** [comment]
@oxie just add it as an environmental var set to true and restart the application.

Here's the commit where they added it, haven't found other documentation about it: https://github.com/provectus/kafka-ui/commit/3dc4446321716016e4c2517be4e04a692cdee7a7#diff-bee1096f3c435f4f12a5bdda31ce9a16bdd2aa9463c3ad8e11ad97fb968bbec5R48

**Comment by oxie** [comment]
yes seems this is the solution, please put it in the documentation:

```
  values:
    env: 
    - name: filtering.groovy.enabled
      value: "true"
```

**Comment by Haarolean** [comment]
>please put it in the documentation:

@oxie this repo is no longer maintained, see my comment [above](https://github.com/provectus/kafka-ui/issues/4437#issuecomment-2077685765)

**Comment by abhineetsbhamra** [comment]
> yes seems this is the solution, please put it in the documentation:
> 
> ```
>   values:
>     env: 
>     - name: filtering.groovy.enabled
>       value: "true"
> ```

@oxie and @MatthiasGabriel can you plz guide what is the equivalent env var name for setting this flag? is it `KAFKA_FILTERING_GROOVY_ENABLED`?

**Comment by ll14m4n** [comment]
@abhineetsbhamra the env is `FILTERING_GROOVY_ENABLED`, not  `KAFKA_FILTERING_GROOVY_ENABLED`. just checked myself, it works.
