### ISSUE TITLE
White dot on the "Key Serde" dropdown

### ISSUE THREAD

**Issue by sierikov** [provectus/kafka-ui#4447]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

A white dot from "Keep contents" is visible on top of the "Key Serde" dropdown.

### Expected behavior

No white dot is visible. 

### Your installation details

Docker deployment.

### Steps to reproduce

1. Start Kafka UI
2. (Create and) Open any topic
3. Click "Produce record"
4. Enable (violet) "Keep contents"
5. Click on "Key Serde"
6. Hover the first item in the dropdown.   

### Screenshots

<img width="305" alt="Screenshot 2024-05-16 at 13 44 46" src="https://github.com/provectus/kafka-ui/assets/22551739/3f8b1b33-813a-4b82-ab33-56ac69e38fc8">
<img width="267" alt="Screenshot 2024-05-16 at 13 49 44" src="https://github.com/provectus/kafka-ui/assets/22551739/c98f0d51-8b4a-4ea4-9b65-e3c43813fe9b">

### Additional context

The problem is in the `z-index` of the dropdown. We can set it to `12` to fix this problem.

**Comment by sierikov** [comment]
I want to claim this issue.

**Comment by Haarolean** [comment]
Please note this repo is not maintained (#4255). However, happy to see your contributions here: https://github.com/kafbat/kafka-ui

**Comment by sierikov** [comment]
Moved both [Pull Request](https://github.com/kafbat/kafka-ui/pull/395) and [Issue](https://github.com/kafbat/kafka-ui/pull/395) to the [kafbat/kafka-ui](https://github.com/kafbat/kafka-ui)
