### ISSUE TITLE
[e2e-check] need to run ui-checks in the CI with test results

### ISSUE THREAD

**Issue by mikementor** [provectus/kafka-ui#446]
Currently, check will run automatically on `mvn verify`(https://github.com/provectus/kafka-ui/blob/master/.github/workflows/backend.yml#L33), but check disabled with `@Disabled`. Because checks need Selenoid to run

What do we want:
- Checks run on local selenoid
- Failed checks fail build, passed checks do not
- Failed checks shouldn't stop actions from gathering allure results( see https://github.com/mikementor/java-ui-checks/blob/master/.github/workflows/build.yml#L41)
- Green(or red) arrow with link to allure results(that on gh-pages, e.g.`https://provectus.github.io/kafka-ui/allure-results/19`,gh-pages already work, you only need to publish artifacts(allure test results) on `gh-pages` branch)

See(would be almost identical steps):
https://github.com/mikementor/java-ui-checks/blob/master/.github/workflows/build.yml

**Comment by bvolodarskiy** [comment]
finished and merged into master
