### ISSUE TITLE
Slow listing of connectors

### ISSUE THREAD

**Issue by fallen-up** [provectus/kafka-ui#4460]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

when going into connectors or immediately with a filter (connectors?q=mongo) it can take about 10-25 seconds to load.
if debug through developer-tools, you can see that "connectors" hangs in pending for some time and only then starts loading.
One unusual thing: there are a lot of them, a couple dozen of them.
![image](https://github.com/provectus/kafka-ui/assets/11389898/cf409eb8-8edc-476c-99f5-7dfd13f90a9e)

with ingress kafka-connects everything is normal. redpanda-console opens them instantly (despite the amount).

other details:
couple dozens of connects and several hundred connectors are plugged in. response in size is not so big as it seems - 348KB.
but there are about 10000 lines in json.

### Your installation details

1.0

**Comment by germanosin** [comment]
Me and @Haarolean no longer support this repo.
Don't you mind to propose your request to our repo https://github.com/kafbat/kafka-ui

**Comment by fallen-up** [comment]
already https://github.com/kafbat/kafka-ui/issues/448

**Comment by fallen-up** [comment]
-

**Comment by germanosin** [comment]
Thanks!
