### ISSUE TITLE
[bug]topic messages show incorrect string value

### ISSUE THREAD

**Issue by hashkey-ops-admin** [provectus/kafka-ui#4461]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

The topic messages show incorrect string value as we use fastjson to serialize the topic message like this:
```
RecordMetadata recordMetadata = producer.send(<TOPIC_NAME>, JSON.toJSONString(message)).get();
```

We expected to see topic message like this:
```
{
      "userId":1712238412889623552,
      "totalStatus":2,
      "time":1718850732154,
      "msgId":"b00976ea-ab16-4ac5-8e23-4f8a4194b5c4"
}
```

However, we got message like this on kafka-ui:
```
{
	"msgId": "b00976ea-ab16-4ac5-8e23-4f8a4194b5c4",
	"time": 1718850732154,
	"totalStatus": 2,
	"userId": 1712238412889623600
}
```

As you can see, the `userId` is different.
Can u help check why this happened? Looks like it's due to something wrong happens during the deserialization of Long type to string(the userId is in Long type).

### Your installation details

We deployed kafka-ui with docker image, this image is:

provectuslabs/kafka-ui   latest    cf4ebffbd785   11 months ago   260MB

Current time is 2024/06/20 UTC, we didn't see any bug fix in this year(2024).

### Steps to reproduce

You could produce topic message like what I described in the detail part and check it on kafka-ui, then you should get the different userId.

**Comment by Haarolean** [comment]
Hi, PTAL at #4255 
And I believe we fixed this here: https://github.com/kafbat/kafka-ui

**Comment by hashkey-ops-admin** [comment]
@Haarolean Appreciate for ur quick answer.
I've tried the latest image from ghcr.io/kafbat/kafka-ui:latest and it works.
