### ISSUE TITLE
How can I avoid the red error in IDEA

### ISSUE THREAD

**Issue by Drun1baby** [provectus/kafka-ui#4468]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

<img width="1892" alt="image" src="https://github.com/provectus/kafka-ui/assets/75228348/01087c03-331d-4e63-bd42-7986dddc7236">

### Expected behavior

I want to solve it and run it with IDEA

if it is hard to solve, I just want remote debug in IDEA while avoiding these red errors

### Your installation details

v 0.71

### Steps to reproduce

just download the source.zip in release and open it with IDEA

**Comment by Haarolean** [comment]
this repo is not maintained (#4255), see https://github.com/kafbat/kafka-ui
