### ISSUE TITLE
Version check doesn't work as expected

### ISSUE THREAD

**Issue by feym78** [provectus/kafka-ui#4471]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

Just installed kafka-ui in k8s with kafka-ui version 0.7.2 by helm chart and noticed a warning about version.
As I can see 0.7.2 is the newest version, but behavior of version check is strange:
![image](https://github.com/user-attachments/assets/1f4e56c9-b1be-44d2-853d-628f6084fff8)
I looked at the issues and didn't find solution or explanatrion for this. 
As I can inderstand for now this behavior could be expected if backend can't reach github repo - https://github.com/provectus/kafka-ui/blob/master/kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/GithubReleaseInfo.java#L12
But pod with kafka-ui can access this url, I checked it by running wget request inside of the pod with kafka-ui and got response with json.
Also as I could inderstand from sources that when this information can't be accessed then there should be a message in logs - https://github.com/provectus/kafka-ui/blob/master/kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/GithubReleaseInfo.java#L38
but there is not any errors about it in actual log, same for browser console log
Can anyone please explain why is UI acts like this?
Thank you.

### Expected behavior

After installation in environment with internet access kafka-ui reports correctly about it's version.

### Your installation details

1. app version 0.7.2 or master
2. helm chart 0.7.6

### Steps to reproduce

1. Install kafka-ui version 0.7.2 or master
2. login to the UI
3. check version notice in the top of the page

**Comment by feym78** [comment]
Upd
problem disappeared on the next day, but still wondering why it happened.
![image](https://github.com/user-attachments/assets/7eb3b827-f6a6-4174-afe5-d80692017fcb)

**Comment by Haarolean** [comment]
this repo is not maintained (#4255), see https://github.com/kafbat/kafka-ui . We fetch version info upon app startup on the backend and the timeout is 10 seconds (here, in old repo, it might be 2s instead)

**Comment by feym78** [comment]
@Haarolean Oh, that wasn't very obvious! 
Thanx for your reply, will check new project's repo
