### ISSUE TITLE
Would you consider support for MSK & IAM integration ?

### ISSUE THREAD

**Issue by andormarkus** [provectus/kafka-ui#454]
Hello

AWS announced support for a new SASL mechanism called AWS_MSK_IAM which enables to handle both authentication and authorisation with AWS IAM. Is there a chance to add support for that mechanism to kafka-ui?

[source](https://aws.amazon.com/blogs/big-data/securing-apache-kafka-is-easy-and-familiar-with-iam-access-control-for-amazon-msk/):
```
If you’re using the Java clients (such as Java Producer, Consumer, Kafka Streams, or Kafka Connect), 
you’re in luck—all you need to do is to reference the Java library using Maven:

<dependency>
    <groupId>software.amazon.msk</groupId>
    <artifactId>aws-msk-iam-auth</artifactId>
    <version>1.0.0</version>		
</dependency>
```

Thanks,
Andor

**Comment by germanosin** [comment]
Hey, @andormarkus, looks pretty interesting. We are using MSK rather often in our projects.
