### ISSUE TITLE
Invalid Helm Chart Repository

### ISSUE THREAD

**Issue by ggobbe** [provectus/kafka-ui#475]
**Describe the bug**
Kafka-UI Helm Chart Repo is not a valid chart repository

**Set up**
```bash
❯ helm version
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```

**Steps to Reproduce**

1. Run 
```bash
❯ helm repo add kafka-ui https://provectus.github.io/kafka-ui
Error: looks like "https://provectus.github.io/kafka-ui" is not a valid chart repository or cannot be reached: failed to fetch https://provectus.github.io/kafka-ui/index.yaml : 404 Not Found
```

**Expected behavior**
Repo to be added

**Comment by PatTheSilent** [comment]
This change https://github.com/provectus/kafka-ui/commit/8b729c6e8d6e148b37966cac253653f54be951aa has made the repo invalid. It removed the helm chart from existance...

**Comment by PatTheSilent** [comment]
@mikementor the thing is doing things again :) 

```
Error: failed to fetch https://provectus.github.io/kafka-ui/kafka-ui-0.0.1.tgz : 404 Not Found
Error: exit status 1
```

And I've seen that allure has uploaded new test results 5 minutes ago which, I'm assuming, borked it again.

**Comment by mikementor** [comment]
yep...  returned back, we'll  remove those suspicious actions with publishing test results for now
<img width="489" alt="Screenshot 2021-05-19 at 12 29 31" src="https://user-images.githubusercontent.com/3846115/118789859-df42b800-b89d-11eb-90d3-036f0ae493b8.png">
 should work again

**Comment by PatTheSilent** [comment]
Thanks! Works now!

**Comment by chris878787** [comment]
Hello @mikementor , I faced the same issue today with kafka-ui repo. Are there any updates regarding the repo kafka-ui??

Helm version:
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}

helm repo add kafka-ui https://provectus.github.io/kafka-ui
Error: looks like "https://provectus.github.io/kafka-ui" is not a valid chart repository or cannot be reached: failed to fetch https://provectus.github.io/kafka-ui/index.yaml : 404 Not Found

Do I miss something?
Thank you!

**Comment by PatTheSilent** [comment]
@chris878787 they've changed it to https://github.com/provectus/kafka-ui-charts

**Comment by chris878787** [comment]
@PatTheSilent Really thank you for letting me know it. Now it works, :)

**Comment by eklavyasagar** [comment]
@mikementor issue still exists.

helm version:
version.BuildInfo{Version:"v3.13.2", GitCommit:"2a2fb3b98829f1e0be6fb18af2f6599e0f4e8243", GitTreeState:"clean", GoVersion:"go1.20.10"}

helm repo add kafka-ui https://provectus.github.io/kafka-ui
Error: looks like "https://provectus.github.io/kafka-ui" is not a valid chart repository or cannot be reached: failed to fetch https://provectus.github.io/kafka-ui/index.yaml : 404 Not Found

Changed the url to https://github.com/provectus/kafka-ui. Still issue persists.
