### ISSUE TITLE
Add a topic list filtering (permission-based)

### ISSUE THREAD

**Issue by giom-l** [provectus/kafka-ui#482]
### Is your proposal related to a problem?

I provide this UI to some of my users but I would like to be able to filter out the topics they will be able to see on the cluster

### Describe the solution you'd like

This UI is wonderful for administration but also for topic browsing and I use it to let my users simply (as some of them are not technical ones) browse some messages when they need to.

Topic list can be filtered from the search bar but it could be also good to be able to set a global filter on startup.
This could ensure users can not access to data they should not see.
This kind of issue could be resolvable by Kafka ACL, but I'm not sure it is implemented yet (and we may provide access to some topics on cluster that we are not managing)

To solve this, it could be helpful to have an environment variable like `KAFKA_CLUSTERS_[N]_TOPIC_PREFIX_FILTER` that would prevent to load any other topic on the list that do not start with this prefix.
Of course, topic search bar would also take that parameter so that a research would not return any topic that should be filtered.

### Describe alternatives you've considered

Kafka ACL, but may be harder to implement. And it depends on kafka cluster configuration (that we may not own)

### Additional context

Need to figure out how it could be working with topic creation when not on `readonly` mode.
I see 2 possibilities here : 
- The user can create a topic but it will not accessible on the list (which could be misleading about the UI behaviour and lead to multiple topic creation if user don't understand what's going on)
- The creation is prevented if the topic name does not respect the prefix set (clearer and error prone IMO)

**Comment by Haarolean** [comment]
#753

**Comment by Haarolean** [comment]
This feature will be available within #753
