### ISSUE TITLE
MTLS / connect to secure broker

### ISSUE THREAD

**Issue by zagr0** [provectus/kafka-ui#555]
### Is your proposal related to a problem?

Hi, first of all, thank you for such great tool!
We have MTLS enabled for our kafka cluster, and require key and certificate for broker's connection to be configured for UI
is there way to configure that?

### Describe the solution you'd like

would be really great to have instructions to achieve MTLS
https://github.com/provectus/kafka-ui#connecting-to-a-secure-broker

**Comment by germanosin** [comment]
Hi, @zagr0. Thanks for creating this request. We already have these description in a PR.
basic scenario would be just to add:
```
KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SSL
```

**Comment by zagr0** [comment]
Hi, @germanosin , that's awesome!
Is there a way to point UI to use my custom client key and certificate for SSL auth?

**Comment by germanosin** [comment]
@zagr0 sure, 
You can attach your truststore and keystore to docker and pass them to config
```
KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_LOCATION
KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_PASSWORD
KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEY_PASSWORD
KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_PASSWORD
KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_LOCATION
```

**Comment by RustamGimadiev** [comment]
I will close this issue, please reopen in case of provided solution does not work
