### ISSUE TITLE
Can't connect to Kafka with SASL

### ISSUE THREAD

**Issue by EnzOuille** [provectus/kafka-ui#573]
Hi, i have kafka installed with docker and running with SASL_PLAINTEXT, when i try to go to the kafka ui web page, i only get 500 Error. This is my config

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    networks:
      - kafka_installation_default
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: 'local'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka:9092'
      KAFKA_CLUSTERS_0_ZOOKEEPER: 'zookeeper:2181'
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: PLAIN
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="enzo" password="cisternino"'

**Comment by germanosin** [comment]
Hi, @EnzOuille thanks for sharing this issue. Could you please provide your kafka config for example in a docker compose file. This will help us to reproduce this issue.

**Comment by EnzOuille** [comment]
Hi thanks for the quick answer, below is my config of kafka in docker :

  kafka:
    image: wurstmeister/kafka:latest
    hostname: kafka
    container_name: kafka
    networks:
      - kafka_installation_default
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: SASL_PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS:  SASL_PLAINTEXT://192.168.0.34:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.auth.SimpleAclAuthorizer
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KAFKA_SUPER_USERS: User:admin,User:enzo
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: 'true'
    volumes:
    - /var/lib/docker/volumes/kafka_vol/_data:/etc/kafka

And this is the jaas file config 

KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="admin"
    password="admin-secret"
    user_admin="admin-secret"
    user_enzo="cisternino";
};

KafkaClient {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    user_admin="admin-secret";
};

Client {};

**Comment by germanosin** [comment]
@EnzOuille thanks for quick sharing, we'll try it locally and return to you soon.

**Comment by heywood8** [comment]
[Documentation ](https://github.com/provectus/kafka-ui#connecting-to-a-secure-broker) says "To be continued"
What is the correct way to set username and password for SASL using kafka-ui env vars?

**Comment by EnzOuille** [comment]
@germanosin ok thanks for that !

**Comment by germanosin** [comment]
@EnzOuille, looks like you missed trailing *;*.
I created example docker compose here: https://github.com/provectus/kafka-ui/blob/master/docker/kafka-ui-sasl.yaml#L19

**Comment by EnzOuille** [comment]
Hi, thanks for that, i was effectively missing this. Even when i had this, my kafka ui can launch in docker but i have no information on the web page, and i can see on the logs that the kafka ui failed to get messages (Timed out waiting for a node assignment), also i saw that on bootstrap servers you do not put SASL_PLAINTEXT, on my own without this kafka exit, saying that he cannot connect to kafka ui.

**Comment by germanosin** [comment]
@EnzOuille you are always welcome)
