### ISSUE TITLE
Configure different clusters

### ISSUE THREAD

**Issue by barebu** [provectus/kafka-ui#588]
Hello
Thank you so much for the product
Please explain :
1. How to use kafka-ui (docker) to work with multiple clusters. I saw an example (https://github.com/provectus/kafka-ui/blob/master/kafka-ui-api/src/main/resources/application-local.yml), but it is not clear how to pass at the start of the container
2. Is it possible to configure authentication to access the kafka-ui interface?

If documentation exists somewhere, please give it

**Comment by germanosin** [comment]
Hi, @barebu. Thank you for creating this issue.

1. To configuring multiple clusters you have to pass them as array either in config either threw env variables.

For example:

```
docker run -p 8080:8080 \
	-e KAFKA_CLUSTERS_0_NAME=local \
	-e KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092 \
	-e KAFKA_CLUSTERS_1_NAME=remote \
	-e KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS=remote:9092 \
	-e KAFKA_CLUSTERS_2_NAME=more \
	-e KAFKA_CLUSTERS_2_BOOTSTRAPSERVERS=more:9092 \
	-d provectuslabs/kafka-ui:latest 
```

2. Of course, for now we support only OAuth2 providers

for example: 
```
 -e SECURITY_BASIC_ENABLED=true \
  -e SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_AUTH0_CLIENTID=uhvaPKIHU4ZF8Ne4B6PGvF0hWW6OcUSB \
  -e SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_AUTH0_CLIENTSECRET=YXfRjmodifiedTujnkVr7zuW9ECCAK4TcnCio-i \
  -e SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_AUTH0_ISSUER_URI=https://dev-a63ggcut.auth0.com/ \
```

We are using Spring security for this, you could check this article for a wider description:
https://spring.io/blog/2018/03/06/using-spring-security-5-to-integrate-with-oauth-2-secured-services-such-as-facebook-and-github

**Comment by Haarolean** [comment]
AUTH_ENABLED: 'true' instead of SECURITY_BASIC_ENABLED
