### ISSUE TITLE
[Feature Request] Simple UI searching topic by topic name

### ISSUE THREAD

**Issue by ducminhnguyen** [provectus/kafka-ui#606]
### Is your proposal related to a problem?
One broker may have thousands of topic, I suggest we add a simple searching of topic by name on the UI

**Comment by RustamGimadiev** [comment]
Hi @ducminhnguyen, thanks for the request! Currently, the interface allows you to search topics by name in the `Topics` tab. Is it not what you are looking for? 
<img width="1617" alt="Screenshot 2021-07-02 at 08 34 53" src="https://user-images.githubusercontent.com/1175760/124226073-2664cf80-db11-11eb-83f8-583caffa5838.png">
