### ISSUE TITLE
JsonSchema is not working properly with schema registry

### ISSUE THREAD

**Issue by germanosin** [provectus/kafka-ui#643]
**Describe the bug**
Json messages with schema registry have prefix 5 bytes with magic symbol & schema version. This could break message reader. 
Let's add tests and cover this case

**Comment by sreenivasvp** [comment]
Request :
/api/clusters/ENV-Test/topics/configuration-service/messages?limit=100
Response :
{"code":5000,"message":"Failed to parse record from topic configuration-service","timestamp":1625668145100,"requestId":"2c1db961","fieldsErrors":null}
