### ISSUE TITLE
Consumer groups for a topic are not displayed

### ISSUE THREAD

**Issue by ashevtsov-wawa** [provectus/kafka-ui#652]
**Describe the bug**
List of consumer groups is not displayed on the `Consumers` tab in the topic view. `consumergroups` call succeeds and returns correct information but the data is not displayed on the web page.

**Set up**
* Pod in EKS cluster
* `provectuslabs/kafka-ui:latest` image
* `KAFKA_CLUSTERS_0_READONLY=true`
* `KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=SSL`
* `SERVER_SERVLET_CONTEXT_PATH=/kafka-ui`
* certificate has ACLs with `Read`, `Describe` and `DescribeConfigs` permissions for all topics (`*`).

**Steps to Reproduce**

1. Open kafka-ui
2. Click `Topics` under the Kafka cluster on the left-hand side
3. Select a topic
4. Switch to `Consumers` tab
5. `No active consumer groups` message will be displayed

**Expected behavior**
Should display the list of consumer groups

**Screenshots**
![image](https://user-images.githubusercontent.com/72090248/125141948-77159300-e0e4-11eb-88f7-4e2952ddc58b.png)

**Comment by GneyHabub** [comment]
Hi @ashevtsov-wawa! Thanks for your contribution. The fix for this issue is currently in progress, will be merged ASAP.

**Comment by germanosin** [comment]
This issue is solved in master.
