### ISSUE TITLE
Ability to search and filter Kafka connectors by type, name and statuses 

### ISSUE THREAD

**Issue by IldarAlmakaev** [provectus/kafka-ui#666]
### Is your proposal related to a problem?

As a user, I'd like to filter deployed Kafka connectors by name, statuses(e.g. FAILED, RUNNING), and their type (SOURCE, SINK)

(Write your answer here.)

### Describe the solution you'd like
At this moment, we haven't got a feature to filter connectors by their statuses, types and names.
Please, take a look at the screenshot below:
<img width="1402" alt="Screenshot 2021-07-16 at 15 59 50" src="https://user-images.githubusercontent.com/11831199/125951646-75c0fe48-a9a7-4fb6-8d6e-9193154dd982.png">

(Describe your proposed solution here.)
There is a controller `com.provectus.kafka.ui.controller.KafkaConnectController` with several REST endpoints
We need to add a new GET request or modify an existing to be able to filter connectors by:
* name
* status (RUNNING, FAILED, etc)
* and type (SOURCE, SINK)

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by Haarolean** [comment]
Done within 0.3.
