### ISSUE TITLE
Use secured JMX interface on Kafka cluster

### ISSUE THREAD

**Issue by anderssynstad** [provectus/kafka-ui#684]
As JMX on a production Kafka cluster should ideally have both auth and SSL enabled, it would be useful if Kafka UI could connect to it.

**Comment by germanosin** [comment]
@anderssynstad thanks for creating this issue. we'll take it into next milestone.

**Comment by Haarolean** [comment]
hey @anderssynstad , would you able to check out the changes I've made? 
I've tested jmx auth but couldn't get ssl working, probably some misconfiguration happened, but I'm pretty sure it will work properly.
I can provide a jar file to let you build a dockerfile yourself.

**Comment by Haarolean** [comment]
This feature will be released within `0.2` release.
