### ISSUE TITLE
High memory usage 

### ISSUE THREAD

**Issue by digdiver** [provectus/kafka-ui#691]
**Describe the bug**

I've running Docker image at EC2 t2.meduim instance. Within a few days, all free memory has gone. And I need to start/stop the instance to return it to a working state.

**Set up**
via docker on EC2 t2.meduim instance

**Steps to Reproduce**

1. run docker, wait for a few days. And instance became unreachable.

**Expected behavior**
It must run for more than a few days.

**Comment by germanosin** [comment]
Hi, @digdiver. Thanks for creating this issue. Could you please provide additional information how are you running UI for Apache Kafka. Are you using docker or jar? If you are using jar, how is your heap configured.

**Comment by digdiver** [comment]
> Hi, @digdiver. Thanks for creating this issue. Could you please provide additional information how are you running UI for Apache Kafka. Are you using docker or jar? If you are using jar, how is your heap configured.

I've using docker:

docker run -d --name kafkaui -e KAFKA_CLUSTERS_0_NAME=local -e LOGGING_LEVEL_ROOT=error -e KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=test_kafka_1:9092,test_kafka_2:9092,test_kafka_3:9092 -e KAFKA_CLUSTERS_0_ZOOKEEPER=test_kafka_1:2181,test_kafka_2:2181,test_kafka_3:2181 --add-host test_kafka_1:172.16.0.29 --add-host test_kafka_2:172.16.0.188 --add-host test_kafka_3:172.16.0.246 -p 8083:8080 provectuslabs/kafka-ui:latest

**Comment by digdiver** [comment]
The docker running for 21 hours
![image](https://user-images.githubusercontent.com/51635999/126280077-79b41eb7-c295-4dc6-8400-4624a192a0ae.png)

**Comment by germanosin** [comment]
Thanks, for provided info. 
1. Virt is not a actual memory usage size, you should check RES column for actual memory usage more info here (https://www.deonsworld.co.za/2012/12/20/understanding-and-using-htop-monitor-system-resources/)
2. When you are running java vm in docker, by default it consumes 1/2 of all available memory (It allocates it for Heap). If you want to reduce it, you could pass -m flag (more details here: https://docs.docker.com/config/containers/resource_constraints/) 
3. UI for Apache Kafka could work in 256MB Heap size, so feel free to reduce it.
4. You mentioned that your instance become unreachable in few days - this might be not a problem with memory, but cpu usage, could you check cpu credits usage?

**Comment by digdiver** [comment]
I've set up docker run -m 1g
After 10 hours oom-kill occurs:
```
Jul 26 16:59:42 ip-172-16-0-95-mon-central-dev kernel: [37035.383287] Tasks state (memory values in pages):
Jul 26 16:59:42 ip-172-16-0-95-mon-central-dev kernel: [37035.383287] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
Jul 26 16:59:42 ip-172-16-0-95-mon-central-dev kernel: [37035.383605] [   2680]     0  2680  1959774   198734 11382784        0             0 java
Jul 26 16:59:42 ip-172-16-0-95-mon-central-dev kernel: [37035.383607] oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=7ff62134e8629f1ae991a631618a2cbccb8e5157cf9fbd1677e9c07287070041,mems_allowed=0,oom_memcg=/docker/7ff62134e8629f1ae991a631618a2cbccb8e5157cf9fbd1677e9c07287070041,task_memcg=/docker/7ff62134e8629f1ae991a631618a2cbccb8e5157cf9fbd1677e9c07287070041,task=java,pid=2680,uid=0
Jul 26 16:59:42 ip-172-16-0-95-mon-central-dev kernel: [37035.391725] Memory cgroup out of memory: Killed process 2680 (java) total-vm:7839096kB, anon-rss:768368kB, file-rss:26568kB, shmem-rss:0kB, UID:0 pgtables:11116kB oom_score_adj:0
Jul 26 16:59:43 ip-172-16-0-95-mon-central-dev kernel: [37035.474453] oom_reaper: reaped process 2680 (java), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
Jul 26 16:59:43 ip-172-16-0-95-mon-central-dev dockerd[1174]: time="2021-07-26T16:59:43.124871788Z" level=info msg="ignoring event" container=7ff62134e8629f1ae991a631618a2cbccb8e5157cf9fbd1677e9c07287070041 module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
```

**Comment by germanosin** [comment]
Hi, @digdiver. Thanks for detailed report. We'll try to reproduce it.

**Comment by Haarolean** [comment]
The cluster is up on aws. Waiting for the result & monitoring.

**Comment by Haarolean** [comment]
45 hours passed, memory usage is the same -- 444mb. I'll wait up for a few more days.

**Comment by Haarolean** [comment]
I couldn't reproduce the issue. The cluster is up for 3 days, 445 mb of memory is used. 
@digdiver I can recommend you building the docker image yourself to enable heap dumping.
Having a jar file you can modify the Dockerfile the following way:
```
FROM openjdk:13
VOLUME /tmp
ARG JAR_FILE
COPY "./${JAR_FILE}" "/kafka-ui-api.jar"

EXPOSE 8080
CMD java -Xmx1024m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath="/tmp" -jar kafka-ui-api.jar
```
And run the build via `docker build . --build-arg JAR_FILE=kafka-ui-api-0.1.1-SNAPSHOT.jar --tag provectuslabs/kafka-ui:latest` and after that you could run it the same way you did or via `docker-compose`. 
You can download a jar file clicking 'releases' or build one yourself via maven.
Let us know how it goes.

**Comment by Haarolean** [comment]
Please leave a comment in this issue and provide a heap dump file if you encounter this issue again.
Also, not that there's a version 0.2 has been release recently.
