### ISSUE TITLE
Add an ability to create topic with custom parameters 

### ISSUE THREAD

**Issue by germanosin** [provectus/kafka-ui#7]
- Provide a list of available topic parameters with default values
- Update the topic creation endpoint to use list of custom parameters
- Validate custom parameters

**Comment by Gataniel** [comment]
https://github.com/provectus/kafka-ui/pull/20 - ui part PR
https://github.com/provectus/kafka-ui/issues/14 - ui part issue

https://github.com/provectus/kafka-ui/blob/master/kafka-ui-react-app/src/components/Topics/New/CustomParams/customParamsOptions.tsx - file with ALL available custom parameters with default values. Created it myself - I might have missed something - feel free to update

**Comment by Gataniel** [comment]
1) update backend topic creation API to handle custom params 
the schema is the following
<img width="420" alt="Screenshot 2020-04-13 at 12 53 26" src="https://user-images.githubusercontent.com/3863871/79111739-c7892e00-7d85-11ea-9a82-916274f816fb.png">

`{name: "test"
partitions: "1"
replicationFactor: "1"
...,
configs: {
cleanup.policy: "delete", 
..., 
customParams: {
'timestamp1': { name: customParamName, value: customParamValue },
...
'timestamp3': { name: customParamName3, value: customParamValue3 }
},
retention.bytes: "-1",
}
...,
}`

**Comment by germanosin** [comment]
> 1. update backend topic creation API to handle custom params
>    the schema is the following
> 
> <img alt="Screenshot 2020-04-13 at 12 53 26" width="420" src="https://user-images.githubusercontent.com/3863871/79111739-c7892e00-7d85-11ea-9a82-916274f816fb.png">
> 
> `{..., configs: { ..., customParams: { 'timestamp1': { name: customParamName, value: customParamValue }, 'timestamp2': { name: customParamName2, value: customParamValue2 }, ... }, }, }`
> 
> 1. add validation for custom params(
>    no empty values,
>    no invalid values(strings for ints, etc),
>    no duplicate values
>    )

Why do we need  ` timestamp in custom params map?
```customParams: { 'timestamp1' ``

**Comment by Gataniel** [comment]
@germanosin  thats outdated. Custom params now are simply under config = { ... customParams } just with other options
