### ISSUE TITLE
Contribution: Define naming convention for Git branches

### ISSUE THREAD

**Issue by IldarAlmakaev** [provectus/kafka-ui#704]
### Is your proposal related to a problem?

(Write your answer here.)

### Describe the solution you'd like

(Describe your proposed solution here.)

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by MarselAhmetov** [comment]
Now I use following naming: issue#704_Some_inforamive_words
I think that it is convenient, informative and beautiful.
How do you think?

**Comment by Haarolean** [comment]
I suggest it would be nice to use grouping tokens at least.
For example:
`issues/123`
`feature/feature_name`
`bugfix/fix_thing`

**Comment by Haarolean** [comment]
Take a look at PR #731.
