### ISSUE TITLE
Expose broker log dirs

### ISSUE THREAD

**Issue by germanosin** [provectus/kafka-ui#707]
Add endpoints:
* /api/clusters/{clusterName}/brokers/{id}/logdirs
expected outcome: 
```json
[
 {
     "name": "",
     "error": "",
     "topics": {
         "topicName": {
             "partitions": [
                 {
                     "paritititon": 0,
                     "size": 11212121,
                     "offsetLag": 0
                 }
             ]
         }         
     }
 }
]
```
* /api/clusters/{clusterName}/brokers/logdirs
```json
[
 {
     "name": "",
     "error": "",
     "topics": {
         "topicName": {
             "partitions": [
                 {
                     "broker": 0,
                     "paritititon": 0,
                     "size": 11212121,
                     "offsetLag": 0
                 }
             ]
         }         
     }
 }
]
```

Use AdminClient describeLogDirs to get this info

**Comment by tdavletov** [comment]
@germanosin what is the purpose of the "name" and "error" response fields?

**Comment by germanosin** [comment]
@tdavletov Name is the logdir name and you can. get error from LogDirInfo object, it could be null

**Comment by workshur** [comment]
@germanosin Are we sure we need both? I think we can use /api/clusters/{clusterName}/brokers/logdirs
 and group dirs by broker on UI side

**Comment by germanosin** [comment]
I think we could have both endpoints, and let's check how we can do this on UI. I'm thinking to have per broker page in future

**Comment by workshur** [comment]
I would suggest to have one page with filtration by broker

**Comment by tdavletov** [comment]
> @tdavletov Name is the logdir name and you can. get error from LogDirInfo object, it could be null

@germanosin I see, thanks. I read that kafka's "documentation says, that partitions will be distributed among the directories round-robin style". So for multiple directories we will see same topic in different parts of response json. I'm going to implement it that way but I don't know how it will look on UI so if you have any concerns about it, let's discuss.

**Comment by tdavletov** [comment]
> I would suggest to have one page with filtration by broker

@workshur, makes sense

**Comment by tdavletov** [comment]
Updated spec (one endpoint):
- /api/clusters/{clusterName}/brokers/logdirs

OR
- /api/clusters/{clusterName}/brokers/logdirs?broker=0&broker=1

Response:
```
[
 {
     "name": "",
     "error": "",
     "topics": {
         "topicName": {
             "partitions": [
                 {
                     "broker": 0,
                     "paritititon": 0,
                     "size": 11212121,
                     "offsetLag": 0
                 }
             ]
         }         
     }
 }
]
```
