### ISSUE TITLE
Show Internal Topics doesn't do a repagination

### ISSUE THREAD

**Issue by survivant** [provectus/kafka-ui#710]
I have multiple topics auto-generated by confluentinc at startup.  I clicked on Show Internal Topics to hide them, but when I did that, I was expecting the UI to remove all filtered rows and redo the pagination.  In my case, I should have only 1 page instead of 2 pages blank with th 3th with the data

![image](https://user-images.githubusercontent.com/191879/126803131-25b62571-004c-4df0-a0fc-de97951d25d6.png)
![image](https://user-images.githubusercontent.com/191879/126803181-0bdbee25-e4bb-4a87-8749-4b954a94b726.png)

**Comment by germanosin** [comment]
Hi, @survivant . Thanks for creating issue. We'll take into current milestone.

**Comment by germanosin** [comment]
We should add this filter in /topics request and update frontend to support it
