### ISSUE TITLE
Add UI for broker log dirs

### ISSUE THREAD

**Issue by workshur** [provectus/kafka-ui#711]
Add an interface to display structure of broker log dirs. 
- page contains table/list of directories  grouped by Broker
- row/item list equal to logdir
- Each row contains controls to update logDir (select with list of available logDirs)

Related issues:
https://github.com/provectus/kafka-ui/issues/707
https://github.com/provectus/kafka-ui/issues/708

**Comment by Haarolean** [comment]
`/api/clusters/{clusterName}/brokers/logdirs`

Each broker on broker page should be clickable, there has to be an expandable partition list inside with broker dirs for each
