### ISSUE TITLE
Add UI to display list of broker configs 

### ISSUE THREAD

**Issue by workshur** [provectus/kafka-ui#712]
Add an interface to display broker configs 

AC:
- page contains table/list of broker configs 
- row/list item is equal to config property
- Each row contains controls to update config property (input and submit)
- each submit must be confirmed by user. (Use ConfirmationModal component)

Related Issues:
https://github.com/provectus/kafka-ui/issues/701
https://github.com/provectus/kafka-ui/issues/702
https://github.com/provectus/kafka-ui/issues/703

**Comment by Haarolean** [comment]
`/api/clusters/{clusterName}/brokers/{id}/configs`
UI should look the same as topic configs
