### ISSUE TITLE
Messages: not able to go back

### ISSUE THREAD

**Issue by survivant** [provectus/kafka-ui#721]
in the messages, if I click on NEXT, I'm not able to go back like: <- PREV
![image](https://user-images.githubusercontent.com/191879/127020350-25807234-0e32-43a0-9837-6afb7f0ea05b.png)
![image](https://user-images.githubusercontent.com/191879/127020390-f22b342b-15bc-4dee-bd3b-02c1ffff4bf1.png)

I have to click BACK on the browser.

**Comment by germanosin** [comment]
Hi, @survivant. Thank you for your contribution. We'll add this feature to next release.

**Comment by Haarolean** [comment]
We decided not to implement such a feature. The reason is its behavior might be ambiguous (e.g. what if there are newer messages?; offset calculation, etc). The best solution for now would be using your browser's history navigation buttons.
