### ISSUE TITLE
Consumes list in empty in Topics/Consumergroups

### ISSUE THREAD

**Issue by survivant** [provectus/kafka-ui#729]
The screen Topics/consumes doesn't show the consumers connected, but there are listed in the consumes sections.

![image](https://user-images.githubusercontent.com/191879/127335407-2f7581a8-f89b-4c7e-a068-d85459b576cc.png)
![image](https://user-images.githubusercontent.com/191879/127335440-8090785b-69f5-47f0-a3cb-2684c1a9c36e.png)

example from AKHQ
![image](https://user-images.githubusercontent.com/191879/127335489-14c2ee12-d09d-4e93-8058-a04426c4d4cc.png)

**Comment by germanosin** [comment]
@survivant this is a bug in 0.1.0 version it is already fixed in master and will be released in 0.2 soon

**Comment by survivant** [comment]
if it's in the master, can you push a new dockerimage with the tag latest.  You could add github action to build/push on each commit, like that we got the latest changes.

In my docker-compose file I have this.  So each time the image change, I'll get the latest version
````
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
````

**Comment by germanosin** [comment]
@survivant, every commit to master create new image with tag provectuslabs/kafka-ui:master, rovectuslabs/kafka-ui:latest is used for releases
