### ISSUE TITLE
ACL: Expose cluster's ACLs (read/only)

### ISSUE THREAD

**Issue by germanosin** [provectus/kafka-ui#754]
Backend should provide list of ACL lists per resource group. 
Frontend should display these lists with resource group type filter

**Comment by jonasgeiregat** [comment]
Created API proposal for this feature, https://github.com/provectus/kafka-ui/pull/1511

**Comment by sw-tracker** [comment]
Will this still be included in release 0.5?

**Comment by Haarolean** [comment]
Within this issue we'll implement **just** the display of ACLs. For the ACLs management, refer to ##124.

**Comment by S1M0NM** [comment]
Hi, we just checked out v0.7.0 but it seems there is a issue with the ACL Page in readonly mode:

![image](https://github.com/provectus/kafka-ui/assets/47780028/b699a7eb-6c1a-4ec8-84b4-d0df10fdf9c7)
![acl_read-only-delete-dialog](https://github.com/provectus/kafka-ui/assets/47780028/550288bc-b89b-46f9-9be0-8830bc6dd260)

The delete button is displayed next to the ACLs and a confirmation dialog even opens.
An error occurs when confirming.

I would expect not to see the delete button at all.

---
In addition, the list always snaps into a different order when the ACLs are re-fetched, making meaningful browsing impossible.

**Comment by iliax** [comment]
@S1M0NM thank you for feedback, we will take a look and improve soon
