### ISSUE TITLE
Bug in Connector topic link

### ISSUE THREAD

**Issue by MarselAhmetov** [provectus/kafka-ui#755]
**Describe the bug**
I start kafka-ui-connectors.yaml
There one KafkaConnect for two clusters with two connectors
<img width="1775" alt="Снимок экрана 2021-07-30 в 18 04 49" src="https://user-images.githubusercontent.com/49659004/127657018-1c3d3285-097e-4bd9-a4a2-f7a9d3519be4.png">

`source-activities` topic exists only on `local` cluster and if I will tap to `source-activities` from `Kafka-Connect` section in `secondLocal` cluster I will get nonexistent page:
<img width="544" alt="Снимок экрана 2021-07-30 в 18 07 31" src="https://user-images.githubusercontent.com/49659004/127657313-8121bed7-7d58-441b-9b9d-6eacec15f7e3.png">

**Set up**
I start kafka-ui-connectors.yaml

**Steps to Reproduce**

1. Start kafka-ui-connectors.yaml
2. Open section
<img width="245" alt="Снимок экрана 2021-07-30 в 18 09 54" src="https://user-images.githubusercontent.com/49659004/127657591-24dd9022-ce12-4916-8d75-2ea2246730cf.png">
3. Tap to 
<img width="169" alt="Снимок экрана 2021-07-30 в 18 11 18" src="https://user-images.githubusercontent.com/49659004/127657721-3b782d61-fdfd-46e5-8bcc-9f92f03e152b.png">

**Comment by ValentinPrischepa** [comment]
Could not reproduce this for "kafka-ui-connectors.yaml", please see attached screenshot.
![image](https://user-images.githubusercontent.com/14006390/147299881-d356a33e-2fa8-4561-90d0-352155332244.png)
