### ISSUE TITLE
Connector doesn't show trace when failed

### ISSUE THREAD

**Issue by tuananhlai** [provectus/kafka-ui#793]
**Describe the bug**

Kafka Connector doesn't show stack trace when they fail to run.

**Set up**

1. Create a new connector (I used Debezium)
2. Config the connector with the wrong password.

**Steps to Reproduce**

1. Click `Kafka Connector` in the side bar.
2. Click on a connector.

**Expected behavior**

`Trace` column show the stack trace of the failure.

**Screenshots**

![image](https://user-images.githubusercontent.com/42168740/129319307-5cf3acad-f895-41e7-ad15-196887d55c79.png)

**Additional context**
(Add any other context about the problem here)

**Comment by germanosin** [comment]
Hi, @tuananhlai. Thanks for creating this issue. Will try to add it in next version
