### ISSUE TITLE
How to add multiple kafka clusters with single kafka-UI

### ISSUE THREAD

**Issue by vangahari** [provectus/kafka-ui#812]
Is kafka-UI for multiple clusters, It seems for multiple clusters with single dashboard. But how can we configure that, there is no proper information about it

**Comment by vangahari** [comment]
I think I found how to configure multiple cluster with same UI

**Comment by vangahari** [comment]
Hi, Team
I have configure multiple cluster with Kafka-UI, But it is showing only 3 cluster, Is it not allowing more than 3 clusters..?

Please suggest me if it will not support more than 3 clusters

**Comment by germanosin** [comment]
Hi, @vangahari. Thanks for creating issue. There is no such limit. Could you please share your config?

**Comment by vangahari** [comment]
@germanosin Sorry, I gave number same in the env variable as shown in the following screen shot
<img width="426" alt="Screenshot 2021-08-23 at 7 05 03 PM" src="https://user-images.githubusercontent.com/45491142/130456653-9038a619-1365-4e5d-8ede-95f78bc31c54.png">

I changed it to 3, its working now
    environment:
        #dev cluster config
        KAFKA_CLUSTERS_0_NAME: "dev-cluster"
        KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: ""
        #Staging cluster config
        KAFKA_CLUSTERS_1_NAME: "stg-cluster"
        KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS: ""
        #ewf cluster config
        KAFKA_CLUSTERS_2_NAME: "preprod-cluster"
        KAFKA_CLUSTERS_2_BOOTSTRAPSERVERS: ""
        #demo cluster config
        KAFKA_CLUSTERS_3_NAME: "demo-cluster"
        KAFKA_CLUSTERS_3_BOOTSTRAPSERVERS: ""
      @germanosin Thanks for the quick reply

**Comment by germanosin** [comment]
Great, thank you for provided info!
