### ISSUE TITLE
Ability to set Jackson2JsonEncoder log level

### ISSUE THREAD

**Issue by dimitri-fert** [provectus/kafka-ui#815]
### Is your proposal related to a problem?

I'm frustrated not being able to set log level of `org.springframework.http.codec.json.Jackson2JsonDecoder` logger. 
The documentation currently states to set `LOGGING_LEVEL_ROOT` and `LOGGING_LEVEL_COM_PROVECTUS` env vars to define log levels but even when set to, let's say `error` level, there are still `debug` logs written by  `org.springframework.http.codec.json.Jackson2JsonDecoder` with, AFAIK, no way to change such level.

As a result I'm seeing a lot of unwanted messages such as : 

```
15:04:47.016 [boundedElastic-1] DEBUG org.springframework.http.codec.json.Jackson2JsonEncoder - [79a205af] Encoding [class ClusterStats {
    brokerCount: 3
    zooKeeperStatus: 0
    activeControllers: 1
    onlinePa (truncated)...]
```

### Describe the solution you'd like

I would like to be able to set up an env vars to define log level of the `org.springframework.http.codec.json.Jackson2JsonDecoder`  logger (e.g `LOGGING_LEVEL_J2J_DECODER`)

### Describe alternatives you've considered

No other so far

**Comment by germanosin** [comment]
Hi, @dimitri-fert . Thanks for creating this issue. We'll try to reproduce it, and return to you soon.

**Comment by esmeneev** [comment]
@Haarolean Hi, can I work on this?

**Comment by Haarolean** [comment]
@esmeneev hey, sure thing!

**Comment by Haarolean** [comment]
@esmeneev any luck?

**Comment by esmeneev** [comment]
@Haarolean I'm working on the issue

**Comment by esmeneev** [comment]
@Haarolean this was fixed by [#1231. ](https://github.com/provectus/kafka-ui/pull/1231), I've checked latest master, there were no `Jackson2JsonDecoder` logs, whereas in build from 6351361c they appear. I think we can close this issue.

**Comment by Haarolean** [comment]
@esmeneev okay, thanks! There are various issues in "Up for grabs" column in "Roadmap" project if you're interested ;)

**Comment by Marcuse7** [comment]
Could the issue title be changed to "... Jackson2Json_De_coder ..."?

**Comment by Haarolean** [comment]
@Marcuse7 why?
