### ISSUE TITLE
Configure package backward compatibility of Kafka Connect

### ISSUE THREAD

**Issue by antipova926** [provectus/kafka-ui#819]
**Describe the bug**
I use kafka-connector 5.2.4 and I have an 404 error during getting list of connectors
With kafka-connector 6.0.1 it works. 
**Set up**
```
./mvnw clean install -Pprod 
docker-compose -f ./docker/kafka-ui.yaml up

```

**Steps to Reproduce**

1. Create connector
2. Click Kafka Connect to view all created connectors

**Expected behavior**
All connectors are shown in connectors's list

**Screenshots**
(If applicable, add screenshots to help explain your problem)
<img width="1774" alt="Screenshot 2021-08-25 at 14 36 08" src="https://user-images.githubusercontent.com/44370201/130784013-72f0ed22-113f-4f94-ae34-a203d49587a1.png">

**Additional context**
(Add any other context about the problem here)

**Comment by iliax** [comment]
fixed, tested on confluentinc/cp-kafka-connect:5.1.0
