### ISSUE TITLE
npm run build is running out of memory

### ISSUE THREAD

**Issue by apryiomka** [provectus/kafka-ui#827]
**Describe the bug**

```
 Running 'npm run build' in /root/***/kafka-ui-react-app
[INFO]
[INFO] > kafka-ui@0.1.0 build /root/***/kafka-ui-react-app
[INFO] > react-scripts build
[INFO]
[INFO] Creating an optimized production build...
[INFO] The build failed because the process exited too early. This probably means the system ran out of memory or someone called `kill -9` on the process.
[INFO] The build failed because the process exited too early. This probably means the system ran out of memory or someone called `kill -9` on the process.npm ERR! code ELIFECYCLE
[INFO] npm ERR! errno 1
[INFO] npm ERR! kafka-ui@0.1.0 build: `react-scripts build`
[INFO] npm ERR! Exit status 1
[INFO] npm ERR!
[INFO] npm ERR! Failed at the kafka-ui@0.1.0 build script.
[INFO] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[INFO]
[INFO] npm ERR! A complete log of this run can be found in:
[INFO] npm ERR!     /root/.npm/_logs/2021-08-26T20_40_19_667Z-debug.log
```

How much memory does the build need? I am running with 4GB of RAM and it doesn't seem to be enough.

**Comment by jhonDoe15** [comment]
when trying to build locally on my personal win10 laptop:

800MB were used for `npm i`
`npm run build` failed with:

```
.\src\redux\reducers\clusters\selectors.ts
Cannot find module: 'generated-sources'. Make sure this package is installed.

You can install this package by running: npm install generated-sources.

```
which installing didnt work with cause of `npm ERR! 404 Not Found - GET https://registry.npmjs.org/generated-sources - Not found`

**Comment by Haarolean** [comment]
@GneyHabub could you take a look at this please?

**Comment by GneyHabub** [comment]
@jhonDoe15 After you've done `npm i`, you should generate some files with `npm run gen-sources` command

**Comment by jhonDoe15** [comment]
Didn't the comment saying `running: npm install generated-sources.` specified it ran it by itself?

**Comment by GneyHabub** [comment]
@jhonDoe15  `generated-sources` is a directory, not a package. It contains some API-related classes that are supposed to be generated with the [OpenAPI generator](https://github.com/OpenAPITools/openapi-generator-cli). `npm` mistakenly took it for a package

**Comment by jhonDoe15** [comment]
tried running `npm i` again followed by the suggested command, then running `npm run build` and got similar (might be same same) error:
```
kafka-ui\kafka-ui-react-app>npm run build

> kafka-ui@0.1.0 build
> react-scripts build

Creating an optimized production build...
Failed to compile.

.\src\redux\reducers\clusters\selectors.ts
Cannot find module: 'generated-sources'. Make sure this package is installed.

You can install this package by running: npm install generated-sources.


Terminate batch job (Y/N)? y

```

on branch `origin/master`

**Comment by GneyHabub** [comment]
@jhonDoe15 well, yes, [openapi-generator](https://github.com/OpenAPITools/openapi-generator) uses Java
