### ISSUE TITLE
Documentation website in Material for MkDocs

### ISSUE THREAD

**Issue by andormarkus** [provectus/kafka-ui#836]
### Is your proposal related to a problem?

The current documentation is a few markdown files and lacking a website for the documentation.

### Describe the solution you'd like
[Material for MkDocs](https://squidfunk.github.io/mkdocs-material/) provides no code static website for your project.
Its is very easy to setup, and it has native integration with [GitHub Pages](https://pages.github.com/)

I am happy to submit a base PR, later I will need team guidance to finish it.

Thanks,
Andor

**Comment by germanosin** [comment]
Hi, @andormarkus. This looks interesting. We'll take it into next versions

**Comment by Haarolean** [comment]
Hey, sorry for the delay, this got lost. 
I've familiar with jekyll a bit, but I suppose mkdocs is a better option for us?
As you mentioned that you're willing to propose a PR, we'll be glad to see one!

**Comment by Haarolean** [comment]
Decided to stick with gitbook #2727
