### ISSUE TITLE
Can not use a .proto definition with line comments

### ISSUE THREAD

**Issue by zarezadeh** [provectus/kafka-ui#844]
**Describe the bug**
When using a protobufFile as a cluster deserializer if the `.proto` file contains a line comment it can not be parsed correctly. This is because all lines of the file are joined together and form a single line file before parsing the protobuf definition. The fix is pretty easy and I can prepare a PR if you wish.

**Set up**
A cluster with protobufFile as deserializer.

**Steps to Reproduce**

1. Add a cluster with protobufFile as deserializer
2. Use a `.proto` definition which contains a line comment somewhere before the end of the file

**Expected behavior**
The service should be started successfully but it will complain about the unexpected end of protobuf definition.

**Screenshots**
(If applicable, add screenshots to help explain your problem)

**Additional context**
(Add any other context about the problem here)

**Comment by germanosin** [comment]
Hi, @zarezadeh. Thanks for your contribution!
