### ISSUE TITLE
Created connector in the local cluster is duplicated to the secondLocal cluster 

### ISSUE THREAD

**Issue by antipova926** [provectus/kafka-ui#846]
**Describe the bug**

When I create a connector in the Local cluster I also see this connector in the Second cluster. It works in both ways.

**Set up**

`./mvnw clean install -Pprod`
`docker-compose -f ./docker/kafka-ui-connectors.yaml up`

**Steps to Reproduce**

1. Go to the Local cluster
2. Create a topic with a message
3. Create a connector
4. Go to the Second Local cluster 

**Expected behavior**
Created connector only in the Local cluster

**Screenshots**

https://user-images.githubusercontent.com/44370201/131527173-ba87e34a-f04c-457e-8780-ed2b02287711.mov

**Additional context**
Connector's config: 
``` 
{
  "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",    
  "connection.url": "jdbc:postgresql://postgres-db:5432/test",     
  "connection.user": "dev_user",   
  "connection.password": "12345",
  "topics": "TEST_TOPIC",
  "table.name.format": "sink_activities_e2e_check",
  "key.converter": "org.apache.kafka.connect.storage.StringConverter",
  "key.converter.schema.registry.url": "http://schemaregistry0:8085",
  "value.converter": "org.apache.kafka.connect.json.JsonConverter",
  "value.converter.schema.registry.url": "http://schemaregistry0:8085",
  "auto.create": "true",
  "pk.mode": "record_value",
  "pk.fields": "id",
  "insert.mode": "upsert",
  "errors.log.enable": "true",
  "errors.log.include.messages": "true"
}
```

**Comment by IldarAlmakaev** [comment]
Thanks, @antipova926 for finding this issue.
We realized that there is a misconfiguration on kafka-ui side. I'll fix it asap.
Let me assign myself this ticket and resolve the issue
