### ISSUE TITLE
Ability to provide a separate Message name for each topic when using ProtobufFile

### ISSUE THREAD

**Issue by zarezadeh** [provectus/kafka-ui#849]
### Is your proposal related to a problem?

When using a protobufFile definition for parsing messages, it is assumed that all topics use a single message type. But this assumption is not valid in a lot of common scenarios IMO. It could be helpful to use a separate message type for each topic in a cluster.
### Describe the solution you'd like

Instead of setting a single message name in `protobufMessageName` when configuring a cluster, use a map of `topic -> messageName` in order to have different message names for each topic. Also, we can use a predefined key in this map (e.g. `_default`) to set a message name for all other topics without explicit mapping.

### Describe alternatives you've considered

Using _Schema Registry_ is a better alternative when possible but in legacy deployments when messages in Kafka topics don't adhere to the format schema registry expects, this is not an option.

### Additional context

I've already started working to prepare a PR, but I'd like to discuss the best solution before submitting the PR.

**Comment by germanosin** [comment]
Hi, @zarezadeh. Thanks for creating this issue. We'll take this in the next version.

**Comment by zarezadeh** [comment]
It's great @germanosin, so if you are OK with the proposed solution I would prepare and send the PR very soon.

**Comment by germanosin** [comment]
@zarezadeh . Great! I would be happy to review it.
