### ISSUE TITLE
[0.2.0] readonly mode not respected at topics list level & consumer groups level

### ISSUE THREAD

**Issue by giom-l** [provectus/kafka-ui#855]
**Describe the bug**
When a cluster is set readonly, I expect that no modification item is ever display.
It has been fixed some time ago on topic page, but in v0.2.0, some stuff are not correct.

On dashboard page, we can see the readonly mode
![image](https://user-images.githubusercontent.com/29728596/132256495-7627e9e4-52cf-458f-99c6-baa84a7c4682.png)

However, on each cluster "Topics" page, which list all the topic, I can see the checkboxes beside each topic.
And when I select any of them, the buttons "Delete selected topics" and "Purge messages of selected topics" appear, which is not wanted.

![image](https://user-images.githubusercontent.com/29728596/132256611-9192b536-fddf-4ddd-8c7a-5fc1078dfbff.png)

Also, on a consumer group page, I have access to "reset offsets" and "delete consumer group"
![image](https://user-images.githubusercontent.com/29728596/132259268-78e6338b-62e1-42ea-b3da-04ba753cec3b.png)

**Expected behavior**
When in readonly, I should not be able to modify/delete/create anything at any level.

**Additional context**
(Add any other context about the problem here)

**Comment by germanosin** [comment]
Hi, @giom-l. Thanks for creating this issue. We'll fix it in next minor version.
