### ISSUE TITLE
Simple login doesn't work with SERVER_SERVLET_CONTEXT_PATH 

### ISSUE THREAD

**Issue by asatsi** [provectus/kafka-ui#861]
**Describe the bug**
I have setup SERVER_SERVLET_CONTEXT_PATH as part of the deployment in Kubernetes. The ingress rule uses this URI. Everything works well if the spring AUTH ENABLED is not set. Once I enable the AUTH, the URL takes me to the default /login page instead of the $SERVER_SERVLET_CONTEXT_PATH/login page and fails to load.

**Comment by germanosin** [comment]
Hi, @asatsi thx for creating this issue. We'll try to fix it in the next minor version.
