### ISSUE TITLE
Deserialization of messages of the same topic with payloads of different types (AVRO/JSON)

### ISSUE THREAD

**Issue by Schiavi91** [provectus/kafka-ui#897]
**Describe the bug**
If a message with JSON payload is sent to a topic that has an AVRO schema in the schema registry, it will not be displayed in the "messages" tab even if no error is generated. The message is still added to the total message counter.

**Set up**
Executed in the local environment with docker-compose.

**Steps to Reproduce**
1. Create a topic (aaa-topic)
2. Add the corresponding avro schemas to the registry schema (aaa-topic-key and aaa-topic-value)
3. Send a message with payload in AVRO to the topic
4. Send a message with payload in JSON to the topic
5. Check that the second message is not present in the "messages" tab

**Expected behavior**
Three possible behaviors:
1. It should be reported in some way, it shouldn't be hidden because in this case the user doesn't notice the problem.
2. Each message should be deserialized with the correct deserializer.
3. The user should be able to choose how to deserialize the message (it could be useful for both the payload and the key).

**Additional context**
From the tests performed it seems that all messages are deserialized in the same way in which the first one was deserialized. If you send the first message with AVRO payload, all the following with JSON payload will not be displayed; if instead you send the first message with JSON payload, all the following with AVRO payload will be shown but without being deserialized with the registered schema.

**Comment by germanosin** [comment]
Hi, @Schiavi91. Thx for creating this issue. We'll definitely look and fix this problem in next versions.

**Comment by Schiavi91** [comment]
Hi @germanosin, do you have any idea on when this milestone will be released?

**Comment by germanosin** [comment]
Hi, @Schiavi91. I expect it would be released by the end of October.

**Comment by Haarolean** [comment]
This will be taken into consideration within version 0.4. Unfortunately we don't have a bandwidth for this in 0.3.

**Comment by iliax** [comment]
@Schiavi91 problem should be fixed with PR https://github.com/provectus/kafka-ui/pull/1593 . Currently if you have schemaRegistry specified in your config we will first try to deserialize message with schemaregistry formatter (avro/protobuf/json-schema) and if it is not possible -  fallback to string formatter. So, every message will be present in response.
