### ISSUE TITLE
Show/set deserializer for key and value

### ISSUE THREAD

**Issue by Schiavi91** [provectus/kafka-ui#900]
### Is your proposal related to a problem?

It would be nice to be able to see (and maybe set) the deserializers used for the key and value of each topic.
In relation to issue #897 I have not found any way to see which deserializer is used for the key and for the
value, is it possible to find this information in the frontend?

### Describe the solution you'd like

Add two fields in the search form of the "Messages" tab that allow you to set deserializers for the key and payload you want to use to view messages.

### Describe alternatives you've considered

Add two settings in the "Settings" tab instead of the two fields in the search form of the "Messages" tab.

**Comment by Haarolean** [comment]
Will be done within #1777 in the current release. Please follow that issue.
