### ISSUE TITLE
Cannot view/browse messages

### ISSUE THREAD

**Issue by metalshanked** [provectus/kafka-ui#904]
**Describe the bug**
I set up an SSL enabled cluster and I can see most of the info except browsing/viewing messages.
I tested it with kafdrop and i can see the messages but no matter what offsets or settings i enter, kafka-ui shows "no messages found" for the same topic

**Set up**
Docker provectuslabs/kafka-ui:master version : v0.2.1-SNAPSHOT(928dbd7)

**Screenshots**
![2021-09-24_17-17-02](https://user-images.githubusercontent.com/57646596/134751252-80bdab62-f7a8-4446-beb0-cf10b3fa95f8.png)

**Additional context**
(Add any other context about the problem here)

**Comment by germanosin** [comment]
@metalshanked. Thanks for creating this issue. Could you please provide more information? 
What is your config for UI for Apache Kafka? 
What is the serializing format for these messages?
If yes, could you provide schemas?

**Comment by metalshanked** [comment]
> @metalshanked. Thanks for creating this issue. Could you please provide more information?
> What is your config for UI for Apache Kafka?
> What is the serializing format for these messages?
> If yes, could you provide schemas?

Sure, here is the info.
Kafka version:2.3-IV1
kafka setup is SSL only with below kafka-ui configs
-e KAFKA_CLUSTERS_0_NAME=dev
-e KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS={MY KAFKA SERVER:PORT}
-e KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=SSL
-e KAFKA_CLUSTERS_0_PROPERTIES_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
-e KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_LOCATION={MY JKS DIRECTORY}
-e KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_PASSWORD={PASSWORD}
-e KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_LOCATION={MY JKS DIRECTORY}
-e KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_PASSWORD={PASSWORD}
-e KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEY_PASSWORD={PASSWORD}

The kafka messages are plaintext with with event per message. like log events.
I seem to able to view everything else apart from the browsing the messages.
I dont have schema registry setup

Is there any special config required to view/browse messages apart from the above?

**Comment by zuzana** [comment]
it seems that when deployed, the request path is not correct:

consumer groups (work)

```
https://sub.domain.com/my/special/path/api/clusters/kafka-shared/topics/user-updated-dev11/consumer-groups
```

messages - original request made by kafka ui (doesn't work):

```
https://sub.domain.com/api/clusters/kafka-shared/topics/user-updated-dev11/messages?attempt=0&limit=100&seekDirection=FORWARD&seekType=OFFSET&seekTo=0::6
```

messages - manually rewritten in new browser tab (works):

```
https://sub.domain.com/my/special/path/api/clusters/kafka-shared/topics/user-updated-dev11/messages?attempt=0&limit=100&seekDirection=FORWARD&seekType=OFFSET&seekTo=0::6
```

The `/my/special/path` part is missing. 

I just can't find where is the problem, whether in React or Java code.

**Comment by germanosin** [comment]
@zuzana  Thanks for digging into this.
