### ISSUE TITLE
Schemas subjects list should be searchable/filterable

### ISSUE THREAD

**Issue by akamensky** [provectus/kafka-ui#906]
### Is your proposal related to a problem?

It currently is not. Only page text search works (if browser provides this functionality).

### Describe the solution you'd like

Just as with topics -- the list of subjects should be searchable/filterable.

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by germanosin** [comment]
Thanks, for creating this issue. We'll try to add this in the next major versions.

**Comment by Haarolean** [comment]
Search and pagination has been implemented within #1208 and #1191. 
Leaving this for filtering implementation in 0.5.
