### ISSUE TITLE
Consumer Reset Offsets fails on EARLIEST and OFFSET

### ISSUE THREAD

**Issue by Ryaryu** [provectus/kafka-ui#916]
**Describe the bug**
When I try to reset a consumer offset using Reset Type=EARLIEST or OFFSET, I get some errors, described below, regardless if the consumer is active or not.

**Set up**
I've just started the UI via Docker as written in the project's README.

**Steps to Reproduce**
If I try to do a reset using EARLIEST, I get a HTTP 400 with this body:

```
{
  "code": 4001,
  "message": "Fields validation failure",
  "timestamp": 1633026371116,
  "requestId": "69a92c26",
  "fieldsErrors": [
    {
      "fieldName": "partitionsOffsets[0].offset",
      "restrictions": [
        "must not be null"
      ]
    }
  ]
}
```
The request body sent was:

```
{
  "topic": "MY-TOPIC",
  "resetType": "EARLIEST",
  "partitions": [
    0
  ],
  "partitionsOffsets": [
    {
      "partition": 0,
      "offset": null
    }
  ]
}
```
In this case I believe the "offset" being null is the problem with the endpoint. If I change the offset to 0, or change the type from EARLIEST to OFFSET, the result is now:

```
{
  "code": 5000,
  "message": "blockOptional() is blocking, which is not supported in thread reactor-http-epoll-6",
  "timestamp": 1633025573504,
  "requestId": "22a99bbd",
  "fieldsErrors": null
}
```
I've looked in README but found nothing that would be able to solve this. Am I doing something wrong?

**Comment by germanosin** [comment]
Hi, @Ryaryu. Thanks for your issue. We'll try to fix it in next minor version.

**Comment by germanosin** [comment]
Btw this is already fixed in master. Could you please try the image with tag master?

**Comment by germanosin** [comment]
Fixed in https://github.com/provectus/kafka-ui/pull/871

**Comment by Ryaryu** [comment]
> Btw this is already fixed in master. Could you please try the image with tag master?

I've tested, it works! Thanks!
