### ISSUE TITLE
Сonsumers list loading takes too long

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#927]
> - When viewing Cluster -> Topic -> Consumers, it seems like far more is being loaded than just consumer groups for that particular topic.
>   It takes much longer to load than, e.g., Kowl does for pulling the same information

**Comment by Haarolean** [comment]
Might get fixed within #921.

**Comment by Haarolean** [comment]
@clocklear hey, could you check if this is still an issue for you with `master` labeled docker image?

**Comment by EI-Joao** [comment]
Hi I am running the latest version v0.5.0 and when I try to list anything related to consumers it takes at least 30/40 seconds. 

It seems this is the case:
When viewing Cluster -> Topic -> Consumers, it seems like far more is being loaded than just consumer groups for that particular topic

fyi: we are running the .jar (not docker) and when we go to Cluster -> Consumers we have 10 to 14 pages of consumers and it also takes 30 to 40 seconds  

btw: the best kafka tool I have used soo far

**Comment by Haarolean** [comment]
@EI-Joao hey, thanks for the kind words! Please raise a new issue, we'll take a look for sure.
