### ISSUE TITLE
Consumer list loading fails with insufficient permissions

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#928]
>- If any permissions issues are encountered while loading the individual consumer group, the entire request fails. That >wouldn’t necessarily be an issue, but it is when you’re loading all consumer groups, and not just the one requested

**Comment by bystnik** [comment]
@Haarolean After investigation and attempts to reproduce I see that more details require on this issue. 1. it's not clear what kind of permission prevent the consumer list to be loaded and how to set them up. 2. What does "the entire request fails" mean? Is an exception thrown or does it just return an unexpected (incorrect or empty) list?

Also would be nice to have steps to reproduce if possible. Thx

**Comment by Haarolean** [comment]
Originally posted [here](https://news.ycombinator.com/item?id=28722315). The guess is some ACL/MSK permission fails, we'll put this on hold until more details are provided.
