### ISSUE TITLE
Add docker-compose example with SSL secured kafka

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#929]
https://news.ycombinator.com/item?id=28722315
>  - I don't see any docs on how to access a topic that is secured with certificates (Kowl's relevant config [2])

**Comment by Haarolean** [comment]
Moreover, we have to update the README:
https://github.com/provectus/kafka-ui#connecting-to-a-secure-broker ("to be continued")

**Comment by Haarolean** [comment]
@AKonstantin1337 hey, thanks for the feedback. This thing is still a WIP :)

**Comment by AKonstantin1337** [comment]
@Haarolean ohh thanks)
any ETA?)

**Comment by Haarolean** [comment]
within a week

**Comment by lbruno69** [comment]
same problem here, any news?

**Comment by Haarolean** [comment]
@AKonstantin1337  @lbruno69 on it

**Comment by Haarolean** [comment]
An example is located [here](https://github.com/provectus/kafka-ui/blob/master/documentation/compose/kafka-ssl.yml).
