### ISSUE TITLE
SASL - unable to set JAAS config

### ISSUE THREAD

**Issue by kreuzj** [provectus/kafka-ui#933]
**Describe a bug**

I'm trying to configure Kafka UI to connect to Kafka cluster using SASL/SCRAM but Kafka-UI log still shows following error:

`java.lang.IllegalArgumentException: Could not find a 'KafkaClient' entry in the JAAS configuration. System property 'java.security.auth.login.config' is not set `

I did the environment variable setting according the guide available in GitHub, but I am not sure where the problem is

**Set up**
The app is deployed using helm chart, here is screenshot of env. settings:
![image](https://user-images.githubusercontent.com/61864627/135905641-843889dd-3bc3-43eb-9a65-18f925313971.png)

JAAS config looks like this:
`KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="my-user" password="my-user-password";'`

Can you pls. help to resolve this problem? Thanks

**Steps to Reproduce**
N/A 

**Expected behavior**
My intention is to connect to Kafka cluster using SASL/SCRAM

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Haarolean** [comment]
Hi, thanks for reaching out. I'll take a look into this soon.

**Comment by Haarolean** [comment]
@kreuzj I have a feeling there's an extra environment variable might be required.
Could you please try adding KAFKA_OPTS variable like [this](https://github.com/provectus/kafka-ui/blob/master/docker/kafka-ui-sasl.yaml#L43)? (Line 43)
Let me know how it goes.

**Comment by poblin-orange** [comment]
I guess the corresponding variables do not exist. Is KAFKA_OPTS a workaround ?

**Comment by Haarolean** [comment]
@poblin-orange hey, please raise a new issue if you encounter something like this.
