### ISSUE TITLE
Split KafkaCluster to static & cached parts

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#950]
via Ilya:
>Reason: split data that changes and static data
Step:
create ClusterInfo class and place all static data there (from config and data can be filled on bootstrap)
create ClusterState class and place all dynamic data there (metrics, lastExceptions, statuses)
create Clusters class to store ClusterInfo objects
create ClusterStateCache to store ClusterState objects
refactor existing code that uses ClustersStorage to use either Clusters or ClusterStateCache
for all mutation operations we should add onActionXXX method that should be used by cache to update its internal state (ex. onTopicCreated(..), onTopicDelete(..))

**Comment by iliax** [comment]
implemented in https://github.com/provectus/kafka-ui/pull/1036 pr
