### ISSUE TITLE
The topic function page of kafka ui have some layout problems

### ISSUE THREAD

**Issue by MarsSu0618** [provectus/kafka-ui#966]
### Bug Description
I have encountered some problems about kafka ui. Please follow as: 
1. I found when i want to click `next page` in **topic function page**, the kafka ui always running and not show everything in the end so that i just view some of topics in first page.

2. In **topic function page**, i found this table list exceed web layout. 

I consider this issue maybe is ui problem, hope someone can solve it in future.

**Comment by GneyHabub** [comment]
Hello @MarsSu0618! Could you please provide some screenshots? It's not quite clear, what exactly the issues are

**Comment by MarsSu0618** [comment]
@Haarolean 40 topics.

**Comment by Haarolean** [comment]
@MarsSu0618 are there any errors and/or stacktraces in container logs when this 504 occurs?

**Comment by MarsSu0618** [comment]
@Haarolean I checked docker logs but it do not show anythings about error message.

**Comment by Haarolean** [comment]
@MarsSu0618 hey, please give it a try (image tagged `master`). Is the problem gone?
